### ISSUE TITLE
Required Field Validator is ignored when inside a tabpanel

### ISSUE THREAD

**Issue by jcm4101** [DevExpress/AjaxControlToolkit#10]
As described above, the required field validator doesn't fire when inside of a tabpanel

**Comment by MikhailTymchukDX** [comment]
Do you mean that ValidatorCallout does not work inside the TabPanel, but Required Field Validator works?

**Comment by jcm4101** [comment]
Yes, that is correct

**Comment by MikhailTymchukDX** [comment]
TabPanel uses an UpdatePanel internally, so this issue seems to be a duplicate of the #21 issue.
Would you please check if the workaround described there applies to your scenario?

**Comment by MikhailTymchukDX** [comment]
Closed due to inactivity.
