### ISSUE TITLE
IE 10 ACT Tabs/Modals Not Working...

### ISSUE THREAD

**Issue by cgountanis** [DevExpress/AjaxControlToolkit#100]
Easy to reproduce, just use IE 11 in 10 Mode/Document type. You get JS error. I saw that you might have already addressed this issue based on modals just making sure this fixes Tabs as well please. This going to be released 16.2 and any ETA? For now we just down graded.

**Comment by MikhailTymchukDX** [comment]
We have no JavaScript errors in v16.1 with Tabs.
Would you please provide a sample project that illustrates this issue?

**Comment by cgountanis** [comment]
I made a new project and I could not reproduce. Maybe I was having issues with modals and forgot a runat="server" on the tabpanel and just assumed the issue was combined. Not really sure now, it was about a month ago. The issue in question seems to be solved and slated for 16.2 (https://github.com/DevExpress/AjaxControlToolkit/issues/17). We can consider this closed and just hope 16.2 comes out soon for modals.
