### ISSUE TITLE
Html Editor doesn't save content from DesignerMode

### ISSUE THREAD

**Issue by madhav5589** [DevExpress/AjaxControlToolkit#104]
I have been using AjaxControlToolkit.HtmlEditor on aspx page. I recently upgraded the ACT version to 16.1.0.0. I see that the content of Editor doesn't got saved to database until at least I click on HtmlMode or PreviewMode from DesignerMode. Every time as long as I at least click on HtmlMode or PreviewMode, the content gets saved but never save directly from DesignerMode. This issue started only after I upgraded the version.

**Comment by MikhailTymchukDX** [comment]
What AJAX Control Toolkit version have you upgraded from?

We have no issues similar to the described one. We recommend moving to [HtmlEditorExtender](https://github.com/DevExpress/AjaxControlToolkit/wiki/HtmlEditor), because Editor is deprecated since PR #71

**Comment by madhav5589** [comment]
@MikhailTymchukDX I upgraded from version 7.1213. It wonder that it works when at least I switch to Html mode or preview mode once. Can you please let me know which event (page refresh or something) occurs when one switch from designer view to html/preview mode ?

Thanks for suggestion. I will move to HtmlEditorExtender.

**Comment by MikhailTymchukDX** [comment]
There is `Sys.Extended.UI.HtmlEditor.ToolbarButtons.ModeButton._onclick()` method that in turn, calls the `Sys.Extended.UI.HtmlEditor.EditPanel.set_activeMode()` that performs the actual mode switching.
