### ISSUE TITLE
TabPanel Renders Content Template to the side out of view

### ISSUE THREAD

**Issue by ChristopherBuller** [DevExpress/AjaxControlToolkit#108]
After upgrade, The TabPanel content no longer renders in the correct place TabStripPlacement="Top".
It makes the page unusable, the ContentTemplate is completely out of view
[TabPanel.docx](https://github.com/DevExpress/AjaxControlToolkit/files/266780/TabPanel.docx)

**Comment by MikhailTymchukDX** [comment]
Please see https://github.com/DevExpress/AjaxControlToolkit/issues/5#issuecomment-196755356 and https://github.com/DevExpress/AjaxControlToolkit/issues/5#issuecomment-197203997 for working this around.

Please inform if this helped you.

**Comment by ChristopherBuller** [comment]
This fixed the issue with the placement of the tab panel;
Now I need to fix the CSS for the tabs, the header draws floating over the content.
I can imagine this is a similar fix; restore the pieces of the CSS that are important to the control after manipulating. Thank you for your assistance!

**Comment by MikhailTymchukDX** [comment]
@ChristopherBuller It would be nice if you share a sample project, so we can check it and include a fix for headers into the next release.

**Comment by MikhailTymchukDX** [comment]
Feel free to reopen this issue if you have any info related to headers.
