### ISSUE TITLE
ValidatorCallOutExtender displays "Control Is Invalid" when fired 

### ISSUE THREAD

**Issue by jcm4101** [DevExpress/AjaxControlToolkit#11]
The control ignores the ErrorMessage property set in the validator and just replaces it with "Control Is Invalid" string

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project that illustrates this issue?

**Comment by githieu** [comment]
Please find the following simple example:
```
<asp:UpdatePanel ID="UpdatePanel1"  runat="server" UpdateMode="Conditional" >
        <ContentTemplate>
            <asp:TextBox ID="txtName" runat="server" MaxLength="30" Width="80" ></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator_txtName" runat="server" EnableClientScript="true" 
                Display="None" SetFocusOnError="true"
                ErrorMessage="This field is mandatory" 
                ControlToValidate="txtName"  ValidationGroup="UserForm"></asp:RequiredFieldValidator>
            <ajaxToolkit:ValidatorCalloutExtender ID="ValidatorCalloutExtender1_txtName" HighlightCssClass="ValidatorCallout" 
                TargetControlID="RequiredFieldValidator_txtName" runat="server" Width="300px"></ajaxToolkit:ValidatorCalloutExtender>

            <br /><br />
            <asp:Button ID="btnSaveUserForm" runat="server" Text="Save"  OnClick="btnSave_Click" ValidationGroup="UserForm" />
            <asp:Button ID="btnPostback" runat="server" Text="Test Postback"  OnClick="btnPostback_Click" Visible="true"/>

        </ContentTemplate>
    </asp:UpdatePanel>
```

btnPostback_Click contains only the following line of code: `UpdatePanel1.Update();`

1. Click on Save button: OK (ValidatorCalloutExtender is displayed and focus is set to txtName)
2. Click on Test Postback button: OK, a callback is done without validation, ValidatorCalloutExtender disappear
3. Click again Save button: NOK, ValidatorCalloutExtender does not appear but validator is working because postback is not fired and focus is set to txtName

**Comment by MikhailTymchukDX** [comment]
@githieu Is this code for issue #21?

**Comment by githieu** [comment]
@MikhailTymchukDX yes this code is for issue #21. I have no JavaScript error.

**Comment by MikhailTymchukDX** [comment]
@jcm4101 This situation arises when a project uses .NET Framework 4.5+, but `WebUIValidation.js` is not present on the page that contains ValidatorCallout.
This script is responsible for unobtrusive validation in newer versions of .NET Framework.

To work this around, either [disable the unobtrusive validation](http://jupaol.blogspot.ru/2012/09/enabling-unobtrusive-validation-from.html) or add the `WebUIValidation.js` script onto your page.
`WebUIValidation.js` comes with default ASP.NET project template and is set up in `Site.Master` file:
```aspx
<asp:ScriptManager runat="server">
	<Scripts>
		<asp:ScriptReference Name="WebUIValidation.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebUIValidation.js" />
	</Scripts>
</asp:ScriptManager>
```
