### ISSUE TITLE
Error during AjaxControlToolkit.AjaxFileUploadHelper.ProcessRequest

### ISSUE THREAD

**Issue by Helluva3ngineer** [DevExpress/AjaxControlToolkit#111]
I'm completely blocked trying to use this control.  After clicking upload, the AjaxFileUploadHandler.axd is called and I receive the following error:

_This method or property is not supported after HttpRequest.Form, Files, InputStream, or BinaryRead has been invoked._

I literally removed every other control on the page and comment out the event handlers except for the two associated with the upload control.  How do I even begin to debug this?  Thanks.

**Comment by MikhailTymchukDX** [comment]
Are you using it in the existing project or a clean one?
Providing a sample project with the error you described will help a lot.

**Comment by Helluva3ngineer** [comment]
This is an existing project that was in development for years and now I'm attempting to extend it. I can't provide the source code and an example really doesn't help.  At this point I think there is something in the rendering pipeline that is causing a problem, such as adding a header, etc.  I'm hoping someone has seen this problem before.

**Comment by nallar** [comment]
> after HttpRequest.Form, Files, InputStream, or BinaryRead has been invoked.

Can you add breakpoints on the getters in `HttpRequest` and see what's calling them?

Don't suppose you have something in `Application_BeginRequest` which is using one of them?

**Comment by MikhailTymchukDX** [comment]
@Helluva3ngineer Feel free to reopen the issue if you have any info that might help us investigate what causes this error.

**Comment by daylightburns** [comment]
I encountered this issue as well.

I found that in Web.config,
`<trace enabled="true" requestLimit="50" pageOutput="false" traceMode="SortByTime" localOnly="false" />`
produced the behavior described by @Helluva3ngineer .

I've reproduced & resolved the issue several times in succession to verify.

**Comment by MikhailTymchukDX** [comment]
We changed the approach introduced in PR #428 to more flexible solution in the context of PR #429.
AjaxFileUpload detects stream mode automatically, the `useBufferlessInputStream` property is removed.
