### ISSUE TITLE
AjaxFileUpload not working inside asp:WizardStep control

### ISSUE THREAD

**Issue by farubin** [DevExpress/AjaxControlToolkit#122]
AjaxFileUpload not working inside asp:WizardStep control. I have read about this issue. The workaround by adding a `<div>` container.

Can this be fixed in future releases?

**Comment by AlekseyMartynov** [comment]
Hi @farubin

>  I have read about this issue.
 
Could you provide more details? We would like to read about the issue too.

**Comment by farubin** [comment]
Sure...

If you place an AjaxFileUpload control inside a Wizard control in any WizardStep that is not the StartStep the control stop working.

It never uploads te file since the UploadComplete event is not fired.
To Hack this you have to put the AjaxFileUpload inside a DIV with style="display:none" inside the Wizard LayoutTemplate and modify the div style in code behind to show it in the desired WizardStep.

The error I get is:
Line: 3431
Error: Sys.ArgumentException: Cannot deserialize. The data does not correspond to valid JSON.
Parameter name: data

My intuition is that the AjaxFileUpload control is registering clientscript only if postback is false (that's why it works in start WizardStep)

For reproducing the issue .... just put a Wizard control with 2 steps  in the aspx page. First place the AjaxFileUpload inside first step and then move it to the second step.

**Comment by AlekseyMartynov** [comment]
Thanks, we'll look into it.

**Comment by farubin** [comment]
Your welcome.... if a fix for this is released please let me know.
