### ISSUE TITLE
tempFolder is not recognized when using sanitizer htmleditor

### ISSUE THREAD

**Issue by FurkanGozukara** [DevExpress/AjaxControlToolkit#129]
Hello. It gives the following error

Parser Error Message: Unrecognized attribute 'tempFolder'. Note that attribute names are case-sensitive.

I am trying to open HtmlEditorExtender page from your sample site

![error](https://cloud.githubusercontent.com/assets/19240467/15875899/f6c82634-2d12-11e6-8505-0931e9083bc6.png)

**Comment by MikhailTymchukDX** [comment]
Hello,

It seems you run the latest source of a Sample Site, which uses `AjaxControlToolkit.dll` compiled from one of the releases.
In the latest release, we made changes to that assembly (see #22), so using a DLL from the release in the source code of the latest Sample Site version will lead to this error.

There should be no error if you run the Sample Site from the downloaded solution without any changes.

Please check what assembly the Sample Site references.
I am looking forward to your response.

**Comment by MikhailTymchukDX** [comment]
Also, you can run a Sample Site from the `Documents\ASP.NET AJAX Control Toolkit\SampleSite` folder if you run [the installer](https://go.devexpress.com/AjaxControlToolkit_Website_Download.aspx).

**Comment by FurkanGozukara** [comment]
I also tested with my own project too. It gives that error. Webconfig does not recognize attribute as tempFolder

**Comment by MikhailTymchukDX** [comment]
It does not recognize the attribute, because it was added to `Web.config of a Sample Site after the latest release.
You can safely remove the attribute from `Web.config`.

**Comment by FurkanGozukara** [comment]
ah so that attribute is not necessary? alright

by the way nuget sanitizer also adds that attribute automatically

**Comment by MikhailTymchukDX** [comment]
The code that adds this attribute does not exist, so the NuGet package can not do that.
Would you please record a video that shows it? You can use the [Jing tool](https://www.techsmith.com/jing.html) for that purpose.

**Comment by FurkanGozukara** [comment]
i guess you are right

i just composed a new project and i dont see that attribute

ty
