### ISSUE TITLE
How can i modify MicrosoftAjaxWebForms.js and use modified version or can you implement defer feature to update panel

### ISSUE THREAD

**Issue by FurkanGozukara** [DevExpress/AjaxControlToolkit#130]
Hello. I have a very serious problem. I need to delay the update of the client side without blocking the browser

I am using asp.net 4.5

I found which function updates the client side UI and it is _scriptIncludesLoadComplete

So after the response from the server received, I want to delay the function call 

I have asked  a question here but nobody solved yet

Can you implement a feature that we can delay the update of the client side?

Or how can i modify _scriptIncludesLoadComplete and add delay feature and use it?

here my question : http://stackoverflow.com/questions/37237675/how-to-defer-the-update-at-the-client-side-after-async-postback-in-updatepanel

The parameters there are outdated. In the latest version the parameters are

_scriptIncludesLoadComplete: function(e, b) {

 this._updatePanel(j, c.content)

All those called in the function _onFormSubmitCompleted . so if you can add a feature that we can delay the run of _onFormSubmitCompleted that would be great

**Comment by MikhailTymchukDX** [comment]
The `MicrosoftAjaxWebForms.js` file is a part of [Microsoft AJAX](https://msdn.microsoft.com/en-us/library/bb398874.aspx) and is added by Visual Studio with the `Microsoft.AspNet.ScriptManager.MSAjax` NuGet package when a new project is created using Visual Studio Project Templates. So, we cannot modify it on our side.

However, you can modify a local copy of that file, which resides in the `Scripts\WebForms\MSAjax` folder of your project by default.
