### ISSUE TITLE
How can i bundle MicrosoftAjax.js and MicrosoftAjaxWebForms.js

### ISSUE THREAD

**Issue by FurkanGozukara** [DevExpress/AjaxControlToolkit#131]
ASP.net 4.5, ajaxtoolkit 16.1 latest

I have downloaded both files into my script folder

Then i bundle them like this in the global.asax file

```
        void Application_Start(object sender, EventArgs e)
    {
        System.Web.Routing.RouteTable.Routes.Ignore("{resource}.axd/{*pathInfo}");
        RegisterRoutes(System.Web.Routing.RouteTable.Routes);

        var ajaxBundle = new ScriptBundle("~/bundles/MsAjaxJs");
        ajaxBundle.Include(new string[] { 
         "~/Scripts/MicrosoftAjax.js",
         "~/Scripts/MicrosoftAjaxWebForms.js"
    });


        BundleTable.EnableOptimizations = true;
        BundleTable.Bundles.Add(ajaxBundle);
    }
```

Then in my page i use them like this but it is not working

inside head

```
    <asp:PlaceHolder runat="server">
        <%:System.Web.Optimization.Styles.Render("~/bundles/MsAjaxJs") %>
    </asp:PlaceHolder>
```

Inside body

```
    <asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="Server">
    <asp:ScriptManager runat="server" ID="SC1" ScriptMode="Release" LoadScriptsBeforeUI="true"
        EnablePartialRendering="true">
        <Scripts>
            <asp:ScriptReference Path="~/bundles/MsAjaxJs" ScriptMode="Release" />
        </Scripts>
    </asp:ScriptManager>
```

But, I  still see `ScriptResource.axd` files are called which contains `MicrosoftAjax.js` and `MicrosoftAjaxWebForms.js` with addition to my bundle file

![toomany](https://cloud.githubusercontent.com/assets/19240467/15878359/14b523f8-2d23-11e6-8206-7f38759f6763.png)

**Comment by MikhailTymchukDX** [comment]
It seems you are rendering files twice: the first time with the `System.Web.Optimization.Styles.Render` call and the second time using ScriptManager.

Please remove the first block.
Also, check if `MicrosoftAjax.js` and `MicrosoftAjaxWebForms.js` are present in your source code as they might be loaded implicitly.

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX 
I think a better way is to use the [Microsoft.AspNet.ScriptManager.MSAjax](https://www.nuget.org/packages/Microsoft.AspNet.ScriptManager.MSAjax/) package which registers the bundle and takes care of script mappings on it's own. More info in https://blogs.msdn.microsoft.com/pranav_rastogi/2012/09/21/asp-net-4-5-scriptmanager-improvements-in-webforms/

**Comment by FurkanGozukara** [comment]
MikhailTymchukDX yes i removed but still renders. can i directly link to that script for that asp:ScriptManager ? whatever i tried i failed .

**Comment by FurkanGozukara** [comment]
for example i tried like this but still that file is rendered twice

    <asp:ScriptManager runat="server" ID="SC1" ScriptMode="Release" LoadScriptsBeforeUI="true" EnableCdn="false"
        EnablePartialRendering="true"> 
               <Scripts>
            <asp:ScriptReference Path="Scripts/MsAjax/MicrosoftAjaxWebForms.js" ScriptMode="Release" />
        </Scripts>
    </asp:ScriptManager>

I want to use only my local file so i can modify and use it

**Comment by MikhailTymchukDX** [comment]
@FurkanGozukara If you check scripts content in browser's debugger you will note that its content differs from the files that you put into the bundle.
These scripts are added automatically from the [`System.Web.Extensions` assembly](http://www.infinitezest.com/articles/where-are-the-asp-net-ajax-library-javascript-files.aspx) when you place ScriptManager on your page.

You can not stop rendering them, but you can order ScriptManager to include it into your bundle. To do this, add this lines to your code:
```csharp
ScriptManager.ScriptResourceMapping.AddDefinition("MsAjaxJs", new ScriptResourceDefinition {
	Path = "~/bundles/MsAjaxJs",
	CdnPath = "http://ajax.aspnetcdn.com/ajax/4.5.1/1/MsAjaxBundle.js",
	LoadSuccessExpression = "window.Sys",
	CdnSupportsSecureConnection = true
});

ScriptManager.ScriptResourceMapping.AddDefinition("MicrosoftAjax.js", new ScriptResourceDefinition {
	Path = "~/Scripts/WebForms/MsAjax/MicrosoftAjax.js",
	CdnPath = "http://ajax.aspnetcdn.com/ajax/4.5.1/1/MicrosoftAjax.js",
	LoadSuccessExpression = "window.Sys && Sys._Application && Sys.Observer",
	CdnSupportsSecureConnection = true
});

ScriptManager.ScriptResourceMapping.AddDefinition("MicrosoftAjaxWebForms.js", new ScriptResourceDefinition {
	Path = "~/Scripts/WebForms/MsAjax/MicrosoftAjaxWebForms.js",
	CdnPath = "http://ajax.aspnetcdn.com/ajax/4.5.1/1/MicrosoftAjaxWebForms.js",
	LoadSuccessExpression = "window.Sys && Sys.WebForms",
	CdnSupportsSecureConnection = true
});
```
and replace ScriptReference `Path` attribute with `Name` attribute:
```xml
<asp:ScriptReference Name="MsAjaxJs" />
```
