### ISSUE TITLE
HtmlEditorExtender stripes out pre tag

### ISSUE THREAD

**Issue by FurkanGozukara** [DevExpress/AjaxControlToolkit#133]
Hello. I have coded my own quoting system since HtmlEditorExtender does not have a quote system. Or does it have?

for quote, i am using pre tag. However, the latest HtmlEditorExtender in version 16.1.0 stripes out the pre tag. It just removes the part that contains pre tag. 

I mean like

`<pre><pre>CeFurkan: Wrote</pre>dsfsdfs</pre>`

This is removed at the client side before posting to the server. How can i allow this tag?

I also tried with span class="myClass" and it removes class tag this time

my settings are

code behind
`htmlEditorExtender1.EnableSanitization = true;`

front code
 ```
<ajaxToolkit:HtmlEditorExtender ID="htmlEditorExtender1" TargetControlID="txtMessageBody"
                    runat="server" DisplaySourceTab="True">
                    <Toolbar>
                        <ajaxToolkit:Undo />
                        <ajaxToolkit:Redo />
                        <ajaxToolkit:Bold />
                        <ajaxToolkit:Italic />
                        <ajaxToolkit:Underline />
                        <ajaxToolkit:StrikeThrough />
                        <ajaxToolkit:Subscript />
                        <ajaxToolkit:Superscript />
                        <ajaxToolkit:JustifyLeft />
                        <ajaxToolkit:JustifyCenter />
                        <ajaxToolkit:JustifyRight />
                        <ajaxToolkit:JustifyFull />
                        <ajaxToolkit:InsertOrderedList />
                        <ajaxToolkit:InsertUnorderedList />
                        <ajaxToolkit:CreateLink />
                        <ajaxToolkit:UnLink />
                        <ajaxToolkit:RemoveFormat />
                        <ajaxToolkit:SelectAll />
                        <ajaxToolkit:UnSelect />
                        <ajaxToolkit:Delete />
                        <ajaxToolkit:Cut />
                        <ajaxToolkit:Copy />
                        <ajaxToolkit:Paste />
                        <ajaxToolkit:BackgroundColorSelector />
                        <ajaxToolkit:ForeColorSelector />
                        <ajaxToolkit:FontNameSelector />
                        <ajaxToolkit:FontSizeSelector />
                        <ajaxToolkit:Indent />
                        <ajaxToolkit:Outdent />
                        <ajaxToolkit:InsertHorizontalRule />
                        <ajaxToolkit:HorizontalSeparator />
                    </Toolbar>
                </ajaxToolkit:HtmlEditorExtender>

```

And web config

 `<ajaxControlToolkit useStaticResources="true" renderStyleLinks="false" htmlSanitizer="AjaxControlToolkit.HtmlEditor.Sanitizer.DefaultHtmlSanitizer, AjaxControlToolkit.HtmlEditor.Sanitizer" />`

**Comment by FurkanGozukara** [comment]
By the  way it was working at my previous version which was 4.5.7.123

Also when we enable  EnableSanitization it does check at the server side too right?

**Comment by FurkanGozukara** [comment]
someone else proposed this solution and it seems like working

what do you think @MikhailTymchukDX  ?

http://stackoverflow.com/questions/37715579/htmleditorextender-stripes-out-pre-tag/37723213?noredirect=1#comment62920527_37723213

**Comment by MikhailTymchukDX** [comment]
The `<pre>` tag is designed for pre-formatted text blocks like program code, etc. Pre-formatted text saves newlines and whitespace sequences as is. HtmlEditorExtender cannot work with such blocks now - it saves text only, but collapses a whitespace symbol sequence into a single whitespace.
 
We recommend you use the `<blockquote>` tag for quoting instead of `<pre>`, because it is specially designed for quoting and is supported by the extender.
 
>By the way it was working at my previous version which was 4.5.7.123

We checked this version and found that sanitization was broken at that time, so keeping `<pre>` tag was actually a bug.
 
>Also when we enable EnableSanitization it does check at the server side too right?

Yes, that’s right.
 
>someone else proposed this solution and it seems like working

This is another way of solving the problem. However, custom sanitizer implementation can affect your site security, so make sure it prevents [XSS attacks](https://en.wikipedia.org/wiki/Cross-site_scripting).

**Comment by FurkanGozukara** [comment]
oh ty let me try blockquote tag for quote system
