### ISSUE TITLE
When EnableSanitization is set true, does HtmlEditorExtender make server side check?

### ISSUE THREAD

**Issue by FurkanGozukara** [DevExpress/AjaxControlToolkit#134]
I tested and it stripes out the client side not whitelisted tags and it works fine.

But client side can always be modified. So i wonder does it make server side check too? After the client response received.

I have installed default AjaxControlToolkit.HtmlEditor.Sanitizer from github

**Comment by MikhailTymchukDX** [comment]
Yes, `HtmlEditorExtender` [combines allowed tags] (https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/HtmlEditorExtender/HtmlEditorExtender.cs#L177) with corresponding allowed attributes from all Toolbar buttons before sending it to a Sanitizer: 
```csharp
// Check Whether EnableSanitization is disabled or not.
if(EnableSanitization && Sanitizer != null) {
	var elementWhiteList = MakeCombinedElementList();

	if(!elementWhiteList.ContainsKey("span"))
		elementWhiteList.Add("span", new string[0]);

	if(!elementWhiteList.ContainsKey("br"))
		elementWhiteList.Add("br", new string[0]);

	result = Sanitizer.GetSafeHtmlFragment(result, elementWhiteList);
}
```

**Comment by FurkanGozukara** [comment]
nice ty. so i don't need additional server side check once sanitizer is enabled

**Comment by MikhailTymchukDX** [comment]
Exactly.
