### ISSUE TITLE
LineChart max width being ignored

### ISSUE THREAD

**Issue by LeadMagnet** [DevExpress/AjaxControlToolkit#135]
I'm using the LineChart control on a 4.5 WebForms application to display data in 24 Y axis elements. Axis labels are all 5 characters long. Chart renders off the right side of the screen.

Setting ChartWidth="800" in ASPX is ignored. 
In code, setting LineChart1.Width = System.Web.UI.WebControls.Unit.Pixel(800) is ignored.

Chart has a huge margin between the left parent container edge and the vertical axis legend for some reason

Happens only in IE or Edge (any version), although in FF and Opera the large margin is present, just not as big as IE

Page has no CSS aside from what is defined in the control. No other JS code. No other controls.

**Comment by MikhailTymchukDX** [comment]
Would you please provide a screenshot and/or sample project that illustrates this issue?

**Comment by LeadMagnet** [comment]
screen shot uploaded to http://i.imgur.com/uempO5l.png

shows the HTML element style settings, weird margin, all identified in red.

**Comment by LeadMagnet** [comment]
FYI, in the image you'll see 2 errors identified in the debug console, they both say...

SVG4601: SVG Path data has incorrect format and could not be completely parsed.

Both errors say the same.

**Comment by MikhailTymchukDX** [comment]
Unfortunately, I cannot reproduce this issue based on the information you provided.

I have attached a sample project that uses the latest AJAX Control Toolkit release: 
[LineChart.zip](https://github.com/DevExpress/AjaxControlToolkit/files/320349/LineChart.zip)

Would you please modify it to illustrate conditions under which LineChart breaks?
