### ISSUE TITLE
Calendar extender not selecting years

### ISSUE THREAD

**Issue by nanoserg** [DevExpress/AjaxControlToolkit#137]
When StartDate is setting for Calendar extender (in Properties or in program)  you cannot select other page in Year mode.  Version 16.0

**Comment by MikhailTymchukDX** [comment]
I cannot reproduce the described behavior.
Would you please provide a sample project that illustrates this issue?

**Comment by nanoserg** [comment]
I Cannot attach ZIP file! Bug! Bug!

**Comment by nanoserg** [comment]
How I can send project ?

**Comment by MikhailTymchukDX** [comment]
Maybe it's [too large](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)?

**Comment by nanoserg** [comment]
17 Mb

**Comment by MikhailTymchukDX** [comment]
I believe you can remove the `packages` folder to get rid of binaries that can be restored by NuGet during compilation.

**Comment by nanoserg** [comment]
IE11, Edge cannot work, filesize 6Mb

**Comment by nanoserg** [comment]
https://cloud.mail.ru/public/GcHv/3eD5RkkuL
