### ISSUE TITLE
How to restrict OnUploadComplete event when filename lenth exceeds the limit

### ISSUE THREAD

**Issue by Narayana187** [DevExpress/AjaxControlToolkit#141]
Hi, I'm using Ajaxfileupload control for multiple files drag and drop. there i need to stop the file to upload when the Filename length exceeds its limit. it is not happening via code from both Server side and client side. so please help me out in this regard.

**Comment by MikhailTymchukDX** [comment]
You can not interrupt the uploading process.

However, uploaded files are not saved to the disk until you call the [`SaveAs()`](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload#saveasfilename) method explicitly.
So, you can [call it inside `OnUploadComplete`](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.SampleSite/AjaxFileUpload/AjaxFileUpload.aspx.cs#L59) event handler and rename the file according to your needs or cancel saving of the file.
