### ISSUE TITLE
Upgraded to ajaxcontroltoolkit16.1 from 4.1 and getting script errors in IE

### ISSUE THREAD

**Issue by nkcoder22** [DevExpress/AjaxControlToolkit#143]
I upgraded a web project that is using version ajaxcontroltoolkit verion 4.1 to 16.1 and I started getting these script errors. Fixed some of them by checking online but could not figure out this. It happens in both chrome and IE.

IE Error:
0x800a138f - JavaScript runtime error: Unable to get property '_events' of undefined or null reference

Chrome Error:

ScriptResource.axd?d=ttHJThnCxyEWy44Depc0y4w9DUXWLHb-Bzq9rrCoOZhA9QQO36iVQiRtMLP-QoB-nM1-qSDpgENRJO…:5 Uncaught TypeError: Cannot read property '_events' of null

Any help appreciated. Thanks!

**Comment by Jojo67** [comment]
I'm having a similar problem after upgrading - load of WebRequestErrorEvent script errors coming through over night so I suspect triggered by robots crawling the site.  The site actually does work, I just all these errors overnight.  A lot seem to be to do with 'missing' debug.js files but I don't know why the site even needs them or where they are supposed to be. (eg "AjaxControlToolkit|HtmlEditorExtender.HtmlEditorExtenderBehavior.debug.js’ does not exist or there was a problem loading it",   I'm not even using the Html editor. Could you tell me what you did to fix all the other errors you had?  I can't find any information on line which relates to the current version.

**Comment by MikhailTymchukDX** [comment]
Thanks for reporting this!

I performed an upgrade of the default ASP.NET Web application template project from v4.1 to v16.1, but could see no errors.
It seems that there is something else involved that causes the described error.

Can you provide a sample project that illustrates this issue?

**Comment by nkcoder22** [comment]
I am working with legacy .nET web application with mix of AJAX controls along with regular .NET controls. I am not sure if I can create a sample project exactly in the same flow as it is a complex one and I dont know how simple your sample project is. Our web application wont work in any other browsers other that IE8 and that is the reason I am trying to upgrade it now. I can see it working in chrome after the upgrade but seeing this error behind the scenes and in IE I am getting the error before I can even open it. Do you have any suggestions on importing any other script files that can fix this? We use lot of modal pop and update panel controls and I am not sure if anything has changed with these controls in latest versions. We also use jquery and the version is jquery-1.4.1.min.js, do I need a latest version does ACT has any dependency on jquery version?

**Comment by MikhailTymchukDX** [comment]
>Do you have any suggestions on importing any other script files that can fix this?

We still have no information about what can cause this, so we cannot give you any solution.

To provide an example, you can try removing all private data and specific code gradually from the application and check if the error persists.
We need an application with only one page and all infrastructure needed to illustrate this issue.

>does ACT has any dependency on jquery version?

No. The AJAX Control Toolkit does not depend on jQuery.

**Comment by MikhailTymchukDX** [comment]
Feel free to reopen this issue once you have a sample application or if you have any questions that might help construct it.

**Comment by urvilshahcs** [comment]
I am getting the similar error , I upgraded from version 4 to version 17.1 and I have no way to determine what is causing this error, you guys have found any fixture ?
