### ISSUE TITLE
Scripting exceptions

### ISSUE THREAD

**Issue by Jojo67** [DevExpress/AjaxControlToolkit#144]
My production site gets a lot of WebRequestErrorEvent script errors over night so I suspect they are triggered by robots crawling the site. The site actually does work, I just get all these errors overnight. 

eg

"An error occurred processing a web or script resource request. The requested resource ‘ZAjaxControlToolkit|HTMLEditor.Toolbar_buttons.ModeButton.debug.js|’ does not exist or there was a problem loading it"
I get similar errors for ‘ZAjaxControlToolkit|HTMLEditor.Toolbar.debug.js|’, 'ZAjaxControlToolkit|HTMLEditor.Toolbar_buttons.StrikeThrough.debug.js|’, ‘ZAjaxControlToolkit|AjaxFileUpload.AjaxFileUpload.StartEventArgs.debug.js|’ and others.

I'm not using the controls mentioned in these errors anywhere on the site so I don't understand why these files are even required.  My users are unaware of any issues.  Is there something I need to remove to prevent this or, if they are required to be there despite being unused, where do I get them and where do I put them?

Thanks
Jo

**Comment by MikhailTymchukDX** [comment]
Hello, @Jojo67 
Thank you for posting this interesting issue.

The AJAX Control Toolkit does not load unnecessary script files other than ones used by controls on a page.

As for URL probing, it can be a crawler that tries to fetch URLs that existed on your site some time ago, but are no longer present. This is normal, and you don't have to make any actions to prevent this.

Please see this thread, which may help you: [Massive 404 attack with non existent URLs. How to prevent this?](http://webmasters.stackexchange.com/questions/63024/massive-404-attack-with-non-existent-urls-how-to-prevent-this)

If you feel that you need more information about these requests, you can log additional parameters by using a custom [WebRequestDetailedErrorEvent](http://james.newtonking.com/archive/2006/08/10/WebRequestDetailedErrorEvent) class.

I am looking forward to your response.

**Comment by Jojo67** [comment]
Thanks Mikhail, that makes sense.  I didn’t get the flood of exceptions last night so perhaps the crawler has caught on now.

**Comment by MikhailTymchukDX** [comment]
I'm happy I could help you. Feel free to reopen this issue if you find additional details regarding it.
