### ISSUE TITLE
ajaxToolkit:AutoCompleteExtender version 3.5.7

### ISSUE THREAD

**Issue by eldridgegl** [DevExpress/AjaxControlToolkit#149]
I have AjaxControlToolkit version 3.5.7.1213 and VS 2013 an am having issues with ajaxToolkit:AutoCompleteExtender (not firing) and reading online, they mention version 4 should resolve my issue. What version 4 should I upgrade to? is there an online process to do this upgrade? Is there a license restriction or any compatibility issues I should try to avoid for this upgrade?

**Comment by MikhailTymchukDX** [comment]
Would you please describe these issues in more detail?

>they mention version 4 should resolve my issue.

Would you please provide a source of this info?

>is there an online process to do this upgrade?

No, there is no online upgrade process, but the [official upgrade guide](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below) will help you to upgrade the toolkit to the latest version, 16.1.

>Is there a license restriction or any compatibility issues I should try to avoid for this upgrade?

The AJAX Control Toolkit remains open source software, so you don't need to buy a license for the toolkit. However, if you work with the source code of the toolkit, make sure you follow the [BSD license](https://github.com/DevExpress/AjaxControlToolkit/blob/master/LICENSE.txt) terms.

**Comment by eldridgegl** [comment]
Thank you for your reply.
The compilation issue I had went away after I added assemblies into the
web.config file. Although I still have issues around the settings page
(have not had time to investigate), I have gotten by the compilation issue
in order to continue business. Thank you.

**Comment by MikhailTymchukDX** [comment]
I'm happy to hear that the problem is solved.
Feel free to reopen this issue if you have any further questions.

**Comment by eldridgegl** [comment]
Hi, sorry, I responded via email for the wrong issue. I will see how to reactivate this issue or open a new one.
