### ISSUE TITLE
Modal popup rendering behind other objects when chart is present

### ISSUE THREAD

**Issue by petrozio** [DevExpress/AjaxControlToolkit#15]
Intermittent issue with Modal Popup rendering behind charts and gridviews. Seems like the presence of a chart is the cause. Can't interact with popup.
![capture](https://cloud.githubusercontent.com/assets/17831974/13750364/81ba5ad0-e9db-11e5-9033-fd01f7f578eb.PNG)

**Comment by savornicesei** [comment]
Are you using AjaxControlToolkit v16.1?
I'm asking this because we had similar issues that were gone after we upgraded the library from 15.x to 16.1 (latest).

**Comment by petrozio** [comment]
Thank you! With some very quick testing it seems to have worked. Appreciate the reply.
