### ISSUE TITLE
After adding multiple files in upload queue initially select file button only allows for single select

### ISSUE THREAD

**Issue by flo-rider** [DevExpress/AjaxControlToolkit#154]
I use the ajaxfileuload control. When I initially click the 'Select file' button I can select multiple files. I add 2 files to the upload queue. When I don't upload these, but immediately click the same 'Select file' button again, I'm only allowed to select a single file and NOT multiple. I've set the MaximumNumberOfFiles="10", so that can't be it either. Is this a bug?

**Comment by MikhailTymchukDX** [comment]
Yes, it is a known bug that is fixed now: #136

**Comment by flo-rider** [comment]
Ah cool. Question, I can't use the installer (I'm on Visual Studio Express for Web), so I downloaded the sourcecode here: https://github.com/DevExpress/AjaxControlToolkit/releases/tag/16.1.0
But after building I get a AjaxControlToolkit.dll file that is version 15.1.2.0 and not 16.1.0...and I was actually looking to get the 16.1.1 version which solves an Ajaxfileupload issue I was having...how can I get that version?

**Comment by MikhailTymchukDX** [comment]
We did not update the assembly version, because it was updated automatically by our internal build task.
So, you have to update it manually to be in sync with the release version.

**Comment by flo-rider** [comment]
Sorry, I'm really new to GitHub so I apologize if I'm asking something stupid here. Where exactly can I find the latest version? I also downloaded the latest source and built that solution, but still end up with version 15.1.2.0. Is there a direct link to 16.1.1 or how do I go about getting/building that?

**Comment by Skybladev2** [comment]
@flo-rider You are doing everything right. Just grab the code from the main page of the repo, change assembly version to whatever you want and compile.

Assembly version in the source code is not updated, because it is patched during build pipline from external source. Hence, it can be any number and does not affect anything.

**Comment by flo-rider** [comment]
Ah, good to hear, still learning :) I'm now looking through the code's properties files and xml files, but where in the code can I change the assembly version? I just want to make sure it's set to 16.1.1.0 so at least in the future I know which version is in production.

**Comment by MikhailTymchukDX** [comment]
@flo-rider  You need to change [these 2 lines](https://github.com/DevExpress/AjaxControlToolkit/blob/master/SharedAssemblyInfo.cs#L10-L11):
```csharp
[assembly: AssemblyVersion("15.1.2.0")]
[assembly: AssemblyFileVersion("15.1.2.0")]
```

to

```csharp
[assembly: AssemblyVersion("16.1.1.0")]
[assembly: AssemblyFileVersion("16.1.1.0")]
```
