### ISSUE TITLE
Allow for setting language labels in codebehind

### ISSUE THREAD

**Issue by flo-rider** [DevExpress/AjaxControlToolkit#156]
Please add a way to dynamically set the language labels of the control from codebehind. It seems right now we are forced to workaround via clientside like this: http://stackoverflow.com/questions/24687983/changing-ajaxfileupload-controls-language/24688766#24688766

Alsol, this workaround does not seem to address the option to set the text of upload status fields, such as "(pending)", or the javascript alert message that a certain dragged in filetype is not supported. Would love to have more robust control over this from the code.

**Comment by MikhailTymchukDX** [comment]
Hi @flo-rider 

The AJAX Control Toolkit localizes controls according to the current culture settings, which come from the client's browser.

There can be 2 reasons why you don't see a localized control:

1. The server overrides the current UI culture with special markup. For example, the `@Page` directive, which forces a page to be localized with French resources, will look like this:

    ```aspx
    <%@ Page UICulture="fr"  %>
    ```

    You can try to override this setting in code-behind with the following code:

    ```csharp
    Thread.CurrentThread.CurrentUICulture = new CultureInfo(culture);
    ```

   For more information about ASP.NET localization, please see this MSDN artcle: [How to: Set the Culture and UI Culture for ASP.NET Web Page Globalization](https://msdn.microsoft.com/en-us/library/bz9tc508.aspx)

1. The current UI culture is set correctly, but there are no localized resources for that culture in the toolkit. You can fix this in 2 ways:

  1. Create custom localization and add it to your site. Here is an article that will guide you through this process: [Creating a custom localization](https://github.com/DevExpress/AjaxControlToolkit/wiki/Creating-a-custom-localization).

  1. Add/update the localization resource file to/in the source code.

    For example, the [German localization file](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/Localization/Resources_de.js) contains resources for the Calendar extender only, but [French resources](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/Localization/Resources_fr.js) contain `AjaxFileUpload` localization as well.

    An advantage of this approach is that such a localization will become built-in as soon as we merge it with the [main repo](https://github.com/DevExpress/AjaxControlToolkit).
