### ISSUE TITLE
Autocomplete not working with FriendlyUrl routing

### ISSUE THREAD

**Issue by WebSAE** [DevExpress/AjaxControlToolkit#159]
Below is all my code that is having the issue:

AutoComplete.aspx

<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AutoComplete.aspx.cs" Inherits="AutoComplete" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <style type="text/css">
        .loading {
            background-image: url(images/Animated16x16/loader.gif);
            background-position: right;
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
   <asp:ScriptManager ID="ScriptManager1" runat="server" />

            <asp:TextBox ID="txtContactsSearch" runat="server" Width="400px"/>

            <ajaxToolkit:AutoCompleteExtender ServiceMethod="SearchCustomers" MinimumPrefixLength="2"
                ID="AutoCompleteExtender1" runat="server" 
                CompletionInterval="100" 
                EnableCaching="false" 
                CompletionSetCount="10" 
                TargetControlID="txtContactsSearch"
                FirstRowSelected="false" 
                OnClientHiding="OnClientCompleted"
                OnClientPopulated="OnClientCompleted" 
                OnClientPopulating="OnClientPopulating">
            </ajaxToolkit:AutoCompleteExtender>
            <ajaxToolkit:TextBoxWatermarkExtender runat="server" 
                BehaviorID="TextBox1_TextBoxWatermarkExtender" 
                TargetControlID="txtContactsSearch" 
                ID="TextBox1_TextBoxWatermarkExtender" 
                WatermarkText="Start Typing Your University Name"/>

            <script type="text/javascript">
                function OnClientPopulating(sender, e) {
                    sender._element.className = "loading";
                }
                function OnClientCompleted(sender, e) {
                    sender._element.className = "";
                }
            </script>
    </div>
    </form>
</body>
</html>

Also tried adding ServicePath="~/" to the autocomplet but it didn't work.

AutoComplete.aspx.cs

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Script;
using System.Web.Services;

public partial class AutoComplete : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    //[System.Web.Script.Services.ScriptMethod()]
    //[System.Web.Services.WebMethod]
    [System.Web.Services.WebMethodAttribute, System.Web.Script.Services.ScriptMethod]
    public static List<string> SearchCustomers(string prefixText, int count)
    {
        using (SqlConnection conn = new SqlConnection())
        {
            //conn.ConnectionString = ConfigurationManager.ConnectionStrings["constr"].ConnectionString;
            conn.ConnectionString = ConfigurationManager.ConnectionStrings["TBDConnString"].ConnectionString;
            using (SqlCommand cmd = new SqlCommand())
            {
                //cmd.CommandText = "select ContactName from Customers where ContactName like @SearchText + '%'";
                cmd.CommandText = "select distinct Institution_Name from Accreditation_2016_03 where Institution_Name like '%' + @SearchText + '%'";

                cmd.Parameters.AddWithValue("@SearchText", prefixText);
                cmd.Connection = conn;
                conn.Open();
                List<string> customers = new List<string>();
                using (SqlDataReader sdr = cmd.ExecuteReader())
                {
                    while (sdr.Read())
                    {
                        //customers.Add(sdr["ContactName"].ToString());
                        customers.Add(sdr["Institution_Name"].ToString());
                    }
                }
                conn.Close();
                return customers;
            }
        }
    }
}

Global.asax

<%@ Application Language="C#" %>
<%@ Import Namespace="System.Web.Routing" %>

<script RunAt="server">

    void Application_Start(object sender, EventArgs e)
    {
        RouteConfig.RegisterRoutes(RouteTable.Routes);
    }

</script>

App_Code\App_Start\RouteConfig.cs

using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Routing;
using Microsoft.AspNet.FriendlyUrls;

namespace ASP
{
    public static class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            var settings = new FriendlyUrlSettings();
            settings.AutoRedirectMode = RedirectMode.Permanent;
            routes.EnableFriendlyUrls(settings);
        }
    }
}

I also tried commenting out the "settings.AutoRedirectMode = RedirectMode.Permanent;" but that didn't work.

Thanks.

**Comment by MikhailTymchukDX** [comment]
Hi @WebSAE 
I can not build a project from the layout that you provided.
Would you please provide a sample project that illustrates this issue?
