### ISSUE TITLE
UpdatePanelAnimationExtender not triggered in from DropDownList controls

### ISSUE THREAD

**Issue by JasonRosenthal** [DevExpress/AjaxControlToolkit#162]

**Comment by AlekseyMartynov** [comment]
Please review the [guidelines for submitting bugs](https://github.com/DevExpress/AjaxControlToolkit/blob/master/CONTRIBUTING.MD) and provide more details about the issue.
Thanks.

**Comment by JasonRosenthal** [comment]
[WebApplication1.zip](https://github.com/DevExpress/AjaxControlToolkit/files/352418/WebApplication1.zip)

Sorry I thought I was succinct.  Please find sample test application.   Reproducing the bugs are trivial.  Any change to any control should trigger the Animation.  TextBox and Checkbox triggers seem to work in IE and Chrome.   Using chrome, the dropdown trigger will also work.  But no browser works for ChilderenAsTriggers (press the button in the sample).  This is not a exhaustive test sample, testing the triggers against all possible controls that the updatepanel supports is recommended.  Thanks.

**Comment by JasonRosenthal** [comment]
I nugeted back to 4.1.60919 and everything works in that version.  I just need to put toolscriptmanager back.

**Comment by AlekseyMartynov** [comment]
Thanks, reproduced.

@MikhailTymchukDX 
in [this line](https://github.com/DevExpress/AjaxControlToolkit/blob/16.1.0/AjaxControlToolkit/Scripts/UpdatePanelAnimation.js#L71), for DropDownList1 `sender._activeElement` is `<option>` not  `<select>`

**Comment by JasonRosenthal** [comment]
Pressing the button in the sample updates the UpdatePanel via its ChildrenAsTriggers property set to True.   The animation should trigger every time the UpdatePanel updates.  The animation doesn't work for me in any browser in the ChildrenAsTriggers case.   Thanks!

**Comment by AlekseyMartynov** [comment]
Ok, now I understand that we have 2 issues:
* No animation if update is triggered by a DropDownList control
* No animation if update is triggered by a control inside the UpdatePanel

**Comment by JasonRosenthal** [comment]
Thanks! Those are the two use cases I've run into so far in my code.  There may be other triggers that don't work as I'm not using or testing the UpdatePanel to its limits.

**Comment by MikhailTymchukDX** [comment]
@JasonRosenthal, we will fix an issue with the `ChildrenAsTriggers` property within #170 context.
Please subscribe to it to track its progress.
