### ISSUE TITLE
htmleditorextender causing IndexSizeError when datalist.databind() is triggered - problem only occurs with Edge browser (sorry)

### ISSUE THREAD

**Issue by dominicafonso** [DevExpress/AjaxControlToolkit#163]
I have a textbox with a htmleditorextender on the same page as a dropdownlist and datalist. The dropdownlist is used to choose a value. 
              
```
  <td >
                        <asp:TextBox ID="body" runat="server" Width="100%" Height="400px" Wrap="False" TextMode="MultiLine" ValidateRequestMode="Disabled"></asp:TextBox>
                        <ajaxToolkit:HtmlEditorExtender ID="body_HtmlEditorExtender" runat="server" Enabled="True" EnableSanitization="False" TargetControlID="body"></ajaxToolkit:HtmlEditorExtender>
  </td>
```
```
                               <td>
                                    <asp:DropDownList ID="fromchoice" runat="server" AppendDataBoundItems="True" DataSourceID="fromdata" DataTextField="mail_from" DataValueField="mail_from" AutoPostBack="True">
                                        <asp:ListItem>Please select</asp:ListItem>
                                    </asp:DropDownList>
                                </td>
```

When an item is selected the following runs in the codebehind.   
```
 Protected Sub fromchoice_SelectedIndexChanged(sender As Object, e As EventArgs) Handles fromchoice.SelectedIndexChanged
        includedmaillist.DataBind()
    End Sub
```

The first time this happens the list refreshes without any warnings, but the second time a selection is made the list does not refresh and the following error is received in the console:

The datalist and dropdownlist have nothing to do with the textbox-htmleditorextender, but they are on the same page.

SCRIPT: 5022 IndexSizeError 
ScriptResource.axd (753,25)

following the error takes me to the debugger showing the scriptresource.axd with this header
// Name:        HtmlEditorExtender.HtmlEditorExtenderBehavior.debug.js
// Assembly:    AjaxControlToolkit
// Version:     4.5.7.1005
// FileVersion: 4.5.7.1005
// (c) 2010 CodePlex Foundation
/// <reference name='MicrosoftAjax.js' />
/// <reference path='../ExtenderBase/BaseScripts.js' />
/// <reference path='../Common/Common.js' />
/// <reference path="~/Common/Common.pre.js" />

the section that the error refers to is:

```
            _editableDiv_submit: function () {
                var char = 3;
                var sel = null;

                setTimeout(function () {
                    if (this._editableDiv != null)
                        this._editableDiv.focus();
                }, 0);
                if (Sys.Browser.agent != Sys.Browser.Firefox) {
                    if (document.selection) {
                        sel = document.selection.createRange();
                        sel.moveStart('character', char);
                        sel.select();
                    }
                    else {
                        sel = window.getSelection();
(753)                        sel.collapse(this._editableDiv.firstChild, char);
                    }
                }

                this._textbox._element.value = this._encodeHtml();
            },
```

**Comment by AlekseyMartynov** [comment]
I see that you are using an old verions of AJAX Control Toolkit:

> Version: 4.5.7.1005

Can you check the problematic page with the current 16.1 version please?

See also: [Upgrading from v7.x and below](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below)

**Comment by MikhailTymchukDX** [comment]
@dominicafonso  Feel free to reopen this issue if you have any additional information regarding it.
