### ISSUE TITLE
Unable to access other controls on page when using toolkit items. 

### ISSUE THREAD

**Issue by simonprice33** [DevExpress/AjaxControlToolkit#167]
HI, 

I am working with the ASP.Net AJAX Toolkit that you are now responsible for and I am having some difficulty with using the AJAX Upload and interacting with other controls that exist on the page. 

What I am trying to achieve is to upload a file, and collect information from the page at the same time. 

I have tried the following 

1. Accessing the control(s) directly 
2. Newing up an instance of the class
3. Searching for the controls on the page

none of which have worked. 

this is the code I am currently working with in the code behind 

```
ProtectedSub OnUploadComplete(sender AsObject, e AsAjaxFileUploadEventArgs)
    Dim t AsString
    t = "no text"
    Dim cph As System.Web.UI.WebControls.ContentPlaceHolder = Master.FindControl("MainContent")
    
    ForEach ctrl In cph.Controls
        If ctrl.GetType() = GetType(TextBox) Then
            Dim tb AsTextBox = ctrl
            If tb.ID = "TextBox1"Then
                t = tb.Text
            EndIf
        EndIf
    Next
    
    Dim fileName AsString = Path.GetFileName(e.FileName)
    Dim fileSaveLocationAndName = Path.Combine(_initialFileSaveLocation, fileName)
    ajaxFu.SaveAs(fileSaveLocationAndName)
    Dim fu AsNewFileUploads(fileSaveLocationAndName, _connStr)
EndSub
```

as you can see I am giving t a value to begin with, however at the end of the method the value is "" (nothing) because its not finding the controls current value, even after a postback to set the value. 

Any and all help is very much appreciated. 

Simon

**Comment by AlekseyMartynov** [comment]
Hi @simonprice33 

If I understand correctly, you are trying to read a value of `TextBox1` during a file uploading AJAX request.

Unfortunately it's not supported. Those AJAX requests are performed independently of the ASP.NET page infrastructure, and any changes made to controls' state (such as the value of the `Text` property) are not visible.

**Comment by simonprice33** [comment]
I was expecting a response like that.  Any ideas on how I could achieve what I am looking to do?  My initial thought it put a jquery event on the button click of upload and try and tie the events in this way some how.

**Comment by AlekseyMartynov** [comment]
It depends on a particular use case.

If it is a data entry form then a typical flow can be:
* Upload files with temporary names (for example, use Guids) and save their names in the Session state
* Wire things up when the form in submitted

If synchronous processing is absolutely necessary then it might be better to use an ordinary `<input type="file">` element instead.

**Comment by MikhailTymchukDX** [comment]
Feel free to reopen this issue if you need further assistance.
