### ISSUE TITLE
Update hyperlinks in SampleSite

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/AjaxControlToolkit#169]
We have outdated links pointing to CodePlex.

"AJAX Control Toolkit Project Page" in Default.aspx

"Animation Reference" in
- DropDown.aspx
- ListSearch.aspx
- PopupControl.aspx
- UpdatePanelAnimation.aspx
- AutoComplete.aspx
- HoverMenu.aspx
- ValidatorCallout.aspx
- Animation.aspx

**Comment by MikhailTymchukDX** [comment]
Outdated. See #193 for details.
