### ISSUE TITLE
Ajax ComboBox ItemList rendering issue

### ISSUE THREAD

**Issue by GMan4911** [DevExpress/AjaxControlToolkit#171]
AjaxControlToolKit 16.1
VS Development web server/browser
FireFox

If the ComboBox is a child of an asp:Panel with scrolling enabled, the ItemList dropdown is rendered in an incorrect position anytime the Panel is scrolled.  In the attached screencapture, the blue ItemList belongs to the "Access Restrictions" ComboBox.
![capture](https://cloud.githubusercontent.com/assets/20495559/16897862/d489d038-4b8d-11e6-99a2-d1923df88a30.JPG)

**Comment by MikhailTymchukDX** [comment]
I suggest you apply the `position: relative` rule to a parent container of the ComboBox to fix the issue.

Check this idea and let us know your results.
