### ISSUE TITLE
The HTMLEditorExtender cannot handle certain html tags

### ISSUE THREAD

**Issue by gidmeister2** [DevExpress/AjaxControlToolkit#172]
Suppose I put in some "MathML" tags (MathML produces mathematical formulas).  So I put:
```html
<mrow class="MJX-TeXAtom-ORD">
<mstyle displaystyle="true" scriptlevel="0">
</mstyle>
</mrow>
```
The result, unfortunately, is this:
```html
<mrow class="MJX-TeXAtom-ORD"</mstyle></mrow>
```
Notice that the end bracket is missing from the mrow tag, and the “mstyle” tag is gone completely.

When I click a SUBMIT button and read out the text into a variable, the contents of the variable have the messed-up result.

This means that the extender can’t handle language additions such as MathML (used to portray math formulas), and probably not SVG (vector graphics) either.

MathML is not supported by all browsers, and often people use JavaScript libraries to fudge a result that looks OK on those browsers.  But even if the A.C.T encounters new or unknown tags, they should be left as is,  as opposed to merging some and deleting others.

There are two views in the `HTML Editor Extender` – one of them is SOURCE view – that is how I pasted in the tags.

The above of course is just a snippet of math, a full formula (that it was taken from) looks like:

 ```html
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="upper F left-parenthesis x right-parenthesis equals integral Subscript a Superscript x Baseline f left-parenthesis t right-parenthesis d t period">
<mrow class="MJX-TeXAtom-ORD">
<mstyle displaystyle="true" scriptlevel="0">
<mi>F</mi>
<mo stretchy="false">(</mo>
<mi>x</mi>
<mo stretchy="false">)</mo>
<mo>=</mo>
<msubsup>
<mo>?</mo>
<mi>a</mi>
<mi>x</mi>
</msubsup>
<mi>f</mi>
<mo stretchy="false">(</mo>
<mi>t</mi>
<mo stretchy="false">)</mo>
<mi>d</mi>
<mi>t</mi>
<mo>.</mo>
</mstyle>
</mrow>
</math>
```
So if I have a page with an extender as follows:
```html
<asp:TextBox ID="TextBoxContents" runat="server" TextMode="MultiLine" 
                 Height="500px" Width="900px" style="max-width:900px" ></asp:TextBox>

        <ajaxToolkit:HtmlEditorExtender ID="HtmlEditorExtender1"  EnableSanitization="false" 
            TargetControlID="TextBoxContents" DisplaySourceTab="true"   runat="server">
          </ajaxToolkit:HtmlEditorExtender>
</asp:TextBox>
```
and  a SUBMIT button that submits the contents of the textbox – that’s when I run into the bug..

Is there any way to quickly fix this?

**Comment by Seteh** [comment]
Hi @gidmeister2, 

The issue lies [in this line of code](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/HtmlEditorExtender/HtmlEditorExtender.cs#L168) and there is no way to quickly overcome this behavior.

**Comment by gidmeister2** [comment]
I would think that it could be fixed by replacing:
` result = Regex.Replace(result, "[^<]<[^>]*script[^>]*>", "", RegexOptions.IgnoreCase | RegexOptions.ECMAScript);
by something like:
` result = Regex.Replace(result, "[^<]<[\s]*script[^>]*>", "", RegexOptions.IgnoreCase | RegexOptions.ECMAScript);`
But I am not sure.  Or, the regex could be replaced by a custom function that is more specific.
I have forked the Ajax Control Toolkit and will try replacing the line, and see if it helps, but I would suggest that the main coders of the ACT take a look at it.

**Comment by Seteh** [comment]
@gidmeister2  thank you for the advice, we'll take it into account.
