### ISSUE TITLE
Minify files on the save operation in VS 2015

### ISSUE THREAD

**Issue by MikhailTymchukDX** [DevExpress/AjaxControlToolkit#175]
[Bundler & Minifier](https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40) does not minify files on saving
I suggest adding a custom gulp task that does the same for developers that use VS 2015.

**Comment by AlekseyMartynov** [comment]
Also check how new .NET Core projects work. They have bundleconfig.json and aren't using Gulp anymore.
