### ISSUE TITLE
Norton flagged Ajax Control Toolkit as being dangerous!

### ISSUE THREAD

**Issue by gidmeister2** [DevExpress/AjaxControlToolkit#181]
Hi,
today I got a message that: AjaxControlToolkitVsPackage.dll was dangerous.  I got this from a Norton security product (Norton Security Scan).  I'm not sure if this file was from your codeplex page.  In fact, earlier this morning I noticed a menu item in visual studio that asked if I wanted VB version 14, and I said yes, and it installed an extension.  Perhaps it installed this one.  
Anyway, I thought I'd let you know.

**Comment by AlekseyMartynov** [comment]
Hi
Thank you for contacting us.

Here is a VirusTotal scan of AjaxControlToolkitVsPackage.dll from the current 16.1 installer (zero detection rate):

https://www.virustotal.com/en/file/14ae37b8d3c0cd706d738169ecdf31b7090ba56454a8f79f9ae29148ea362d9b/analysis/1469564838/

I suggest that you perform a full anti-virus scan of your machine and then reinstall the Toolkit from this link: https://go.devexpress.com/AjaxControlToolkit_Website_Download.aspx

**Comment by gidmeister2** [comment]
I just ran McAfee, which did not find anything, and I'm now running malwarebytes.  I see that you also ran Symantec, and it found no problem.  So its a mystery.  Anyway, thanks for checking.
