### ISSUE TITLE
ACT 16.2

### ISSUE THREAD

**Issue by PerseusTheGreat** [DevExpress/AjaxControlToolkit#183]
Hi,
When ACT 16.2 will be released?
Please add a new roadmap part to wiki section and please provide descriptions about your future programs or releases or etc... there.
Thanks.

**Comment by Mehul** [comment]
Hi,
In general, we release about 2-3 releases per year of the ASP.NET AJAX Control Toolkit. We don't have plans for a roadmap however, can you tell me what you're looking for in the toolkit and I'll tell you if it's something we have planned.

**Comment by PerseusTheGreat** [comment]
Hi,
Since ACT 16.1, many errors, bugs, defects and etc... have been fixed, but developers should build new releases manually to use these changes.
I think official releases of ACT should be scheduled for seasons like other DevExpress UI Frameworks.

I apologize, I'm beginner in English.

**Comment by Mehul** [comment]
Thanks for the feedback, we'll consider having a definite schedule. For now, please keep an eye on my blog: https://devexpress.com/Mehul for info on ASP.NET AJAX Control Toolkit releases. Thanks.
