### ISSUE TITLE
Ajax extensions work on local machine but not on web

### ISSUE THREAD

**Issue by jonathn6** [DevExpress/AjaxControlToolkit#186]
I have a web site which I am developing in visual basic.  I use Visual Studio 2015 community and have installed the most recent version of the Ajax toolkit.  I am using master pages as well.  I have the following line of code right after the <%@ Page ....%> tag:

`<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>`

I also have the following code within my main content tage:

`<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>` 

I am making use of the <ajaxToolkit:CalendarExtender> and the <ajaxToolkit:MutuallyExclusiveCheckBoxExtender>.

Both extenders work fine when I test them on my development machine.  When I build my application and put the resuting files to my web server, the extenders fail to work.

What am I missing?

Thank you,
Jonathan

**Comment by MikhailTymchukDX** [comment]
Hi @jonathn6 ,
There can be various reasons for that situation.

Would you please check the console and network tabs of the browser's development tools (F12 ) for errors?
