### ISSUE TITLE
AjaxFileUpload: Question about the auto start upload when file is selected

### ISSUE THREAD

**Issue by Garfieldcc** [DevExpress/AjaxControlToolkit#191]
I got a question about the AjaxFileUpload component.

I have viewed the documentation and found that there are a property called "AutoStartUpload", but i cannot find in my VS2015. 

Is there any solutions about this issue, or better ways to do that?

**Comment by MikhailTymchukDX** [comment]
Hi @Garfieldcc 
Thank you for this notice.
This property relates to [the latest version](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs#L159) of the source code which is not released yet.

We'll get wiki in sync with the next release once it is published to avoid confusion.

**Comment by MikhailTymchukDX** [comment]
The [v16.1.1 is released](https://community.devexpress.com/blogs/aspnet/archive/2016/08/11/asp-net-ajax-control-toolkit-v16-1-1-the-power-of-continuous-integration.aspx), and the [control documentation](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload) is up to date now.
