### ISSUE TITLE
populate HTMLEditorExtender from codebehind

### ISSUE THREAD

**Issue by dominicafonso** [DevExpress/AjaxControlToolkit#194]
My understadning is that the HTMLEditorExtender causes two div elements to but placed in the page. When the client puts some content in the content div, and sends it back to the server, the server receives a html version of that content, i.e the version from the source div. I want to store that content and send it back to another textbox (with HTMLEditorExtender) in a different place/page. The problem is that what comes back is the html, but it gets placed in the content div rather than the source div.

If i do something in the codebehind to store the textbox.text and then send it to a diferent a textbox then my content gets converted to html. I'm happy that this isn't a bug, but rather the main feature of the extender.

So, is there a way to populate the source div from the codebehind?

My reason for doing this is that i want to allow text and pictures to be typed/pasted into a single container and have the formatting preserved.

**Comment by MikhailTymchukDX** [comment]
Yes, you are right, HtmlEditorExtender sends encoded HTML to and from the server to populate the content div.
It has no built-in capabilities for populating source div, because source tab is optional and only content tab is always present.
 
Would you please describe your scenario in greater detail?

The goal can be achieved with the HtmlEditorExtender, but it will be a complex solution.
We'll try to find an easier approach.

**Comment by dominicafonso** [comment]
The goal is to give a user a box where they can write a message and paste an image if they want to. It for feedback on a website. I am storing the data in sql and then listing it in a page. The sql part is ok and text with fancy formatting is fine. I just can't get he image to display. I've tried sending the stored html to a new div in the page as htmlgenericcontrol.innerhtml rather than back to a textbox and it almost works, but the image doesn't get drawn.

If i return the html to the textbox with entender i can copy it, paste it to the source tab and when i return to the content tab the pic gets drawn.

**Comment by dominicafonso** [comment]
some additional info. I have created a small example to demonstrate the current behaviour.

The are two stages:
1) User input - here everything looks as intended
2) Server response - this is what comes back from the server

Here is the html that actually appears in the page, grabbed using the browser developer tools.

html for content tab

`<div class="ajax__html_editor_extender_texteditor" style="height: 258px; overflow: auto; clear: both; visibility: visible;" id="ContentPlaceHolder1_improvementlist_imp_desc_HtmlEditorExtender_5_ExtenderContentEditable" contenteditable="true">text<br><a href="link.com">link</a><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVQImWNQ0o9BRgwU8gGejBDmY/IxUwAAAABJRU5ErkJggg==" alt=""></div>`

html for source tab

`<div class="ajax__html_editor_extender_texteditor" style="height: 258px; overflow: auto; clear: both; visibility: hidden; display: none;" id="ContentPlaceHolder1_improvementlist_imp_desc_HtmlEditorExtender_5_ExtenderContentEditable" contenteditable="true">text<br><a href="link.com">link</a><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVQImWNQ0o9BRgwU8gGejBDmY/IxUwAAAABJRU5ErkJggg==" alt=""></div>`

text in source tab

`text<br><a href="link.com">link</a><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVQImWNQ0o9BRgwU8gGejBDmY/IxUwAAAABJRU5ErkJggg==" alt="">`


response

html for content tab

`<div class="ajax__html_editor_extender_texteditor" style="height: 258px; overflow: auto; clear: both;" id="ContentPlaceHolder1_improvementlist_imp_desc_HtmlEditorExtender_5_ExtenderContentEditable" contenteditable="true">text<br><a href="link.com">link</a><br>&lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVQImWNQ0o9BRgwU8gGejBDmY/IxUwAAAABJRU5ErkJggg==" alt=""&gt;</div>`

html for source tab

`<div class="ajax__html_editor_extender_texteditor" style="height: 283px; overflow: auto; clear: both; visibility: visible;" id="ContentPlaceHolder1_improvementlist_imp_desc_HtmlEditorExtender_5_ExtenderSourceView" contenteditable="true">text&lt;br&gt;&lt;a href="link.com"&gt;link&lt;/a&gt;&lt;br&gt;&amp;lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVQImWNQ0o9BRgwU8gGejBDmY/IxUwAAAABJRU5ErkJggg==" alt=""&amp;gt;</div>`

text in source tab

`text<br><a href="link.com">link</a><br>&lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVQImWNQ0o9BRgwU8gGejBDmY/IxUwAAAABJRU5ErkJggg==" alt=""&gt;`

So the only difference is the
`<img>` tag is converted to `&lt; img &gt;`

**Comment by MikhailTymchukDX** [comment]
Thank you for this clarification.
Unfortunately, I cannot reproduce this markup change.
Would you please attach a sample project that illustrates this issue?
 
Based on your previous posts I would suggest using simple div with separate file upload controls for the feedback form, provided this feedback is not visible to public.

**Comment by dominicafonso** [comment]
I have just updated my version to a much newer version and am still getting some odd results. 

if i go for an image pasted in with no text or text after the image it works fine.
if i put some text before the image then the image simply disapears when the content is sent to and return from the server.

i'll test with the newest version of the toolkit as soon as i can get a copy installed

I wasn't able to get the latest version because the download link is dead on this page: http://cdn.devexpress.com/Release/ACT/16.1/20160811/AjaxControlToolkit.Installer.16.1.1.exe
giving this response:
 This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>MissingKey</Code><Message>Missing Key-Pair-Id query parameter or cookie value</Message></Error>

**Comment by MikhailTymchukDX** [comment]
@dominicafonso Thank you for pointing out this link to us! We are fixing it.
You can download the installer from the GitHub release as well: https://github.com/DevExpress/AjaxControlToolkit/releases/download/16.1.1/AjaxControlToolkit.Installer.16.1.1.exe

As for the HTML change, the extender performs [a set of replacements](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/HtmlEditorExtender/HtmlEditorExtender.cs#L160-L201) to remove malicious markup. This is the reason why the part of the initial markup may disappear.

**Comment by MikhailTymchukDX** [comment]
Feel free to reopen this issue if you have any questions regarding it.
