### ISSUE TITLE
AsyncFileUpload generates a new Session ID when a cookieless session is enabled

### ISSUE THREAD

**Issue by karl611** [DevExpress/AjaxControlToolkit#203]
I want to use AsyncFileUpload inside ModalPopupExtender, for the moment it works, but when I leave the ModalPopupExtender I see that the session is lost, there is a new session ID. My web application uses these settings:

    <sessionState mode="InProc" timeout="20" cookieless="true"/>
    <authentication mode="Windows"/>

Best regards, Matthias

**Comment by MikhailTymchukDX** [comment]
Hi @karl611 
Would you please provide a sample project that illustrates this issue?

**Comment by karl611** [comment]
I prepared a sample project. You can click on the button and upload a pdf file, then you leave the ModalPopupExtender by "OK". When you click next time on "Show ModalPopupExtender" you see in the URL that session ID has changed.

[WebApplication1.tar.gz](https://github.com/DevExpress/AjaxControlToolkit/files/429831/WebApplication1.tar.gz)
