### ISSUE TITLE
BarChart is not rendered on a webpage when ClientIDMode is set to AutoID

### ISSUE THREAD

**Issue by htm-git** [DevExpress/AjaxControlToolkit#211]
I am getting an error with the Bar Chart after deploying a web page to Server 2012 R2.

 Unhandled exception at line 437, column 9 in http://localhost:61100/PartechTrans/ScriptResource.axd?d=z48y4oai1GgZ_a25brgQ9zD7rMfezY4sEp5Qnn37-rlZ89uRTV-Wsg-lM4_ZNzOWQ2VmVspM40ER72YqFszMf_2pESipSyouigdyVNX1wTvW4j2EqGJHpzdepIG3HgYn0&t=ffffffffcfeeeb28

0x800a138f - JavaScript runtime error: Unable to set property 'innerHTML' of undefined or null reference

Everything works perfectly on the DEV PC. 

From any web browser, accessing the page there is only a line across the page where the control should render. The data is being retrieved and is identifiable in View Source, but the control is not present.  

this line is where the error halts execution, when attempting to view the page on the test server within VS.

ln 437 =   this._parentDiv.innerHTML = svgContents;

I have an image attached.  

This is a fully deployed web site that is working, this was just adding a new page. The control is on an aspx page which has 2 master page levels. The first provides the navigation panel, and the top level parent master page provides the site header and other logo and login controls.

https://www.devexpress.com/Support/Center/Attachment/GetAttachmentFile/bd33d5f7-7082-11e6-80bf-00155d62480c

**Comment by htm-git** [comment]
title was an error, I don't seem to be able to edit it.

**Comment by MikhailTymchukDX** [comment]
Hi @htm-git,
Thank you for posting this issue.
I tried to reproduce it using the information you provided but did not manage.

Would you please clarify the following:
* The AJAX Control Toolkit version you are using.
* The site root URL and page URL with BarChart.
* The browser(s) you are using.

A sample project that illustrates this issue would be also of great help to quickly identify the problem.

**Comment by htm-git** [comment]
toolkit is ver 16.1.1
The site is test server on our local LAN. On that server I have installed VSExpress2012 for debugging issues like this.

When the site is accessed from any PC on our LAN using the internal URL everything works accept the control renders in the browser (EDGE) as a straight line where the graph should appear.  The data is listed in the page source as indicated above. This site tests a large number of functions from web services to SQL connectivity, its been online for 5 years, upgraded from Server 2008 to 2012 R2.

Tested the page in Chrome, Firefox, and IE11 as well.

**Comment by MikhailTymchukDX** [comment]
>using the internal URL 

Would you please provide this URL? If it contains sensitive data, remove it so I'm able to understand the structure of the project.

Also, please provide a markup for BarChart that is used to display it.

**Comment by htm-git** [comment]
the url is internal.

http:\\aspdemosvr2

It is resolved internally by DNS.

**Comment by htm-git** [comment]
Are you using Master Pages?

**Comment by MikhailTymchukDX** [comment]
Hi @htm-git ,
Yes I'm using Master Pages, but cannot get the result similar to yours.

I've attached a sample project to make sure we run the same code in our environments:
[BarChartTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/454584/BarChartTest.zip)

Please deploy this project to your IIS and check if the problem persists.

Also, I noticed a `ctl00_` prefix in the control ID.
Would you please execute the `this.get_id()` method while debugger is at line 7 and show me the result?

**Comment by htm-git** [comment]
I hope this is what you are looking for. Please let me know if you need something else.

And my control has 2 levels of Master Pages, if they makes a difference in your test project. I will try to set that up now and past back soon.

![image](https://cloud.githubusercontent.com/assets/21956309/18272888/6f852248-7408-11e6-991a-a273600115a1.png)

**Comment by MikhailTymchukDX** [comment]
@htm-git thank you for that info.
I was able to reproduce this error by adding the following attributes to the `system.web/pages` element in Web.config:
```xml
<pages controlRenderingCompatibilityVersion="4.0" clientIDMode="AutoID">
```

This forces ASP.NET to generate `ctl00_` prefix that is removed by the script, making `getElementById()` call invalid.
Here is a sample project which illustrates this issue: [BarChartTest2.zip](https://github.com/DevExpress/AjaxControlToolkit/files/456665/BarChartTest2.zip)

If you have these settings applied in your project, please remove them and see the result.
I look forward to your response.

**Comment by htm-git** [comment]
I have some issues running your project on my dev server. And am still working to test on DEV PC. I believe you created it with .Net 4.5 and my environments are both still 4.0. 

I believe my first concern would be to make this a page level change, as I am sure you could image that such a global change would have an impact on the overall sites operation.

Do you know how I can remove these at the page level itself?

**Comment by htm-git** [comment]
Removing just the clientIDMode="AutoID" attribute from the web config <pages property corrected the display of the bar chart. I am investigating the impact on the remainder of the site.

**Comment by MikhailTymchukDX** [comment]
OK, this means that for .NET 4.0 projects, only the `ClientIDMode` affects ID generation.
You can set `ClientIDMode` to `Predictable` in code-behind for a particular page:
```
Page.ClientIDMode = ClientIDMode.Predictable
```
or particular control:
```
BarChart1.ClientIDMode = ClientIDMode.Predictable
```

You can also set it for a page using the @Page directive:
```aspx
 <%@ Page ClientIDMode="Predictable" %>
```
For more information about `ClientIDMode`, please refer to this MSDN article: https://msdn.microsoft.com/en-us/library/system.web.ui.clientidmode%28v=vs.100%29.aspx

**Comment by htm-git** [comment]
Thank you for all of your help, I think this is resolved.

**Comment by MikhailTymchukDX** [comment]
@htm-git Not yet. We provided you with a workaround, but [the code that caused this error](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/BarChart.js#L6) still exists.

At the moment, we are evaluating if it was added for some special purpose and whether it is safe to remove it.

**Comment by htm-git** [comment]
Here is an update, I made the code changes as described to the web config. The page renders correctly in Edge, FF, Chrome, but NOT IE 11.

**Comment by MikhailTymchukDX** [comment]
That's strange, because setting `ClientIDMode` to `Predictable` fixes my sample application for all browsers, including IE 11.

Would you please show the page rendered markup in IE 11?

**Comment by htm-git** [comment]
Well, I retested and first time I got a break on the SVG non compatible browser error message, but now it is working in IE 11.

**Comment by htm-git** [comment]
Well, I retested and first time I got a break on the SVG non compatible browser error message, but now it is working in IE 11.

**Comment by htm-git** [comment]
Well, I retested and first time I got a break on the SVG non compatible browser error message, but now it is working in IE 11.
