### ISSUE TITLE
AjaxFileUpload prevents a page's Load event from firing

### ISSUE THREAD

**Issue by jaxjurgas** [DevExpress/AjaxControlToolkit#213]
Trying out AjaxFileUpload Demonstration on the http://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx site
It returns an error
Got the same in my application

please Help
![2016-09-05 1](https://cloud.githubusercontent.com/assets/22019740/18262250/aff34d04-73b4-11e6-85e8-2bc008f8c860.png)

**Comment by MikhailTymchukDX** [comment]
Hi @jaxjurgas,
Thank you for reporting this issue. We are investigating it.

Would you please also provide the following info?
* Specify the AJAX Control Toolkit version you are using.
* Page markup with AjaxFileUpload.
* The Web.config `system.webServer/handlers` section content.
* A site deploy method (VS development web-server, IIS). 
* A screenshot of the error in the console of your browser.
 
It would be of a great help if you create a sample project that illustrates this issue.
I look forward to your response and appreciate your cooperation.

**Comment by MikhailTymchukDX** [comment]
We have fixed the [AjaxFileUpload demo](http://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx) on the Sample Site.

**Comment by brunchto** [comment]
got an error also with v16.1.1. it was ok with 16.1.0
it seems that page events are no more executed with v16.1.1.0 so i cannot regen my context and the destination folder.
by the way, it will be really cleaner if we could pass context data within the uploader...

**Comment by MikhailTymchukDX** [comment]
Hi @brunchto ,
Would you please provide a sample project that illustrates this issue?

**Comment by brunchto** [comment]
Hi, 

with v16.1.0, when i click on "upload", default_load (with
.IsInFileUploadPostBack=true) is executed, so path is initialized for
the uploadComplete event. 

with v16.1.1, only uploadComplete event is executed. 

Bruno 

Le 2016-09-12 17:10, MikhailTymchukDX a écrit : 

> Hi @brunchto [1] ,
> Would you please provide a sample project that illustrates this issue? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3]. 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DevExpress/AjaxControlToolkit","title":"DevExpress/AjaxControlToolkit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DevExpress/AjaxControlToolkit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MikhailTymchukDX in #213: Hi @brunchto ,\r\nWould you please provide a sample project that illustrates this issue?"}],"action":{"name":"View Issue","url":"https://github.com/DevExpress/AjaxControlToolkit/issues/213#issuecomment-246379593"}}}
 

Links:
------
[1] https://github.com/brunchto
[2]
https://github.com/DevExpress/AjaxControlToolkit/issues/213#issuecomment-246379593
[3]

**Comment by MikhailTymchukDX** [comment]
Hi @brunchto ,
We changed request handling by the `AjaxFileUpload` in PR #123 

As a result, page processing ends during the `AjaxFileUpload.Init` event and the `Page.Load` event does not fire.
This is intended, because the `AjaxFileUpload` and the page itself is not in a correct state during these requests.

This also means that `IsInFileUploadPostBack` property cannot be used to determine the file upload phase, so it will be deprecated.

In this situation, you can use the `AjaxFileUpload.UploadStart` event to detect the beginning of the file upload and store information in a Session object. I've updated your sample project to demonstrate this: [WebSite7_1.zip](https://github.com/DevExpress/AjaxControlToolkit/files/470262/WebSite7_1.zip)

Please let me know if this helped you.

**Comment by rdurrance** [comment]
I know that this is an old thread but putting it in a session variable does not work because the page does not postback to get the variables. Is there a solution with the newer version?
Thank you
