### ISSUE TITLE
AjaxFileUplaod  doesn't work on server 

### ISSUE THREAD

**Issue by Phantom2** [DevExpress/AjaxControlToolkit#214]
Ich have two webs with pages including AjaxFileupload. Both pages work properly in the devenv VS2013 with the built-in webserver.
When publishing the webs to a 2008r2 server, the AjaxFileuplaod shows an error. Ich can drop the file, but downloading will not start.

**Comment by MikhailTymchukDX** [comment]
Hi @Phantom2 ,

Would you please check your site root URL and apply [this workaround](https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203889967) if needed?

You can also [get the latest build of the AJAX Control Toolkit](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) and set upload URL explicitly with the new `UploadHandlerPath` property.

**Comment by Phantom2** [comment]
Hi @MikhailTymchukDX 

Thanks for your help, I've inserted UseAbsolutehandlerPath="false" to my fileuplaods.
<cc1:AjaxFileUpload ID="AjaxFileUpload1" runat="server" UseAbsolutehandlerPath="false" ...

Could you please add this property ("UseAbsolutehandlerPath") to
https://ajaxcontroltoolkit.codeplex.com/wikipage?title=AjaxFileUpload&referringTitle=Reference

best regards
Klaus

**Comment by MikhailTymchukDX** [comment]
I'm happy to hear that the problem is solved.

The wiki is moved from CodePlex to GitHub, so an up-to-date AjaxFileUpload reference is available here: https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload
