### ISSUE TITLE
Question regarding ClientScriptResource and ASCX controls

### ISSUE THREAD

**Issue by cshomo11** [DevExpress/AjaxControlToolkit#216]
Hi,

I am in the process of trying to update our code base to .Net 4.6.1 and also update the Toolkit from 4.6 to 16.1 (I know, this is far from ideal). So far I have been able to get most controls to build and function correctly with the exception of around 6 ascx controls. The team that build these controls back in 2009-2010 used the ClientScriptResource tag along with the ScriptUserControl in the Toolkit to embed javascript files that handled all of the control's AJAX. I removed all references to the ScriptUserControl and the controls build but the embedded javascript files are no longer being loaded into the browser. All of the controls were setup as follows:
`<Assembly: WebResource("ProjectName.OrderQuantityBehavior.js", "text/javascript")> 
<ClientScriptResource("ProjectName.OrderQuantityBehavior", "ProjectName.OrderQuantityBehavior")> _
Partial Public Class OrderDatesAndQuantityControl`

The javascript files are located in a subfolder where all of the controls are located, specifically Controls/App_LocalResources/Scripts. I have tried different paths, different namespaces, and moving files around and I cannot find anything that will load the JS correctly. The frustrating part is that I can't even get an error to throw. No console errors, no Visual Studio exceptions, nothing. Is this a simple issues of the paths needed changed or is there something else I need to add to get these javascript files back into the browser?

**Comment by MikhailTymchukDX** [comment]
Hi @cshomo11,
Thank you for contacting us with such an interesting issue!

The ScriptUserControl, which is derived from the UserControl, was removed from the AJAX Control Toolkit in v15.1.
This means it is not affected by the control processing pipeline of the toolkit, despite you applied proper attributes to your custom control and embedded valid scripts in the assembly.

To return these controls into the toolkit flow, you need to derive them from the [`ScriptControlBase`](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/ExtenderBase/ScriptControlBase.cs) class.
Please refer to this article for more details: [Creating a custom control](https://github.com/DevExpress/AjaxControlToolkit/wiki/Creating-a-custom-control).

If such a conversion is not possible, the only way to load these scripts is to make it explicitly.
For example, you can use the [`ClientScriptManager.RegisterClientScriptResource`](https://msdn.microsoft.com/en-us/library/system.web.ui.clientscriptmanager.registerclientscriptresource(v=vs.110).aspx) method to register required scripts or any other method that suit you needs.

Please don't hesitate to contact me if you need additional information regarding the upgrade process.

**Comment by cshomo11** [comment]
Mikhail,

Thanks for the speedy reply. I changed the ascx control’s inherited base class to inherit from ScriptControlBase instead of UserControl but now I am confronted with this error.
[cid:image001.jpg@01D20851.6DA07090]

Neither ScriptControlBase or ExtenderControlBase inherit from UserControl.  I don’t know if there is anything else I can do with that or if I should just move on to the ClientScriptManager method you also recommended.

**Comment by MikhailTymchukDX** [comment]
@cshomo11 
I don't see the image. Would you please submit it again?

**Comment by cshomo11** [comment]
Sorry, I sent it as an attachment this time.

**Comment by MikhailTymchukDX** [comment]
Nope, still no image.
It seems that GitHub email relay can not put mail attachments to the web site posts.

Would you please use the site to upload the image or provide a public link to that image?

**Comment by cshomo11** [comment]
Ah okay, here is a link to the error image. https://postimg.org/image/osrjkdkzz/

**Comment by MikhailTymchukDX** [comment]
Thank you for the image.
As the error message states, you cannot use an arbitrary class with the @**Control** directive, because it implies that the class is derived from the `System.Web.UI.UserControl` class.

Converting `UserControl` to `ScriptControlBase` requires changing the architecture of the application.
It's currently difficult to guess how complex your control is, so it would be nice if you provide a code sample that illustrates your controls' structure.

**Comment by cshomo11** [comment]
This control is pretty complex. It has several date fields that all interact with one another and also complies an order quantity amount based on the days selected. Between this and the 4 or 5 other controls built this way, I don't know if we would currently have the time to change the architecture. I will have to try the other method you described yesterday using the RegisterControlScriptResource and see if that might help. Thank you for your help!
