### ISSUE TITLE
AjaxFileUploadHelper.RootTempFolderPath - replace with a web.config setting

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/AjaxControlToolkit#22]
Discussion started in PR https://github.com/DevExpress/AjaxControlToolkit/pull/14.

Proposal: expand `AjaxControlToolkitConfigSection` with a child element for various upload settings.

**Comment by MikhailTymchukDX** [comment]
@AlekseyMartynov 
There is no need to make it global setting. Let's make it instance property.

**Comment by AlekseyMartynov** [comment]
Global setting is more convenient if there are plenty of upload controls in the app.

**Comment by MikhailTymchukDX** [comment]
There can be plenty of controls of any type in the app.
Why introduce global setting for upload control?

**Comment by AlekseyMartynov** [comment]
Well, temp path is by its nature a global setting. Cannot imagine a scenario when it would be useful to change it for a single control.
