### ISSUE TITLE
HTMLEditorExtender image upload

### ISSUE THREAD

**Issue by bjthomson** [DevExpress/AjaxControlToolkit#227]
Similar to https://github.com/DevExpress/AjaxControlToolkit/issues/43

### Minimal steps to reproduce the bug
Created a minimal web site, 1 page, dropped the HtmlEditorExtender on it. Attached it to a text control.
Added the full Toolbar suite, including the image upload.
Added the entry in web.config 
&lt;handlers&gt;
      &lt;add name="AjaxFileUploadHandler" verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit"/&gt;
    &lt;/handlers&gt;
in the code-behind (c#) Added an event handler for ImageUploadComplete 
ran the page, F12'd the browser diagnostic, tried to add an image.
It never got as far as the c# event - got client error.
Console window says:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)POST - http://localhost/AjaxFileUploadHandler.axd?contextKey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&controlID=HtmlEditorExtender1_ajaxFileUpload&fileId=0D5BC50A-7072-01F0-9AE0-84BF1D1D27C2&fileName=crash_test_dummy.jpg&chunked=false&firstChunk=true
SCRIPT5022: error raising upload complete event and start new upload
ScriptResource.axd (1468,21)

Since it seems to be looking for the handler to be installed in the default web site, I did that, 
tried again
HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - http://localhost/AjaxFileUploadHandler.axd?contextKey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&controlID=HtmlEditorExtender1_ajaxFileUpload&fileId=EC3088A9-8133-7BAD-D315-BEB9C32DBAAC&fileName=Crown.jpg&chunked=false&firstChunk=true
SCRIPT5022: error raising upload complete event and start new upload
ScriptResource.axd (1468,21)

I also tried adding  a path to the entry in web.config
<add name="AjaxFileUploadHandler" verb="*" path="TestHTMLEditorExtender/AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit"/>
### A site deployment method
- [ ] VS development web-server,
- [ ] IIS
### Also gave the IIS AppPool\DefaultAppPool user full control on C:\Windows\Temp, as suggested in various places.
[TestHTMLEditorExtender.zip](https://github.com/DevExpress/AjaxControlToolkit/files/491635/TestHTMLEditorExtender.zip)

**Comment by bjthomson** [comment]
(By the way requiring a change of permissions on the temp folder is not a good idea when the site is running in a shared host / Azure)

**Comment by MikhailTymchukDX** [comment]
Merged with #168
Please download the [AppVeyor CI master branch artifacts](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/branch/master/artifacts) or apply a workaround described here: https://github.com/DevExpress/AjaxControlToolkit/issues/168#issuecomment-236840248
