### ISSUE TITLE
ModalPopupExtender cannot extend the HiddenField control

### ISSUE THREAD

**Issue by ManuelPadovani** [DevExpress/AjaxControlToolkit#228]
### The installation method
NuGet package

### Minimal steps to reproduce the bug
Extend a modalpopupextender with an hidden field. so i can manage from codebehind some function before show the popup.

### Actual result
Error 500: Generata eccezione di tipo 'System.Web.HttpUnhandledException'. L'estensione 'ModalPopupExtender_Modifiche' non può estendere 'hdf_Modifiche'. Le estensioni di tipo 'AjaxControlToolkit.ModalPopupExtender' non possono estendere i controlli di tipo 'System.Web.UI.WebControls.HiddenField'. 
extension modalpopupextender_modifiche can not extend hdf_modifiche. the extension of type modalpopupextender can not extend control of type hiddenfield.

### Expected result
In every previous versions this worked great.

### Browser(s) used
any

### A site deployment method
IIS

[ASPX_FILE.txt](https://github.com/DevExpress/AjaxControlToolkit/files/492585/Nuovo.documento.di.testo.txt)

**Comment by MikhailTymchukDX** [comment]
Fixed in #229
