### ISSUE TITLE
AjaxFileUploadHandler.axd not found in subsite

### ISSUE THREAD

**Issue by EdwinRoestenburg** [DevExpress/AjaxControlToolkit#231]
### The installation method
- [X] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Create subsite of Default Web Site in IIS
Add ajaxfileupload control to a usercontrol on a page in the subsite

### Actual result
The AjaxFileUploadHandler.axd will be search in the root site, and it won't be found there, because it lives in the subsite.
Logging from IIS:
... POST /AjaxFileUploadHandler.axd contextKey=.... 404 0 2 8

### Expected result
The AjaxFileUploadHandler.axd should be found at the level where is has been added.

### Browser(s) used
Internet Explorer 11

### A site deployment method
- [ ] VS development web-server,
- [X] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @EdwinRoestenburg ,
AjaxFileUpload does not detect the site structure, so you need to specify the upload handler path explicitly using the `UploadHandlerPath` property:
```aspx
<ajaxToolkit:AjaxFileUpload
    runat="server"
    UploadHandlerPath="MyApplication/AjaxFileUploadHandler.axd" />
```

**Comment by EdwinRoestenburg** [comment]
I will give that a go, but that would mean that I would have to configure these settings for different environments. Depending on where I publish to, the application may or may not live in a subsite.

 

For now I reverted to the last 1.15 release, where this is not an issue.

 

Edwin.

**Comment by MikhailTymchukDX** [comment]
Would you please clarify what is the 1.15 release, so we can check it and see the difference with the current release?

**Comment by EdwinRoestenburg** [comment]
Sorry :( , I was too quick here. I meant release 15.1.4

 

E.
