### ISSUE TITLE
.Net Framework 4.6.1

### ISSUE THREAD

**Issue by DougRudd** [DevExpress/AjaxControlToolkit#239]
My organization will be remove the .Net 4.0 Framework from our environment. Is there are a 4.6.0 or 4.6.1 Framework version of the AjaxControlToolkit?

**Comment by MikhailTymchukDX** [comment]
Apparently, you cannot do this.

As [this post blog](https://blogs.msdn.microsoft.com/astebner/2015/06/17/a-couple-of-notes-about-net-framework-4-6-setup-behaviors/) states, the .NET Framework 4.6 is an in-place upgrade for all of the following versions of the .NET Framework:

* .NET Framework 4
* .NET Framework 4.5
* .NET Framework 4.5.1
* .NET Framework 4.5.2

So, AJAX Control Toolkit will continue to work as long as you have the .NET 4.6.1 Framework in your system.
