### ISSUE TITLE
Keep AjaxControlToolkit.SampleSite in sync with current version of ACT

### ISSUE THREAD

**Issue by savornicesei** [DevExpress/AjaxControlToolkit#24]
Hi,
The AjaxControlToolkit.SampleSite website should be converted to a Web Application (it's currently a classic web site) and it should reference either the assemblies from the /bin folder or directly the needed projects.

**Comment by MikhailTymchukDX** [comment]
The AjaxControlToolkit.SampleSite website already references projects inside the solution:
 ![image](https://cloud.githubusercontent.com/assets/17080984/13821473/ed3eff76-ebb2-11e5-8984-c310117ac1c9.png)

**Comment by savornicesei** [comment]
I'm pretty sure it was using old dll's on my local machine. I'll check this up on a fresh pull.

How about converting it to a Web App project?

Thanks,
Simo

**Comment by MikhailTymchukDX** [comment]
AJAX Control Toolkit is a set of extensions that runs on any type of a Web project.
Do you have any issues specific to the Website project type?

**Comment by MikhailTymchukDX** [comment]
Closed due to inactivity.
