### ISSUE TITLE
Ajax Calendar Extender causes "0x800a01bd - JavaScript runtime error: Object doesn't support this action"

### ISSUE THREAD

**Issue by JimInAz** [DevExpress/AjaxControlToolkit#241]
Working in VS Enterprise 2015 on a simple ASP.net webforms project and have a page with a standard text box and a calendar extender from AJAX Toolkit v16.1 (installed using the installer). When I run the project I get "0x800a01bd - JavaScript runtime error: Object doesn't support this action" on the calendar extender. Have found NOTHING useful on the web about this. Any clue what's happening or what I can do to fix it?
 -Yes, Ajax is installed correctly. I have Ajax combo boxes on the form and they're not causing any problems.

**Comment by MikhailTymchukDX** [comment]
Hi @JimInAz ,
Would you please provide a sample project that illustrates this issue?
