### ISSUE TITLE
Error reading labels

### ISSUE THREAD

**Issue by Phantom2** [DevExpress/AjaxControlToolkit#242]
I've inserted an AjaxFileUpload as AjaxFileUpload1 in an aspx-file:

div id="divFile"
cc1:AjaxFileUpload ID="AjaxFileUpload1" runat="server" UseAbsolutehandlerPath="false"
         MaximumNumberOfFiles=3 OnUploadComplete="AjaxFileUpload1_UploadComplete" OnUploadCompleteAll="AjaxFileUpload1_UploadCompleteAll" ThrobberID="myThrobber" OnUploadStart="AjaxFileUpload1_UploadStart" />
/div
 

My code is:

protected void AjaxFileUpload1_UploadComplete(object sender, AjaxControlToolkit.AjaxFileUploadEventArgs e)
        {
            string Nummer = lblVgNummer.Text;
            string Path = Ablage + Nummer + @"\";
            AjaxFileUpload1.SaveAs(Path + e.FileName.ToString());
        }

The line "string Nummer = lblVgNummer.Text;" reads a number from a label. The label ist initiated with "Text="2016-01-25-001" and is overwritten by a function that loads the current number from a database.
When I read "lblVgNummer.Text" it always returns the initiated number, but not the current number.

I'd be glad if anyone has an idea.

**Comment by MikhailTymchukDX** [comment]
Hi @Phantom2 ,

`UploadComplete` is a server side event. It is executed during [a page lifecyle](https://msdn.microsoft.com/en-us/library/ms178472.aspx?#Anchor_2), before Validation stage:

![aaa](https://i-msdn.sec.s-msft.com/dynimg/IC386473.png)

It means that if you don't store the label value between page requests, it will be always default.

Depending on your situation, you can store the required value in a [Session](https://msdn.microsoft.com/en-us/library/system.web.sessionstate.httpsessionstate.aspx) or query it from the database inside the event handler.

**Comment by Phantom2** [comment]
OK! Thanks!
I already tried to store the value in a hidden field, but that also did not work.
I'll try a session variable.

**Comment by Phantom2** [comment]
Hi! Session works! Thaks a lot.
I close the the request.
