### ISSUE TITLE
Update jasmine

### ISSUE THREAD

**Issue by savornicesei** [DevExpress/AjaxControlToolkit#25]
Hi,
I noticed ACT uses jasmine 2.2.0 but the latest version (2.4.1) allows tests to be run in random order.
I think it's a great addition to make sure tests are well defined.

Thanks,
Simo

**Comment by MikhailTymchukDX** [comment]
[TestRunner.aspx](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.Jasmine/TestRunner.aspx) page runs every spec separately inside the `iframe` element.
Specs are isolated, and only one spec from spec list is running every moment of time.

This is achieved with custom test reporter, that passes `specIndex` as a parameter to a page that contains tests:
```js
var specIndex = queryString.getParam("specIndex");

var env = jasmine.getEnv();
env.specFilter = function(spec) {
	return spec.id === "spec" + specIndex;
};
```

With this approach, test randomizing is not necessary.
