### ISSUE TITLE
"Access Denied" error during build

### ISSUE THREAD

**Issue by MV10** [DevExpress/AjaxControlToolkit#250]
In reference to v16.1.1.0, installed via NuGet command line, deployed to IIS 7.5 on Win8.1 Pro, targeting .NET 4.0:

The site is up and running in production, but it was copied to a dev workstation to begin migration to VS2013. That is the Win8.1 Pro / IIS 7.5 setup. Everything in the site (over 13,000 pages in a Kentico content-management system, it's a large city website) builds properly except anything with references to AjaxControlToolkit. The build process throws an "Access is Denied" error the first time it has to touch the toolkit.

The production site is actually on 16.1.0 which is what we started with in dev. I used NuGet to remove 16.1.0 then tried running the installer for 16.1.1 but I didn't see the demo project in IIS nor was I able to add a reference, so I forced the 16.1.1 version with the NuGet command line (without forcing the version, for some reason it would get 16.1.0 again, every time).

Based on various stackoverflow posts and similar discussions about this problem I think we're set up right as far as permissions go -- the site's Bin folder allows read/execute to IIS_[machine] and the various Temp ASP.NET Files folders in the Windows .NET subdirs allow access to the app pool identity -- though I don't believe that would impact build, only runtime execution. In the web.config impersonate is set to "true" which also apparently caused problems for some people, but again I assume that isn't a build concern.

The VISX portion does run, I'm not sure whether that uses the same DLL which ends up in the Bin folder. If I open an ASPX file the toolkit shows up in the toolbox and a quick test shows it'll insert the right tags into the file when I select a control.

We aren't sure how to proceed.

**Comment by MikhailTymchukDX** [comment]
HI @MV10 ,
Would you please check the following?
* Access rights to the `Bin` folder
* Pre- and post-build events, which can cause file locking
* Is local IIS on a dev machine running and does it use DLLs from the project's `Bin` folder?

**Comment by MV10** [comment]
Access rights appear to be correct.

IIS_[machine] has all permissions except Full on Bin and everything below it.

The project was newly Opened as a Web Site from IIS, so there isn't even an SLN folder. There are no pre/post Build events defined.

Yes, local IIS (7.5, not Express) and yes the web.config references DLLs from the Bin folder. The site is configured as a virtual with it's own app domain.

**Comment by MikhailTymchukDX** [comment]
Thank you for that info.

Setting access rights to IIS_[machine] account only is not enough, because you are likely to run Visual Studio IDE under user account.

So, please try the following:
* Set a `Full control` permission for the `Bin` folder for `Everyone`.
* Stop local IIS service before the compilation to make sure it does not lock any file.
* Download the [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) utility and try to find the process that uses AjaxControlToolkit.dll. If you find it, shut down that process.

After that you should be able to build the project without locking issues.
If it's not the case, please repeat the search in the Process Explorer to find out what process locks the file.

**Comment by AlekseyMartynov** [comment]
@MV10 if possible please attach a screenshot?
What is the path? Read or write error?

Here are some suggestions for solving a similar issue:
http://stackoverflow.com/q/4998136

**Comment by MV10** [comment]
@MikhailTymchukDX we'll give those a try, thanks. Since it's a content-management system, IIS is (unfortunately) configured to compile, and since it works in production (and our setup appears to mirror production) I'm not expecting IIS to have the file locked, but we'll certainly try everything!

@AlekseyMartynov the machine is pretty locked-down, I probably can't easily get a screenshot out. The path is simply: C:\Kentico\Bin ... although we've used a few other paths with the same result (we moved it there just last night to simplify our troubleshooting).

It appears to be a read problem (NuGet is able to refresh the file, if I rename or delete the DLL, for example, so other processes under VS are able to write there, but I can't think of a reason VS would be writing to that file in normal build conditions). The exact error message is:

Could not load file or assembly 'AjaxControlToolkit, Version=16.1.1.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e' or one of its dependencies. Access is denied.

Hadn't seen that particular stackoverflow, I'll try those too and report back. Thanks.

**Comment by MV10** [comment]
@MikhailTymchukDX forgot to add, the user is in the local admin group and that group has full control rights everywhere, including the project and bin folder.

Tried all of these without success:
- Giving "Everyone" full control
- Stopping IIS before build
- Process Explorer finds 0 matches
- Clearing TFS cache
- Disabling Windows indexing and rebooting

Waiting for a network admin to temporarily disable anti-virus.

We even tried timing the Process Explorer "Find" button-click to run while build was running. Still 0 results. (I couldn't remember whether PE's Find window updates continuously and automatically.)

Pretty frustrating stuff! I'll report back after we try disabling AV.

**Comment by MV10** [comment]
Disabling AV had no effect.

Since IIS is configured to compile, we also pointed a browser to the site and got the same error. I think the stack trace is just a list of calls that lead to running the same build process VS would perform but here it is in case we're overlooking something useful.

`[FileLoadException: Could not load file or assembly 'AjaxControlToolkit' or one of its dependencies. Access is denied.]

[FileLoadException: Could not load file or assembly 'AjaxControlToolkit, Version=16.1.1.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e' or one of its dependencies. Access is denied.]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +210
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +242
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +17
   System.Reflection.Assembly.Load(String assemblyString) +35
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +122

[ConfigurationErrorsException: Could not load file or assembly 'AjaxControlToolkit, Version=16.1.1.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e' or one of its dependencies. Access is denied.]
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +12497284
   System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +499
   System.Web.Configuration.AssemblyInfo.get_AssemblyInternal() +131
   System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +331
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +148
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +172
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +1151

[HttpException (0x80004005): Could not load file or assembly 'AjaxControlToolkit, Version=16.1.1.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e' or one of its dependencies. Access is denied.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618996
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458613`

**Comment by AlekseyMartynov** [comment]
More related links:
* [Could not load file or assembly 'AjaxControlToolkit' or one of its dependencies. Access is denied.](https://forums.asp.net/t/1043427.aspx)
* [IIS issue: Access Denied](http://www.sitepoint.com/forums/showthread.php?615173)

I think that the issue is due to wrong filesystem permissions or their inheritance.

**Comment by MV10** [comment]
The web.config (which is very large) had an impersonation entry referencing the service account used with the production server. We added that account to the developer's local admin group and it started working. 

I'm surprised that VS would _build_ under a runtime impersonation identity dredged up from web.config, of all places, but that was definitely the problem.

Thank you for the assistance.
