### ISSUE TITLE
The nested ModalPopup is located outside the viewport when scrolling the document window

### ISSUE THREAD

**Issue by 0bo0** [DevExpress/AjaxControlToolkit#257]
Hello,
draggable ModalPopup doesn't work correctly when it is nested. See the file linked at the end. If a document is bigger than the viewport, scrolling the document makes the inner popup drift out of the view. If PopupDragHandleControlID attribute is removed then it behaves correctly, but users can't check what's behind the inner popup.
I'm sure it doesn't work with 16.x branch but older ones likely had the same issue.

https://gist.github.com/0bo0/897dcf87f21f64cfbc196401e46d0480

**Comment by MikhailTymchukDX** [comment]
@0bo0 
Thank you for posting such a well-formed example, it helped a lot!

While the fix for this issue is on the way, I would recommend not placing an inner popup inside another popup, but on a same level of hierarchy.
This allows avoiding positioning issues, because an inner popup places itself relative to the parent, that may lead to unpredicted displacements..

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX ,
unfortunately it's not an option in my case. I use modal popups in UI framework with multi-level nesting of dynamically loaded ascxs. Modifying the framework, then probably all apps that use it, just to make the popups draggable is just not worth it. Without "drag" feature it has worked well for years, so in case it won't/can't be fixed in the toolkit I'll rather resign from that option instead of redesigning everything. I hope the fix is feasible in the toolkit itself. Thank you for looking into this.
Best regards,
0bo0

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX,
this patch doesn't fix the issue. Now it works even worse. 
1. Only the most inner/last popup is being repositioned which is wrong and it is a big step back that also corrupts the no-drag mode.
2. In drag mode nested popup is positioned relatively to the outer one, it is not centered on the view.
3. Try this with my sample page: open outer popup, scroll down, open inner popup. It is outside of the view (this is probably because point 2.)
I've the same behavior on IE11 & FF50.

**Comment by MikhailTymchukDX** [comment]
> 1. Only the most inner/last popup is being repositioned which is wrong and it is a big step back that also corrupts the no-drag mode.

Would you please clarify your scenario? Do you expect all popups to be moved when dragging only one of them?

**Comment by 0bo0** [comment]
Ok, it looks like I made a little mistake in point 1.
The behavior I described there occurs only when the outer modal is draggable and the inner one is not. If both are not draggable it works well, the same as it worked before the fix  (there's a slight difference I see in my production app - if I open outer popup, then the inner popup, then resize the browser window to be bigger - one of background masking divs keeps the old size and part of the view is brighter, but I can't repeat this on my demo page yet). 

Points 2 and 3 remain valid, I mean the fix doesn't solve the problem in such scenarios.

There is also another thing which is and was wrong regarding drag mode. Offset of a popup in draggable mode is lost if you scroll a document. 

I think modal popups should be view-stationary and work as follows:
1) In non-draggable mode it should behave the same as it is now or it was in the past.
2) In draggable mode - base position calculated as in non-draggable mode (all popups centered by default). If a user drags a popup, relative offset from the base popup position is calculated and kept as a separate variable(s). If user scrolls the document base position of each popup is calculated again, as it would be in a non-drag mode, then "drag-offset" of each popup is added to that 'base' position.
What do you think?

**Comment by MikhailTymchukDX** [comment]
Hi @0bo0,
 
While this behavior could be useful in a scenario with nested draggable popups, after a thorough analysis, we came to the conclusion that we can't support it in the context of the current component design. Modifying the design will drastically affect all current projects where popups are used. We will keep this issue in mind and will consider updating the popup in the future once we decide to redesign it.
 
Currently, I suggest you disable ModalPopup dragging and try to base your solution on a non-draggable mode.

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX ,
ok, I get it that the new behavior may brake something. But what about fixing the bug with positioning of inner popups while keeping the OLD behavior (by the old behavior I mean loosing drag offsets after the document is scrolled)?
Whatever your answer will be, thanks for taking the time to look into this issue.

**Comment by MikhailTymchukDX** [comment]
If you mean centering of nested popups when they are draggable (like in non-draggable mode), then I can implement it and give you that version for a test.
Once we are both happy with the result, I'll merge it into the master branch.

**Comment by 0bo0** [comment]
That would be great. Just let me know when you have something I can test.

**Comment by MikhailTymchukDX** [comment]
Hi @0bo0 ,
Please check out [my fork](https://github.com/MikhailTymchukDX/AjaxControlToolkit/tree/fix-nested-modal-popup).

If you need binaries, use [this download page](https://ci.appveyor.com/project/MikhailTymchukDX/ajaxcontroltoolkit/build/896/artifacts).

With the changes I made, ModalPopup behaves in the following way in draggable mode:
1. All popups are kept centered on scrolling a document.
2. The top popup can be dragged inside the viewport without issues.
3. Dragging a popup outside the viewport produces positioning issues, but document size is not changed.

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX ,
thanks for the update. I've tested it today and indeed there are problems when dragging a popup to the edge of a window. But it's relatively less important than another issue. Centering doesn't work correctly if outer popup has a different size than inner one. Try with this: #pan_outer { width: 600px; }  The inner popup will be aligned with the top left corner of the outer one while it should be centered on the view.

**Comment by MikhailTymchukDX** [comment]
Hi @0bo0 ,
I changed calculation of a popup position. It is centered now.
As usual, you can check the result at [my fork](https://github.com/MikhailTymchukDX/AjaxControlToolkit/tree/fix-nested-modal-popup) or [download binaries](https://ci.appveyor.com/project/MikhailTymchukDX/ajaxcontroltoolkit/build/976/artifacts).

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX,
tried that and centering option works as expected. Unfortunately, I discovered another issue, but didn't have time yet to repeat that in demo. One of the recent changes altered the way that popups respond to 'width' style. In the past having width:80% on all the popups made their width the same (80% of window size), regardless of the level of nesting. With the new dll I see in my prod app that inner popups are progressively smaller the deeper you go with nesting, even if all of them have 'width:80%' style. And that is very bad. As I wrote, I have not analyzed that thoroughly yet, just wanted to give you some quick feedback.

**Comment by MikhailTymchukDX** [comment]
I checked this issue with different versions of the toolkit down to v4.1.50508, and it behaves exactly in the same manner as in the latest version of the toolkit.
What version of the AJAX Control Toolkit are you using in your production application?

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX 
I've updated the file from the first post, please check it. Let's say this is a baseline, for which I wanted to add dragging functionality.

1. Let's start with non-draggable popups. With DropShadow=False modal div has 'position:fixed' style, so adding 'width:xx%' sets the size of the modal to a percent of window size (expected behavior)

2. If DropShadow is enabled then 'foregroundElement' div is added to DOM as a parent of modal div, and modal div has 'position:relative' style, so 'width:xx%' style on the modal div doesn't work as expected (it's no longer % of a window size). 

3. Enabling dragging (please try this on one of the inner modals) switches position mode of the modal div to 'absolute', which also makes the styling work differently than in 1) - inner popup width is relative to the outer.

It seems this problem existed also in the previous versions. I've never used draggable modals nor DropShadow (I have 'box-shadow' style instead), so I haven't noticed it because it worked as expected with (non-draggable and DropShadow=False).

Fortunately I was able to overcome these problems. If I use 'width:80vw' instead of 'width:80%' I have the same appearance regardless of drag/shadow settings. It seems that 'vw' unit is not supported directly by System.Web.UI.WebControls.Unit, from C# it has to be set with Style.Add( HtmlTextWriterStyle.Width, "80vw" ) instead of Width="80%" (or via css selector) which is kind of small hack.

All browsers my apps run on can handle 'vw' so with that modification I'm able to use dragging functionality the way I wanted and I'm quite happy right now.

I don't know if you want to address these issues in the current version of ModalDialog control, but just be aware that they exist.

Thanks for your support.

**Comment by MikhailTymchukDX** [comment]
Hi @0bo0 ,
Thank you for your detailed explanation and sharing your workaround with us!

I think it's better to mark the current issue as resolved, so we can merge the fix into the master branch.

Then, you can file a new issue regarding the popup width by copying its description from your previous comment. 
This way, we can continue working on it using the latest code base.
