### ISSUE TITLE
ajaxfileupload control can not upload (shown on server folder but can not open) filename has unicode character

### ISSUE THREAD

**Issue by hayrettinbulut** [DevExpress/AjaxControlToolkit#26]
ajaxfileupload control upload files but filenames that has unicode character (turkish character ) can not open. Other files has no problem. Is there any   globalization f options for ajaxfileupload control.. All files can upload but unicode named files can not open (lik  ççğşü.jpg) When I clik on file i get " the file is too big or corrupted" error

**Comment by hayrettinbulut** [comment]
unicode named  pdf files  can upload and can open in server 
unicode named  image files(jpeg or png ..)  can upload but  can not open in server 
so interesting. What is problem.

**Comment by MikhailTymchukDX** [comment]
I can upload .jpg files with Unicode characters in file name without problems when I run an [AjaxFileUpload page](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.SampleSite/AjaxFileUpload/AjaxFileUpload.aspx) from the Sample Site.
Would you please provide a sample image and sample project to illustrate this issue?

**Comment by tcssistemas** [comment]
Same problem about AjaxFileUpload Control, in my site and in sample website...
Any help?

**Comment by MikhailTymchukDX** [comment]
@skymail5 Would you please try this workaround https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203437189?

I am looking forward to your results.
