### ISSUE TITLE
AJAX Menu.js 4.5.6 

### ISSUE THREAD

**Issue by dbrewerton** [DevExpress/AjaxControlToolkit#260]
Hello, Menu.js AJAX 4.5.6 has interprets un-
[Menu.txt](https://github.com/DevExpress/AjaxControlToolkit/files/600823/Menu.txt)

validated user input as source code on line 173. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

This issue was captured by HP Enterprise Fortify Static Code Analyzer. According to SCA:
Abstract:

The file Menu.js interprets unvalidated user input as source code on line 173. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

Explanation:

Many modern programming languages allow dynamic interpretation of source instructions. This capability allows programmers to perform dynamic instructions based on input received from the user. Code injection vulnerabilities occur when the programmer incorrectly assumes that instructions supplied directly from the user will perform only innocent operations, such as performing simple calculations on active user objects or otherwise modifying the user's state. However, without proper validation, a user might specify operations the programmer does not intend.

Example: In this classic code injection example, the application implements a basic calculator that allows the user to specify commands for execution.
...
	userOp = form.operation.value;
	calcResult = eval(userOp);
...

The program behaves correctly when the operation parameter is a benign value, such as "8 + 7 * 2", in which case the calcResult variable is assigned a value of 22. However, if an attacker specifies languages operations that are both valid and malicious, those operations would be executed with the full privilege of the parent process. Such attacks are even more dangerous when the underlying language provides access to system resources or allows execution of system commands. In the case of JavaScript, the attacker may utilize this vulnerability to perform a cross-site scripting attack.

**Comment by MikhailTymchukDX** [comment]
Since the [Menu.js](http://ajax.aspnetcdn.com/ajax/4.5/6/Menu.js) file is a part of [Microsoft Ajax](https://msdn.microsoft.com/en-us/library/ee341002.aspx), we cannot fix issues in it. 
I recommend you submit your inquiry using the [Microsoft Connect](http://connect.microsoft.com/) site or do this in the [ASP.NET AJAX + Ajax Control Toolkit](https://forums.asp.net/1022.aspx) section on the official Microsoft forum.
