### ISSUE TITLE
Only include necessary scripts in bundle

### ISSUE THREAD

**Issue by 0liver** [DevExpress/AjaxControlToolkit#274]
I've just updated ACT from v4.1.40412.0 to **16.1.1** via NuGet following the [official guide](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below) and configured bundling according to the linked article [How to use bundling and CDN](https://github.com/DevExpress/AjaxControlToolkit/wiki/How-to-use-bundling-and-CDN).

The bundle is there, I have only a single request for the ACT script resources - but the response seems to contain all (?) script there is and weighs **1244290** bytes! That's 1.2MB!

Before turning on bundling, I had less than 10 files included from the toolkit.

Is there a way to cut down the bundle to only the files actually needed by my application? It seems to me that if there isn't, then the whole bundling feature is actually an anti-feature because who would want to load 1.2MB when 200kB are enough?

**Comment by MikhailTymchukDX** [comment]
Hi @0liver ,
The AJAX Control Toolkit bundle contains all scripts from the toolkit. This is the reason of its large size.
To reduce the size of downloading data, you have several options:
1. Use [CDN bundle](https://github.com/DevExpress/AjaxControlToolkit/wiki/How-to-use-bundling-and-CDN#cdn), which is compressed. Its size is 226 Kb for v16.1.1.
2. Use a control bundle. It is an XML file that describes what toolkit control are used in an application. The AJAX Control Toolkit reads this file and creates a bundle for these controls only.
[Here is the example](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.Tests/TestData/AjaxControlToolkit.config) of a control bundle configuration file. It is placed to the root of a web application.

**Comment by 0liver** [comment]
Hi @MikhailTymchukDX,

thanks for your timely response. I wasn't aware of the XML configuration option :-) But most importantly: it works.

Thanks.

**Comment by 0liver** [comment]
Hi @MikhailTymchukDX,

thanks for your timely response. I wasn't aware of the XML configuration option :-) But most importantly: it works.

Thanks.
