### ISSUE TITLE
AjaxFileUpload improvement ideas

### ISSUE THREAD

**Issue by sab39** [DevExpress/AjaxControlToolkit#275]
I'm working on switching my project from another Ajax file upload control to AjaxControlToolkit's AjaxFileUpload. I've found it extremely helpful to have access to the source code and so far it's more reliable than the one I was using before as well.

While I've been working on it I've been keeping a mini-wishlist of ideas for improvements to AjaxFileUpload. I can't definitively commit to anything, but I'm potentially interested in working on the changes myself and contributing the code back to the project. Before I start making changes to the code I'd like to find out if the general approach I have in mind would be acceptable or whether I should just plan on having my own customized fork.

These are the changes I have in mind:

  - Ability to set the TempDir path in code so it can be done without config changes
  - Make DeleteAllTemporaryFiles safe to call even if uploads are in progress elsewhere, eg only delete if more than 24h old
  - Use WebRequestManager instead of raw XHR in order to honor event hooks set on it
  - Optionally use WebForms standard system for page callbacks so that the server-side event handlers can update other controls on the page, change viewstate, tell UpdatePanels to reload etc.
  - Separate events (client and server side) for uploadSuccess and uploadCancel
    - Still call UploadCompleteAll in both cases for backward compatibility
  - Provide documentation of the arguments passed to the client-side event handlers
  - Add SaveAs method to UploadEventArgs and make the one on the control itself obsolete
  - More control over rendering:
    - Don't use hardcoded style attributes
    - Allow text and CssClasses of individual UI elements to be customized
    - Customizeable html of the pending uploads list, including an option for per-file cancel buttons
    - Either have a separate version for single-file uploads or a dedicated UI for MaximumNumberOfFiles=1

**Comment by MikhailTymchukDX** [comment]
Hi @sab39 ,
You are always welcome to make changes to the AJAX Control Toolkit.

The main concern is to avoid breaking changes.
Also, avoid implementing features that are specific to a user's task and can be implemented on the client side without touching the code of the toolkit.

To get familiar with technical aspects of contributing, please read [the contributing guide](https://github.com/DevExpress/AjaxControlToolkit/blob/master/CONTRIBUTING.MD#pull-requests) before providing a pull-request.

**Comment by MikhailTymchukDX** [comment]
@sab39
I'm closing this issue and hope to see pull-requests from you in the future.
If you have any questions, don't hesitate to contact us.
