### ISSUE TITLE
Which version Jquery is better for Ajaxcontroltoolkit 16.1.1?

### ISSUE THREAD

**Issue by eoctopus** [DevExpress/AjaxControlToolkit#276]
Hi,

I used the version 16.1.1, but which the jquery version should I use?
The issue is when pick a date from the calendar control, sometime the value is blank, but sometime is fine.
Somebody has an idea?

Thanks,

Michael

**Comment by pmcfernandes** [comment]
You can use anyone. If you having problems with lastest versions add jquery migrate script
