### ISSUE TITLE
Upgrade AjaxControlToolkit dll from version 3.0.20820.0 to 16.1

### ISSUE THREAD

**Issue by harshal-a** [DevExpress/AjaxControlToolkit#278]
I need to upgrade my ajaxcontroltoolkit dll versioned - 3.0.20820 with the latest version 16.1

Below are couple of controls/class, for which I am facing issue:

1. CollapsiblePanelExtender: property used: CollapsedCssClass & ExpandedCssClass

2. PasswordStrength: property used: Strength

3. CalendarExtender: property used: CalendarMode & Enum - CalendarModeType

Q. What can we use instead of above properties as they are not available in version - 16.1?

**Comment by MikhailTymchukDX** [comment]
Hi @harshal-a ,
 
I checked [the AJAX Control Toolkit v3.0.20820](https://ajaxcontroltoolkit.codeplex.com/releases/view/16488) and did not find any property you mentioned.
Would you please provide a link to that release?

**Comment by harshal-a** [comment]
Hi,

I do not have the link for that release. Below is the code snippet for your reference we have:

Public CollapsiblePanel As New AjaxControlToolkit.CollapsiblePanelExtender()
CollapsiblePanel.CollapsedCssClass = "cssclassname"
CollapsiblePanel.ExpandedCssClass = "cssclassname"

Similarly, for other classes/controls we have used their respective properties.

Thanks,
Harshal A.

**Comment by MikhailTymchukDX** [comment]
Ok, maybe you can attach a DLL that you are using?

**Comment by harshal-a** [comment]
Sorry, I can't do that, The dll is on client machine and we are not allowed to do so.

**Comment by harshal-a** [comment]
![image](https://cloud.githubusercontent.com/assets/24520841/21101066/65d0829c-c09d-11e6-9419-4eccefa5044f.png)

**Comment by MikhailTymchukDX** [comment]
@harshal-a  
This is a screenshot of an assembly structure taken from a DLL that I downloaded from [the official release at CodePlex](https://ajaxcontroltoolkit.codeplex.com/releases/view/16488):
![image](https://cloud.githubusercontent.com/assets/17080984/21107099/99e74a6c-c0a1-11e6-90ce-7c7778e56160.png)
 
I don't see any property that you mentioned.

**Comment by harshal-a** [comment]
![image](https://cloud.githubusercontent.com/assets/24520841/21128295/b3db90c6-c11f-11e6-950b-abbbcd50fff7.png)


Dll file type is not supported here.
Please refer the screen image with highlighted properties.

**Comment by AlekseyMartynov** [comment]
> Dll file type is not supported here.

Please try uploading as a ZIP archive.

**Comment by harshal-a** [comment]
[AjaxControlToolkit.zip](https://github.com/DevExpress/AjaxControlToolkit/files/648314/AjaxControlToolkit.zip)

Oops, my bad.

**Comment by MikhailTymchukDX** [comment]
@harshal-a
Thank you for providing this assembly.
It seems to be a custom build based on version 3.0.20820 of the toolkit.
 
There is only one property that can be replaced by the property of the same functionality in v 16.1:
`CalendarExtender.CalendarMode` can be replaced with `CalendarExtender.DefaultView` and corresponding enum is `CalendarDefaultView`.
 
There are no direct replacement for the rest of the properties you mentioned, so you have to write custom code to achieve the same functionality as you had before.
