### ISSUE TITLE
HtmlEditorExtender loses focus on Page_Load

### ISSUE THREAD

**Issue by nitromgd** [DevExpress/AjaxControlToolkit#279]
I am using the latest version 16.1.1
I installed using the Installer
I am using I.E. 11
I am running the project from the VS development web-server

My issue is simple.  
I create a new Visual Basic ASP.NET Web Forms Site.  I then add a TextBox to Default.aspx.  I then add TextBox1.Focus() to Page_Load.  I launch the site and TextBox1 has focus.
I then add the HtmlEditorExtender, launch the site and focus on TextBox1 is lost.  I have tried many workarounds to get this to work with no avail.  I have the same problem that involves an update panel with a save button where I would like focus to return to the text box once I submit but I thought I would start simple.
Any help would be greatly appreciated.
Thank you

[WebSite3.zip](https://github.com/DevExpress/AjaxControlToolkit/files/655449/WebSite3.zip)

**Comment by saajuboy** [comment]
was this bug fixed?
