### ISSUE TITLE
Ajax control toolkit 15.1.3.0 issue

### ISSUE THREAD

**Issue by nickgsoft** [DevExpress/AjaxControlToolkit#280]
I tried Ajax control toolkit 15.1.3.0 and when I use calendarextender control, selected year seems like have bug. I will attach the video for this bug to this blog if I can, but first I open calendar using image icon, and then I select date some where in 06-15-2018 which will update date in textbox. then again I open the calendar extender control and try to select 2019 year, it doesn't allow 2019, even if I click on 2019, it select 2018. 

the code is below:-
`<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AjaxCalendar.aspx.cs" Inherits="WebApplication1.AjaxCalendar" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager runat="server" ID="scriptmgrPrice" EnablePartialRendering="true" EnableScriptLocalization="true" 
            EnableScriptGlobalization="true" ScriptMode="Release"></asp:ScriptManager>
       
        <div>
            <table>
                <tr>
                    <td nowrap>
                        <asp:TextBox ID="txtPriceDate" runat="server" Width="100px"></asp:TextBox>
                        <asp:ImageButton ID="imgBtnPriceDate" runat="server" CssClass="normal_btn" ImageAlign="absmiddle" 
                            ImageUrl="/images/ss_icon_calendar.gif" ToolTip="Display Calendar" />
                        <ajaxToolkit:CalendarExtender id="calPriceDate" runat="server" popupbuttonid="imgBtnPriceDate"
                            targetcontrolid="txtPriceDate"/>
                      
                    </td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>`

### The installation method
- [ ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by nickgsoft** [comment]
[2016-12-16_7-50-30.zip](https://github.com/DevExpress/AjaxControlToolkit/files/657337/2016-12-16_7-50-30.zip)

**Comment by MikhailTymchukDX** [comment]
Hi @nickgsoft ,
I tried to reproduce this issue based on a video you provided, but did not detect any problems.

Would you please provide a sample project that illustrates this issue?
Also, please specify what browser version you are using.

**Comment by nickgsoft** [comment]
[AjaxCalendar.zip](https://github.com/DevExpress/AjaxControlToolkit/files/658286/AjaxCalendar.zip)

attached is the sample project

**Comment by MikhailTymchukDX** [comment]
Hi @nickgsoft ,
I tried to replicate the bug using your sample project, but didn't manage: http://screencast.com/t/XAOLgOm2

I'm using IE 11.0.9600.18500:
![image](https://cloud.githubusercontent.com/assets/17080984/21306172/b716c98e-c5e0-11e6-94a1-5c4f279a41a4.png)

**Comment by nickgsoft** [comment]
thanks for sharing your screenshot, but i tried same project by changing 16.1.1.0 and it worked and then same project i changed 16.1.1.0 to 15.1.3.0 and got same error.

I have same browser version as you and i have windows 7 version. but i change with my other windows 10 and 4 other developers pc with combination of different environment and they did see same issue with 15.1.3.0

The issue really comes when we click Year switch from 2018 to 2019, it doesn't pick up the 2019. it shift one year prior to selected year, but as soon as i switch to 2020 it works and then i can switch back to 2019 fine. So selected year back word working as expected, but selecting year forward from years selection panel, it doesn't work sometimes.

Also with 16.1.1.0, i had the hidden field which started giving me error which i have to change to textbox to resovle the issue. So something in 16.1.10 might be bug that prevent us to usign the hiddenfield.

 <asp:TextBox  ID="hiddenTargetControlID" runat="server" style="display:none;" />
 <asp:HiddenField ID="hiddenTargetControlID" runat="server" />

**Comment by MikhailTymchukDX** [comment]
@nickgsoft 
>thanks for sharing your screenshot, but i tried same project by changing 16.1.1.0 and it worked and then same project i changed 16.1.1.0 to 15.1.3.0 and got same error.

Do I understand it correctly that you have some external factors that prevent you from using the latest version of the toolkit, and so you need a workaround for v15.1.3?

**Comment by nickgsoft** [comment]
Please ignore this request as i was able to manage to go to new version 16.1.1.0 and now its working as expected. You were correct about external factor as being the custom enhancement to control to add Week Number. it would be nice to enhance this control to include week number.

**Comment by MikhailTymchukDX** [comment]
@nickgsoft 
Thank you for your response. To keep things clear, I'm closing this issue.

I don't understand how a week number feature should look like.
Would you please post a new issue with the example describing a calendar's new behavior?
