### ISSUE TITLE
AJAX Calendar Extender - Windows 10 Tablet

### ISSUE THREAD

**Issue by rayatcarroll** [DevExpress/AjaxControlToolkit#284]
Hi there, downloaded this control, its very good so far, but only issue I've seen is running the web app (site) via a dell windows 10 tablet doesn't show the calendar control, actually none of the extender controls are showing, do I need to adjust security in IE or install some control on the tablet? Using visual studio 2012 pro, update 5, windows server 2012.

**Comment by MikhailTymchukDX** [comment]
Hi @rayatcarroll ,
I've checked [the Sample site](https://ajaxcontroltoolkit.devexpress.com/) with the Windows 10 tablet, and everything works well including the Calendar extender.

Would you please check your web application in another browser?
If the problem persists only on the tablet, would you please check a browser's console for errors?

**Comment by rayatcarroll** [comment]
thanks for the feedback, I did check it with chrome and of course it works perfect, challenge is I need it to run in IE (SSRS Report Printing). I can't see any errors on the web page but will continue to evaluate.

**Comment by rayatcarroll** [comment]
looks like an unexpected call to the rounded corners, then assuming all ajax objects.

![screenshot 2017-01-10 10 25 50](https://cloud.githubusercontent.com/assets/25015417/21819115/36aab9d6-d71f-11e6-9cad-fb95415724d3.png)


![screenshot 2017-01-10 10 23 42](https://cloud.githubusercontent.com/assets/25015417/21819042/ea67baec-d71e-11e6-8596-3938a6560fd3.png)

**Comment by rayatcarroll** [comment]
Seems the test or sample site works fine. so what can it be?

![screenshot 2017-01-10 10 28 10](https://cloud.githubusercontent.com/assets/25015417/21819188/919cbcea-d71f-11e6-9cb1-b44035983eae.png)
![screenshot 2017-01-10 10 27 59](https://cloud.githubusercontent.com/assets/25015417/21819189/92242856-d71f-11e6-8487-2281b61b67e0.png)

**Comment by rayatcarroll** [comment]
works in VS2012 test mode, same browser, but not in production system. tried app pool as classic 4.0 and integrated 4.0, no difference.

**Comment by rayatcarroll** [comment]
seems the web.config was defaulted to httpruntime 4.0, not 4.5, seems to be working now.
