### ISSUE TITLE
V 16.1.1-FileUpload: JSON Error in OnUploadComplete Event - Sys.ArgumentException: Cannot deserialize.

### ISSUE THREAD

**Issue by nitinphansalkar** [DevExpress/AjaxControlToolkit#286]
### The installation method
- [ ] NuGet package

### Steps to reproduce the bug
The user uploads the file using Upload button in the FileUpload control.
The file is uploaded in the TEMP folder of the server (Windows\Temp\_AjaxFileUpload folder)
Then in the OnUploadComplete event -
1. Get the Byte Array of file data from AjaxFileUploadEventArgs parameter of the event
2. Try inserting it in SQL Server table. While the Parameters for the SQL stored procedure are being built, on the last "String" parameter suddenly the code jumps to the event error handler and shows the following error in a dialog box:
------------------------------------------------------
http://localhost:54707/ScriptResource.axd?d=D9drwtSJ4hBA6O8UhT6CQgpXCD1qinW4JQMZEulR4i9agpZvcQpXII5IhvWlVxdFAWSv2wOvry2vKPNBwZaGtoOAsfV_970iEegMrPrWe23VqntJU355JMh8X01BYDij25EvJyUO-9vqAiN9ZSBQQdM6hBruRT9bNCEYIJiq-tA1&t=ffffffffc7ae6e38

0x800a139e - JavaScript runtime error: Sys.ArgumentException: Cannot deserialize. The data does not correspond to valid JSON.
-----------------------------------------------------
The procedure in the ScriptResource.axd which throws the error is:
`Sys.Serialization.JavaScriptSerializer.deserialize = function Sys$Serialization$JavaScriptSerializer$deserialize(data, secure) {
    var e = Function._validateParams(arguments, [
        {name: "data", type: String},
        {name: "secure", type: Boolean, optional: true}
    ]);
    if (e) throw e;
    if (data.length === 0) throw Error.argument('data', Sys.Res.cannotDeserializeEmptyString);
    try {    
        var exp = data.replace(Sys.Serialization.JavaScriptSerializer._dateRegEx, "$1new Date($2)");
        
        if (secure && Sys.Serialization.JavaScriptSerializer._jsonRegEx.test(
             exp.replace(Sys.Serialization.JavaScriptSerializer._jsonStringRegEx, ''))) throw null;
        return eval('(' + exp + ')');
    }
    catch (e) {
         throw Error.argument('data', Sys.Res.cannotDeserializeInvalidJson);
    }
}
`

This is happening in Version 16.1.1 earlier versions 15.x were running fine. **My code has not changed.**

This happens in IE 11, Edge, Firefox and Chrome browsers (latest versions). Others have not been tested.

**Comment by MikhailTymchukDX** [comment]
Hi @nitinphansalkar ,
Would you please provide a sample project that illustrates this issue?

**Comment by nitinphansalkar** [comment]
Here is the code:

    protected void AjaxFileUpload1_OnUploadComplete(object sender, AjaxFileUploadEventArgs file)
    {
        try
        {
            string strFileName = Path.GetFileNameWithoutExtension(file.FileName);
            string strFileExt = Path.GetExtension(file.FileName);

            byte[] byteFileData = new byte[file.FileSize];
            byteFileData = file.GetContents();

            string[] strDocMap = Session["DOCMAP"].ToString().Split('|');   //user|year|category

            StoredProcedure objSP = new DAL.StoredProcedure(strSqlCon);
            SqlParameter[] ParamCollection = new SqlParameter[6];

            ParamCollection[0] = new SqlParameter("@COMP_ID", strDocMap[0]);
            ParamCollection[1] = new SqlParameter("@FILE_YEAR_ID", int.Parse(strDocMap[1]);
            ParamCollection[2] = new SqlParameter("@FILE_CATEGORY_ID", int.Parse(strDocMap[2]);
            ParamCollection[3] = new SqlParameter("@FILENAME", strFileName);
            ParamCollection[4] = new SqlParameter("@FILE_BYTES", byteFileData);
// Errors out on below line showing JSON Dialog box..

            ParamCollection[5] = new SqlParameter("@FILE_CONTENT_TYPE", strFileExt); 

            objSP.Execute("InsertDoc", ParamCollection);

           file.DeleteTemporaryData();
        }
        catch (Exception e)
        {
                //Error handling code.
        }
    }

**Comment by nitinphansalkar** [comment]
UPDATE: I installed NuGet package for version 16.1.0 and it works. So the latest version 16.1.1 has some issue. Please note that I have NOT added the TempFolder attribute for the AjaxControlToolkit in the web.config that was introduced in the 16.1.1

**Comment by MikhailTymchukDX** [comment]
Hi @nitinphansalkar ,
I tried to replicate your code without SQL-related block in a test project and it works without errors: 
[AjaxFileUploadTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/707573/AjaxFileUploadTest.zip)

Please try to remove the call of a stored procedure and check the result.

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.
