### ISSUE TITLE
Calendar extender displays incorrect selectable dates for start/end range 

### ISSUE THREAD

**Issue by grandavenuesoftware** [DevExpress/AjaxControlToolkit#287]
### The installation method
- [ ] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
1) Using Chrome on Windows 10, open the web page for the demo of the AJAX Control Toolkit Calendar extender: https://ajaxcontroltoolkit.devexpress.com/Calendar/Calendar.aspx
2) Click the "Calendar with date range" field to open the Calendar popup

### Actual result
Popup displays Aug 2, 2010 as a valid date and allows it to be selected, even though the "startDate" property of the CalendarExtender was set to Aug 3, 2010 (screen capture from Google Chrome on Windows 10).
![capture](https://cloud.githubusercontent.com/assets/23563897/21911802/0179f75c-d8e8-11e6-9894-18df6393b3d3.JPG)

### Expected result
Popup should display Aug 2, 2010 as a crossed-out date and prevent its selection (screen capture from Microsoft Edge on Windows 10).
![capture](https://cloud.githubusercontent.com/assets/23563897/21911883/60f2ccf4-d8e8-11e6-9fd3-3c06e435373f.JPG)

### Browser(s) used
Fail: Safari and Chrome
Pass: Edge, IE and Firefox

Firefox passed on both Windows 10 and macOS 10.12.
Chrome failed on both Windows 10 and macOS 10.12.
Safari failed on macOS 10.12.
Edge and IE passed on Windows 10.

### A site deployment method
- [ ] VS development web-server,
- [X] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @grandavenuesoftware
I checked the Calendar extender with Chrome on Windows 10 and it works as intended.

Please specify the following:
* Your system locale
* Time zone on your computer
* Chrome version
* Errors in the browser's console, if any

**Comment by grandavenuesoftware** [comment]
I just went back and tested the same behavior on a website using an older version of the AJAX Control Toolkit (4.5.7.1213), and it does not have the same bug.

Here is the old Calendar set for a start date of 13 Jan 2017:
![capture](https://cloud.githubusercontent.com/assets/23563897/21937999/0927f8a4-d97f-11e6-876c-b72007a2e6f1.JPG)

And here is the new Calendar, set for a start date of 13 Jan 2017:
![capture](https://cloud.githubusercontent.com/assets/23563897/21938032/3404400a-d97f-11e6-87b9-2b1654c56522.JPG)

Both screen captures were taken using Chrome 55 on Windows 10.  I used our application for these screen captures because the old AJAX Control Toolkit demo for the calendar (http://ajaxcontroltoolkit.com/Calendar/Calendar.aspx) didn't set the date ranges so it couldn't be used to test/duplicate the problem.

One note: When I looked at the page generated by the two different versions of the Calendar control, they set the startDate property differently:
Old version: "startDate":"Fri, 13 Jan 2017 00:00:00 GMT"
New version: "startDate":"2017-01-13T00:00:00"

It's possible this is completely unrelated to the problem, but I thought I'd point it out.

Let me know if there's any additional information I can provide.

**Comment by grandavenuesoftware** [comment]
Thanks for fixing this!

Beginner question: How do we follow up and find out when this gets incorporated into a "stable" release?

**Comment by AlekseyMartynov** [comment]
@grandavenuesoftware
Mehul Harry makes announcements in [his blog](https://community.devexpress.com/blogs/aspnet/archive/tags/AJAXControlToolKit/default.aspx).
Also you can get the fix right away. Check [Updating the Project from CI Builds](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-project-from-CI-builds).

**Comment by grandavenuesoftware** [comment]
@MikhailTymchukDX and @AlekseyMartynov,

We downloaded and tested with build386. This change fixes the bug.

Thank you!
