### ISSUE TITLE
0x800a1391 - JavaScript runtime error: 'console' is undefined"

### ISSUE THREAD

**Issue by rkreddyv** [DevExpress/AjaxControlToolkit#289]
I get below error when I select the date in Ajax Calendar Control: I should be able to select only month and year from the calendar control. We have some javascript functions to perform this functionality. We are upgrading from v1.0.20229.0 to V16.1.1:  Any help is really appreciated: 

Placed below code in header section of master page. 
<head>
    <asp:PlaceHolder runat="server">
        <%:System.Web.Optimization.Styles.Render("~/Content/AjaxControlToolkit/Styles") %>
    </asp:PlaceHolder>
</head>

Placed below code in form section of content page
<asp:ScriptManager ID="ScriptManager1"  runat="server">
        <Scripts>
                       <asp:ScriptReference Path="~/Scripts/AjaxControlToolkit" />
          </Scripts>
</asp:ScriptManager>

We get below error: 

"Unhandled exception at line 1237, column 5 in http://localhost:61018/Scripts/AjaxControlToolkit/Debug/Common.debug.js

0x800a1391 - JavaScript runtime error: 'console' is undefined"

This is the Script: 
===========
<asp:TextBox ID="txtDate" runat="server" Width="75px" CssClass="textBox_RED"></asp:TextBox>
<Ajax:CalendarExtender ID="AjaxCalender" runat="server" Animated="true" TargetControlID="txtDate" ClientIDMode="Static" 
	Format="MM/dd/yyyy" BehaviorID="calendar1" FirstDayOfWeek="Monday" OnClientDateSelectionChanged="checkDate" OnClientHidden="onCalendarHidden" OnClientShown="onCalendarShown"     
	PopupButtonID="btnCalender" CssClass="CalenderCSS" 
	PopupPosition="Right" DefaultView="Months" ></Ajax:CalendarExtender>
<asp:ImageButton ID="btnCalender" ImageUrl="~/imgs/s_calendar.gif" runat="server" />

Javascript for the 3 events of the calendar control:
====================================

    <script type="text/javascript">

        function checkDate(sender, args) {
            var p = sender._selectedDate;
            if (sender._selectedDate >= new Date()) {
                alert("Date cannot be greater than today!");
                var k = getDaysInMonth(new Date());
                var m = p.getMonth();
                var l = (m < 10) ? '0' + m : m;
                var now = new Date();
                now.setDate(1);
                now.setHours(-1);
                //document.getElementById("ctl00$ContentPlaceHolder1$txtDate").value = now.format("MM/dd/yyyy");
                document.getElementById("<%=txtDate.ClientID%>").value = now.format("MM/dd/yyyy");
                
            }
            else {
                var k = getDaysInMonth(p);
                var m = p.getMonth() + 1;
                var l = (m < 10) ? '0' + m : m;
                //document.getElementById("ctl00$ContentPlaceHolder1$txtDate").value = l + '/' + k + '/' + p.getFullYear();
                document.getElementById("<%=txtDate.ClientID%>").value = l + '/' + k + '/' + p.getFullYear();
            }
        }

        function onCalendarShown() {

            var cal = $find("calendar1");
            //Setting the default mode to month
            cal._switchMode("months", true);

            //Iterate every month Item and attach click event to it
            if (cal._monthsBody) {
                for (var i = 0; i < cal._monthsBody.rows.length; i++) {
                    var row = cal._monthsBody.rows[i];
                    for (var j = 0; j < row.cells.length; j++) {
                        Sys.UI.DomEvent.addHandler(row.cells[j].firstChild, "click", call);
                    }
                }
            }
        }

        function onCalendarHidden() {
            var cal = $find("calendar1");
            //Iterate every month Item and remove click event from it
            if (cal._monthsBody) {
                for (var i = 0; i < cal._monthsBody.rows.length; i++) {
                    var row = cal._monthsBody.rows[i];
                    for (var j = 0; j < row.cells.length; j++) {
                        Sys.UI.DomEvent.removeHandler(row.cells[j].firstChild, "click", call);
                    }
                }
            }

        }

        function call(eventElement) {
            var target = eventElement.target;
            switch (target.mode) {
                case "month":
                    var cal = $find("calendar1");
                    cal._visibleDate = target.date;
                    cal.set_selectedDate(target.date);
                    //cal._switchMonth(target.date);
                    cal._blur.post(true);
                    cal.raiseDateSelectionChanged();
                    break;
            }
        }

        function getDaysInMonth(aDate) {
            // returns the last day of a given month
            var m = new Number(aDate.getMonth());
            var y = new Number(aDate.getYear());

            var tmpDate = new Date(y, m, 28);
            var checkMonth = tmpDate.getMonth();
            var lastDay = 27;

            while (lastDay <= 31) {
                temp = tmpDate.setDate(lastDay + 1);
                if (checkMonth != tmpDate.getMonth())
                    break;
                lastDay++
            }
            return lastDay;
        }

 
    </script>

### The installation method
- [ ] NuGet package

### A site deployment method
- [ ] VS development web-server,

===

Thanks
Rama

**Comment by MikhailTymchukDX** [comment]
Hi @rkreddyv ,
This error occurs because of the incorrect check for console existence.

You can get the latest build from [our CI server](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/393/artifacts) to apply the fix to your application or copy [this change](https://github.com/DevExpress/AjaxControlToolkit/commit/2cfe3cce6d3e22f8f7bd2c2f7d47e96b3c3ea4f7#diff-dd89824002a249f5999fb0265ea735a0R1237) manually to the `Scripts/AjaxControlToolkit/Debug/Common.debug.js` file.

**Comment by kalipatel12** [comment]
How to put ContextKeys in ajaxfileupload control
 in AjaxControlToolkit-16.1.1

**Comment by MikhailTymchukDX** [comment]
Hi @kalipatel12 ,
You can set any string value to this field in server code:
```csharp
protected void Page_Load(object sender, EventArgs e) {
    ajaxFileUpload.ContextKeys = "any value";
}
```

However, this field is not included into the life cycle of a control, and so you will lose assigned values on your next request.
