### ISSUE TITLE
Need help getting started

### ISSUE THREAD

**Issue by barryfz** [DevExpress/AjaxControlToolkit#291]
### The installation method
- [ ] Installer

### Minimal steps to reproduce the bug

Created new web app
Modifed Default.aspx

added textbox, image, calendar extender:
       <div class="col-md-4">
            Date: <asp:TextBox ID="txtDate" runat="server"></asp:TextBox>
            <asp:ImageButton runat="Server" ID="Image1" ImageUrl="~/images/calendar.gif" AlternateText="Click to show calendar" /><br />
            <ajaxToolkit:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="txtDate" PopupButtonID="Image1"/>
        </div>

Went to NuGet and installed the AjaxControlToolkitStaticResources
Added the ScrriptManger 
        <asp:ScriptManager runat="server">
            <Scripts>
                <%--To learn more about bundling scripts in ScriptManager see http://go.microsoft.com/fwlink/?LinkID=301884 --%>
                <%--Framework Scripts--%>
                <asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />

added the placeholder in the master
   <asp:PlaceHolder runat="server">
        <%: Scripts.Render("~/bundles/modernizr") %>
        <%: System.Web.Optimization.Styles.Render("~/Content/AjaxControlToolkit/Styles/Bundle") %>
    </asp:PlaceHolder>

ran it both Debug = true/false - same error
### Actual result
Unhandled exception at line 1, column 14425 in http://localhost:4635/Scripts/AjaxControlToolkit/Bundle?v=f2xAAd2TWOdmsmrwe3Ko7FqubUV1OQ66mzQ_gdvdZuk1

0x800a1391 - JavaScript runtime error: 'Type' is undefined

### A site deployment method
- [ ] VS development web-server,

**Comment by MikhailTymchukDX** [comment]
Would you please attach a sample project that illustrates this issue?

**Comment by barryfz** [comment]
This is in vs2015
[MyAjaxControlToolkitTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/732602/MyAjaxControlToolkitTest.zip)

**Comment by MikhailTymchukDX** [comment]
@barryfz Thank you for providing this sample project!

This error occurs because AJAX Control Toolkit bundle is loaded before the Microsoft Ajax.
As AJAX Control Toolkit depends on Microsoft Ajax; it fails to load necessary types.

To fix it, please place the Microsoft Ajax bundle script reference before the AJAX Control Toolkit bundle script reference:
```aspx
<asp:ScriptManager runat="server">
  <Scripts>                
    <asp:ScriptReference Name="MsAjaxBundle" />
    <asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />
  </Scripts>
</asp:ScriptManager>
```

**Comment by barryfz** [comment]
That did it. Thanks for your help with this.
