### ISSUE TITLE
When will next release version available ?

### ISSUE THREAD

**Issue by madhav5589** [DevExpress/AjaxControlToolkit#293]
Just wanted to know when the next version of ACT will be available ? There is an issue already been  resolved (#128) since quite a while but can't get it until next version includes it. 
Can you please provide an update on that?

Thanks.

**Comment by MikhailTymchukDX** [comment]
Hi @madhav5589 ,

At he moment we have no scheduled time for the next release of the AJAX Control Toolkit.

You can get the latest build of the AJAX Control Toolkit from [our CI system](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts) as described in the [Updating the Project from CI Builds](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) article.

Also, we have released [a preview version of the installer](https://community.devexpress.com/blogs/aspnet/archive/2017/01/30/asp-net-ajax-control-toolkit-support-for-vs2017-rc.aspx) recently with VS 2017 RC support. This installer includes the #128 issue fix, so you can try it as well.

**Comment by madhav5589** [comment]
@MikhailTymchukDX Thank you for providing information. It will be handy. :)
