### ISSUE TITLE
Ajaxtoolkit 16.1.1 in VS 2015

### ISSUE THREAD

**Issue by sanjeevcid** [DevExpress/AjaxControlToolkit#295]
### The installation method
- [x] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Expected result
what setting to be done after installation in VS 2015 so that all the controls work in ASP.net WebApplication and while working slideshowextender the add slideshow show method not displaying. pl. help.

**Comment by MikhailTymchukDX** [comment]
Hi @sanjeevcid ,
Your scenario is not entirely clear to me.
Would you please attach a sample project that illustrates this issue?
