### ISSUE TITLE
AjaxControlToolkit 16.1.1 with HtmlAgilityPackSanitizerProvider: unable to change font size,name,color

### ISSUE THREAD

**Issue by stanleycia** [DevExpress/AjaxControlToolkit#296]
### The AJAX Control Toolkit \<VERSION\>
16.1.1
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

HTMLAgilityPack 1.4.9.5
### Minimal steps to reproduce the bug
Use <ajaxToolkit:HtmlEditorExtender> with sanitizer provider = HtmlAgilityPackSanitizerProvider
Change font name,size,color

put back to HtmlEditorExtender from database, the result: font size,name,color still the same

### A site deployment method
- [ ] VS development web-server,
- [x] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @stanleycia ,
Your scenario is not entirely clear to me.

Do you edit HTML inside an HtmlEditorExtender and then reload a page loading another HTML from your database into the HtmlEditorExtender in code-behind?

**Comment by stanleycia** [comment]
Sorry.. Just ignore it. No issue.
