### ISSUE TITLE
Extender controls of type 'AjaxControlToolkit.HoverMenuExtender' cannot extend controls of type 'System.Web.UI.HtmlControls.HtmlGenericControl'

### ISSUE THREAD

**Issue by MikhailTymchukDX** [DevExpress/AjaxControlToolkit#3]
Original CodePlex issue: https://ajaxcontroltoolkit.codeplex.com/workitem/28044

Upgraded toolkit to version 15.1.4.0, pointed to new dll in Visual Studio (2013) and get this error when running asp.net website in debug: 

**Extender controls of type 'AjaxControlToolkit.HoverMenuExtender' cannot extend controls of type 'System.Web.UI.HtmlControls.HtmlGenericControl'**

here is the aspx code:
```
<div id="MainNavigationDiv" runat="server"> <ul> <li runat="server" id="XYZ_aspx" class="hoverpopupVx" > <a class="hoverpopupVx">XYZ Menu Item</a> </li> </ul> </div> <cc1:HoverMenuExtender ID="HoverMenuExtenderComplaints" runat="server" TargetControlID="XYZ_aspx"
 PopupControlID="XYZPanel" PopupPosition="Bottom" OffsetX="0"
 OffsetY="0" PopDelay="0" HoverCssClass="hoverpopupV">
</cc1:HoverMenuExtender>
```

**Comment by vivekceb** [comment]
@MikhailTymchukDX  Can you let us knwo when this would be fixed or next release or a workaround solution for above error

**Comment by MikhailTymchukDX** [comment]
Hello, @vivekceb 
You can replace a `div` with `asp:Panel` as a workaround.
