### ISSUE TITLE
AjaxControlToolkit - Access is denied

### ISSUE THREAD

**Issue by petrozio** [DevExpress/AjaxControlToolkit#30]
Just upgraded to 16.1, but now getting an access denied error. Tried giving permissions to the "Temporary ASP.NET F
![capture](https://cloud.githubusercontent.com/assets/17831974/13850242/7cd0175c-ec2f-11e5-9ffd-0fb098fece72.PNG)
iles" folder but didn't help.

**Comment by MikhailTymchukDX** [comment]
It looks like IIS issue.
Please try this workaround: http://stackoverflow.com/a/9068413/644496

**Comment by petrozio** [comment]
The Temp folder under Framework was empty, but the temp folder under Framework64 was not. Couldn't delete the contents though because file were in use.

**Comment by MikhailTymchukDX** [comment]
Would you please clarify whether AjaxControlToolkit.dll is locked by some process?

**Comment by petrozio** [comment]
I would imagine the website that is using it has it locked. I would think deleting it would be a bad thing.

**Comment by MikhailTymchukDX** [comment]
Would you deploy this website locally and check whether AjaxControlToolkit.dll is loaded correctly?

**Comment by petrozio** [comment]
I'm not sure how. I have VS local, but the aspx files on shared folder that I connect to on the server. The site still seems to run fine, just VS that sees the error.

**Comment by MikhailTymchukDX** [comment]
IIS that runs a site on the server locks the DLLs to ensure nobody deletes or modifies it. 
To run the site locally, you can install [AjaxControlToolkit NuGet package](https://www.nuget.org/packages/AjaxControlToolkit/) to add required dlls to your project.

**Comment by petrozio** [comment]
That is how I installed Ajax.

**Comment by petrozio** [comment]
I finally fixed it by giving permissions to the following directory:
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files

Notice this is not the Framework64 folder. Did this on my local PC.
