### ISSUE TITLE
Ajax Control Tool Kit 16.1.1 controls not working in Visual Studio 2015 Professional Windows 7 Ultimate

### ISSUE THREAD

**Issue by sanjeevcid** [DevExpress/AjaxControlToolkit#300]
### The installation method
- [x] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by AlekseyMartynov** [comment]
Dup of #295? 😉

**Comment by MikhailTymchukDX** [comment]
@sanjeevcid ,
Please describe your problem in greater detail:
* Do you see controls in a toolbar?
* Can you drag them on a page?
* Can you run an application without errors?

If you see error messages, take a screenshot and attach it to this issue.
