### ISSUE TITLE
Export table to excel gets error.

### ISSUE THREAD

**Issue by barryfz** [DevExpress/AjaxControlToolkit#302]
### The installation method
- [ ] Installer

### Minimal steps to reproduce the bug
Code below

page def has EnableEventValidation  = false

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ScribeHours.aspx.cs" Inherits="FcmClinicSchedule.ScribeHours" EnableEventValidation = "false" %>
...
<body>
    <form id="appointments" method="post" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <div class="div_header">
        <FCMheader:FCMheader ID="FCMheader1" runat="server"></FCMheader:FCMheader>
    </div>
    <div style="margin: 10px; width: 100%; overflow: auto; vertical-align: top;">
        <div style="width: 125px; vertical-align: top; height: 100%; float: left; margin-right: 20px;">
            <uc2:Menu ID="Menu2" runat="server"></uc2:Menu>
        </div>
        <div style="width: 80%;float: left; vertical-align: top">
            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                <ContentTemplate>
                    <asp:Panel ID="Panel1" Visible="true" runat="server">
                        <asp:ValidationSummary ID="ValidationSummary2" runat="server" ValidationGroup="DateGroup" />
                    </asp:Panel>
                    <div>
                        <div class="dataEntry">
                            <fieldset class="box floatleft" style="width: 40em; height: 140px;">
                                <ul>
                                    <li>
                                        <asp:Label ID="lblScribe" runat="server" Text="Scribe:" Width="100px" Font-Bold="True"></asp:Label>
                                        <asp:DropDownList ID="ddlScribe" runat="server" DataSourceID="dsScribeList" DataTextField="Scribe"
                                            DataValueField="ScribeId" Height="20px" Width="200px">
                                        </asp:DropDownList>
                                    </li>
                                    <li>
                                        <asp:Label ID="lblStartDate" runat="server" Text="Start Date:" Width="100px" Font-Bold="True"></asp:Label>
                                        <asp:TextBox ID="txtStartDate" runat="server" MaxLength="10" Style="text-align: justify;
                                            top: 0px; left: 0px;" Width="14.5em" HtmlEncode="False" DataFormatString="{0:d}" />
                                        <ajaxToolkit:CalendarExtender ID="calExtStartDate" runat="server" TargetControlID="txtStartDate"
                                            PopupPosition="TopRight" PopupButtonID="imgStartDate" />
                                        &nbsp;<asp:ImageButton ID="imgStartDate" runat="server" ImageUrl="~/SupportFiles/images/calendar.gif" />
                                        <asp:RequiredFieldValidator ID="rfStartDate" runat="server" ErrorMessage="Start Date required"
                                            Text="*" CssClass="ERRORred" ControlToValidate="txtStartDate" Font-Bold="True"
                                            ValidationGroup="DateGroup"></asp:RequiredFieldValidator>
                                    </li>
                                    <li>
                                        <asp:Label ID="lblEndDate" runat="server" Text="End Date:" Width="100px" Font-Bold="True"></asp:Label>
                                        <asp:TextBox ID="txtEndDate" runat="server" MaxLength="10" Style="text-align: justify;
                                            top: 0px; left: 0px;" Width="14.5em" HtmlEncode="False" DataFormatString="{0:d}" />
                                        <ajaxToolkit:CalendarExtender ID="calExtEndDate" runat="server" TargetControlID="txtEndDate"
                                            PopupPosition="TopRight" PopupButtonID="imgEndDate" />
                                        &nbsp;<asp:ImageButton ID="imgEndDate" runat="server" ImageUrl="~/SupportFiles/images/calendar.gif" />
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="End Date required"
                                            Text="*" CssClass="ERRORred" ControlToValidate="txtEndDate" Font-Bold="True"
                                            ValidationGroup="DateGroup"></asp:RequiredFieldValidator>
                                    </li>
                                    <li>
                                        <div style="text-align: right; padding:20px 30px 5px 0px">
                                            <asp:Button ID="btnSubmit" runat="server" Text="Submit" OnClick="btnSubmit_Click"
                                                ValidationGroup="DateGroup" />
                                            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                                            <asp:Button ID="btnExcel" runat="server" Text="Export to Excel" OnClick="btnExcel_Click"
                                                ValidationGroup="DateGroup" />
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                        </div>
                        <div style="float: left; width: 100%">
                            <div style="width: 100%; padding-right: 25px; padding-left: 25px">
                                <asp:GridView ID="grdScribeHours" runat="server" AutoGenerateColumns="False" DataSourceID="dsScribeHours"
                                    Visible="False" BorderStyle="Solid" BorderWidth="1px" Caption="&lt;h3&gt;Scribe Hours&lt;/h3&gt;"
                                    CaptionAlign="Top" CellPadding="5" Width="50em">
                                    <Columns>
                                        <asp:BoundField DataField="Scribe" HeaderText="Scribe" ReadOnly="True" SortExpression="Scribe" />
                                        <asp:BoundField DataField="Week" HeaderText="Week" ReadOnly="True" SortExpression="Week" />
                                        <asp:BoundField DataField="Hours" HeaderText="Hours" ReadOnly="True" SortExpression="Hours">
                                            <ItemStyle HorizontalAlign="Right" />
                                        </asp:BoundField>
                                        <asp:BoundField DataField="WeekNo" HeaderText="WeekNo" ReadOnly="True" SortExpression="WeekNo"
                                            Visible="False" />
                                    </Columns>
                                </asp:GridView>
                            </div>
                        </div>
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>

The page displays the data in a gridview with a button for Export that calls this code behind.

      protected void btnExcel_Click(object sender, EventArgs e)
        {
            DataLayer.ScribeDsTableAdapters.ScribeHoursTableAdapter ta = new DataLayer.ScribeDsTableAdapters.ScribeHoursTableAdapter();
            DataLayer.ScribeDs.ScribeHoursDataTable t = new DataLayer.ScribeDs.ScribeHoursDataTable();
            ta.Fill(t, Convert.ToInt32(ddlScribe.SelectedValue), Convert.ToDateTime(txtStartDate.Text), Convert.ToDateTime(txtEndDate.Text));

            // This actually makes your HTML output to be downloaded as .xls file
            Response.Clear();
            Response.ClearContent();
            Response.ContentType = "application/octet-stream";
            Response.AddHeader("Content-Disposition", "attachment; filename=TimeBreakdown.xls");

            // Create a dynamic control, populate and render it
            GridView excel = new GridView();
            excel.DataSource = t;
            excel.Caption = "<b>Scribe Hours</b>";
            excel.DataBind();
            excel.RenderControl(new HtmlTextWriter(Response.Output));

            Response.Flush();
            Response.End();
        }

### Actual result

JavaScript runtime error: Sys.WebForms.PageRequestManagerParserErrorException: The message received from the server could not be parsed.

debug has

"ScriptManager1=UpdatePanel1%7CbtnExcel&__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%2FwEPDwULLTE2OTY5NzEzMzAPZBYCAgMPZBYEAgcPZBYCZg9kFgQCBQ8QDxYCHgtfIURhdGFCb3VuZGdkEBUBFEd1aXJsLVN0ZWFybGV5LCBHYWlhFQEENjg2MhQrAwFnZGQCHw88KwARAgEQFgAWABYADBQrAABkAgsPD2QPEBYDZgIBAgIWAxYCHg5QYXJhbWV0ZXJWYWx1ZWUWAh8BZRYCHwFlFgNmZmZkZBgCBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WAgUMaW1nU3RhcnREYXRlBQppbWdFbmREYXRlBQ5ncmRTY3JpYmVIb3Vycw9nZLJGJ9f3%2B995GQjyKzoX1wXshenlqaJNVzGRs5SBLo3v&__VIEWSTATEGENERATOR=D1365347&ddlScribe=6862&txtStartDate=2%2F1%2F2017&txtEndDate=2%2F28%2F2017&__ASYNCPOST=true&btnExcel=Export%20to%20Excel"

### A site deployment method
- [ ] VS development web-server,

Sample would have to include database, hope you don't need that.  I can upload asp and cs files if you need more.

**Comment by barryfz** [comment]
I pasted part of the page code but I don't see it?  Do I need to upload a file?

**Comment by barryfz** [comment]
I am upload the aspx file to be sure I have completely defined the problem. If anything else is needed let me know.
[ScribeHours.aspx.txt](https://github.com/DevExpress/AjaxControlToolkit/files/764491/ScribeHours.aspx.txt)

Not using materpage yet as this is updating an old app.

**Comment by MikhailTymchukDX** [comment]
Hi @barryfz ,
I cannot understand how AJAX Control Toolkit relates to this issue.
Would you please provide a sample project so that we can research the issue?

**Comment by AlekseyMartynov** [comment]
@barryfz 

> I pasted part of the page code but I don't see it? Do I need to upload a file?

This may be due to improper quoting. See [Creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

I guess that the button which click is being handled is surrounded with UpdatePanel.  
Try either of the following:

1. Force a full PostBack for the button: http://stackoverflow.com/q/2545508
2. Extract the export functionality to a separate [handler](https://msdn.microsoft.com/en-us/library/bb398986.aspx) and invoke it by a simple HTML link instead of handling a server-side button click.

As Mikhail noted, the question doesn't relate to AJAX Control Toolkit, so I'm closing the issue.

**Comment by barryfz** [comment]
The project is way to beig and requires a database. I will try to reduce it on.  I don’t know that this is specifically a toolkit problem, it appears to be caused by the ScriptManager which the tollkit requires. I have never had the ScriptManage on a page doing an excel export and never had a problem with the export until now.  I did upload the page file that shows the layout.

Barry FItzgerald
barry@barryfz.com
