### ISSUE TITLE
AjaxToolKit 16.1.1 not working in VS 2015 Professional

### ISSUE THREAD

**Issue by sanjeevcid** [DevExpress/AjaxControlToolkit#303]
Sir,

I am using VS 2015 Professional and AjaxToolKit 16.1.1,
When using ASP.net creating Website through New Web Project
or WebForms, the AjaxToolkit is not working.

But, when the Website is created using Empty Website the 
AjaxControlToolKit is working.

Pl. rectify the mistake in the AjaxTookTkit software.

Regards,
Sanjeeva Rao,
CID, Telangana State,
Hyderabad.

**Comment by MikhailTymchukDX** [comment]
Hi @sanjeevcid ,

We did not manage to reproduce this issue.
Would you please provide the [Visual Studio activity log](https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/), so we can make research and find out what causes this?
