### ISSUE TITLE
How can i add custom whitelist tag? I have had one but not working anymore after i have converted old website to new website project

### ISSUE THREAD

**Issue by MonsterMMORPG** [DevExpress/AjaxControlToolkit#306]
I am trying like this on a website project but it is giving error

This CS file is placed under Old_App_Code folder in the project

```
using AjaxControlToolkit.HtmlEditor.Sanitizer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


    public class NewSanitier : DefaultHtmlSanitizer, IHtmlSanitizer
    {
        private static readonly string[] whiteListTags = { "pre"};

        string IHtmlSanitizer.GetSafeHtmlFragment(string htmlFragment, Dictionary<string, string[]> whiteList)
        {
            foreach (var tag in whiteListTags)
            {
                if (!whiteList.ContainsKey(tag))
                    whiteList.Add(tag, new string[0]);
            }

            return base.GetSafeHtmlFragment(htmlFragment, whiteList);

        }
    }

```

In web config

`  <ajaxControlToolkit htmlSanitizer="NewSanitier, Old_App_Code" />`

Here the necessary images
![gg11](https://cloud.githubusercontent.com/assets/4149474/23094315/81d005e0-f607-11e6-92a3-23df548c4fde.png)
![gg33](https://cloud.githubusercontent.com/assets/4149474/23094316/81eca8d0-f607-11e6-9d4f-4926cb0b26fe.png)
![gg22](https://cloud.githubusercontent.com/assets/4149474/23094317/82080e0e-f607-11e6-859f-7b7afbea2c53.png)

**Comment by MikhailTymchukDX** [comment]
Hi @MonsterMMORPG ,
It seems that Type.GetType() can not find your `NewSanitizer` class type: https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/HtmlEditorExtender/HtmlEditorExtender.cs#L43

Please check the assembly name and default namespace of your Web application (Project -> <Project_Name> Properties... -> Application -> Default namespace):
![image](https://cloud.githubusercontent.com/assets/17080984/23118275/a645a840-f764-11e6-8ba7-bff155a3fc9b.png)

Then, add a fully qualified name of the sanitizer to Web.config like this:
```xml
<ajaxControlToolkit htmlSanitizer="YourNamespaceName.NewSanitizer, YourAssemblyName" />
```

**Comment by MonsterMMORPG** [comment]
@MikhailTymchukDX  ty very much for detailed answer

as you see i didnt add any namespace to sanitize function

do i need to add namespace? i also have checked and assembly name and default namespace are same in my case

**Comment by MonsterMMORPG** [comment]
@MikhailTymchukDX  ok i have made like this but still not working

`  <ajaxControlToolkit htmlSanitizer="PP_Web_Project.MyHtmlSanitizer, PP_Web_Project"/>`

![projecdsa](https://cloud.githubusercontent.com/assets/4149474/23184137/aa6ed690-f88f-11e6-8d20-2adb3d5a51c6.png)

**Comment by MikhailTymchukDX** [comment]
@MonsterMMORPG If you don't specify a namespace for a class explicitly, the Default namespace will be used.
To check what actual namespace a class has, use any disassembler like [ILSpy](http://ilspy.net/):
![image](https://cloud.githubusercontent.com/assets/17080984/23201241/c130ac32-f8e9-11e6-8558-94c7a61c18fe.png)
