### ISSUE TITLE
validators not working with version 16.1

### ISSUE THREAD

**Issue by brillox** [DevExpress/AjaxControlToolkit#31]
Hi, I have attached a file with the whole code.... the validators are working OK with the tool kit version 15.1 but not with version 16.1; with the latest version they fire JavaScript exceptions  on the "On_Validate" method saying something the stack is full. I am afraid I did not took a note of the whole exception as I was very keen to revert it back to the previous version as I  had  a release to do today.
[ValidatorsErrors.txt](https://github.com/DevExpress/AjaxControlToolkit/files/178256/ValidatorsErrors.txt)

**Comment by brillox** [comment]
Oh and the installation did not add any control in the toolbox of VS 2015, I had to add it manually

**Comment by savornicesei** [comment]
None of them are working?
In my project that uses ACT 16.1 the Required validator and Regex validator are working fine.

**Comment by brillox** [comment]
on my one project none of them were working; shame I will be on Holiday from next Monday for one week but if I can, tomorrow I'll download it again version 16.1 and give it another go so if I see the exceptions I'll pass it to you.

Thanks

**Comment by githieu** [comment]
I had the same issue (stack is full) after upgrading to 16.1.
Removing the appSettings line <add key="ValidationSettings:UnobtrusiveValidationMode" value="None" /> in Web.config has corrected this problem  (appSetting that I added in 15.1 as workaround, see Issue [#28018](https://ajaxcontroltoolkit.codeplex.com/workitem/28018)).

**Comment by brillox** [comment]
which appsettings line??

**Comment by githieu** [comment]
Please see my updated comment

**Comment by brillox** [comment]
Ok, but I do not have that line at all

**Comment by githieu** [comment]
I suppose this error appears if you don't use Unobtrusive Validation which use data-* attributes for validation instead of generate a javascript for each control to validate. 
Unobtrusive Validation is the default behavior since Framework 4.5

**Comment by brillox** [comment]
so what you are suggesting is for me to "add" that line into my app settings?

**Comment by brillox** [comment]
Right I got our best friend (Google) to help me.. I am going to download that version and try without the app setting line and with it to test if that was the cause or not. I'll keep you posted within today

**Comment by githieu** [comment]
No, if you are using .NET Framework 4.5 and AjaxControlToolkit 16.1 you should use Unobtrusive Validation and then not add this line.

**Comment by brillox** [comment]
sorry now I am confusing according to this post http://www.codeguru.com/csharp/.net/net_asp/using-unobstructive-validation-in-asp.net-4.5-web-forms.htm I should use that line; infact i just downloaded version 16.1 and now I get these errors for all the required field validators

`Uncaught RangeError: Maximum call stack size exceeded
#10 http://localhost/patientaccess/ScriptResource.axd?d=4r6deNsBAJugq8KoQkHBcPoNZYCBm9VM4UZqnIeXGg5HzspkUyt2z6cB1XFJnRoQxchCg2lKFDZoM81TicI6qTDS4lQAhZYifgiQme_gSX5cVvOS7FBcPJS0j9nMcziEr1z0QHJlXZ3f1HYEIggYzw2&t=ffffffff81a867ec:1:8998 Sys.Extended.UI.ValidatorCalloutBehavior._onvalidate()
#9 http://localhost/patientaccess/ScriptResource.axd?d=9Mc74Ma71rFyw7J4BQwiLeNCCY5rieWVcmsIiWaDD_LrPaODGySkxC1z__eVxtaa2hWNaj11RPZ0QPhbGjI1cUMSuFLANndb3jJIrzpFi9vYMQ_IfnXWRqCiX5AN1zUpM_iRninBxi47XohHmpZOGZhFqiKr7pBq4iwZMhgeY1I1&t=40eb3b32:5:307 HTMLSpanElement.()
#8 http://localhost/patientaccess/ScriptResource.axd?d=9Mc74Ma71rFyw7J4BQwiLeNCCY5rieWVcmsIiWaDD_LrPaODGySkxC1z__eVxtaa2hWNaj11RPZ0QPhbGjI1cUMSuFLANndb3jJIrzpFi9vYMQ_IfnXWRqCiX5AN1zUpM_iRninBxi47XohHmpZOGZhFqiKr7pBq4iwZMhgeY1I1&t=40eb3b32:5:307 ._originalValidationMethod()
#7 http://localhost/patientaccess/ScriptResource.axd?d=4r6deNsBAJugq8KoQkHBcPoNZYCBm9VM4UZqnIeXGg5HzspkUyt2z6cB1XFJnRoQxchCg2lKFDZoM81TicI6qTDS4lQAhZYifgiQme_gSX5cVvOS7FBcPJS0j9nMcziEr1z0QHJlXZ3f1HYEIggYzw2&t=ffffffff81a867ec:1:8998 Sys.Extended.UI.ValidatorCalloutBehavior._onvalidate()
#6 http://localhost/patientaccess/ScriptResource.axd?d=9Mc74Ma71rFyw7J4BQwiLeNCCY5rieWVcmsIiWaDD_LrPaODGySkxC1z__eVxtaa2hWNaj11RPZ0QPhbGjI1cUMSuFLANndb3jJIrzpFi9vYMQ_IfnXWRqCiX5AN1zUpM_iRninBxi47XohHmpZOGZhFqiKr7pBq4iwZMhgeY1I1&t=40eb3b32:5:307 HTMLSpanElement.()
#5 http://localhost/patientaccess/ScriptResource.axd?d=9Mc74Ma71rFyw7J4BQwiLeNCCY5rieWVcmsIiWaDD_LrPaODGySkxC1z__eVxtaa2hWNaj11RPZ0QPhbGjI1cUMSuFLANndb3jJIrzpFi9vYMQ_IfnXWRqCiX5AN1zUpM_iRninBxi47XohHmpZOGZhFqiKr7pBq4iwZMhgeY1I1&t=40eb3b32:5:307 ._originalValidationMethod()
#4 http://localhost/patientaccess/ScriptResource.axd?d=4r6deNsBAJugq8KoQkHBcPoNZYCBm9VM4UZqnIeXGg5HzspkUyt2z6cB1XFJnRoQxchCg2lKFDZoM81TicI6qTDS4lQAhZYifgiQme_gSX5cVvOS7FBcPJS0j9nMcziEr1z0QHJlXZ3f1HYEIggYzw2&t=ffffffff81a867ec:1:8998 Sys.Extended.UI.ValidatorCalloutBehavior._onvalidate()
#3 http://localhost/patientaccess/ScriptResource.axd?d=9Mc74Ma71rFyw7J4BQwiLeNCCY5rieWVcmsIiWaDD_LrPaODGySkxC1z__eVxtaa2hWNaj11RPZ0QPhbGjI1cUMSuFLANndb3jJIrzpFi9vYMQ_IfnXWRqCiX5AN1zUpM_iRninBxi47XohHmpZOGZhFqiKr7pBq4iwZMhgeY1I1&t=40eb3b32:5:307 HTMLSpanElement.()
#2 http://localhost/patientaccess/ScriptResource.axd?d=9Mc74Ma71rFyw7J4BQwiLeNCCY5rieWVcmsIiWaDD_LrPaODGySkxC1z__eVxtaa2hWNaj11RPZ0QPhbGjI1cUMSuFLANndb3jJIrzpFi9vYMQ_IfnXWRqCiX5AN1zUpM_iRninBxi47XohHmpZOGZhFqiKr7pBq4iwZMhgeY1I1&t=40eb3b32:5:307 ._originalValidationMethod()
#1 http://localhost/patientaccess/ScriptResource.axd?d=4r6deNsBAJugq8KoQkHBcPoNZYCBm9VM4UZqnIeXGg5HzspkUyt2z6cB1XFJnRoQxchCg2lKFDZoM81TicI6qTDS4lQAhZYifgiQme_gSX5cVvOS7FBcPJS0j9nMcziEr1z0QHJlXZ3f1HYEIggYzw2&t=ffffffff81a867ec:1:8998 Sys.Extended.UI.ValidatorCalloutBehavior._onvalidate()`

**Comment by brillox** [comment]
so I should add that line in web config?

**Comment by brillox** [comment]
seems that is the ValidatorCalloutBehavior the problem by the way

**Comment by brillox** [comment]
so to recap...  I am using DOT NET 4.5 and the toolkit 16.1; according to the UnobtrusiveValidationMode docs this is set to "None" by default unless we do use an appsetting key to set it to true, therefore by removing the app setting key from my web config I still get the errors...

>UnobtrusiveValidationMode:
 Specifies how ASP.NET globally enables the built-in validator controls to use unobtrusive JavaScript for client-side validation logic.  
Type: UnobtrusiveValidationMode
Default value: None
Remarks: If this key value is set to "None" [default], the ASP.NET application will use the pre-4.5 behavior (JavaScript inline in the pages) for client-side validation logic. If this key value is set to "WebForms", ASP.NET uses HTML5 data-attributes and late bound JavaScript from an added script reference for client-side validation logic.

**Comment by githieu** [comment]
OK, I don't know why but in my case the default value of UnobtrusiveValidationMode seems to be "Webforms" and not "None" (I'm using Framework 4.5.2).
I just tested again:
- if I add  `<add key="ValidationSettings:UnobtrusiveValidationMode" value="None" />`  I have this JavaScript error: **Out of stack space** (and I can see in HTML code that data-* attributes are **NOT** generated)
- if I change this setting to `<add key="ValidationSettings:UnobtrusiveValidationMode" value="Webforms" />` , it works (and I can see in HTML code that data-* attributes are generated)
- if I remove line it works (and I can see in HTML code that data-* attributes are generated)

**Comment by brillox** [comment]
I tried the 3 option too but it does not work with Framework 4.5; I cannot update framework as is a Company policy to decide what Framework to use. Does this mean that I am stuck with version 15.1 for ever now unless we use Framework 45.2 ?

**Comment by brillox** [comment]
so that is a bug :-)

**Comment by sanjeevcid** [comment]
working
ASP.net on Visual Studio 2015 Professional and recently installed AjaxToolKit 16.1.1
i am working in ASP unfortunatelly i didn't found ToolscriptManager
and when used scriptmanager using SlideShowExtender i didn't found in
image tasks - Add slideshow page method.
