### ISSUE TITLE
can not add scriptmanager for v16.1

### ISSUE THREAD

**Issue by smisich** [DevExpress/AjaxControlToolkit#310]
### The installation method
- [ ] Installer
### Minimal steps to reproduce the bug
added reference to AjaxControlKit v16
in master page i registered the assembly
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

how do i add in the script manager? so that I can run ajaxToolkit controls?

theres no scriptmanager under v16.1 in the toolbox.
Only under Ajax extensions. 

### Browser(s) used
IE 11

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

[SiteMaster.txt](https://github.com/DevExpress/AjaxControlToolkit/files/815481/SiteMaster.txt)

**Comment by MikhailTymchukDX** [comment]
Hi @smisich 
`ScriptManager` is the standard ASP.NET control. You can find it under AJAX Extensions tab of the toolbox:
![image](https://cloud.githubusercontent.com/assets/17080984/23543087/966a87d8-0001-11e7-89eb-fda16177832a.png)

**Comment by smisich** [comment]
Why do i get the sqiggly line under ScriptManager underlined below? It says element is not known?

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content><asp:Content ID="Content2" ContentPlaceHolderID="cphMain" runat="server">    <ajaxToolkit:ScriptManager runat="Server" EnableScriptGlobalization="true"        EnableScriptLocalization="true" ID="ScriptManager1" ScriptMode="Debug" CombineScripts="true" /> 

    On Friday, 3 March 2017 9:09 PM, MikhailTymchukDX <notifications@github..com> wrote:
 

 Hi @smisich
ScriptManager is the standard ASP.NET control. You can find it under AJAX Extensions tab of the toolbox:

**Comment by MikhailTymchukDX** [comment]
@smisich Use `asp:` prefix for a ScriptManager:
```
<asp:ScriptManager runat="server" />
```
