### ISSUE TITLE
TabContainer

### ISSUE THREAD

**Issue by Godling888** [DevExpress/AjaxControlToolkit#313]
### The installation method
- [ ] Installer
- [ X] NuGet package
- [ ] A custom build from the source code

TabConatainer tabs HREF is set to href="%23"

### Expected result
href="#" should be the generated link for the tabs

### Browser(s) used
IE11 & Chrome

### A site deployment method
- [X ] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
@Godling888 Your scenario is not entirely clear to me.
Would you please provide a sample markup?

**Comment by Godling888** [comment]
Sorry for being unresponsive. I later discovered the issue was caused by an outdated version of Microsoft's anti-xss library.
