### ISSUE TITLE
Lost Toolkit in move to VS 2017

### ISSUE THREAD

**Issue by kipcarter** [DevExpress/AjaxControlToolkit#314]
### The installation method
Removed Visual Studio 2015 and installed Visual Studio 2017

### Actual result
Can't see Toolkit in the my project 'toolbox'

Are there any documents showing process of updating the Toolkit from prior versions of VS to 2017?

**Comment by MikhailTymchukDX** [comment]
Hi @kipcarter ,
The AJAX Control Toolkit comes as an IDE extension that is installed per Visual Studio instance.
This means that it is not automatically installed when a new instance of Visual Studio appears on your machine.
You can run [a preview version of the installer](http://cdn.devexpress.com/Release/ACT/17.1/20170130/AjaxControlToolkit.Installer.17.0-preview.exe?customer=trial&Expires=1809032400&Signature=Mlyed6Mlvmpy490toLYqMGbweiwX7n3vmU3pu6j3Ze9NjxK%7EpBhxGxRMo5VrB-RGsKkmOiU2hg7ELssditHaxRnRN3MxR-5OTQynNZNPnjlNXunCT-plJrHw9urNY6loJQ3t0vnz1EXFzky64sIU6PzMfybzcZfP9d7KtBEsfU0_&Key-Pair-Id=APKAJXDNBD2DCSFOCFMQ) with VS 2017 support or use [a NuGet package](https://www.nuget.org/packages/AjaxControlToolkit/).

**Comment by kipcarter** [comment]
I’ve got v16.1.1 installed in my VS 2017 IDE I can see it in my NuGet browser inside VS and it shows I have it. Still not showing up in the Toolbox for some reason. I’m pretty sure I need to add it to the Toolbox before I can drag and drop extension items onto my page.
 
Not seeing anything to direct me to get the extensions into the toolbox even though it is in the project.

**Comment by kipcarter** [comment]
I figured it out!

Add a tab to the toolbox 
Right click on the new tab
Click on 'choose items
At the bottom of the window choose 'browse'
Select Ajax ontrolToolkit.dll then open 
When you are back to the 'Choose Toolbox Items ' window click 'OK'
Done!
