### ISSUE TITLE
ModalPopupExtender sometimes doesn't show

### ISSUE THREAD

**Issue by kreggMowrey** [DevExpress/AjaxControlToolkit#32]
I have an issue where I have pop up panels that show up fine the first time, maybe a second time but usually always fails the third time I invoke.  When it fails it properly sets the background CSS  class but the popup panel doesn't appear and the main web form still responds to interactions.  If I refresh the webpage the popups work again for one or two times.  Anyone else have this issue?

**Comment by savornicesei** [comment]
Hi Kregg, 

What browser did you use? Do you have any javascript errors in the browser when the popup fails?

**Comment by githieu** [comment]
I had a similar issue but with the previous version (15.1.4). I upgraded to 16.1 in order to get the fix (see Item 27971 & Item 28021 in 16.1 changelog).

**Comment by dparks2** [comment]
my experience was the same as @githieu 

@kreggMowrey  ...but to add, the third popup didn't actually fail, it's just appears below/behind other objects like a gridview, detailview or other non-popup panel. if you're able to scroll the page you could see the popup was behind everything else.

**Comment by kreggMowrey** [comment]
@dparks2 Yes that is exactly what it looks and feels like - it just showing up behind everything else.  I am using 15.1.4 as @githieu mentioned so will look into the items he has specified.  Thank you all for your help.
