### ISSUE TITLE
HtmlEditorExtender generates an extra <br />

### ISSUE THREAD

**Issue by madhav5589** [DevExpress/AjaxControlToolkit#320]
I have been using HtmlEditorExtender on aspx page. I saw that when we create a link using CreateLink button, it generates the link properly but when we delete it manually, it still keeps br tag. I also confirmed from sample page [here](https://ajaxcontroltoolkit.devexpress.com/HtmlEditorExtender/HtmlEditorExtender.aspx). If you delete the data/link, from html mode of view, you can see <br /> and hence it gets saved to the database.
Can you please advice ?
Thanks

**Comment by MikhailTymchukDX** [comment]
Hi @madhav5589 
I don't face this behavior when performing the actions you described.
Would you please record a short video to illustrate the issue? You can use [Jing](https://www.techsmith.com/jing.html) for this purpose.

**Comment by madhav5589** [comment]
Hi @MikhailTymchukDX , I have captured the video from the sample site of ACT. You may see that when you remove the link from editor, it still carries the br tag.

[Ajaxcontroltoolkit_HtmlEditorExtender.zip](https://github.com/DevExpress/AjaxControlToolkit/files/900187/Ajaxcontroltoolkit_HtmlEditorExtender.zip)

**Comment by madhav5589** [comment]
Hi @MikhailTymchukDX ,

I verified this fix on Chrome. But somehow, in IE11 and Edge browsers, it still carries br tag. Can you please confirm ?

Thanks.

**Comment by MikhailTymchukDX** [comment]
Hi @madhav5589,
Yes, there was an issue with IE and Edge. We have fixed it.
Thank you for bringing it to our attention!

**Comment by madhav5589** [comment]
@MikhailTymchukDX  Thanks. You're welcome. :)
