### ISSUE TITLE
Calendar Extender resets on postback

### ISSUE THREAD

**Issue by khuzaima** [DevExpress/AjaxControlToolkit#321]
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Browser(s) used
Google Chrome / FireFox 
### A site deployment method
- [X] VS development web-server,
- [X] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @khuzaima 
Would you please provide a sample project that illustrates this issue?

**Comment by khuzaima** [comment]
<%@ Page Language="VB" AutoEventWireup="false" CodeFile="calendar.aspx.vb" Inherits="umrah_calendar" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="sm1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="up1" runat="server">
            <ContentTemplate>
                <div>
                    <asp:TextBox ID="tb1" runat="server" AutoPostBack="True"></asp:TextBox>
                    <asp:CalendarExtender ID="tb1_CalendarExtender" runat="server" BehaviorID="tb1_CalendarExtender" Format="yyyy-MM-dd" TargetControlID="tb1" />
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</body>
</html>


Code Behind
========

Partial Class umrah_calendar
    Inherits System.Web.UI.Page

    Private Sub umrah_calendar_Init(sender As Object, e As EventArgs) Handles Me.Init
        If Not Me.IsPostBack Then
            tb1_CalendarExtender.SelectedDate = Now.Date
        End If
    End Sub
End Class

**Comment by khuzaima** [comment]
<asp:ScriptManager ID="sm1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="up1" runat="server">
            <ContentTemplate>
                <div>
                    <asp:TextBox ID="tb1" runat="server" AutoPostBack="True"></asp:TextBox>
                    <asp:CalendarExtender ID="tb1_CalendarExtender" runat="server" BehaviorID="tb1_CalendarExtender" Format="yyyy-MM-dd" TargetControlID="tb1" />
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>

**Comment by MikhailTymchukDX** [comment]
@khuzaima  Thank you for providing a sample.
I tested it and the calendar resets its value to a hard-coded date.
What is the expected result of this code execution?

**Comment by khuzaima** [comment]
Hi Mikhail,

Thank you for very prompt responses.

Another observation is that if I do not initialize any value to this text
box, it work perfectly OK and store the date which I select after the page
is loaded.

But if on PageInit if I have assigned any value, It doesn't retain the
value of the date which I select from calendar extender. Although the
initilization is done only if its not a postback.

I have tried both ways, with UPDATE PANEL and WITHOUT UPDATE PANEL.

Expected result is:

   - I need to initialize some date when the page is first loaded and its
   not a post-back.
   - after the page has been loaded, whenever the user select any date from
   the calendar, the textbox should retain the selected value and not the
   pre-initialized value.

Regards
Khuzaima

--
Regards,
Mukarram Shk. Yaseenali
+91 99788 02752
<https://www.google.com/a/almasaarr.com/images/logo.gif?alpha=1>
Scan the QR Code for Business Card

**Comment by MikhailTymchukDX** [comment]
@khuzaima 
The CalendarExtender uses a ViewState to get or set the `SelectedDate` property.
[The actual assignment](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Calendar/CalendarExtender.cs#L147-L162) occurs during control rendering, which goes after the `Init` event.

Here is an image with an ASP.NET page lifecycle, which illustrates this behavior: 
![ASP.NET page lifecycle](https://i-msdn.sec.s-msft.com/dynimg/IC386473.png)

So, I think it's perfectly fine to assign an initial value to a textbox which the calendar extends.

If you are not satisfied with this solution, you can replace a CalendarExtender with any other calendar, like [jQuery UI Datepicker](https://jqueryui.com/datepicker/), because AJAX Control Toolkit has no conflicts with third-party libraries.

**Comment by MikhailTymchukDX** [comment]
I'm closing this issue.
Feel free to reopen it if you need further assistance.
