### ISSUE TITLE
Version 17.1.0 not appearing as a choice in VS NuGet Package Manager

### ISSUE THREAD

**Issue by grandavenuesoftware** [DevExpress/AjaxControlToolkit#323]
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Attempted to use NuGet Package Manager in Visual Studio to update local version of AjaxControlToolkit from 15.1.4 to 17.1.0.

### Actual result
Version 17.1.0 does not appear as a choice.  16.1.1 is the latest version to be displayed, and is also listed as the "Latest stable" version.

### Expected result
Expected version 17.1.0 to be available as a choice in the "Version" drop-down menu for VS projects.

### Browser(s) used
N/A.

### A site deployment method
- [ ] VS development web-server,
- [x] IIS

![screencapture](https://cloud.githubusercontent.com/assets/23563897/24871386/0c3fa876-1ddf-11e7-9d27-7e2ed2c94dfc.jpg)

![screencapture](https://cloud.githubusercontent.com/assets/23563897/24871482/572f9fb2-1ddf-11e7-9d98-ffc77fc38801.jpg)

**Comment by MikhailTymchukDX** [comment]
Hi @grandavenuesoftware,

v17.1 is not released yet. The latest release is v16.1.1 as you can see at the last screenshot.

**Comment by MikhailTymchukDX** [comment]
@grandavenuesoftware v17.1 is out: https://www.nuget.org/packages/AjaxControlToolkit/
