### ISSUE TITLE
AjaxFileUpload events have an invalid sender

### ISSUE THREAD

**Issue by tehjiapin** [DevExpress/AjaxControlToolkit#327]
### The installation method
- [ ] Installer
- [# ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Setting up the extender as normal way

### Actual result
Failed at ImageUploadComplete as the sender is now a AjaxFileUpload.UploadRequestProcessor instead of AjaxFileUpload. Thus I'm not able to cast it and do the SaveAs as before. 

### Expected result
The ImageUploadComplete sender was previously a AjaxFileUpload which I can cast and do SaveAs.

### Browser(s) used
IE

### A site deployment method
- [ #] VS development web-server,
- [ ] IIS

**Comment by tehjiapin** [comment]
Thank a trillion for the prompt fix.

**Comment by duy14nguyen** [comment]
can you please let me know how to fix this? am i supposed to change OnImageUploadComplete to AjaxFileUpload in the <htmleditorextender> tag?

**Comment by MikhailTymchukDX** [comment]
@dnn14 You can [download the latest build from our CI](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts) and replace the AjaxControlToolkit.dll in your project with the downloaded version.

**Comment by dnn14** [comment]
thank you so much for your reply. but when i do `<ajaxToolkit:HtmlEditorExtender ID="MyHtmlEditorExtender" runat="server" TargetControlID="txtInstruction" DisplaySourceTab="true"
AjaxFileUpload="MyHtmlEditorExtender_ImageUploadComplete"  >
`
it tells me that it's read-only and cannot be set. can you please let me know the correct syntax? thank you

**Comment by dnn14** [comment]
Hello MikhailTymchukDX,
sorry to bother you again but i don't know if I am doing something wrong or what but when i resize the image, save and re-display the content, it doesn't keep the image new dimension. Please let me know if there's a fix for it. Thank you

**Comment by MikhailTymchukDX** [comment]
Hi @dnn14 
Your scenario is not entirely clear to me.
Would you please provide a video record of your steps? You can use a [Jing tool](https://www.techsmith.com/jing.html) for this purpose.

**Comment by dnn14** [comment]
i created the video and hopefully it will explain it better. Thank you for your help.
https://www.screencast.com/t/MTiTY9Mopp

**Comment by dnn14** [comment]
Thank you for your response. I downloaded and installed the latest build 17.1.2.0 and images are still getting resized to its original when display in literal. can you please shed some light? thank you

**Comment by MikhailTymchukDX** [comment]
Hi @dnn14 

This issue is not related to HtmlEditorExtender.
The image you uploaded is handled by your browser. If you switch to the HtmlEditorExtehder source or preview mode, there will be no image size changes.

If you need to change the size of an image you'll need to set its size explicitly with `height` and `width` attributes or resize it on the server before rendering.

**Comment by dnn14** [comment]
if you resize the image inside the editor wouldn't it keep the new size of that image when you re-displaying content?

**Comment by MikhailTymchukDX** [comment]
Actually, not. You are resizing a copy of that image on a client.
When you upload an image to a server, it is stored with an original size, so changing its size has no effect on the image you already uploaded.
