### ISSUE TITLE
Old Uppercase property not working after upgrade from 7

### ISSUE THREAD

**Issue by Thierry-S** [DevExpress/AjaxControlToolkit#332]
Hi,

I was running a custom build of the toolkit, based on 7.1213 from Dec 2013.
(where I had implemented fixes for bugs I raised here, which are now fixed)

On a production server with IIS which runs this ACT 7.1213 version, I have no errors and all works fine.

On my local VS with IIS Express, I tried to upgrade to the latest ACT 17.1.0.0 after reading https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below . I simply replaced the dll in the project, replace `ajaxcontroltoolkit:scriptmanager` with `asp:scriptmanager` and adjusted a few things.
But I get errors (in the console in Chrome developer tools) in js code that deals with the ModalPopupExtender.

My "old" working code:

        var popup = $find('BehaviorId');
        popup._OnOkScript = '$find("' + this.get_element().id + '").saveComment()';
        popup.show();

The `saveComment()` is never fired.

If I modify the markup on the ascx page to include this:
`<ajaxToolkit:ModalPopupExtender ... OnOkScript="TestBlaBla();" />`

The popup object (on breakpoint at `popup.show()` above) has TWO onOkScript, with lower and upper case:

        _OnOkScript: "$find("ctl00_Body_XXXXX").saveComment()"
        _onOkScript: "TestBlaBla();"

I then fixed my code to use the lower case:

        popup._onOkScript = '$find("' + this.get_element().id + '").saveComment()';

and it all works fine.

Elsewhere, I have noticed a warning in the console: `get_PopupControlID() is deprecated. Use get_popupControlID() instead.`, and looking at the callstack, I see this code in the source:

    get_PopupControlID: function() {
        Sys.Extended.Deprecated("get_PopupControlID()", "get_popupControlID()");
        return this.get_popupControlID();
    },
    set_PopupControlID: function(value) {
        Sys.Extended.Deprecated("set_PopupControlID(value)", "set_popupControlID(value)");
        this.set_popupControlID(value);
    },

Have you guys changed a lot of capitalization around the code? This is a bit late for me to upgrade I know... I think I'm just suggesting you list on the upgrade page mentioned above that some capitalization has changed, maybe even provide a list? Or have I missed a post somewhere? Are there other changes that I should be aware of when upgrading? Or maybe it's bad practice to access the property directly, I should have used `set_OnOkScript`, which you might have already wrapped with a deprecated warning? Damn. Just checked, you have ;-)

Thanks,
T

**Comment by MikhailTymchukDX** [comment]
Hi @Thierry-S 

Yes, we corrected accessors capitalization some time ago. This is a non-breaking change, so we did not include it in the list of breaking changes. 

Note that it's a bad practice to access the property directly, because some logic can be executed during property accessing.
To access the `onOkScript` property, please use the `get_onOkScript` getter and the `set_onOkScript` setter.

**Comment by Thierry-S** [comment]
Thanks for the reply.
It's opened for debate that changing the capitalization of properties is non-breaking... it did break my code... bad practice doesn't mean it's not done in the real world.
Anyway, i'm all sorted now, hopefully this page will get indexed by search engines and others might find it useful, since you're not documenting this elsewhere.
Thanks again.
