### ISSUE TITLE
Issue - Cannot read property 'getFullYear' of null

### ISSUE THREAD

**Issue by thaufee** [DevExpress/AjaxControlToolkit#337]
### The installation method
- [x] NuGet package

After upgrading to ACT v17.1. I have been forced to change of using ACT's ToolkitScriptManager to ASP's ScriptManager. After I change this, I was getting "Uncaught TypeError: Cannot read property 'getFullYear' of null" in all the pages where I have Calendar Extender control.

Help me how can I get this done!

**Comment by Skybladev2** [comment]
@thaufee This can be related to #331 
Did you try to update your project with [the latest custom build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts)?

**Comment by thaufee** [comment]
@Skybladev2 Thanks much for giving me the correct path to find solution. Latest custom build has a solution for this issue.
