### ISSUE TITLE
Sys.Extended.Deprecated is undefined in Rating control

### ISSUE THREAD

**Issue by NiekRood** [DevExpress/AjaxControlToolkit#339]
I have a question regarding the rating control.

My CurrentRating is set to 0. When a user submits the review I want to validate if the current rating is > 0, but I can not get this to work.

<cc1:Rating   ID="RateGeneral"  runat="server" ReadOnly="false" 
   StarCssClass="Rate" WaitingStarCssClass="Rate-Wait"  EmptyStarCssClass="Rate-Empty" 
     FilledStarCssClass="Rate-Full" ClientIDMode="Static"  BehaviorID="RatingBehavior1" CurrentRating="0"  MaxRating="5"  > 
</cc1:Rating>

<asp:CustomValidator id="CustomValidator1" runat="server" Display="Dynamic" ErrorMessage="Please select rating"  ValidationGroup="ReqGroep" ClientValidationFunction="CustomValidator1_ClientValidate" ></asp:CustomValidator>

My validationcode is:

function CustomValidator1_ClientValidate(source, args) {

    if ($find('RatingBehavior1').get_Rating() != 0) // rating is not zero
    {
        args.IsValid = true;
    }
    else {
        args.IsValid = false;
    }
}

The error I get is:
Uncaught TypeError: Sys.Extended.Deprecated is not a function
    at Sys.Extended.UI.RatingBehavior.get_Rating

So my question is how to validate the rating control. The value cannnot be 0

The AJAX Control Toolkit  version 17.1.1.0
.NET Framework 4.5

**Comment by MikhailTymchukDX** [comment]
Hi @NiekRood 
There is an error in the old `get_Rating()` method.
Please call the new `get_rating()` method instead:

```js
function CustomValidator1_ClientValidate(source, args) {
	if ($find('RatingBehavior1').get_rating() != 0) // rating is not zero
	{
		args.IsValid = true;
	}
	else {
		args.IsValid = false;
	}
}
```
