### ISSUE TITLE
Auto complete not working in iPad on forward typing

### ISSUE THREAD

**Issue by krajchn** [DevExpress/AjaxControlToolkit#341]
### The installation method
NuGet package

### Minimal steps to reproduce the bug
1. Type a string in the text box in the following site in iPad
http://ajaxcontroltoolkit.com/AutoComplete/AutoComplete.aspx
2. Suggestion list is not shown while typing a text of any length
3. Now delete some characters
4. Continue typing again. Now suggestion list is shown

### Actual result

Suggestion list is not shown on forward typing a text of any length

### Expected result
Suggestion list should be shown

### Browser(s) used
Safari
Chrome

### A site deployment method
VS development web-server,
IIS

My site is similar to the following

http://ajaxcontroltoolkit.com/AutoComplete/AutoComplete.aspx

**Comment by MikhailTymchukDX** [comment]
Hi @krajchn 
I tested AutoComplete with Safari and Chrome on iPad and detected no issues.
Would you please specify the version of iOS and browsers you are using?

**Comment by MikhailTymchukDX** [comment]
We expected an answer from you, however, haven't received it during the last 14 days.
So, we assume that the problem is resolved and will close the ticket.
If the problem still persists, please do not hesitate to reactivate it.

**Comment by krajchn** [comment]
Thanks for the response @MikhailTymchukDX 

Sorry for my delayed response. 
I found out the issue to be in CompletionInterval. I solved it by changing from 5 milliseconds to 1000 milliseconds. Now it is fixed.
