### ISSUE TITLE
Has the open source status of the AJAX Control Toolkit been revoked?

### ISSUE THREAD

**Issue by kipcarter** [DevExpress/AjaxControlToolkit#342]
I was cloning a web app project that I have been working on to attempt to filter out some of the glut that has accumulated in the original project.  All was fine till I attempted to add the AJAX Control Toolkit to the new project and I was unable to find it through the 'Extensions and Updates' tool in VS.

Is the AJAX Control Toolkit no longer available?

### The AJAX Control Toolkit \<VERSION\>
Current version

### The installation method
- X **Visual Studio 2017 Extensions and Updates**
- [ ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Immediate

### Actual result
NOT FOUND!

### Expected result
Find and install to project

### Browser(s) used
N/A

### A site deployment method
- [X] VS development web-server,
- [ ] IIS

**Comment by Mehul** [comment]
For VS integration, be sure to follow the guide here:
https://github.com/DevExpress/AjaxControlToolkit/wiki/Step-by-Step-Installation-Guide

**Comment by kipcarter** [comment]
Thanks!
