### ISSUE TITLE
I installed ajax control tool kit But it was not displaying in toolbox I also installed from NUGET manager Then also it was not showing in tool box  I am using Visual studio 2015 please help regarding this.

### ISSUE THREAD

**Issue by rajeshvku** [DevExpress/AjaxControlToolkit#343]
### The installation method
- [ ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @rajeshvku 
Please attach the installation log that is located in your %TEMP% directory.
For details, refer to the [Troubleshooting Installer Issues](https://github.com/DevExpress/AjaxControlToolkit/wiki/Troubleshooting-Installer-Issues) article.

**Comment by MikhailTymchukDX** [comment]
We expected an answer from you, however, haven't received it during the last 14 days.
So, we assume that the problem is resolved and will close the ticket.
If the problem still persists, please do not hesitate to reactivate it.
