### ISSUE TITLE
Error Invalid argument htmleditor

### ISSUE THREAD

**Issue by elidexter** [DevExpress/AjaxControlToolkit#344]
### The AJAX Control Toolkit \<VERSION\>
AjaxToolkit 17.1.1.0
### The installation method
- [ ] Installer
- [ x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Create on vs 2012 net 4.0 or 4.5 emply web form proyect.
add controls like this
 <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <asp:TextBox ID="TextBox1" runat="server" Height="279px" Width="917px"></asp:TextBox>
        <ajaxToolkit:HtmlEditorExtender ID="TextBox1_HtmlEditorExtender" runat="server" 
            BehaviorID="TextBox1_HtmlEditorExtender" TargetControlID="TextBox1" EnableSanitization="false">
     </ajaxToolkit:HtmlEditorExtender> 

run on ie 10 
![error](https://user-images.githubusercontent.com/29461602/27191159-2c2b6c20-51b4-11e7-8e20-48c181e8e713.PNG)

### Actual result
Only work bold not working list and others opcions..like upload imagen
getting same error ...invalid argument.
### Expected result
all opcion working..
### A site deployment method
- [ x] VS development web-server, 2012
- [ x] IIS 8

![error](https://user-images.githubusercontent.com/29461602/27191194-5067302e-51b4-11e7-9f2d-de1b43477622.PNG)

**Comment by polo8896** [comment]
Same problem... help!!!

**Comment by elidexter** [comment]
...the result?..it will be fixed? :(

**Comment by polo8896** [comment]
????????????..............

**Comment by MikhailTymchukDX** [comment]
@elidexter @polo8896  The build containing the fix can be downloaded from [the AppVeyor CI](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts).
