### ISSUE TITLE
Exception when updated Ajaxcontroltoolkit from 4.1 to 17.1 with Asp.net framework 4.4.1

### ISSUE THREAD

**Issue by urvilshahcs** [DevExpress/AjaxControlToolkit#346]
![error_ajaxupdate](https://user-images.githubusercontent.com/10816675/27233809-b4dd0b94-526f-11e7-8793-67d8ff55d7ff.PNG)
I updated the my Asp.net framework from 4.0 to 4.6.1 and I have I have updated from AjaxControlToolkit from version 4.1 to 17.1 and on One particular page where I have link where it redirects to another page, when I do so , I get the error in IE as "Unable to get property '_events' of undefined or null reference" 
and on chrome as attached . 

I find few work around stating to use toolkit script manager but as it is gone in versions above 15, I can't use it , and I tried checking by commenting different part of code ,but no luck . 
Kindly help with the issue.

**Comment by MikhailTymchukDX** [comment]
Hi @urvilshahcs 
Thank you for reporting this issue!
Would you please isolate this page and provide a sample project so we can start researching it?

**Comment by MikhailTymchukDX** [comment]
@urvilshahcs Could you please clarify if the issue persists on your side? 
It would be of a great help if you provide a sample project for us to research this issue.
I appreciate your cooperation.

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.
