### ISSUE TITLE
AjaxControlToolkit DLLs for .Net framework v3.5

### ISSUE THREAD

**Issue by mwiseman1** [DevExpress/AjaxControlToolkit#348]
A.	Would anyone know how I can find the following for .Net framework v3.5 DLLs? I don’t see these DLLs as part of the Ajax Control Toolkit project.
1.	AjaxControlToolkit.HtmlEditor.Sanitizer.dll
2.	AjaxControlToolkit.ReferenceCore.dll
3.	AjaxControlToolkit.StaticResources.dll
4.	AjaxControlToolkit.Tests.dll

B. Are ACT DLLs packaged with any Microsoft Visual Studio and/or Opentext products?

**Comment by MikhailTymchukDX** [comment]
Hi @mwiseman1 

A. The minimum supported .NET Framework version for the AJAX Control Toolkit is 4.0: https://github.com/DevExpress/AjaxControlToolkit/wiki#system-requirements

You may look for older versions of the toolkit at CodePlex ([December 2013 Release](https://ajaxcontroltoolkit.codeplex.com/releases/view/116091) and older).

AjaxControlToolkit.HtmlEditor.Sanitizer.dll and AjaxControlToolkit.StaticResources.dll are distributed as corresponding NuGet packages: https://www.nuget.org/packages/AjaxControlToolkit.HtmlEditor.Sanitizer/ and https://www.nuget.org/packages/AjaxControlToolkit.StaticResources/

Or you can download [the latest custom build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/branch/master/artifacts) from our CI.

AjaxControlToolkit.ReferenceCore.dll and AjaxControlToolkit.Tests.dll are utility DLLs, so we don't distribute them.

B. No, you need to install it explicitly.

**Comment by mwiseman1** [comment]
ACT 3.5 is available in archives… formerly in CodePlex… not sure why you say 4 is minimum. NuGet does not have 3.5… I know that. Where do I get the utility DLLs???? Where’s the Sanitizer and StaticResources for v3.5??

 

Mark Wiseman 

 <http://www.iWriteCode.me> www.iWriteCode.me / eMail:  <mailto:mwiseman@iWriteCode.me> mwiseman@iWriteCode.me

(703) 344-5823

**Comment by MikhailTymchukDX** [comment]
@mwiseman1 
Older NuGet packages like v7.1005.0 are available for .NET 3.5
We dropped support for .NET Framework 3.5 in v15.1: https://community.devexpress.com/blogs/aspnet/archive/2015/03/10/announcing-the-asp-net-ajax-control-toolkit-v15-1.aspx
