### ISSUE TITLE
AutoComplete extender completion list is hidden when CompletionInterval = 0

### ISSUE THREAD

**Issue by naveenkumargc** [DevExpress/AjaxControlToolkit#349]
### The installation method
- [ ] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug

Add a auto complete extender to a text box and set context key to autocomplete extender on page load. Make attribute MinimumPrefixLength to 0 .Try focusing the text box

### Actual result

Autocomplete does not show any list attached to text box even though if there is a successful call happened to backend web service and retrieval of data in json format (watched through network tab of browser)

### Expected result

Autocomplete extender should list as soon as focus on text box happens

### Browser(s) used

Chrome,
IE

### A site deployment method
- [X] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @naveenkumargc 
We cannot reproduce this issue.
Would you please attach a sample project so we can make a research?

**Comment by naveenkumargc** [comment]
Please checkout the following repo:

[Test Auto complete extender](https://github.com/naveenkumargc/Test-Auto-complete-extender)

**Comment by MikhailTymchukDX** [comment]
@naveenkumargc Thank you for the sample project!
The problem is related to `CompletionInterval = 0` but not to the `MinimumPrefixLength` property value.
If you increase it to 100 or so, you'll see a completion list when clicking on a text box.
