### ISSUE TITLE
Generic error every time I try to upload.

### ISSUE THREAD

**Issue by kevinkey619b** [DevExpress/AjaxControlToolkit#353]
### The installation method
- [ ] NuGet package

### Minimal steps to reproduce the bug
Try to upload any image file

### Actual result
Displays (error) in red. No details.

### Expected result
File gets saved to hard drive.

### Browser(s) used
Microsoft Edge.

### A site deployment method
- [ ] VS development web-server,

I'm not sure how to get this working. I installed via the NUGet package. No matter what, the control just returns (error) when I attempt to upload an image. Is it possible to get a more detailed error message?

**Comment by kevinkey619b** [comment]
I have tried in Chrome with the same result: just a generic "(error)" in red. Does this plugin support either Chrome or Edge? How do I get a detailed error message? Is this still supported?

**Comment by kevinkey619b** [comment]
And yes yes yes, the following is in my web.config:
<httpHandlers>
  <add verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit"/>
</httpHandlers>

Is there some other way to do AJAX uploads using .NET 4.5? Having no luck here.

**Comment by MikhailTymchukDX** [comment]
Hi @kevinkey619b 
What is the extension of the file which you are trying to upload?

**Comment by MikhailTymchukDX** [comment]
Duplicate #354
