### ISSUE TITLE
CalendarExtendar with MaskedEditExtender not working with Chrome but working in IE

### ISSUE THREAD

**Issue by NitaKokat** [DevExpress/AjaxControlToolkit#355]
### The installation method
- [x] NuGet package

### Minimal steps to reproduce the bug
Add textbox with CalendarExtendar  and MaskedEditExtender, and try to select date from calendar with empty textbox

### Actual result
textbox does not update selected value it keep mask as is "__ /__ /_____"
### Expected result
it should show selected date in textbox
### Browser(s) used
Chrome
### A site deployment method
- [x] VS development web-server,

**Comment by MikhailTymchukDX** [comment]
Hi @NitaKokat 
What is the mask used in MaskedEditExtender?
What is the date format in your system?

**Comment by NitaKokat** [comment]
mask is "99/99/9999"
date format of my system is "MM/dd/yy"

**Comment by NitaKokat** [comment]
Version of  AjaxControlToolKit is v17.1.0.0

**Comment by MikhailTymchukDX** [comment]
If you want to be sure what date format CalendarExtender has, you can set the `Format` property to "MM/dd/yyyy".

If you want to allow a user to enter date manually with MaskedEditExtender while keeping an ability to select it by the CalendarExtender, you can't do that in the current design.
Both CalendarExtender and MaskedEditExtender assume that they utilize a textbox exclusively. This can lead to unexpected behavior.

**Comment by NitaKokat** [comment]
if both CalendarExtender and MaskedEditExtender utilize a textbox exclusively, then Why it is working in IE ?

**Comment by MikhailTymchukDX** [comment]
@NitaKokat I cannot reproduce this issue in Chrome. 
Would you please provide a sample project that illustrates this issue?

**Comment by NitaKokat** [comment]
@MikhailTymchukDX How can I share Sample project with you? I am not able to attach my sample project because of large size.

**Comment by MikhailTymchukDX** [comment]
@NitaKokat You can upload it to Google Drive or Dropbox.

**Comment by NitaKokat** [comment]
https://drive.google.com/file/d/0B6EY3ZAV7ZntSktkcTBVZDNGTE0/view

**Comment by NitaKokat** [comment]
@MikhailTymchukDX any update on this?

**Comment by MikhailTymchukDX** [comment]
Hi @NitaKokat 
I managed to fix this issue by performing two actions:
1. Set Calendar's `Format` property to "MM/dd/yyyy"
2. Replace AjaxControlToolkit.dll with [the latest custom build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts) from our CI.

**Comment by NitaKokat** [comment]
Hi @MikhailTymchukDX 
I have performed these two actions but still I'm facing same issue.
![image](https://user-images.githubusercontent.com/29773868/27787854-edd37d56-6003-11e7-8057-d4b35dc25dc2.png)

**Comment by MikhailTymchukDX** [comment]
@NitaKokat I believe this happens because of some kind of caching.
I've attached the modified sample project that runs correctly on my computer: [WebApplication1.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1119162/WebApplication1.zip)

If you use IIS Express, make sure there are no `iisexpress.exe` processes running before you start the application.

**Comment by NitaKokat** [comment]
@MikhailTymchukDX  Thank you.. This is working for me

**Comment by NitaKokat** [comment]
Hi @MikhailTymchukDX  When you are going to release next version of AjaxControlToolKit?

**Comment by MikhailTymchukDX** [comment]
We have not planned release date yet.
Please follow [our blog](https://community.devexpress.com/blogs/aspnet/archive/tags/AjaxControlToolKit/default.aspx) for updates.

**Comment by NitaKokat** [comment]
@MikhailTymchukDX any tentative date or how much time it will take, any idea?
