### ISSUE TITLE
CalendarExtender breaks after a postback with the textbox containing an invalid date

### ISSUE THREAD

**Issue by oaktechnology** [DevExpress/AjaxControlToolkit#357]
### The AJAX Control Toolkit \<VERSION\>
17.1.1
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Have a textbox with autopostback set to true and associated with the CalendarExtender
Enter a date which does not match the expected formatted value (i.e. 1/1/2017)
When the page posts back the date cannot be changed via the calendar as all the calendar shows is a white box and nothing is selectable.  
### Actual result
An unworking calendarextender control
### Expected result
Default behaviour for the calendar control. Even if the date is corrected and another postback occurs then the control remains broken unless the page the formview is reloaded completely.
[samplecode.txt](https://github.com/DevExpress/AjaxControlToolkit/files/1123978/samplecode.txt)

### Browser(s) used
Edge, Firefox and Chrome
### A site deployment method
- [X ] VS development web-server,
- [X ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @oaktechnology 
I have managed to reproduce this issue with the AJAX Control Toolkit v17.1.1
Updating to [the latest custom build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/branch/master/artifacts) resolves the problem.
Please refer to [this article](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) for more details.

**Comment by oaktechnology** [comment]
Fantastic, I think that's the fastest response I have ever seen in my life.  Great work and thanks again!
