### ISSUE TITLE
UpdatePanelAnimationExtender issue with AjaxControlToolkit 15.1.3 through 16.1.0 (Unable to get property 'id' of undefined)

### ISSUE THREAD

**Issue by fanningm** [DevExpress/AjaxControlToolkit#36]
In case this hasn't been reported already (I was unable to find anything in the list of Issues here), see the following article which is where I found a "fix" for my issue "Unable to get property 'id' of undefined" when using the UpdatePanelAnimationExtender:
http://stackoverflow.com/questions/33961117/updatepanelanimationextender-doesnt-work-when-usesubmitbehavior-false

Thank you in advance for looking into this.

**Comment by MikhailTymchukDX** [comment]
@fanningm I was able to reproduce this bug in v15.1.4, but it does not exist in v16.1.0.
Please upgrade to the latest version of the AJAX Control Toolkit to resolve this issue.

**Comment by fanningm** [comment]
I had already tried 16.1.0 (as noted in the subject line) which also appeared to exhibit the same error, so there might be something else in my code that is triggering this.  I'll try it again and see if I can come up with anything more specific.
