### ISSUE TITLE
AJAX ModalPopupExtender not working when published to web server

### ISSUE THREAD

**Issue by KarlSNHY** [DevExpress/AjaxControlToolkit#367]
I developed a small web app that uses the AJAX Control Toolkit. On my computer, all of the AJAX controls work properly. However, when I publish my site to my web server, the ModalPopupExtender no longer works.

•My environment: Windows 10, Visual Studio Enterprise 2015, IE 11 
•Server environment: Windows Server 2012 R2, IIS 8.5.9600, IE 11
•Using AJAX Control Toolkit ver 16.1, installed from GitHub repository

When I click the button that should bring up the modal popup window, nothing happens. No error is displayed, even when the site is viewed on the web server using the actual URL (http://servername/appname). What is really strange is that if I go to the site in IIS and click the "Browse *.80 (http)" link, it works properly (using the URL http://localhost/appname)

I know the ACT is working, because I have another button with an ConfirmButtonExtender on it and that works fine (both on my machine and the server). As the ModalPopupExtender uses a CSS file, I was suspicious that it wasn't set up properly. My site uses master pages, so I added the reference to the CSS file in the Master page. I know it is working on my computer, because if I make a small change to the CSS file it is reflected on the popup panel.

In IIS, the site is configured to use an Application Pool. I have set the application pool to use a domain service account. This account has full read/write permissions on the folder containing the web site files & folders.  I have attached a sample project that demonstrates this issue.  When published to the web server, the ConfirmButtonExtender works, but the ModalPopupExtender does not.

[AjaxTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1141986/AjaxTest.zip)

I feel like I am missing something simple, but the nature of this is making it hard to research (too many false links when "server" is included in the search).

**Comment by MikhailTymchukDX** [comment]
Hi @KarlSNHY 
Thank you for reaching out to us.
I tried to replicate your environment and didn't face any errors.

Please try the following:
1. Open a published site with other browsers (Chrome, Firefox) and check if the error occurs.
2. Provide us with the page source in browsers where the problem persists. To get the page source, press Ctrl+U when the page is loaded.

**Comment by KarlSNHY** [comment]
Hi MikhailTymchukDX,

Thank you very much for your prompt reply.  I was surprised to see that when I viewed the page in Chrome it worked perfectly.  Both the ConfirmButtonExtender and ModalPopupExtender functioned normally.

Therefore, I brought the page up I IE, and have attached the page code.  I changed the extension from*.HTM to *.TXT to make sure it came through on this reply.  Please let me know what you think and what further information I can provide.

Thank you again,
Karl

**Comment by MikhailTymchukDX** [comment]
Hi @KarlSNHY 
Thank you for your response.

I slightly modified your sample project:

* Moved some assemblies to NuGet packages, including the AjaxControlToolkit assembly.
* Updated the AJAX Control Toolkit to v17.1.1 to make sure we did not face an old bug.
* Added the [AjaxControlToolkit.StaticResources](https://www.nuget.org/packages/AjaxControlToolkit.StaticResources/) NuGet package to recognize what scripts are being loaded.

Please deploy this project to your IIS, open it in IE and provide us with the page source again: [AjaxTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1145539/AjaxTest.zip)

**Comment by KarlSNHY** [comment]
Hi MikhailTymchukDX,

Success!  When I published your modified project to my web server, it worked properly in IIS (both as the localhost\appname and servername\appname format).  I noticed that in the localhost version the popup panel corners were rounded and not in the other version, but that's trivial at this point.  As you requested, I have attached my page source.

I have to admit that I am not familiar with the processes you describe above.  Can I just get the v17.1.1 version from NuGet, or do I need to remove the existing version first?  I understand that you have just demonstrated that this is not a "bug", so if you want to just point me to some online documentation on how to proceed, that would probably be fine.

I really appreciate your fast responses and continued support!  

Thank you ,
Karl
[Home Page - My ASP.NET Application.txt](https://github.com/DevExpress/AjaxControlToolkit/files/1145619/Home.Page.-.My.ASP.NET.Application.txt)

**Comment by MikhailTymchukDX** [comment]
@KarlSNHY 
I'm happy to hear it!

> Can I just get the v17.1.1 version from NuGet, or do I need to remove the existing version first?

You can install the NuGet package without removing anything in your project as described here: https://github.com/DevExpress/AjaxControlToolkit/wiki/Step-by-Step-Installation-Guide#nuget-package

It will replace your assembly with a proper version.
