### ISSUE TITLE
Version 17 ajaxfileupload doesn't respect allowedfiletypes

### ISSUE THREAD

**Issue by ericberman** [DevExpress/AjaxControlToolkit#372]
### The installation method
- [ ] Installer
- [x ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Install 17.1.1.  Set up an ajaxfileupload control, set allowedtypes="kml".  Drag a KML file onto it.

### Actual result
Throws an exception on the server: "File extension not allowed"; client control simply displays red "error".

### Expected result
Should upload the file

### Browser(s) used
(any)

### A site deployment method
- [ ] VS development web-server,
- [ x] IIS

Reverting to 16.1.1 works flawlessly.

**Comment by MikhailTymchukDX** [comment]
Hi @ericberman 

To fix this error, please add the `additionalUploadFileExtensions` attribute to the `ajaxControlToolkit` section in your Web.config:
```xml
<configSections>
    <section name="ajaxControlToolkit" type="AjaxControlToolkit.AjaxControlToolkitConfigSection, AjaxControlToolkit" requirePermission="false"/>
</configSections>
<ajaxControlToolkit additionalUploadFileExtensions="kml" />
```

More info can be found in our wiki article: https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#allowed-file-extensions

**Comment by ericberman** [comment]
I somehow missed that; thanks so much - works perfectly.
