### ISSUE TITLE
AjaxControlToolkit version upgraded from version 15.1.3.0 to 17.1.1.0, AutoStartUpload="true"

### ISSUE THREAD

**Issue by icstiwari** [DevExpress/AjaxControlToolkit#373]
### The AJAX Control Toolkit \<VERSION\>
17.1.1.0
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
1. Select a file to upload or drag and drop to upload a single file.
2. With AutoStartUpload, there is no "Upload" and "remove" button anymore and it automatically uploads to a temporary location without the need to click Upload button.
### Actual result
File uploads automatically to a temp location.
### Expected result
Question - With this Auto Upload setting, is it still possible to "Remove" the uploaded file if I decide to change my mind and I want to Upload some other single file instead of the one I just uploaded?
### Browser(s) used
Firefox 54.0.1 (32-bit), IE 10,11 and Chrome
### A site deployment method
- [ ] VS development web-server,
- [x] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @icstiwari 
I do not completely understand your scenario.
AjaxFileUpload does exactly what you are trying to do when `AutoUpload` is set to false.

**Comment by icstiwari** [comment]
1. True, understood that when AutoUpload is set to false, 
 You need to first Select a file. After selection you see "Upload" and "Remove" buttons. And if you have made a wrong selection, you could "Remove" the file by clicking "Remove" button and then click Select to pick another file to Upload. Once  you click "Upload" the file gets uploaded to Attachment TEMP folder on the server. And once I click Save button, this file finally gets uploaded to the Attachments folder.

2. Now with AutoUpload set to true, when you Select a file to Upload, it auto uploads to the Attachment TEMP folder. 
I am wondering, if there is any possibility that you could still "Remove" this file from the TEMP folder and Select another file to AutoUpload to the TEMP folder. 
My setting is to Upload only one file at a time.

Hope this clarifies.

**Comment by MikhailTymchukDX** [comment]
@icstiwari 
Thank you for your clarification!

It is impossible to remove an uploaded file with any value of the `AutoUpload` property.

When upload is completed, AjaxFileUpload raises the server-side `UploadComplete` event to which file content and metadata are passed.
Then, an application decides what to do with this info: ignore it, save data as a file, put it to a database, send over the network, so on.
After this event is raised, AjaxFileUpload has no control over the uploaded file.

In the next version of the toolkit, temporary files are deleted immediately after the `UploadComplete` event (you can now check this with [the custom build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/branch/master/artifacts)).

So, if you care about the content of the TEMP folder, you can check the latest version of the toolkit.

**Comment by icstiwari** [comment]
Hmmm, thank you for the explanation!

Right now, after I click the Save button, the File is Moved from the temp folder to the actual Attachments folder.
I think I might have to look into a possibility of adding a "Remove" button outside of the FileUploader. Clicking of this button could then Delete the auto uploaded file from the Temp folder and show/enable the File Uploaders' "Select" button once again to be able to Select a new file. This is just an idea.

Do you foresee any problem in doing so? I know it is of no concern to you what I do after the File is uploaded in the Temp area.

**Comment by MikhailTymchukDX** [comment]
@icstiwari 
Your approach will not work in future versions of the toolkit, because the temporary file is deleted immediately after the `UploadComplete` event is raised. The structure of a temp folder is also changed.

The proper way is to save a file in the `UploadComplete` event handler. That way, the "Remove" buttons will work with your application resources, over which you have full control.

**Comment by icstiwari** [comment]
I think there is a misunderstanding on our implementation of File Uploader.
1. When I Select and AutoUpload a file, the UploadComplete event Uploads the file to a Temporary Folder that is  configured in our application , 
say fullpath = AttachmentPath/AttachmentTemp. 
So the following loads it in this AttachmentTemp folder - 
AjaxFileUpload1.SaveAs(fullpath)

2. And after I click the Save button, I move the file from this AttachmentTemp location to the main Attachment Folder in the application and also insert in the Database. 
SO, while the file is still in the AttachmentTemp folder, I can probably Remove it if the user decides to Select a new one to Upload.

3. What you might be referring to, in the above comment is the Temp Folder (probably "~/App_Data??) that the AjaxFileUploader might be using??

Sorry if I confused you on our implementation.

**Comment by MikhailTymchukDX** [comment]
@icstiwari 
Ok, I got it.
I see no problems with this approach.

**Comment by icstiwari** [comment]
Very good. Thank you for your input!

**Comment by icstiwari** [comment]
While on the subject I would like a few clarifications  - 
1. So, where does the AjaxFileUploader save the Uploaded file when we have AutoUpload set to false or true?
2.  And with the new enhancement you mention that it will Auto Delete the uploaded file from the Temp folder. Which Temp Folder are you referring to and where do I see that?

**Comment by MikhailTymchukDX** [comment]
@icstiwari 
1. It saves the uploaded file to the Temp folder you set in your Web.config:
```xml
<ajaxControlToolkit tempFolder="~/Temp"/>
```

2. The one I mentioned in p.1.

**Comment by icstiwari** [comment]
1. OK, right now I do not have that setting in my web.config under <ajaxControlToolkit>.
2. The only setting I have is one for "AttachmentPath".
3. And then as I mentioned in my earlier comment, I build the path as - 
   fullpath = AttachmentPath/AttachmentTemp.
  So the following loads it in this AttachmentTemp folder -
  AjaxFileUpload1.SaveAs(fullpath)
4. And in my code, when I click "Save" to upload to server and DB, I Move this file (and hence delete from source) from Temp to  "AttachmentPath" folder. 

Question - Are you saying that in the new version, the Uploader will automatically delete from the "fullpath" OR configuring the "<ajaxControlToolkit tempFolder="~/Temp"/>" will be mandatory??

**Comment by MikhailTymchukDX** [comment]
@icstiwari 
No, AjaxFileUpload deletes uploaded files from its own temp folder.
If this folder is not set via Web.config, it is detected automatically.

**Comment by icstiwari** [comment]
>>>If this folder is not set via Web.config, it is detected automatically.
1. Where exactly does the File Uploader save right now - which Temp directory. 
And if those files are not getting deleted right now,  is it ok to Delete those files to clear the Temp folder?

2. And this means for sure that my approach to be able to Remove the Uploaded files will definitely work as confirmed by you - 
>>>
Ok, I got it.
I see no problems with this approach.
>>>
Sorry for repeating myself, but I need to make sure before I promise this solution to anyone and to avoid any conflicts in future upgrades.
And thank you for your time!
