### ISSUE TITLE
Child cascading dropdowns do not reset to prompt on parent value change.

### ISSUE THREAD

**Issue by studmuffler** [DevExpress/AjaxControlToolkit#374]
### The AJAX Control Toolkit 17.1 and below
All versions
### The installation method
- [X] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
1. **replace SampleSite source files with attached files** (App_Data/CarService1.xml, App_Code/CarService.cs)
2. **rebuild and run the SampleSite**
3. **open Cascading Dropdown Extender demo page**
4. **select make, select model, select color.** Note changes to label below dropdowns.
5. **re-select model.** Note that selection in color dropdown did not reset selected item to 'Please select color', and label below did not reflect change in model.

### Actual result
Child dropdowns do not get reset to select prompt when parent dropdown selection changes. It happens when dropdown values are the same (like same colors for all cars in my sample) but works when ALL values are different (original sample package).

### Expected result
Children dropdowns MUST always reset to select prompt independently of underlying data values when any parent selection changes.

### Browser(s) used
All (mostly Chrome)
Visual Studio 2012, Windows 7 Pro

### A site deployment method
- [X] VS development web-server,
- [X] IIS-EXPRESS
[CarsService1.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1177871/CarsService1.zip)

- [ ] IIS

- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @studmuffler

I confirm that this is an issue, but it seems that it has been present for such a long time that some developers started to rely on this behavior in their projects.

So, to keep backward compatibility, we have introduced a new `ClearSelectedItemOnParentChange` property that is set to`false` by default. See #375 for details.  

Please set this property to `true` to enable resetting selection for child components.
