### ISSUE TITLE
CalendarExtender causes JavaScript runtime error after typing invalid date

### ISSUE THREAD

**Issue by tripleseven73** [DevExpress/AjaxControlToolkit#376]
### The AJAX Control Toolkit \<VERSION\>
17.1.0, 17.1.1

### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
1. Create new and empty ASP.NET Web Application project in VS (.NET 4.5)
2. Add AjaxControlToolkit NuGet package
3. Add Default.aspx Web Form
4. Add following controls to Default.aspx:

		<asp:ScriptManager runat="server" ScriptMode="Release" />
		<asp:TextBox runat="server" ID="PayedOn" />
		<ajaxToolkit:CalendarExtender runat="server" TargetControlID="PayedOn" />

5. Run application
6. Place focus on textbox
7. Type something that isn't a date (e.g. "abc")
8. Leave textbox using "Tab" key

### Actual result
JavaScript runtime error:  Unable to get property 'getFullYear' of undefined or null reference

### Expected result
No error. Invalid date should simply be ignored as does the 16.x version.

### Browser(s) used
Internet Explorer 11, Chrome 59.0, FireFox 54.0

### A site deployment method
- [x] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Duplicate #331
