### ISSUE TITLE
XML Parsing error logged in the Firefox browser's console after uploading the file using AjaxFileUpload control from AjaxToolkit

### ISSUE THREAD

**Issue by svetlanamutu** [DevExpress/AjaxControlToolkit#377]
Hello,

I am trying to use the AjaxFileUpload control from the ASP.NET AJAX Toolkit v17.1.1.0 in my ASP.NET web application.  Whenever the file gets uploaded, I get  an error logged int he console of  developer tools in Firefox:
'
XML Parsing Error: no root element found
Location: https://someserver.domain.com/Review/AjaxFileUploadHandler.axd?contextKey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&controlID=MainContent_AjaxFileUpload1&fileId=4B36466C-D84E-B92F-8104-DB63A69D67B4&fileName=Penguins.jpg&chunked=false&firstChunk=true
Line Number 1, Column 1:
AjaxFileUploadHandler.axd:1:1
'

----------
I was able to reproduce the same error with your demo page in the Firefox browser (latest version - 54.0.1, 32-bit, Funnelcake Onboarding Q1 2017 -v1.6 variation mozilla102 - 1.0) at:  https://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx.
Please help me understand how to fix it.

Thank you so much,
Svetlana

### The installation method
- [X] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Just place an the AjaxFileUpload on an empty web form (default page of a web application project in asp.net) and try to use the AjaxFileUpload control with Firefox browser.
### Actual result
Files get uploaded but this error is recorded in the console:
'XML Parsing Error: no root element found
Location: https://someserver.domain.com/Review/AjaxFileUploadHandler.axd?contextKey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&controlID=MainContent_AjaxFileUpload1&fileId=4B36466C-D84E-B92F-8104-DB63A69D67B4&fileName=Penguins.jpg&chunked=false&firstChunk=true
Line Number 1, Column 1:
AjaxFileUploadHandler.axd:1:1'

### Expected result
No error
### Browser(s) used
Firefox. Chrome and IE do not log this error in the console.
### A site deployment method
- [ ] VS development web-server,
- [ x] IIS

**Comment by AbdoMeInc** [comment]
![163599_181373888562782_6354909_n](https://user-images.githubusercontent.com/17953609/32147457-37f5916e-bcf0-11e7-8393-82aa6e272533.jpg)

**Comment by coolboi567** [comment]
I encountered the same error while trying to make PUT ajax call to upload file to Minio's presigned url.
Though action was fine and the upload was a success.

```
var xhr = new XMLHttpRequest ()
xhr.open('PUT', url, true)
xhr.send(file)
```

**Error in console**
```XML Parsing Error: no root element found Location:
http://localhost:9000/test/9c04cd6372077e9b11f70ca111c9807dc7137e4b.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=IHZRE4WP7UPMWK5E1387%2F20180930%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180930T144608Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=32455ec09deb95de48951a92038513112d343265f46e33d35c881d42db0c8eff
Line Number 1, Column 1:```

**Comment by coolboi567** [comment]
I encountered the same error while trying to make PUT ajax call to upload file to Minio's presigned url.
Though action was fine and the upload was a success.

```
var xhr = new XMLHttpRequest ()
xhr.open('PUT', url, true)
xhr.send(file)
```

**Error in console**
```
XML Parsing Error: no root element found Location:
http://localhost:9000/test/9c04cd6372077e9b11f70ca111c9807dc7137e4b.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=IHZRE4WP7UPMWK5E1387%2F20180930%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180930T144608Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=32455ec09deb95de48951a92038513112d343265f46e33d35c881d42db0c8eff
Line Number 1, Column 1:
```

**Comment by AlekseyMartynov** [comment]
@coolboi567 

For PUT method with IIS, check this:
https://stackoverflow.com/q/6147181

**Comment by sathishkumar1911** [comment]
This is  because of empty response.
https://knowledgebase.progress.com/articles/Article/firefox-xml-parsing-error-no-root-element-found-when-updating-record-from-portal-using-rest-api

**Comment by Ovini** [comment]
I think it's due to the return type of controller action method. I received the same error( but not with File Upload) and resolved as per [this article](https://ovinitech.blogspot.com/2019/01/xml-parsing-error-no-root-element-found.html).
