### ISSUE TITLE
AjaxControlToolkit Rating_Changed event fires twice

### ISSUE THREAD

**Issue by polarbear17** [DevExpress/AjaxControlToolkit#379]
### The AJAX Control Toolkit \<VERSION\>
AjaxControlToolkit v 17.1.1
### The installation method
- [ ] Installer
- [ x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Rating control clicked resulted in Rating_Changed event fired twice
### Actual result
Rating count is indeed incremented twice in database
### Expected result
Rating count should only be incremented by one in database
### Browser(s) used
All major browsers tried with same result, Chrome, Firefox, IE, Opera
### A site deployment method
- [ x] VS development web-server,
- [ ] IIS

**Comment by polarbear17** [comment]
Hi.  Thank you for the fix.  Also, can you tell me how to get the fix as I'm new to github.  I  searched and couldn't find a download link for it.  Thanks again.

**Comment by MikhailTymchukDX** [comment]
Hi @polarbear17 
You can download [the latest build from our CI](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts) and replace the AjaxControlToolkit.dll in your project with the downloaded version.

**Comment by polarbear17** [comment]
Hi @MikhailTymchukDX 
That's great.  I'll go ahead and do that.  I'm much appreciated for your help.  Thank you!
