### ISSUE TITLE
new nuget release - when?

### ISSUE THREAD

**Issue by tdjastrzebski** [DevExpress/AjaxControlToolkit#383]
Hi, when do you plan a new NuGet release?
I am particularly interested in #347 & #371.

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski 
While we have no immediate plans to make a release, we have collected some valuable changes to make one.
I'll investigate if we can release a new version in the immediate future and will inform you when we are ready.
Stay tuned.

**Comment by tdjastrzebski** [comment]
Hi @MikhailTymchukDX, I could publish ScriptUserControl extension on NuGet but new act needs to go first.

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski ,
I understand your concern.

If you want to publish a ScriptUserControl package as soon as possible, I propose the following tweak: embed the latest AjaxControlToolkit.dll directly into your package.
When we publish the next release, you can make a new version of a package that has a dependency on the AjaxControlToolkit.

**Comment by grandavenuesoftware** [comment]
Similar desire, hoping for an official release via NuGet that includes the fix for #331.  Thanks.

**Comment by tdjastrzebski** [comment]
Hi @MikhailTymchukDX, I will wait for the new release.

**Comment by sebaim** [comment]
Some news about new package?

**Comment by MikhailTymchukDX** [comment]
@sebaim We have scheduled it for January.
