### ISSUE TITLE
AutoCompleteExtender: MouseClick/Tab working "strange" in Chrome

### ISSUE THREAD

**Issue by MaxZeta** [DevExpress/AjaxControlToolkit#385]
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
In Chrome Windows (Ver >59)  & Chrome Android  :  Mouse Click or Tab key on an item fill textbox correctly , but  Chrome reports a "canceled operation" ( Devtool F12 ) and TextBox.TextChanged fires twice, Updatepanel not Update.
No issue when I press ENTER key in Chrome
No issue in IE11, Edge. 

### Browser(s) used
Chrome Ver 60

**Comment by MikhailTymchukDX** [comment]
Hi @MaxZeta 

I tried to reproduce this behavior using Chrome 60.0.3112.113 (64-bit), but only this warning occurs to me:
![image](https://user-images.githubusercontent.com/17080984/30585688-58b4fa04-9d36-11e7-9248-27aebdcb4632.png)

Would you please provide a sample project so I can research it on my side?

**Comment by MaxZeta** [comment]
Hi Mikhail,

My System : Windows 8.1 64bit, Chrome 61.0.3163.91  32 bit

1) a sample site : http://www.massimozambra.com/demoautocompleteextender/

2) About Textbox_Textchanged fired twice : happens sometimes

3)
Chome Windows:
When I select an item with mouseclick or Tab key , canceled operation
appears
No issue with Enter Key
No issue with IE

Same on Android Chrome when select item with my finger ( Tablet/Smartphone
) ,
no issue with stock browser

[image: Immagine incorporata 1]

Source code in attachment.

If You need something else...

Thanks

Max

2017-09-19 11:35 GMT+02:00 MikhailTymchukDX <notifications@github.com>:

**Comment by MikhailTymchukDX** [comment]
@MaxZeta
Thank you for your response.
Unfortunately, I don't get any errors on your site.

I don't see the source code you attached. This is a known problem when replying via e-mail.
Please add it using a GitHub web site interface.

**Comment by MaxZeta** [comment]
​I've found another user with the same problem:

https://stackoverflow.com/questions/42306954/ajaxcontroltoolkit-autocompleteextender-does-not-work-when-using-mouse-click​


--------------------------------------------------------------------------------------------------------------------------------
My code ( complete ) :
--------------------------------------------------------------------------------------------------------------------------------


<%@ Page Language="VB" MaintainScrollPositionOnPostback="true"
EnableEventValidation="false" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit"
TagPrefix="ajaxToolkit" %>
<%@ Import Namespace="System.Data.oledb" %>
<%@ Import Namespace="System.Data" %>
<%@ Import Namespace="System.Net" %>
<%@ Import Namespace="System.Threading.Tasks" %>
<%@ Import Namespace=" System.IO" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "
http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script runat="server">
    <System.Web.Script.Services.ScriptMethod()>
    <System.Web.Services.WebMethod>
    Public Shared Function GetCompletionList(prefixText As String, count As
Integer) As List(Of String)
        Dim dt As DataTable = New DataTable
        Dim sqlStatement As String = "select trim(Prodotto) from Prodotti
where Prodotto like '%" & prefixText & "%' order by prodotto"
        Dim da As OleDbDataAdapter = New OleDbDataAdapter(sqlStatement,
ConfigurationManager.ConnectionStrings("Spesaconnection").ConnectionString)

        da.Fill(dt)
        Dim l_list As List(Of String) = New List(Of String)
        For Each l_row In dt.Rows
            l_list.Add(l_row(0).ToString)
        Next
        Return l_list
    End Function

    Protected Sub FilterProdotti_TextChanged(sender As Object, e As
EventArgs)
        Me.LabelResult.Text += sender.text & " - " & Now & "<BR>"
    End Sub

    Protected Sub TextBox1_TextChanged(sender As Object, e As EventArgs)
        Me.LabelResult.Text += sender.text & " - " & Now & "<BR>"
    End Sub
</script>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="stylesheet" type="text/css" href="Spesa_stile.css" />
    <title>Spesa</title>
</head>
<body>

    <form id="form1" runat="server">
        <asp:ScriptManager ID="ToolkitScriptManager1" runat="server"
EnablePageMethods="true" EnablePartialRendering="true" />
        <asp:UpdatePanel ID="UpdatePanelFilter" runat="server"
UpdateMode="Conditional" ChildrenAsTriggers="true">
            <ContentTemplate>
                <asp:TextBox ID="TextBox1" CssClass="FilterTextBox"
runat="server" AutoPostBack="true" OnTextChanged="TextBox1_TextChanged"
placeholder="test" />

                <asp:TextBox ID="FilterProdotti" CssClass="FilterTextBox"
runat="server" AutoPostBack="true"
OnTextChanged="FilterProdotti_TextChanged" placeholder="Find..." />
                <ajaxToolkit:AutoCompleteExtender
ID="AutoCompleteExtender1" runat="server" TargetControlID="FilterProdotti"
                    MinimumPrefixLength="1" EnableCaching="true"
                    CompletionSetCount="1" CompletionInterval="5"
                    ServiceMethod="GetCompletionList"

CompletionListCssClass="autocomplete_completionListElement"
                    CompletionListItemCssClass="autocomplete_listItem"

CompletionListHighlightedItemCssClass="autocomplete_highlightedListItem" />
                <div id="result" runat="server">
                    <asp:Label ID="LabelResult" runat ="server" />
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</body>
</html>


2017-09-19 14:18 GMT+02:00 MikhailTymchukDX <notifications@github.com>:

**Comment by MaxZeta** [comment]
Ps: new test on my collegue Pc : Windows 10 64bit, same Chrome version (32bit 61.0..)
Same "error"
![image](https://user-images.githubusercontent.com/32071772/30593038-87f78d96-9d49-11e7-9209-9a4fea1d224e.png)

**Comment by MikhailTymchukDX** [comment]
Hi @MaxZeta 

I managed to reproduce this behavior on your site by typing fast into the second textbox. I see a pending request, which turns canceled when the next request is sent.

According to [the source code](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/AutoComplete.js#L634-L636), this is intended.

However, I could not replicate this behavior locally.
Would you please provide a sample project that illustrates this issue out-of-the-box?

**Comment by MaxZeta** [comment]
Hi Mikhail,

Issued started about six months ago.
Same web application ,   same hosting provider, same AjaxToolkit version.

only difference: Chrome update ( windows and Android )

All Chrome installations I've seen are 32 bit (auto-update)

After some debug in my application I've found the different behaviour
from  *ENTER
KEY* vs *TAB KEY/MOUSE CLICK*

Now, I'm reading the source code in your link:

the different I noticed is: TAB KEY/ MOUSECLICK haven't ev.preventDefault();

Why ?

















2017-09-20 11:31 GMT+02:00 MikhailTymchukDX <notifications@github.com>:

**Comment by MaxZeta** [comment]
Yesss :)

I download AjaxToolKit Source Code 17.0.1.2 , Open in VS2015

*AutoComplete.js*



I have added :

*ev.stopPropagation();*
*ev.preventDefault();*

to* TAB KEY event *and * MouseDown Event*


Recompiled and tested ( maybe too fast test :) )

and issue is gone!!!


    _onListMouseDown: function(ev) {
        if (ev.target !== this._completionListElement) {
            *ev.stopPropagation();*
*            ev.preventDefault();//MaxZeta 20170920: added to resolve
chrome issue*
            this._setText(ev.target);
            this._flyoutHasFocus = false;
        } else { // focus is still on the flyout and we do not want to hide
it
            this._flyoutHasFocus = true;
        }
    },





       else if (k === Sys.UI.Key.enter) {
            if (this._selectIndex !== -1) {

this._setText(this._completionListElement.childNodes[this._selectIndex]);
               * ev.stopPropagation(); **//MaxZeta ????????? needed ?*
                ev.preventDefault();
            } else {
                // close the popup
                this.hidePopup();
            }
        }
        else if (k === Sys.UI.Key.tab) {
            if (this._selectIndex !== -1) {

this._setText(this._completionListElement.childNodes[this._selectIndex]);
                *ev.stopPropagation();*
*                ev.preventDefault();//MaxZeta 20170920: added to resolve
chrome issue*
            }
        }
        else {
            this._timer.set_enabled(true);
            // start the timer to retrieve results since now it is an
actual key
        }






2017-09-20 13:20 GMT+02:00 Massimo Zambra <massimozambra@gmail.com>:

**Comment by MikhailTymchukDX** [comment]
@MaxZeta I'm happy to hear that you resolved the problem.

I need to reproduce and research it on my side to find its cause.
I have made a sample project based on the code you provided: [AutoComplete.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1318727/AutoComplete.zip)

Please modify it so the issue is reproduced and so I can continue my research.

**Comment by MaxZeta** [comment]
[AutoComplete.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1321227/AutoComplete.zip)

In Autocomplete.Zip:

1) modified Default.aspx for you
2) two images 
2.1) WithError: **Your Default.aspx in Chrome 32bit v60 when I click/Tab on a Autocomplete Item**
(I'm not able to reproduce  twice Text_Changed that is the real problem ) 
2.1) NoError: page with same error until yesterday and now ok with new Toolkit 17.0.2  ( ev.preventdefault added)

Good Work :)
