### ISSUE TITLE
AjaxFileUpload - Files over 20mb

### ISSUE THREAD

**Issue by JayH77** [DevExpress/AjaxControlToolkit#389]
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug

<ajaxToolkit:AjaxFileUpload ID="AjaxFileUpload" runat="server" onuploadcomplete="AjaxFileUpload_UploadComplete" ThrobberID ="myThrobber" MaximumNumberOfFiles="1" AllowedFileTypes="wma,mp3,m4a,wav" ClearFileListAfterUpload="true" OnClientUploadStart="UploadStart" OnClientUploadComplete="UploadComplete" />

### Actual result

In 17.1.1...
```js
<script type="text/javascript">
//<![CDATA[
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.AjaxFileUpload.Control, {"allowedFileTypes":"wma,mp3,m4a,wav","clearFileListAfterUpload":true,"clientStateField":$get("cphPageContent_ModalStudentAudio_AjaxFileUpload_ClientState"),"contextKey":"{DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}","enabled":true,"maximumNumberOfFiles":1,"postBackUrl":"/test/student_audio?id=9290","serverPollingSupport":true,"uploadHandlerPath":"/AjaxFileUploadHandler.axd"}, {"uploadComplete":UploadComplete,"uploadError":UploadError,"uploadStart":UploadStart}, null, $get("cphPageContent_ModalStudentAudio_AjaxFileUpload"));
});
//]]>
</script>
```
* This works with files < 20mb, and fails when over. *

### Expected result

In 16.1.1...
```js
<script type="text/javascript">
//<![CDATA[
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.AjaxFileUpload.Control, {"allowedFileTypes":"wma,mp3,m4a,wav","clearFileListAfterUpload":true,"clientStateField":$get("cphPageContent_ModalStudentAudio_AjaxFileUpload_ClientState"),"contextKey":"{DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}","maximumNumberOfFiles":1,"postBackUrl":"/test/student_audio?id=9287","serverPollingSupport":true}, {"uploadComplete":UploadComplete,"uploadStart":UploadStart}, null, $get("cphPageContent_ModalStudentAudio_AjaxFileUpload"));
});
//]]>
</script>
```
### Browser(s) used

Chrome/Edge

### A site deployment method
- [X ] VS development web-server,
- [X ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @JayH77 
I tried to reproduce this issue with this sample project: 
[AjaxFileUploadLargeFilesTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1360503/AjaxFileUploadLargeFilesTest.zip)

However, I successfully uploaded files which are over 20Mb.

Would you please update this project or provide your own to illustrate described issue?

**Comment by JayH77** [comment]
Hi @MikhailTymchukDX 

I'm away until Monday, so will try to do this then. 

Many thanks

**Comment by JayH77** [comment]
Just had a quick change to test.

Your project won't allow me to upload files 1.4mb and 8.3mb but will allow a 40.2mb.

What do you need?

**Comment by MikhailTymchukDX** [comment]
@JayH77 
Would you please provide files that failed to upload so that I can research them?

**Comment by JayH77** [comment]
Hi,

I can do, but I found an error pattern. It might be unrelated to size (I can't fully test as I'm no a different PC, will confirm Monday) but on this PC I can't upload wma files. Let me know if you need me to send one.

**Comment by MikhailTymchukDX** [comment]
I'm sure this is because the .wma extension is not allowed by default starting with v17.1.1.

Please add the following code line to your Web.config:
```xml
<ajaxControlToolkit additionalUploadFileExtensions="wma" />
```

For a complete list of allowed extensions, please see this article: https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#allowed-file-extensions

I look forward to your response.

**Comment by MikhailTymchukDX** [comment]
I've updated the sample project, so you can upload wma files:  
[AjaxFileUploadLargeFilesTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1362536/AjaxFileUploadLargeFilesTest.zip)

**Comment by JayH77** [comment]
Yes, that's working - thanks.

I'll double-check this resolves my issue on the other computer on Monday.

Thanks

**Comment by MikhailTymchukDX** [comment]
Glad to hear it!
I consider the problem solved, so I'm closing this issue.
If it's not, feel free to comment so I can reopen it and we can continue our research.
