### ISSUE TITLE
Is combobox removed from AjaxControlToolkit 17.1.1?

### ISSUE THREAD

**Issue by hayhua** [DevExpress/AjaxControlToolkit#390]
### The installation method
- [ X] NuGet package

### Minimal steps to reproduce the bug
 1. installed AjaxControlToolkit 17.1.1, 
 2. follow install doc steps adding to aspx page: <%@ Register Assembly="AjaxControlToolkit"
 3. Namespace="AjaxControlToolkit" TagPrefix="AjaxControl" %>
 4. added a ComboBox control on Default.aspx page, which VisualStudio 2015 generated this line in Default.aspx.designer.cs:
        protected global::AjaxControlToolkit.ComboBox Build;
 5. Build. got error below
   'ComboBox' does not exist in the namespace 'AjaxControlToolkit'
 6. Open "Object Browser" in VisualStudio2015, check AjaxControlToolkit does not has ComboBox

### Actual result
Build fail
### Expected result
Build pass
### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by AlekseyMartynov** [comment]
No, we did not remove ComboBox or any other control from the Toolkit.

I can see the `ComboBox` class in Object Browser of VS 2015 right after installing the [AjaxControlToolkit package](https://www.nuget.org/packages/AjaxControlToolkit/17.1.1).

![123](https://user-images.githubusercontent.com/4426185/31542703-ce30e3a4-b01b-11e7-83f1-98f73277bd76.png)

We need more information from you. A sample project, a video or any additional details are appreciated.

**Comment by hayhua** [comment]
Hi Alek, thank you for the confirmation of the package. I found that the error was occurred during copying reference in build and publish process, the cause probably in the build scripts. I will investigate further.

**Comment by hayhua** [comment]
I finally figured out the issue was reference path in the project file. The reference build error is gone after correcting the path.

**Comment by MikhailTymchukDX** [comment]
@hayhua Glad to hear it!
I consider this issue resolved, so I'm closing it.
