### ISSUE TITLE
Vulnerabilities - Ajaxcontroltoolkit.dll 17.1.1

### ISSUE THREAD

**Issue by satheeshn1** [DevExpress/AjaxControlToolkit#391]
### The installation method
- [ ] NuGet package

Hi Team,

I ran a vulnerability scan on AjaxControlToolkit.dll which is referenced in one of my ASP.net application. Below are the five vulnerabilities identified in the scan.

1) improper neutralization of script-related html tags in a web page (basic xss) (cwe id 80) - Method: void OnPreRender(System.EventArgs)
2) use of a broken or risky cryptographic algorithm (cwe id 327) - Method: string GetHash(string)
3) External Control of Filename or Path (CWE ID 73) - Method: bool ProcessStream(System.web.HttpContext, System.IO.Stream, string, string, bool, bool, bool) - 2 issues
4) External Control of Filename or Path (CWE ID 73) - Method: void CreateTempFilePathFolder(string)

The category of above issues are Medium. Could you please suggest me the fix for these vulnerabilities?.

Thanks,

**Comment by AlekseyMartynov** [comment]
- Item 2 is about the [Gravatar](https://github.com/DevExpress/AjaxControlToolkit/blob/76b8ebbeb6c3d08e17444e07798c38ff42ab579a/AjaxControlToolkit/Gravatar/Gravatar.cs#L128-L140) control.

  MD5 hashing of *emails* is how [Gravatar works](https://en.gravatar.com/site/implement/hash/). Check the discussion at https://meta.stackexchange.com/q/21117. 

- Items 3 & 4 are about AjaxFileUpload.

  This control has been recently audited and hardened in 17.1.1. See issue #336 and [ASP.NET AJAX Control Toolkit - v17.1.1 - Security Improved and Issues Fixed](https://community.devexpress.com/blogs/aspnet/archive/2017/05/26/asp-net-ajax-control-toolkit-v17-1-1-security-improved-and-issues-fixed.aspx).

  There are no known unresolved security issues with AjaxFileUpload. Filesystem-related routines do comprehensive validation and are [protected using a white list](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#allowed-file-extensions).

- Regarding the Item 1, would you please specify the class name so we can double check?
Also, what is the tool used for the scan?

**Comment by satheeshn1** [comment]
Hi AlekseyMartynov,

Thank you for your response.

I using AjaxControlToolkit 17.1.1 version added in application via Nuget. 

I have attached vulnerabilities which I got in Veracode scanning. could you please suggest on this?.

Thanks,
[Veracode-Ajaxcontroltoolkit.docx](https://github.com/DevExpress/AjaxControlToolkit/files/1398260/Veracode-Ajaxcontroltoolkit.docx)

**Comment by MikhailTymchukDX** [comment]
Hi @satheeshn1 

Thank you for providing this information!

We are analyzing it, here are the immediate results:

* `GenerateFakeData()` for a Twitter control generates test data set, so we see no problem here.  
Also, `Query()` method sends data over HTTPS protocol, so we see no vulnerability here too.

* The path passed to `SaveAs()` method that belongs to AjaxFileUpload control should be controlled by the user code, because the method does not make any assumptions and perform any checks.

* We found the code in `OnPreRender()` method that seems to have problems. It is located in deprecated `HtmlEditor` control.  
We strongly recommend using the modern `HtmlEditorExtender` instead. Please see #70 for more info.

**Comment by cwrightc84** [comment]
AJAX Toolkit Team,

I am a Security Consultant that has a development team that is interesting using AJAX Toolkit to support their development process.  As part of our due diligence and due care, we have conducted a static code analysis on the base AJAX Toolkit 17.1.1 code using our Checkmarx Scanner.

We do not currently have the resources to validate the above code but have concerns over the 11 high findings that were detected by the scanner.  We figured this information would be useful to the AJAX team for improving the code.

Please let us know if there is any information available that can help us validate these HIGH findings as possible false positives or if they are real vulnerabilities that have planned fixes.

I apologize before hand for the format, these findings needed to be pulled from the report manually for sanitization purposes:

Here are the details:

**CLIENT DOM XSS\PATH 1:**
Method Sys$_Application$get_stateString at line 5484 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js gets user input for the href element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user in Sys$_Application$_setState at line 5765 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js.This may enable a DOM XSS attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.debug.js
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.debug.js
Line 5490 5782
Object href write
Code Snippet
File Name /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js
Method Sys._Application.prototype.get_stateString = function
Sys$_Application$get_stateString() {
....
5490. var href = window.location.href;
File Name /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js
Method Sys._Application.prototype._setState = function
Sys$_Application$_setState(entry, title) {

**CLIENT DOM XSS\Path 2:**
Method Sys$_Application$get_stateString at line 5484 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js gets user input for the hash element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user in Sys$_Application$_setState at line 5765 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js.This may enable a DOM XSS attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.debug.js
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.debug.js
Line 5501 5782
Object hash write
Code Snippet
File Name /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js
Method Sys._Application.prototype.get_stateString = function
Sys$_Application$get_stateString() {
....
5501. hash = window.location.hash;
File Name /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.debug.js
Method Sys._Application.prototype._setState = function
Sys$_Application$_setState(entry, title) {
....
5782. frameDoc.write("<html><head><title>" +
htmlEncodedTitle +

**CLIENT DOM XSS\PATH 3:**
Method Sys$_Application$get_stateString at line 5484 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js gets user input for the href element. This
element’s value then flows through client-side code without being properly sanitized or validated and is
eventually displayed to the user in Sys$_Application$_setState at line 5765 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js.This may enable a DOM XSS attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.js
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.js
Line 5490 5782
Object href write
Code Snippet
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js
Method Sys._Application.prototype.get_stateString = function
Sys$_Application$get_stateString() {
....
5490. var href = window.location.href;
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js
Method Sys._Application.prototype._setState = function
Sys$_Application$_setState(entry, title) {
....
5782. frameDoc.write("<html><head><title>" +
htmlEncodedTitle +

**CLIENT DOM XSS\Path 4:**
Method Sys$_Application$get_stateString at line 5484 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js gets user input for the hash element. This
element’s value then flows through client-side code without being properly sanitized or validated and is
eventually displayed to the user in Sys$_Application$_setState at line 5765 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js.This may enable a DOM XSS attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.js
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Script
s/MicrosoftAjax.js
Line 5501 5782
Object hash write
Code Snippet
PAGE 11 OF 174
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js
Method Sys._Application.prototype.get_stateString = function
Sys$_Application$get_stateString() {
....
5501. hash = window.location.hash;
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit.Jasmine/Scripts/MicrosoftAjax.js
Method Sys._Application.prototype._setState = function
Sys$_Application$_setState(entry, title) {
....
5782. frameDoc.write("<html><head><title>" +
htmlEncodedTitle +

**CLIENT DOM XSS\Path 5:**
Method function at line 161 of /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Scripts/DropShadow.js getsuser input for the x element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user in function at line 61 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Scripts/DropShadow.js.This may enable a DOM XSS attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Scripts/DropS
hadow.js
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Scripts/DropS
hadow.js
Line 182 82
Object x appendChild
Code Snippet
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Scripts/DropShadow.js
Method setShadow: function(force, norecurse) {
....
182. this._lastX = location.x;
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Scripts/DropShadow.js
Method buildShadowDiv: function() {
....
82. e.parentNode.appendChild(div);

**Client DOM XSS\Path 6:**
Method function at line 161 of /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Scripts/DropShadow.js gets user input for the y element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user in function at line 61 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Scripts/DropShadow.js.This may enable a DOM XSS attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Scripts/DropS
hadow.js
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Scripts/DropS
hadow.js
Line 183 82
Object y appendChild
Code Snippet
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Scripts/DropShadow.js
Method setShadow: function(force, norecurse) {
....
183. this._lastY = location.y;
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Scripts/DropShadow.js
Method buildShadowDiv: function() {
....
82. e.parentNode.appendChild(div);
Reflected XSS All Clients
Query Path:
CSharp\Cx\CSharp High Risk\Reflected XSS All Clients Version:0
Categories
PCI DSS v3.1: PCI DSS (3.1) - 6.5.7 - Cross-site scripting (XSS)
OWASP Top 10 2013: A3-Cross-Site Scripting (XSS)
STIG: APP3580: CAT I The Designer will ensure the application does not have XSS
vulnerabilities

**Reflect XSS All Client\Path 1:**
Method ComboBox1_ItemInserted at line 98 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.SampleSite/ComboBox/ComboBox.aspx.cs gets user input for the Text element.
This element’s value then flows through the code without being properly sanitized or validated and is
eventually displayed to the user in method ComboBox1_ItemInserted at line 98 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.SampleSite/ComboBox/ComboBox.aspx.cs. This may enable a Cross-Site-
Scripting attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.SampleSite/Co
mboBox/ComboBox.aspx.cs
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit.SampleSite/Co
mboBox/ComboBox.aspx.cs
Line 100 100
Object Text Text
Code Snippet
File Name /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.SampleSite/ComboBox/ComboBox.aspx.cs
Method protected void ComboBox1_ItemInserted(object sender,
AjaxControlToolkit.ComboBoxItemInsertEventArgs e) {
....
100. FeedbackItemInsertedLabel.Text =
String.Format(FeedbackItemInsertedLabel.

**Reflect XSS All Client\Path 2:**
Method <%@ Page Title="" Language="C#" MasterPageFile="~ /Suites/Suite.Master"
AutoEventWireup="true" CodeBehind="NumericUpDownTests.aspx.cs"
Inherits="AjaxControlToolkit.Jasmine.Suites.NumericUpDownTests" %> at line 1 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Suites/NumericUpDownTests.aspx gets user input for the Text element.
This element’s value then flows through the code without being properly sanitized or validated and is
eventually displayed to the user in method <%@ Page Title="" Language="C#"
MasterPageFile="~ /Suites/Suite.Master" AutoEventWireup="true"
CodeBehind="NumericUpDownTests.aspx.cs"
Inherits="AjaxControlToolkit.Jasmine.Suites.NumericUpDownTests" %> at line 1 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Suites/NumericUpDownTests.aspx. This may enable a Cross-Site-
Scripting attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Suite
s/NumericUpDownTests.aspx
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Suite
s/NumericUpDownTests.aspx
Line 28 28
Object Text Write
Code Snippet
File Name /AjaxControlToolkit-
17.1.1/AjaxControlToolkit.Jasmine/Suites/NumericUpDownTests.aspx
PAGE 14 OF 174
Method <%@ Page Title="" Language="C#" MasterPageFile="~/Suites/Suite.Master"
AutoEventWireup="true" CodeBehind="NumericUpDownTests.aspx.cs"
Inherits="AjaxControlToolkit.Jasmine.Suites.NumericUpDownTests" %>
....
28. var TEXT_BOX_INITIAL_VALUE = "<%= TestTextBox.Text %>";

**Reflect XSS All Client\Path 3:**
Method ParseRequest at line 579 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs gets user input for the QueryString_guid
element. This element’s value then flows through the code without being properly sanitized or validated and is eventually displayed to the user in method XhrDone at line 636 of /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs. This may enable a Cross-Site-Scripting attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/AjaxFileUpload
/AjaxFileUpload.cs
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit/AjaxFileUpload
/AjaxFileUpload.cs
Line 580 659
Object QueryString_guid Write
Code Snippet
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs
Method XhrType ParseRequest(out string fileId) {
....
580. fileId = Request.QueryString["guid"];
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs
Method void XhrDone(string fileId) {
....
659. Response.Write(new
JavaScriptSerializer().Serialize(args));

**Reflect XSS All Client\Path 4:**
Method { at line 39 of /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Tabs/TabPanel.cs gets user input forthe ViewState_HeaderText element. This element’s value then flows through the code without being properlyPAGE 15 OF 174 sanitized or validated and is eventually displayed to the user in method RenderHeader at line 251 of
/AjaxControlToolkit-17.1.1/AjaxControlToolkit/Tabs/TabPanel.cs. This may enable a Cross-Site-Scripting
attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Tabs/TabPanel
.cs
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit/Tabs/TabPanel
.cs
Line 40 278
Object ViewState_HeaderText Write
Code Snippet
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Tabs/TabPanel.cs
Method public string HeaderText {
....
40. get { return (string)(ViewState["HeaderText"] ??
string.Empty); }
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/Tabs/TabPanel.cs
Method protected internal virtual void RenderHeader(HtmlTextWriter writer) {
....
278. writer.Write(HeaderText);

**Reflect XSS All Client\Path 5:**
Method { at line 532 of /AjaxControlToolkit-17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs
gets user input for the Request element. This element’s value then flows through the code without being
properly sanitized or validated and is eventually displayed to the user in method XhrDone at line 636 of
/AjaxControlToolkit-17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs. This may enable a Cross-
Site-Scripting attack.
Source Destination
File /AjaxControlToolkit-
17.1.1/AjaxControlToolkit/AjaxFileUpload
/AjaxFileUpload.cs
/AjaxControlToolkit-
17.1.1/AjaxControlToolkit/AjaxFileUpload
/AjaxFileUpload.cs
Line 533 659
Object Request Write
Code Snippet
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs
Method HttpRequest Request {
PAGE 16 OF 174
....
533. get { return Control.Context.Request; }
File Name /AjaxControlToolkit-17.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs
Method void XhrDone(string fileId) {
....
659. Response.Write(new
JavaScriptSerializer().Serialize(args));

V/R,

-Chris W. (christopher.wright@asmr.com)

**Comment by mikeroracle** [comment]
@cwrightc84, I am an Architect at Oracle and we are looking to upgrading to this version of the library. Are you able to share your report?

**Comment by MikhailTymchukDX** [comment]
@satheeshn1 @cwrightc84 @mikeroracle 

Thank you for sharing this valuable info!
We edited the original issue post and removed other comments.
 
Please send any info about security vulnerabilities to info@devexpress.com (we added this note to [CONTRIBUTING.MD](https://github.com/DevExpress/AjaxControlToolkit/blob/master/CONTRIBUTING.MD))
 
We processed your reports and fixed those parts that were related to the toolkit code itself (not the base Microsoft AJAX Framework or test code or design-time code).
They will be included into the upcoming release.
 
Here are pull requests for these fixes:
https://github.com/DevExpress/AjaxControlToolkit/pull/397 
https://github.com/DevExpress/AjaxControlToolkit/pull/395
