### ISSUE TITLE
Adding AjaxControlToolKit getting error

### ISSUE THREAD

**Issue by hayhua** [DevExpress/AjaxControlToolkit#392]
### The installation method
- [ ] Installer
- [ X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
1. add AjaxToolkit as install doc, add to web.config (same result as adding it to aspx page)
```
  <add assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagPrefix="AjaxControl"/>
```
2. run the web page

### Actual result

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
[HttpException (0x80004005): The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).]
   System.Web.UI.ControlCollection.Add(Control child) +11843103
   AjaxControlToolkit.ToolkitResourceManager.RegisterCssReferences(Control control) +624
   System.Web.UI.Control.LoadRecursive() +68
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3811

### Expected result
no error
### Browser(s) used
chrome
### A site deployment method
- [X ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @hayhua 

I could not reproduce this issue:
* I created ASP.NET Web application for .NET Framework 4.5.2
* Installed AjaxControlToolkit v17.1.1 NuGet package
* Added `AsyncFileUpload` to the Default.aspx page.
* Ran the application.

Here is the sample project that was made as a result: 
[AjaxControlToolkitTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1399854/AjaxControlToolkitTest.zip)

Would you please modify it or provide your own so that the issue is reproduced and we can continue our research?

**Comment by hayhua** [comment]
I am using control ComboBox, not the control AsyncFileUpload in the sample project. Maybe that is different?

**Comment by hayhua** [comment]
Analizing the error and source code, i think the error is in code:
AjaxControlToolkit/ComboBox/ComboBox.cs
line 417: ToolkitResourceManager.RegisterCssReferences(this);

AjaxControlToolkit/ToolkitResourceManager.cs
line 199:         public static void RegisterCssReferences(Control control) {
line 203:              // Add the link to the page header instead of inside the body which is not xhtml compliant

which looks like the error mentioned in in link:
https://stackoverflow.com/questions/4995274/the-controls-collection-cannot-be-modified-because-the-control-contains-code-blo
adding code block to page.header causing such problem

**Comment by MikhailTymchukDX** [comment]
Hi @hayhua 
Would you please provide us with a complete sample project so that we can investigate the code which you put into the header?

**Comment by MikhailTymchukDX** [comment]
We were expecting an answer from you, however we didn't receive one in the last 14 days.
We'll assume that the problem is resolved and automatically close the ticket.
If it hasn't, please do not hesitate to comment on this issue.
