### ISSUE TITLE
AjaxFileUpload OnUploadCompleteAll Event Issue

### ISSUE THREAD

**Issue by damianwhoffmann** [DevExpress/AjaxControlToolkit#398]
Response.Redirect() does not work in OnUploadCompleteAll event
The event is fired but you do not get redirected as expected
### The installation method
- [ X ] NuGet package

### Actual result
Control updates to inform the upload has been completed

### Expected result
Expected to redirect to the required page

### Browser(s) used
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### A site deployment method
- [ X ] IIS

.aspx
```html
<div>
   <ajaxToolkit:AjaxFileUpload ID="AjaxFileUpload1" 
                        runat="server" 
                        ClearFileListAfterUpload="true" 
                        MaximumNumberOfFiles="10"
                        AllowedFileTypes="bmp,png,jpeg,jpg"
                        OnUploadComplete="AjaxFileUpload1_UploadComplete"
                        OnUploadCompleteAll="AjaxFileUpload1_UploadCompleteAll"
                    />
</div>
```
.aspx.cs
```C#
protected void AjaxFileUpload1_UploadComplete(object sender, AjaxFileUploadEventArgs e)
{
      Stream imgStream = e.GetStreamContents();
      if (imgStream != null)
      {
            ImageHelper.Saving(imgStream, ItemID);
            imgStream.Dispose();
      }
}

protected void AjaxFileUpload1_UploadCompleteAll(object sender, AjaxFileUploadCompleteAllEventArgs e)
{
      Response.Redirect("/Gallery.aspx?ItemID=" + ItemID);
}
```

**Comment by MikhailTymchukDX** [comment]
Hi @damianwhoffmann 

This server-side event is triggered via an [AJAX call](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/AjaxFileUpload.js#L1282-L1301).
This means that the page you see in the browser will not be updated. If you redirect the page on the server side, it just breaks the response for the client side.

Instead, please use the client event [uploadCompleteAll](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload#uploadcompleteall) and redirect the page in a browser by changing the current page URL:
```aspx
<ajaxToolkit:AjaxFileUpload
    runat="server"
    OnClientUploadCompleteAll="onClientUploadCompleteAll" />
```
```js
function onClientUploadCompleteAll(sender, e) {
    var args = JSON.parse(e.get_serverArguments())
    window.location.href = "../Gallery.aspx?ItemID=" + args.ItemID;
}
```
