### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by maabd** [DevExpress/AjaxControlToolkit#40]
When use version 16.1, the tab header gone to the left and the panels in the right, I used the example came with the installation.

However this problem was not in the previous version

I used VS 2015 and VS 2010 
![ajax_tabs](https://cloud.githubusercontent.com/assets/5729147/14076076/35b57cfc-f4e7-11e5-8e36-8ef47d7a8b7a.png)

**Comment by MikhailTymchukDX** [comment]
Please see this workaround: https://github.com/DevExpress/AjaxControlToolkit/issues/5#issuecomment-196755356

**Comment by maabd** [comment]
Thanks for your replay.

I used the sample you attached in #5 and did not work as attached snapshots

I did some changes to default page to show you the error
pls advice

![ajax_tabs2](https://cloud.githubusercontent.com/assets/5729147/14076752/70d843ea-f4ed-11e5-9ade-89f39a9859d7.png)
[Default.zip](https://github.com/DevExpress/AjaxControlToolkit/files/191693/Default.zip)

**Comment by MikhailTymchukDX** [comment]
My page looks different than yours: 
![image](https://cloud.githubusercontent.com/assets/17080984/14077208/ff65ec9e-f4f1-11e5-98aa-69932f68db7d.png)

Would you please attach a complete project so that I can research it?

**Comment by maabd** [comment]
pls find the full project
on addition I would like to mention that I'm using windows 10, VS 2010 and VS2015
Pls note that the same for the sample application coming with the project
[TabsTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/192925/TabsTest.zip)

**Comment by MikhailTymchukDX** [comment]
Unfortunately, I cannot yet reproduce this issue even with the sample project you provided.
Would you please specify the version of the browser you are using?

**Comment by maabd** [comment]
![ajax_ie_ver](https://cloud.githubusercontent.com/assets/5729147/14102698/d5ca3e54-f5a4-11e5-99fe-84d51878141c.png)

**Comment by MikhailTymchukDX** [comment]
Here is a newer IE version. Yet, I don't think it can be the cause of this issue:
![image](https://cloud.githubusercontent.com/assets/17080984/14102873/d4e2a854-f5a5-11e5-9a68-ea7eb23e9118.png)

Would you please copy here the full source code of the rendered page (right mouse click - View source)?

**Comment by maabd** [comment]
[SourceCode.txt](https://github.com/DevExpress/AjaxControlToolkit/files/193195/SourceCode.txt)

**Comment by MikhailTymchukDX** [comment]
I see no relevant differences in a page's DOM-model.

Would you please check the Document mode at Developer tools Emulation tab (F12)?
It seems your browser is switching to the Internet Explorer 7 document model:
![image](https://cloud.githubusercontent.com/assets/17080984/14104607/bc1e600c-f5ae-11e5-8662-e80a2490838b.png)

**Comment by maabd** [comment]
yes it's work , as you mentioned IE running in compatible mode which is IE 7

but you can see from the snapshots that the sample application is working fine ( I did not add the style to the page), however your sample application need the style sheet to work
on addition my application did not work with or without the style sheet as you can see from the snapshot 

pls advice
![sample](https://cloud.githubusercontent.com/assets/5729147/14105867/dd80c674-f5b6-11e5-8113-3581841f473e.png)
[MyApp_Source.txt](https://github.com/DevExpress/AjaxControlToolkit/files/193297/MyApp_Source.txt)
![myapp](https://cloud.githubusercontent.com/assets/5729147/14105866/dd7fb00e-f5b6-11e5-936d-fea6d836ac96.png)

**Comment by MikhailTymchukDX** [comment]
The sample page on Sample Site works fine, because it does not define `CssClass` for TabContainer.
The sample application in issue #5 defines this attribute, so Tabs content shifts to the right side and we need a workaround.

I don't see where you apply the CSS `tabs` class in the latest [MyApp_Source.txt](https://github.com/DevExpress/AjaxControlToolkit/files/193297/MyApp_Source.txt) file you provided. 
Would you please provide the source code of your .aspx page copied from the IDE as you did it for the [Default.zip](https://github.com/DevExpress/AjaxControlToolkit/files/191693/Default.zip) file?

**Comment by maabd** [comment]
[Search.zip](https://github.com/DevExpress/AjaxControlToolkit/files/194928/Search.zip)

AS far as I see I'm not using any CSS to the tab container, but the page show as previous snapshot

I included the output also

**Comment by MikhailTymchukDX** [comment]
Thank you for posting this sample.

The TabContainer has the `CssClass` property set to "tabcc".
This means you need the following CSS style declaration to workaround the issue:
```css
.tabcc .ajax__tab_header:after {
    clear: both;
}

.tabcc .ajax__tab_header:before, .tabcc .ajax__tab_header:after {
    content: "";
    display: table;
}
```
Please let me know if this helped you.

**Comment by maabd** [comment]
Thanks for your support, this solve the problem I just remove the CssClass.
Last question , how I can put the tab header on top-right position, the attached snapshot come from the old version of the application using  old version from AJAXToolkit , when I upgraded the ajaxtools on the same application the tabs came on left side
If any update for AjaxToolKit , can we know the schedule
![right-to-left](https://cloud.githubusercontent.com/assets/5729147/14141262/c5e5df60-f686-11e5-9815-553e0fd129cf.png)

**Comment by MikhailTymchukDX** [comment]
Please try specifying `TabStripPlacement="TopRight"`.

**Comment by maabd** [comment]
NO, did not work

**Comment by MikhailTymchukDX** [comment]
I see, please add this code to your page to move TabPanel headers to the right:
```aspx
<style>
	.ajax__tab_default .ajax__tab {
		float: right;
	}
</style>
```
Hope this helps.

**Comment by maabd** [comment]
yes , it's work fine

thanks for your support
