### ISSUE TITLE
Combobox dropdownlist positioning error

### ISSUE THREAD

**Issue by MichaelGoyette1** [DevExpress/AjaxControlToolkit#400]
17.1 The AJAX Control Toolkit \<VERSION\>

### The installation method
- [ ] Installer

### Minimal steps to reproduce the bug
css:

position:: absolute;
left: 100px;
top: 100px;

### Actual result
position of Combobox correct - position of dropdown list off by 100px left - 100px top

### Expected result

dropdownlist with combobox

### Browser(s) used
edge, i.e. 
### A site deployment method
- [ ] VS development web-server,

Have seen this problem mentioned many times for past 7-8 years - looking for solution

Thanks - Michael

**Comment by MichaelGoyette1** [comment]
Hi Mikhail,

This reproduces the problem exactly.
I used the code from your first example.
Notice where the dropdown list shows up when you run it.

<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="ComboxBoxTester.aspx.vb" Inherits="PapaGodSystems.ComboxBoxTester" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<!DOCTYPE html>

<link href="Css/ComboBoxTester.css" rel="stylesheet" type="text/css" />
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Combobox Tester</title>
</head>
<body>
    <form id="form1" runat="server">
           
       <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <ajaxToolkit:ComboBox ID="ComboBox1" runat="server" DropDownStyle="DropDownList" AutoCompleteMode="SuggestAppend" CssClass="combo">
            <asp:ListItem Text="Mild" Value="0" /> 
            <asp:ListItem Text="Medium" Value="1" /> 
            <asp:ListItem Text="Spicy" Value="2" /> 
        </ajaxToolkit:ComboBox>

        <style>
            .combo{
                position: absolute;
                left: 100px;
                top: 100px;
            }
        </style>

    </form>
</body>
</html>

Thanks,

Michael

**Comment by MichaelGoyette1** [comment]
Hi Mikhail - Thank You - So this is a real issue - looks like it has been for a long time - I see stuff dating back to 2011 with same problem.  Do I understand this to mean you are hoping to correct this in the 17.1.2 release of the Ajax Control Toolkit? - Michael

**Comment by MikhailTymchukDX** [comment]
@MichaelGoyette1 Yes, labeling an issue with the 17.1.2 milestone means that this change will be included in the v17.1.2 release.

**Comment by MichaelGoyette1** [comment]
Thank You Mikhail - I like the control because it is easy to use straight up - with the list positioning corrected - it will be great - Michael

________________________________
