### ISSUE TITLE
AJAX File Upload Control - error upload RTF files

### ISSUE THREAD

**Issue by mandolfo** [DevExpress/AjaxControlToolkit#403]
### The installation method
- [x] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug

we tried to upload an RTF file using AjaxControlToolkit using  File Upload Control. But  the control failed 
with the error in the image 

![erroreupload](https://user-images.githubusercontent.com/33620799/34410896-8f9dc280-ebd3-11e7-88d2-bd6f8623bebf.jpg)

we tried with different RTF files but the control always failed. 

![erroreupload](https://user-images.githubusercontent.com/33620799/34410964-f6957500-ebd3-11e7-8402-f320c2c0c34f.jpg)

Upload Control can upload RTF files?

### Browser(s) used

Google Chrome, Firefox,Edge

### A site deployment method
- [] VS development web-server,
- [x] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @mandolfo 

To fix this error, please add the `additionalUploadFileExtensions` attribute to the `ajaxControlToolkit` section in your Web.config:
```xml
<configSections>
    <section name="ajaxControlToolkit" type="AjaxControlToolkit.AjaxControlToolkitConfigSection, AjaxControlToolkit" requirePermission="false"/>
</configSections>
<ajaxControlToolkit additionalUploadFileExtensions="rtf" />
```

More info can be found in our wiki article: https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#allowed-file-extensions
