### ISSUE TITLE
Numeric MaskedEditExtender issue onfocus

### ISSUE THREAD

**Issue by gabryk91** [DevExpress/AjaxControlToolkit#406]
Version 18

### The installation method
NuGet package

### Minimal steps to reproduce the bug
```
<asp:textbox runat="server" maxlength="10" id="txtBadge" name="txtBadge" placeholder="Codice badge" required="required"></asp:textbox>
<asp:MaskedEditExtender runat="server" TargetControlID="txtBadge" Mask="9999999999" MaskType="Number" PromptCharacter="" />
```
Write a number in the txtBadge textbox, like 1234567890.
Click on the textbox (focus)

### Actual result
Visible text became 12345

### Expected result
Visible text should be the same entered 1234567890
### Browser(s) used
Chrome
### A site deployment method
VS development web-server,

[Question on StackOverflow with picture](https://stackoverflow.com/questions/48425665/numeric-maskededitextender-issue-onfocus)

**Comment by MikhailTymchukDX** [comment]
Hi @gabryk91 
Your setup is quite uncommon for MaskedEdit. Setting `PromptCharacter` to an empty value breaks the extender's logic.

Would it be better to use the [`FilteredTextBox` extender](https://ajaxcontroltoolkit.devexpress.com/FilteredTextBox/FilteredTextBox.aspx), which is set up in the following way?
```aspx
<asp:TextBox
	runat="server"
	ID="TextBox1"
	MaxLength="10" />
<ajaxToolkit:FilteredTextBoxExtender
	runat="server"
	TargetControlID="TextBox1"
	FilterType="Numbers" />
```

**Comment by gabryk91** [comment]
You are absolutely right @MikhailTymchukDX , I didn't know of FilteredTextBox, thank you!

**Comment by MikhailTymchukDX** [comment]
@gabryk91 Glad to hear it!
I consider this issue resolved, so I'm closing it.
