### ISSUE TITLE
ScriptResource.axd 0x800a139e - JavaScript runtime error: SyntaxError

### ISSUE THREAD

**Issue by citybear01** [DevExpress/AjaxControlToolkit#407]
### The installation method
- [ ] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
This will be difficult as it happens when I try and use DEBUG while inside of VS 2015 and am using IE 11 and the ASP.NET is using V4.5.1 Framework.
### Actual result
I am getting the following error:

Exception was thrown at line 3568, column 4 in http://localhost:58648/ScriptResource.axd?d=mi2OcNv48xWANXsxQ04XhmPxMiAIoslLjMkConhj_s5hINsmMPafNowrPGrNsZjOtckRP4JEqBJFDB35ZAPSR15GRSbRbgoaB7O6Y-RRWaV8_X9nlO-1E-Qmelo25Ffn0&t=51e37521

0x800a139e - JavaScript runtime error: SyntaxError
### Browser(s) used
IE11
### A site deployment method
- [X] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @citybear01,
Would you please provide us with more information about your code?
A sample project would be of a great help for us as well.

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.
