### ISSUE TITLE
AjaxControlToolkit upgraded to 18.1-Assembly 'myAssembly, Version=12.9.0.0, Culture=neutral, PublicKeyToken=null' does not contain a Web resource with name 'myScript.js.js'.

### ISSUE THREAD

**Issue by mounikapk** [DevExpress/AjaxControlToolkit#409]
The AJAX Control Toolkit 18.1

The installation method
Installer
NuGet package

Not a bug. This is more of a support on which I couldn't find any info.
I have upgraded AjaxControlToolkit from 4.0 to 18.1 . Running the application gives me below error-
AjaxControlToolkit upgraded to 18.1-Assembly 'myAssembly, Version=12.9.0.0, Culture=neutral, PublicKeyToken=null' does not contain a Web resource with name 'myScript.js.js'. 

### Browser(s) used
Any browser

### A site deployment method
VS 2017 IISExpress

Thanks,

**Comment by mounikapk** [comment]
My question is around- Why is the .js getting appending to myScript.js file (see error)

**Comment by MikhailTymchukDX** [comment]
I suppose you have custom controls that are derived from the `ExtenderControlBase` class.

Please refer to the [`Creating a Custom Control`](https://github.com/DevExpress/AjaxControlToolkit/wiki/Creating-a-Custom-Control#add-the-clientscriptresource-attribute)guide, where you will see that the AJAX Control Toolkit appends either .js or .min.js to the script name, so you don't need to specify a suffix.

**Comment by mounikapk** [comment]
Thanks for the response.
I have a follow-up question-
With Ajax18.1 we are no more using ToolkitScriptManager, instead asp:ScriptManager. So i updated the same in my aspx files. but my web.config has ajaxToolkit tagprefix. So which tagprefix i should be using- asp: or ajaxToolkit: ?

**Comment by MikhailTymchukDX** [comment]
You need to use the `ajaxToolkit:` prefix if you declare it in Web.config in [the following way](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.SampleSite/Web.config#L35);
```xml
<configuration>
  <system.web>
    <pages>
      <controls>
        <add assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagPrefix="ajaxToolkit"/>
      </controls>
    </pages>
  </system.web>
</configuration>

```

**Comment by mounikapk** [comment]
Yes, I got the above in web.config when i installed NuGet package ACT18.1, my question is when i have to register, what should i use. Currently, we are using this below in my pages individually-

`<%@ Register TagPrefix="actk" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit"%>
...
...
    <asp:ScriptManager ID="MasterPageScriptManager" runat="server" EnablePageMethods="true" OnAsyncPostBackError="ScriptMgrAsyncError" >
        <Scripts>
        <asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />
    </Scripts>

    </asp:ScriptManager>` 

is this usage correct?

**Comment by mounikapk** [comment]
reposting the .aspx markup-
`<%@ Register TagPrefix="actk" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit"%>
`...`
`...`
`<asp:ScriptManager ID="MasterPageScriptManager" runat="server" EnablePageMethods="true" `
`OnAsyncPostBackError="ScriptMgrAsyncError" >`
`<asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />`
`</asp:ScriptManager>` `

**Comment by mounikapk** [comment]
Reposting the Register in .aspx -

`<%@ Register TagPrefix="actk" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit"%>
...
...
<asp:ScriptManager ID="MasterPageScriptManager" runat="server" EnablePageMethods="true" OnAsyncPostBackError="ScriptMgrAsyncError" >

<asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />
</asp:ScriptManager>`

**Comment by MikhailTymchukDX** [comment]
Yes, you need to use the `asp:` prefix for a ScriptManager, because it is a part of ASP.NET. not the AJAX Control Toolkit.

**Comment by programmingbagger** [comment]
Just put this and you will get the post back event fire automatically.


<asp:ScriptManager ID="MasterPageScriptManager" runat="server" EnablePageMethods="true">
            <Scripts>
                <asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />
            </Scripts>
        </asp:ScriptManager>

**Comment by programmingbagger** [comment]
![Untitled](https://user-images.githubusercontent.com/33624662/83340437-93e27300-a2f5-11ea-894b-07d086ea7a04.png)
