### ISSUE TITLE
HTMLExtender. Allow Tabindex=-1 in button from toolbar

### ISSUE THREAD

**Issue by mixfede** [DevExpress/AjaxControlToolkit#412]
### The installation method
- [X ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug

- Create Textbox1 and create textbox2, 
- In textbox2 add extension htmlextender
- Run

### Actual result
and when tab from textbox1.text from textbox2.text,, the tabulation pass for all buttons in toolbar, 
### Expected result
Tab only in buttons from toolbar selected

### Browser(s) used
firefox 58

### A site deployment method
- [ ] VS development web-server,
- [X ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @mixfede
The behavior you described is expected, because toolbar buttons are rendered as an `input` element with type='button'.

Would you please clarify what you want to achieve with this restriction and how users would tab out of the extender?

**Comment by mixfede** [comment]
the point is that to get to the control (Textbox with extend) to get there quickly you have to do it with a click on the control.
Otherwise, imagine a form to send mail, in which with the TAB key we change the field, then, the behavior is to move from the field to + TAB, Subject + TAB, Then for the message you have to type as many TABs as buttons in control would have been defined .. Then the objective is to be able to define for each button if you want to stop (focus on the control) or not
Thank you very much for the question, I hope to be clear, I use google translator.
regards

________________________________
De: MikhailTymchukDX <notifications@github.com>
Enviado: lunes, 12 de febrero de 2018 01:45 p.m.
Para: DevExpress/AjaxControlToolkit
Cc: mixfede; Mention
Asunto: Re: [DevExpress/AjaxControlToolkit] HTMLExtender. Allow Tabindex=-1 in button from toolbar (#412)


Hi @mixfede<https://github.com/mixfede>
The behavior you described is expected, because toolbar buttons are rendered as an input element with type='button'.

Would you please clarify what you want to achieve with this restriction and how users would tab out of the extender?

**Comment by MikhailTymchukDX** [comment]
@mixfede 
You can easily achieve this result by modifying the `tabindex` attribute of HtmlEditorExtender elements directly.
Here is an example where [jQuery library](https://jquery.com/) is used:
```js
$(function () {
  $(".ajax__html_editor_extender_buttoncontainer input")
    .attr('tabindex', function (index, attr) {
    return -1;
  });
  $(".ajax__html_editor_extender_buttoncontainer select")
    .attr('tabindex', function (index, attr) {
    return -1;
  });
  $(".ajax__html_editor_extender_modebuttonscontainer input")
    .attr('tabindex', function (index, attr) {
    return -1;
  });
});
```
