### ISSUE TITLE
AjaxFileUpload control not upload .mkv or .mov or else expect .mp4 file

### ISSUE THREAD

**Issue by rdssiva** [DevExpress/AjaxControlToolkit#413]
Hi,

Am trying to upload file .mkv or else using ajaxfileupload control but unable to upload and red color error message. Am able to upload .mp4 file only.  could you please tell me what is problem?

Thanks

Regards,
Siva

**Comment by AlekseyMartynov** [comment]
This wiki section should help:
[Allowed file extensions](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#allowed-file-extensions)

**Comment by rdssiva** [comment]
Hello Aleksey,

Could you please tell me where i need to included the <ajaxControlToolkit additionalUploadFileExtensions="bmp,wav" /> in Web.Config file?  

Please help me..

Thanks in Advance 

Regards,
Siva

**Comment by rdssiva** [comment]
Hello,

I did it and got the solution. It is working fine.

Thanks.

Regards,
Siva

**Comment by Angate** [comment]
Where in the web.config did you put this? I can't seem to find the correct place for it.

**Comment by MikhailTymchukDX** [comment]
It's located in this section: https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.SampleSite/Web.config#L10-L14
