### ISSUE TITLE
Error while cloning from 'git clone https://github.com/DevExpress/AjaxControlToolkit.git'

### ISSUE THREAD

**Issue by nandakik** [DevExpress/AjaxControlToolkit#417]
After installing git and when i execute commands in git console
git clone https://github.com/DevExpress/AjaxControlToolkit.git

I am getting below error fatal: unable to access 'https://github.com/DevExpress/AjaxControlToolkit.git/': failed to connect to github.com port 443: Timed Out

Please find the attached screenshot
![giterror](https://user-images.githubusercontent.com/36693768/36781554-2ef1f286-1c9c-11e8-937c-6040b028d28f.gif)

**Comment by AlekseyMartynov** [comment]
Your question is off-topic. It's about Git, not about AJAX Control Toolkit.
Try searching or asking at Q&A sites like [stackoverflow.com](https://stackoverflow.com) or [superuser.com](https://superuser.com).

P.S. This thread looks related: https://stackoverflow.com/q/18356502
