### ISSUE TITLE
Error While using GIT CMD to download specific AjaxContro Toolkit version

### ISSUE THREAD

**Issue by nandakik** [DevExpress/AjaxControlToolkit#419]
In the git command prompt i used the command 'git clone https://github.com/DevExpress/AjaxControlToolkit.git' i got below error:
<img width="960" alt="giterror" src="https://user-images.githubusercontent.com/36693768/37076129-2cec3b40-21fb-11e8-887d-0a1153152242.png">

C:\Users\nandakik>git clone https://github.com/DevExpress/AjaxControlToolkit.git

Cloning into 'AjaxControlToolkit'...
fatal: unable to access 'https://github.com/DevExpress/AjaxControlToolkit.git/':
 error setting certificate verify locations:
  CAfile: /mingw64/ssl/certs/ca-bundle.crt
  CApath: none

**Comment by MikhailTymchukDX** [comment]
This is the direct link to download the version you need: https://github.com/DevExpress/AjaxControlToolkit/archive/628efdf.zip
