### ISSUE TITLE
AjaxFileUplaod control send { and } special characters in contextkey parameter to server which is not accepeted by the server team

### ISSUE THREAD

**Issue by nandakik** [DevExpress/AjaxControlToolkit#420]
Since the server team is telling that the contextkey value contains { and } special characters when we upload files using ajaxcontroltoolkit ajaxfileupload control, could you please suggest and other open source file upload / jquery plugins control that does the same functionality as ajaxfileupload control

**Comment by MikhailTymchukDX** [comment]
@nandakik I suggest you use [jQuery File Upload Plugin](https://github.com/blueimp/jQuery-File-Upload).
