### ISSUE TITLE
URL Rewriting

### ISSUE THREAD

**Issue by nandakik** [DevExpress/AjaxControlToolkit#421]
We are using AjaxControlToolkit 4.1 version from past 4 years. We are uploading files using ajaxfileupload control. When we upload files the request will got to Apache Tomcat server with the application URL and by default adding two parameters in the query string contextkey and guid automatically.

For example the url will look like this:
https://reality.alcatel-lucent.com/rsp/action/app/mtap6/MTAPServer/Upload/Upload.aspx?contextkey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&guid=B943E2E3-A536-80BC-F364-E5C39377704A

The two parameters in the URL ContextKey and guid is automatically appended by ajax and the request is sent. The user can't see contextkey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&guid=B943E2E3-A536-80BC-F364-E5C39377704A in the URL. The above URL mentioned in the example is given by the server team.

When i Check AjaxFileUpload.cs page there is one line
internal const string ContextKey = "{DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}";

Now the problem is they (server team) is telling they won't accept { and } characters. The files are not getting uploaded.

Can i rewrite the url in IIS or so from:
https://reality.alcatel-lucent.com/rsp/action/app/mtap6/MTAPServer/Upload/Upload.aspx?contextkey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&guid=B943E2E3-A536-80BC-F364-E5C39377704A

to

https://reality.alcatel-lucent.com/rsp/action/app/mtap6/MTAPServer/Upload/Upload.aspx?contextkey=%7BDA8BEDC8-B952-4d5d-8CC2-59FE922E2923%7D&guid=B943E2E3-A536-80BC-F364-E5C39377704A

so that the request to tomcat server will go like in the above url so that the { and } is replaced with its urlencode characters %7B and %7D respective.

Please any suggestions on this will help me a lot..

**Comment by MikhailTymchukDX** [comment]
@nandakik Yes, you can rewrite URL in IIS.
Here are links that you may find useful:
* https://forums.iis.net/t/1200118.aspx
* https://christierney.com/2014/11/07/iis-url-multiple-specific-character-findreplace/

**Comment by nandakik** [comment]
The params contextkey and guid will not be visible physically in the URL to the user since it's taken care by ajaxfileupload control. But from web server these two params will go, so we can rewrite this on IIS?

**Comment by MikhailTymchukDX** [comment]
@nandakik Yes, if I understand your setup correctly.
