### ISSUE TITLE
AjaxFileUpload: can't clear queue / Max Files Exceeded message results

### ISSUE THREAD

**Issue by StringTheory2** [DevExpress/AjaxControlToolkit#427]
Possible bug, otherwise unable to get a known action to work.
Summary:
ajaxToolkit:AjaxFileUpload, maxfiles=1 is on web form, within ContentTemplate, which is within UpdatePanel.

User cancels out of upload after selecting a file, thereby placing it into queue but not uploading it.

The next time the AjaxFileUpload form is shown, it won't accept another file selection, throwing "Maximum number files exceeded" message, even though I have verified that I have programmatically cleared the queue area via:
  $(".ajax__fileupload_queueContainer").empty();
and also:
  $(".ajax__fileupload_queueContainer").html("").change();

### The installation method
- [ ] Installer
- [x ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
place this into VS web forms project:
  
<asp:ScriptManager ID="ScriptManager1" 
       EnablePageMethods="true" runat="server">
 </asp:ScriptManager>
                                                   
<asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
     <Triggers></Triggers>
     <ContentTemplate>
     <ajaxToolkit:AjaxFileUpload ID="FileUpload1" runat="server" 
                   Width="100%"
                   BackColor="#cceeff" 
                   OnUploadComplete="FileUpload1Complete" 
                   AllowedFileTypes="doc,docx"
                   MaximumNumberOfFiles="1"
                   ClearFileListAfterUpload="true"
                   MaxFileSize="20000"
                   OnUploadStart="FileUpload1Start"
                   OnClientUploadComplete="uploadComplete"
                   OnClientUploadError="uploadError"
            />
 </ContentTemplate>
</asp:UpdatePanel> 

Step 1: Select a file. Don't upload, and don't click remove. 
Step 2: User clicks cancel button outside of updatePanel which runs following code. 
Tried both these statements to clear queue within the cancel button code
   $(".ajax__fileupload_queueContainer").empty();
          $(".ajax__fileupload_queueContainer").html("").change();
The div containing the above ajaxFileUpload control is then hidden via jquery's .hide() method.
Step 3: show the div again.

### Actual result
The upload button continues to show, but no file shows in the queue and the remove button is missing.
A file can't be selected (maximum number of files exceeded)

### Expected result
Clearing the queue via the above method should reset the queue to no files selected. 

Note that I'm unable to force user to gracefully click remove, and unable to keep them from clicking something that will close the upload div, so I'm needing to clear the queue when the user takes an action such as canceling or showing the enclosing div again.

[General questions: is there some better way to re-set the AjaxFileUpload control, possibly even re-writing it to the DOM, as a solution? Is there some other command to re-set AjaxFileUpload's queue, so that it re-sets what it thinks are the current number of files in the queue ? 
tnx
### Browser(s) used
Chrome, latest
### A site deployment method
- [x ] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @StringTheory2 
When you clear the `queueContainer` div, you remove graphical representation of files in the file queue.
AjaxFileUpload stores the file queue internally, and there is no way to manipulate it other than interacting with a control's UI.

I don't completely understand your scenario, because I do not see problems with removing selected files from the file queue even if the control was hidden and re-shown.
Would you please provide a sample project that illustrates the user workflow?

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.
