### ISSUE TITLE
AjaxFileUpload Control

### ISSUE THREAD

**Issue by tcssistemas** [DevExpress/AjaxControlToolkit#43]
Every image i try to upload on the sample website does not work with the AjaxFileUpload control.

The same happens on my own website.. What can i do??

![screenshot_1](https://cloud.githubusercontent.com/assets/18148729/14117804/ad1f6318-f5bc-11e5-97e1-d94df6396e8c.jpg)

**Comment by MikhailTymchukDX** [comment]
Bug #29 in the AjaxFileUpload prevents it from operating properly in a [Medium trust](https://msdn.microsoft.com/en-us/library/wyts434y.aspx) environment.

To workaround it, please set trust level to `Full` in the site's Web.config:
```xml
<configuration>
	<system.web>
		<trust level="Full"/>
	</system.web>
</configuration>
```

**Comment by tcssistemas** [comment]
Hello @MikhailTymchukDX ! Thanks for your reply.
I changed in Ajax solution and it worked for me, but in my site is still not working.
I set trust level and other configs same as the ajax web.config and it still ocurring the error.

```
<system.web>
<pages controlRenderingCompatibilityVersion="3.5" renderAllHiddenFieldsAtTopOfForm="true"  clientIDMode="AutoID" validateRequest="false">
<controls>
<add assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagPrefix="ajaxToolkit"/>
</controls>
</pages>
<trust level="Full"/>
<httpHandlers>
<add verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler,  AjaxControlToolkit" />
</httpHandlers>
</system.web>
<system.webServer>
<handlers>
<add name="AjaxFileUploadHandler" verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit" />
</handlers>
</system.webServer>
```

**Comment by MikhailTymchukDX** [comment]
It looks like the application root is misconfigured.
Is the "www.digital" site folder converted to an application in IIS?

**Comment by tcssistemas** [comment]
Hello @MikhailTymchukDX, yes, www.digital is an app in IIS. I was using version 4.0 and it was working ok, just with this new version its not working. Can you help me? 
Thanks!

**Comment by MikhailTymchukDX** [comment]
The AjaxFileUpload client code expects the application root to be located at `http://localhost/`, so it calls the `http://localhost/AjaxFileUploadHandler.axd` url.
You can tune up this behavior by performing the following steps:
1. Set `UseAbsoluteHandlerPath="false"`.
2. Change the AjaxFileUploadHandler path to `www.digital/galeria/AjaxFileUploadHandler.axd` in Web.config.

**Comment by tcssistemas** [comment]
I did it, its working properly now!

Thank you very much! =)

**Comment by skymail5** [comment]
1) Am using version 15.1, however i do not see this property: "UseAbsoluteHandlerPath" on my AjaxFileUpload control, why is that?

2) where does this file: "AjaxFileUploadHandler.axd" come from, i do not have it in my local project even when i already have the AjaxFileUpload control in my project.

This control was workin fine, then i up graded from 15.1 to 16.1 and that's where my issues began, i then down graded but looks like it was too late.

Lastly, Who can explain why the same issue/problem occurs on the sample site and has not been solved for the last several days: http://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx

**Comment by skymail5** [comment]
@tcssistemas you need to share what exactly you did to solve this issue, coz am still not done with it.

**Comment by MikhailTymchukDX** [comment]
@skymail5

1. This property was introduced in v16.1, so you can not use it when rolling back to the previous version.
2. "AjaxFileUploadHandler.axd" is not a file, it is an [HTTP handler](http://stackoverflow.com/a/11554722/644496).

Would you please provide more details about your site settings?

* Site's root url.
* Page url that contains AjaxFileUpload.
* Browser console errors (if any).

The error on the [Sample site](http://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx) page was caused by bug #29. We applied this workaround to get rid of the error: https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203437189.

**Comment by skymail5** [comment]
Site root URL:
http://realestatedatabase.net

Page URL that contain AjaxFileUpload:
http://realestatedatabase.net/FindAHouse/123AjaxFileUploadControl.aspx

Error is the one is the screen shot i sent earlier, the same error still exits on the sample website.

**Comment by MikhailTymchukDX** [comment]
@skymail5 
The site root URL seems to be properly configured.

We found that AjaxFileUpload fails in a web farm environment in v16.1 (see #53).
Are you running your site in a cluster?

Also, do you see any errors in the browser console, like @tcssistemas did here: https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203524214

**Comment by skymail5** [comment]
Control works fine on my local machine but gives an error online, here is the screen shot:
https://onedrive.live.com/redir?resid=EA7A59587433CBE3!28255&authkey=!AIXER1BvZ2X-qJI&v=3&ithint=photo%2cpng

**Comment by MikhailTymchukDX** [comment]
@skymail5 This is not the screenshot of the browser's console.
We need an image like this one:
![image](https://cloud.githubusercontent.com/assets/17080984/14282270/4d83b4ce-fb46-11e5-881a-a3309964f37b.png)

**Comment by rclancy** [comment]
I'm into my third day trying to resolve this. I'm using AjaxControlToolkit v16.1 in an asp.net v4.6.1 project. On the same machine in IIS Express (VS) it works perfectly, but when I deploy it to IIS by publishing to a local directory (Windows 10 IIS v4.0 integrated pool) I get the (error) when uploading. Setting the trust level doesn't help. UseAbsoluteHandlerPath is not available in VS. Adding the IIS app name to AjaxFileUploadHandler.axd also doesn't help...

**Comment by MohammedMubeen** [comment]
Hi folks,
 following file formats are not able to upload.
Formats - .xlt, .temp,.dwg and .msg 

Please help me.

show below the console error: 

![image](https://user-images.githubusercontent.com/26380140/27232864-2fe29a38-52d5-11e7-9758-4463b66d7295.png)

**Comment by MikhailTymchukDX** [comment]
Hi @MohammedMubeen 
To fix this error, please add the `additionalUploadFileExtensions` attribute to the `ajaxControlToolkit` section in your Web.config:
```xml
<configSections>
    <section name="ajaxControlToolkit" type="AjaxControlToolkit.AjaxControlToolkitConfigSection, AjaxControlToolkit" requirePermission="false"/>
</configSections>
<ajaxControlToolkit additionalUploadFileExtensions="xlt,temp,dwg,msg" />
```

**Comment by MohammedMubeen** [comment]
Hi @MikhailTymchukDX 
My problem is solved, you save my time. Thank you so much for quick reply.

**Comment by MohammedMubeen** [comment]
Hi @MikhailTymchukDX 
I have faced another couple of problems mentioned below:
1. If documents contain name like "2014-2015 and R&D.doc" then I can't able to upload files.
(Note: Also I have investigated the only "&" symbol was not supported. )
2. When I am uploading bulk files continuously then my application went down.Then I need to refresh my application its working fine. Please help me.

**Comment by MikhailTymchukDX** [comment]
Hi @MohammedMubeen
1. I cannot reproduce this issue. Would you please attach a sample file?
2. It looks like the server is run out of memory. Do you see any error in Windows Event Log?

**Comment by MohammedMubeen** [comment]
Hi @MikhailTymchukDX 
Thanks for replay 
1.I have attached sample file.
[2014-2015 and R&D.docx](https://github.com/DevExpress/AjaxControlToolkit/files/1087060/2014-2015.and.R.D.docx)

2.Error log screen shot:
![img_17062017_133425_0](https://user-images.githubusercontent.com/26380140/27317429-eb30a228-55a3-11e7-98e2-0ceab1488f82.png)

I have faced another issue when my application starting time takes more than 3 min.
Below-console error occurs:
![image](https://user-images.githubusercontent.com/26380140/27317500-572e6e10-55a4-11e7-81e0-7847b667b39d.png)

Please help me...

**Comment by MikhailTymchukDX** [comment]
@MohammedMubeen 
1. I created a new project from scratch and could not reproduce this issue: 
[AmpersandTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1088318/AmpersandTest.zip)
Would you please check this file with the attached project and inform us of the results?
2. I meant Windows Event Log which can be accessed from the Control Panel's Event Viewer:
![image](https://user-images.githubusercontent.com/17080984/27336142-5551f552-55d7-11e7-9b46-ff55929eea92.png)
![image](https://user-images.githubusercontent.com/17080984/27336285-b9f458c4-55d7-11e7-9f28-40c97bf9bddd.png)

**Comment by MohammedMubeen** [comment]
Hi @MikhailTymchukDX 
Thanks for more information
1.I have attached sample file."2014-2015 and R&D.docx"
Show below event error
![error](https://user-images.githubusercontent.com/26380140/27368996-5cc5731c-5673-11e7-8aff-c5ddd819f688.png)
![error1](https://user-images.githubusercontent.com/26380140/27368999-5ede7798-5673-11e7-8107-d320bca53e68.png)
![error2](https://user-images.githubusercontent.com/26380140/27369002-616e3a52-5673-11e7-971f-e6a60a219bd4.png)

**Comment by MikhailTymchukDX** [comment]
Hi @MohammedMubeen 
Thank you very much for the screenshots!
I see that the file name passed to an upload handler is not encoded for some reason.
Would you please specify what browser version you are using?

**Comment by MohammedMubeen** [comment]
Hi @MikhailTymchukDX 
Thanks for reply, 
I am using browser - Google Chrome - Version 58.0.3029.110 (64-bit)

**Comment by MikhailTymchukDX** [comment]
Hi @MohammedMubeen 
While I still cannot reproduce this issue in my environment, the information you provided is enough to make a fix.
Please download fixed assemblies from [this custom build](https://ci.appveyor.com/project/MikhailTymchukDX/ajaxcontroltoolkit/build/artifacts) and check your project with it.

For more details about using custom builds, please refer to [this wiki article](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds).
I look forward to your response.

**Comment by MohammedMubeen** [comment]
HI @MikhailTymchukDX 
Thank you for providing more information.
I have removed ajax control kit package and as you suggested I have added only ajax custom build DLL under bin folder, now all are working fine.
Can you please tell me the reason why NuGet ajax control kit package not working in my project.

**Comment by MikhailTymchukDX** [comment]
Hi @MohammedMubeen 
>Can you please tell me the reason why NuGet ajax control kit package not working in my project.

Do you mean that you cannot use any version of the AJAX Control Toolkit NuGet package and have to add a reference manually?

**Comment by MohammedMubeen** [comment]
Hi @MikhailTymchukDX 
Thanks for replay
Yes, your write.

**Comment by MohammedMubeen** [comment]
HI @MikhailTymchukDX 
I facing another issue:
**When uploading bulk documents (20), while uploading 5th file got an error, this time the full uploading operation got stopped. Instead, skip the error file and upload remaining files.**

How to skip error file and continue remaining file? Please help me.

**Comment by MikhailTymchukDX** [comment]
Hi @MohammedMubeen 
1. Please execute the following command in Package Manager Console and provide us the log of this command execution:

    `PM> Install-Package AjaxControlToolkit`

    Package Manager Console window can be accessed via Tools -> NuGet Package Manager -> Package Manager Console menu item.

2. Please provide the following info:
    * The size of each file.
    * Amount of RAM on the server.
    * Web.config of your application.
    * Errors in Windows Event Log if any.

**Comment by MohammedMubeen** [comment]
HI @MikhailTymchukDX 
After Including file format in web.config as you provide previous comments my issue was solved.now I can able to upload bulk documents (20) without any issue.

but in future, any other error occurs during bulk upload, is there any solution for remaining files to upload without fail?

**Comment by MikhailTymchukDX** [comment]
@MohammedMubeen Bulk files uploading does not require any actions from you to work properly.
If it does, feel free to create a new issue.

**Comment by MohammedMubeen** [comment]
@MikhailTymchukDX 
Thanks for all your comments.

**Comment by noyronva** [comment]
Hi @MikhailTymchukDX,

Could you help me with my problem? When uploading a file that exceed to 4mb it was uploaded successfully but when i look at the file in the folder where it's transferred its file size only 4MB but the actual size of the file that was uploaded is 18MB. I already set maxAllowedContentLength="104857600"

![untitled](https://user-images.githubusercontent.com/39689297/40600216-2dc10690-6283-11e8-8741-2acaa2f02be0.png)

Thanks.

**Comment by SengChankakda** [comment]
Hi.,
Please kindly help me to solve this problem.
![28-may-2018 3-29-44 pm](https://user-images.githubusercontent.com/39693102/40605261-fd08b620-628b-11e8-8e6b-b78247b7d2d7.png)
I already use trust level to full in web config already.

**Comment by MikhailTymchukDX** [comment]
Hi @SengChankakda 
* What is the application root url and page url when the control is located?
* What do you see in a browser's console and network tab?
* How did you [configure AjaxFileUploadHandler](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#upload-handler) in Web.config?

If you have a sample project that illustrates this issue, it will greatly help us in our research.

**Comment by SengChankakda** [comment]
@MikhailTymchukDX  
Now I fixed it already by the code below
---------------------------------------------
<location path="AjaxFileUploadHandler.axd">
    <system.web>      
      <httpHandlers>
        <add verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit" />
      </httpHandlers>
      <authorization>
        <allow users="*"/>
      </authorization>
    </system.web>
    <system.webServer>
      <handlers>
        <add name="AjaxFileUploadHandler" verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit" />
      </handlers>
    </system.webServer>
  </location>
--------------------------------------------------------
Thanks for your reply.

**Comment by SengChankakda** [comment]
Hi I am new with ajaxfileupload tool. I not clear how to upload file to folder after event onUploadComplete fired. Please kindly help me.

**Comment by AlekseyMartynov** [comment]
@SengChankakda 

> how to upload file to folder after event onUploadComplete fired

Check comments in `AjaxControlToolkit.SampleSite/AjaxFileUpload/AjaxFileUpload.aspx.cs`:

https://github.com/DevExpress/AjaxControlToolkit/blob/cc40403b1ae845ada78daa4e5cda1a919c7837a3/AjaxControlToolkit.SampleSite/AjaxFileUpload/AjaxFileUpload.aspx.cs#L50-L51
