### ISSUE TITLE
ModalPopupExtender: After confirmation message functionality is not working

### ISSUE THREAD

**Issue by BRahulSoft** [DevExpress/AjaxControlToolkit#430]
Details: The AJAX Control Toolkit 18.1.0 installed from a NuGet package. The AJAXControlToolkit used in the VS2008 ASP.NET application upgraded from v3.0.20820 to v18.1.0

Issue: The confirmation message is getting displayed but nothing is happening after clicking Yes or No buttons.

**ASPX.cs Code:**
protected void Page_Load(object sender, EventArgs e)
    {
          lbtnCancel.Attributes.Add("onclick", "return validateCancel('" + tcMainform.ClientID + "', this);");
    }

**JavaScript:**
function validateCancel (tabcontainer, source) {
    showConfirm(source, 'Are you sure you want to cancel this record?', 'mpeConfirm', 'confirmTitle');
    return false;
}

**ASPX Code:**
<ajaxToolkit:ModalPopupExtender ID="mpeConfirm"
                                       BehaviorID="mpeConfirm" 
                                       runat="server"
                                       OnOkScript="okClick();"
                                       OkControlID="btnConfirmOk"
                                       OnCancelScript="cancelClick();"
                                       CancelControlID="btnConfirmCancel"
                                       PopupControlID="pnlConfirmPopup"
                                       TargetControlID="btnHidConfirmDummy"
                                       BackgroundCssClass="modalBackground">
    </ajaxToolkit:ModalPopupExtender>
    
    <asp:Button ID="btnHidConfirmDummy" runat="server"  Style="display:none" /> 
    <asp:Panel  ID="pnlConfirmPopup" 
                CssClass="modalBox" 
                runat="server" 
                style="display:none;">
               <div id="Div1" class="caption">&nbsp;</div><h4 id="confirmTitle"></h4>    
               <div class="text-right no-wrap">
                   <asp:Button ID="btnConfirmOk" 
                               CssClass="submit yesNo"
                               runat="server" 
                                OnClientClick="disableCheck();"
                               Text="Yes"/>&nbsp;&nbsp;
                   <asp:Button ID="btnConfirmCancel" 
                               CssClass="submit yesNo" 
                               runat="server"
                               Text="No" />
               </div>
    </asp:Panel>

Please advise.

**Comment by MikhailTymchukDX** [comment]
Hi @BRahulSoft 
I could not reproduce this issue based on the code you provided.
Would you please provide sample projects (both with old and new versions of the toolkit) so we can see how your project's behavior is changed?

**Comment by BRahulSoft** [comment]
Hi MikhailTymchukDX! Thanks for your response to post. 

The Server Side event was not getting triggered after clicking "Ok" button of Confirmation Popup. Now, I am able to trigger the Server Side event by adding OnClick="lbtnCancel_Click" into the asp:Panel.

    <asp:Panel  ID="pnlConfirmCancelRecordPopup" 
                CssClass="modalBox" 
                runat="server" 
                style="display:none;">
                <div id="divCancelRecord" class="caption">&nbsp;</div>
                <h4 id="confirmCancelRecordTitle"></h4>  
                <div class="text-right no-wrap">
                   <asp:Button ID="btnCancelRecordYes" 
                               CssClass="submit yesNo"
                               runat="server" 
                               OnClientClick="disableCheck();"
                               Text="Yes"
                               **OnClick="lbtnCancel_Click"**/>
                   <asp:Button ID="btnCancelRecordNo" 
                               CssClass="submit yesNo" 
                               runat="server"
                               Text="No" />
                </div>
    </asp:Panel>
