### ISSUE TITLE
AjaxFileUpload Can't Upload 4MB+

### ISSUE THREAD

**Issue by awmasakityan** [DevExpress/AjaxControlToolkit#434]
Hi All,

Could anyone help me with this? When uploading a file that exceed to 4mb it was uploaded successfully but when i look at the file in the folder where it's transferred its file size only 4MB but the actual size of the file that was uploaded is 18MB. I already set maxAllowedContentLength="104857600"

![untitled](https://user-images.githubusercontent.com/39689297/40600565-7c0fb28c-6284-11e8-8190-e18f1b51f648.png)

Thanks.

**Comment by MikhailTymchukDX** [comment]
Hi @awmasakityan 
Depending on your IIS version, you may need to setup another property in Web.config (see [StackOverflow](https://stackoverflow.com/a/3853785/644496) for details):
```xml
<configuration>
    <system.web>
        <httpRuntime maxRequestLength="1048576" />
    </system.web>
</configuration>
```

If it does not help you, please post the AjaxFileUpload markup here, so we can check if it is configured properly.

**Comment by awmasakityan** [comment]
Hi @MikhailTymchukDX,

Thanks for your response.

i set my maxRequestLength to 1048576 but it still doesn't work. i did some testing with another server and it works. Is it perhaps compatibility issue?

**WORKS ON MY PC (DEVELOPMENT):**
OS:WINDOWS 7 64bit
 IIS version 7.5

**WORKS ON THIS SERVER:**
OS: WINDOWS 10 64bit, WINDOW SERVER 2016
IIS version 10.0

**WONT' WORK ON THIS SERVER:**
OS: WINDOWS 8 64bit, WINDOW SERVER 2012
IIS version 8.0

**Comment by MikhailTymchukDX** [comment]
@awmasakityan 
The AJAX Control Toolkit is compatible with any version of IIS.
You can set both config values so they match as mentioned in [another answer on StackOverflow](https://stackoverflow.com/a/12496077/644496).

If it does not help, you can decrease the `ChunkSize` property value of AjaxFileUpload to 2048 or lower:
```
<ajaxToolkit:AjaxFileUpload runat="server"
        ChunkSize="2048"
</ajaxToolkit:AjaxFileUpload>
```
