### ISSUE TITLE
Conflict between Webcamjs and ajax control toolkit

### ISSUE THREAD

**Issue by CodeGirlRio** [DevExpress/AjaxControlToolkit#440]
Good afternoon, 
I'm using C# webforms framework 4.0 with visual studio 2015 with ajax control toolkit and trying to use webcam.js to capture images from my webcam and I'm having problems with Internet Explorer 11.
I modified the parts in the html file that is using jquery so it will only use javascript and html5. (It opens a tag <video>  in the execution time).
My guess is ajax control toolkit is not compatible with .swf file (flash file), but besides this, Im having the following errors:

- JavaScript critical error at line 332, column 5 in http://localhost:6396/Js/LOG/webcam.js\n\nSCRIPT1010: Identificador esperado ok
-In the line: var shutter = new Audio();   ===>Error: 0x800a1391 -  'Audio' is not defined
- 0x800a1391 - 'Webcam' is not defined (even though it is defined in webcam.js)

The link for webcam.js is  https://github.com/jhuckaby/webcamjs

---> The usage if fine with chrome and firefox.

---> Utilized components and libraries:

Menu.ascx TagName="Menu" TagPrefix="swa" 
jquery-1.9.1.js
jquery-ui-1.10.0.custom.min.js
jquery.multiselect.js
TagName="BOOSTAjaxLoad" TagPrefix="uc3"
BOOSTCtrls  TagPrefix="BC1"
Namespace="AjaxControlToolkit" TagPrefix="cc1" (in the masterpage)
Namespace="AjaxControlToolkit" TagPrefix="cc2"
 TagName="EntityFromUser" TagPrefix="uc2"
 
<cc1:ToolkitScriptManager
<cc1:ModalPopupExtender
<uc2:EntityFromUser 
<cc2:MaskedEditExtender 
<cc2:CalendarExtender     
<BC1:BOOSTButton 
<uc3:BOOSTAjaxLoad

Thank you.

**Comment by MikhailTymchukDX** [comment]
Hi @CodeGirlRio 
We can not construct a sample project based on the info you provided.
Would you please provide a sample project, which we can run out of the box to investigate this issue?

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.
