### ISSUE TITLE
ComboBox Control, autofilter + contains

### ISSUE THREAD

**Issue by mixfede** [DevExpress/AjaxControlToolkit#442]
Is it possible to add option to combobox, which allows to auto-filter the entered text ?? taking into account that the text you are looking for this content in the text.

In the example of the combobox in demo page, if you search "ee" the results would be:
Three
Terrathree
yankee

Thanks!

### The installation method
- [X] Installer
### A site deployment method
- [ ] VS development web-server,
- [X] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @mixfede 
A combobox item list cannot be filtered.
Probably, the [Autocomplete](https://ajaxcontroltoolkit.devexpress.com/AutoComplete/AutoComplete.aspx) extender will meet your requirements.
