### ISSUE TITLE
problem ajaxfileupload with user friendly url pages

### ISSUE THREAD

**Issue by hlikehamed** [DevExpress/AjaxControlToolkit#443]
hi,

when i use **ajaxfileupload** in user friendly url pages(by routing in global.asax) , control not work.

control work fine in aspx page
control not work in aspx routed page

my project Detail:
asp.net webforms
.net 4.6.1
ajaxcontroltoolkit 18.1

i need help.
thanks

**Comment by MikhailTymchukDX** [comment]
Hi @hlikehamed 
Would you please provide a sample project that illustrates this issue?

**Comment by hlikehamed** [comment]
this is sample project :
https://ufile.io/eubeg

Note: routing is commented in global.asax  and control work fine.
if enable routing then fileupload not work

**Comment by hlikehamed** [comment]
@MikhailTymchukDX 

Thank you so much
its worked.
