### ISSUE TITLE
VS2017 Code Analyzer security complaint

### ISSUE THREAD

**Issue by CA2117** [DevExpress/AjaxControlToolkit#444]
building the solution and running VS2017 code analyzer reveals the following warning multiple times : 

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2117-aptca-types-should-only-extend-aptca-base-types

**Comment by MikhailTymchukDX** [comment]
Hi @CA2117 
This is a side effect of deriving component designers from types defined in assemblies without the APTCA attribute such as `System.Design.dll`.
We'll consider splitting designers into separate assemblies to avoid these warnings. At the same time, I wish to note that the warnings don't mean vulnerabilities in code.
