### ISSUE TITLE
Issue with AjaxControlToolkitVsPackage

### ISSUE THREAD

**Issue by chstorb** [DevExpress/AjaxControlToolkit#446]
Issue with AjaxControlToolkitVsPackage when trying to build it with Visual Studio 2017:

"[...] \AjaxControlToolkit\AjaxControlToolkitVsPackage\AjaxControlToolkitVsPackage.cs(16,55,16,62): error CS0246: The type or namespace name 'Package' could not be found (are you missing a using directive or an assembly reference?) [...]"

**Comment by AlekseyMartynov** [comment]
Please install [VS 2010 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=21835#ad36995f-7d06-75a1-2c27-34fdf96cc5d9).

![sdk](https://user-images.githubusercontent.com/4426185/41979926-e907961e-7a2d-11e8-8d90-5a11ffb652fe.png)


Upgrade to 15.0 suggested in #447 is not necessary.

@MikhailTymchukDX 
We may consider switching to NuGet Packages (e.g. [VSSDK.Shell.10](https://www.nuget.org/packages/VSSDK.Shell.10/)) to prevent this kind of issues.

**Comment by MikhailTymchukDX** [comment]
@chstorb We added this task to our backlog. Thanks for tuning in!
