### ISSUE TITLE
User entered number values are being changed after tabbing out of the fields - MaskedEditExtender

### ISSUE THREAD

**Issue by jigarnaik2004** [DevExpress/AjaxControlToolkit#449]
### The AJAX Control Toolkit \Run time version: 2.0.50727 , File version: 3.0.20820.16598
Note: It happens with all versions of AjaxControlToolkit.

### The installation method
- Installer

### Minimal steps to reproduce the bug
User entered number values are being changed after tabbing out of the fields. 

Steps to follow to reproduce the issue:

1) ASP.Net Web Form code for rendering masked text box 
<asp:TextBox ID="txtMainContact" Width="9em" MaxLength="13" runat="server" CssClass="TextboxBorder" />
<cc1:MaskedEditExtender ID="mskMainContact" Mask="(999)999-9999" MaskType="Number" TargetControlID="txtMainContact"
            runat="server" Enabled="True" ClearMaskOnLostFocus="true" AutoComplete="false"  />

2) Compile code and load the page
3) Enter valid phone number 1111111111. Mask applies automatically and it becomes (111)111-1111
4) Press 'x' to clear the text box
5) Enter the number again  1111111111 and tab out from the field.
6) The number changes to random - example 111112222 , 1111211122

### Browser(s) used
IE 11 with IE 7 compatibility mode
(the issue reproduces  on IE11 without compatibility as well )

### A site deployment method
- IIS (The issue reproduces through IIS express as well.)

**Comment by AlekseyMartynov** [comment]
The current version of the Toolkit is 18.1:

![act18](https://user-images.githubusercontent.com/4426185/42031580-66c3f5a0-7adf-11e8-96a7-1627d5d6c152.png)

A binary with `FileVersion` of `3.0.x` is very outdated.

I performed the steps you provided but didn't notice the described anomalies.
Screencast: [act-issue-449.mp4.zip](https://github.com/DevExpress/AjaxControlToolkit/files/2145094/act-issue-449.mp4.zip)

**Comment by MikhailTymchukDX** [comment]
Closed due to inactivity.
