### ISSUE TITLE
AutoComplete: TextBox.TextChanged not firing on Safari/Chrome for MAC, IPAD

### ISSUE THREAD

**Issue by MaxZeta** [DevExpress/AjaxControlToolkit#450]
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

Select an item on AutoComplete
Textbox is correctly filled 
TextBox.TextChanged event not firing on server side.

You must click "Go" on virtual keyboard to confirm text 

It's ok on Chrome Windows, Chrome Android, IE11 , ecc..

### Browser(s) used
Safari on IPAD 10.2
Chrome on IPAD 10.2
Safari on MAC

**Comment by AlekseyMartynov** [comment]
Thanks. Reproduced.

Additional detail: `AutoPostBack=true`

@MikhailTymchukDX 
Presumably, we need to add iOS flags here:
https://github.com/DevExpress/AjaxControlToolkit/blob/dd212e9a4121be06fb9c8bb66c7b4a436de13476/AjaxControlToolkit/Scripts/AutoComplete.js#L727-L730

**Comment by Pritish1989** [comment]
@MikhailTymchukDX @AlekseyMartynov : I am seeing the same for edge browser also for AjaxContolToolKit Version 18.1.0.0. Can you please help here? Its working absolutely fine in chrome and IE.
