### ISSUE TITLE
Use CalendarExtender as a fallback if HTML5 date input field is not supported

### ISSUE THREAD

**Issue by Benjiiim** [DevExpress/AjaxControlToolkit#456]
I would like to use the CalendarExtender only if the HTML5 date input field is not supported by the browser.
The goal is to rely on native browser features when possible, to avoid loading more scripts/styles if not needed and to have a native experience for mobile users.

I was thinking about using a ASP.NET HttpCapabilitiesBase property in order to avoid to load ACT server side if not needed but I can't find a capability for detecting date input field support.
Using the IsMobileDevice could partially do the trick (to not load ACT on mobile devices where date input field is now widely supported and to load it on non-mobile devices regardless of the support) but I have the feeling that this is not a up-to-date feature.

Second idea was to use Modernizr, a much more modern solution to detect the support for such browser features. However, it would be client side and it would be too late to avoid to load ACT which mean I won't save the bandwidth and requests I want to save.
If the only solution is client side, that would mean to switch from ACT to an other framework for date picking such as bootstrap-datetimepicker or JQueryUI which I'm trying to avoid.

How would you achieve this? Any thoughts?
Thanks a lot.

**Comment by MikhailTymchukDX** [comment]
Hi @Benjiiim 
There is no reliable way to check for an HTML5 date input field on the server side.
So, we believe that using any modern client-side library like jQuery UI is the best way to achieve your goal.
