### ISSUE TITLE
ValidatorCalloutExtender does not show inside Repeater ItemTemplate.

### ISSUE THREAD

**Issue by dasilvas3** [DevExpress/AjaxControlToolkit#46]
This is a very strange issue. I have a TextBox custom control which are inside a Repeater ItemTemplate. The custom control allows the user to set the Required ="True" attribute. Eg.`<component:TextBoxMoney runat="server" id="tbxPrice" RequiredField="True" width="40px"/>`
when this attribute is set the control becomes a required field and if the user omits the value for this field the ValidatorCalloutExtender message appears.
When the page is initially loaded and the Repeater populated with records. Everything works fine. (If the user removes the values from the required fields the message is displayed to the user) 
The problem is when I add a new row to the repeater. When this is done, the user can remove any required values from the controls and no message is displayed. 
Now if the user tries to submit the page, the validations fire for these controls and the focus is on the first control that is invalid. But again no ValidatorCalloutExtender message is displayed.

My company is very strick in upgrading third party libraries as this means that many applications will have to be tested so at the moment we are using 1.0.10920.0 version of the AjaxControlTookKit.dll. 

I would appreciate any help on this

adasilva

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project that illustrates this issue?

**Comment by MikhailTymchukDX** [comment]
Closed due to inactivity.
