### ISSUE TITLE
Issue with MicrosoftAjaxWebForms.js and firefox TypeError: access to strict mode caller function is censored

### ISSUE THREAD

**Issue by snowfire20** [DevExpress/AjaxControlToolkit#462]
### The installation method
- [ ] NuGet package

### Minimal steps to reproduce the bug
solution .net 4.7.2 WebForms
using jquery-1.12.2.js
Have a control that uses the Ajaxcontroltoolkit on a page
have an aspxGridview on the page (devexpress v 18.1.6)
in javascript call grid.PerformCallback

### Actual result
Console Error: 

TypeError: access to strict mode caller function is censored MicrosoftAjaxWebForms.debug.js:738:24
	Sys$WebForms$PageRequestManager$_doPostBack https://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxWebForms.debug.js:738:24
	Function$createDelegate/< https://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjax.debug.js:47:16
	__doPostBack https://localhost:44367/DXR.axd:5676:4
	sendPostBackInternal https://localhost:44367/DXR.axd:11620:4
	SendPostBack https://localhost:44367/DXR.axd:11616:4
	CreateGridPostback https://localhost:44367/DXR.axd:40459:3
	SendPostback https://localhost:44367/DXR.axd:40492:3
	SendRequest https://localhost:44367/DXR.axd:40473:4
	gridCallBack https://localhost:44367/DXR.axd:38722:28
	PerformCallback https://localhost:44367/DXR.axd:39965:3
	callback https://localhost:44367//Scripts/Pages/Administration-UserAdministration.js:124:41
	init/exports.confirm/options.buttons.confirm.callback https://localhost:44367//ScriptResource.axd:9783:14
	processCallback https://localhost:44367/ScriptResource.axd:9560:52
	init/exports.dialog/< https://localhost:44367/ScriptResource.axd:10166:7
	dispatch https://localhost:44367/Scripts/jquery-1.12.2.js:5225:16
	add/elemData.handle https://localhost:44367//Scripts/jquery-1.12.2.js:4878:6

### Expected result
Call back Fires and preforms whatever actions its supposed to
### Browser(s) used
Use Firefox (latest)

notes:
MicrosoftAjaxWebForms is not referenced anywhere in our codebase. Backing the AjaxControlToolkit down to version 7.1.12 "fixes" this issue in that MicrosoftAjaxWebForms is no longer included.
according to this: 
https://developercommunity.visualstudio.com/content/problem/166951/the-aspnet-ajax-scripts-are-incompatible-with-use.html
this is a known issue with MicrosoftAjaxWebForms that they don't appear to be interested in fixing. 
what I am requesting is that you update the AjaxControlToolkit with one of the workarounds for this
example: https://mnaoumov.wordpress.com/2016/02/12/wtf-microsoftajax-js-vs-use-strict-vs-firefox-vs-ie/

**Comment by MikhailTymchukDX** [comment]
Hi @snowfire20 
Would you please provide a sample project that illustrates this issue?

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.
