### ISSUE TITLE
Pasting images into HtmlEditorExtender

### ISSUE THREAD

**Issue by rclancy** [DevExpress/AjaxControlToolkit#464]

**Comment by AlekseyMartynov** [comment]
Can you tell what was the Toolkit version that supported this?

**Comment by rclancy** [comment]
Until last week I was using a version in production from 2015

**Comment by MikhailTymchukDX** [comment]
Hi @rclancy 
We cannot identify which release corresponds with version 4.1.7.1213
How did you obtain this DLL? Would you please provide it to us?

**Comment by rclancy** [comment]
Here you go.
From the official site. This was pre-open source

**Comment by MikhailTymchukDX** [comment]
@rclancy We cannot see any links in your reply. Would you please post a message via web site or provide a link as a plain text?

**Comment by rclancy** [comment]
[AjaxControlToolkit.zip](https://github.com/DevExpress/AjaxControlToolkit/files/2611781/AjaxControlToolkit.zip)

**Comment by rclancy** [comment]
Hi,
Is there any update on my issue please?
Regards,
Robert

**Comment by MikhailTymchukDX** [comment]
Hi @rclancy 
We could not reproduce the issue you described using the assembly of v4.1.7.1213.
Would you please provide a sample project that illustrates this issue?

**Comment by rclancy** [comment]
Hi Mikhail, Are you saying that you can’t paste an image into the editor using this dll? I assume your argument is that AjaxControlToolkit never supported this function? Sorry but I can’t provide a sample project.

**Comment by MikhailTymchukDX** [comment]
Hi @rclancy 
I created a sample project using AjaxControlToolkit v7.1.1213 NuGet package, which seems to be the same version you are using: [ToolkitHtmlEditorExtender.zip](https://github.com/DevExpress/AjaxControlToolkit/files/2619090/ToolkitHtmlEditorExtender.zip)
Would you please update this project to illustrate this issue?

**Comment by rclancy** [comment]
(Attachment problems)

From: Robert Clancy
Sent: Wednesday, November 28, 2018 11:56 AM
To: DevExpress/AjaxControlToolkit <reply@reply.github.com>
Subject: RE: [DevExpress/AjaxControlToolkit] Pasting images into HtmlEditorExtender (#464)

Hi Mikhail,

I like it. This version v7.1.1213, which I thought I’d tested, is very old but it sort of works.
Please see the attached, revised app you sent. I’ve made a few changes:

  *   Increased the size of textbox
  *   Added a Save button
  *   Added code behind to debug the content after clicking save
  *   Added label to show the content

If you paste an image, there is an error when you click Save (attached), but it does indeed store the img (base 64?) which is great.
But then there is a second error when the control no longer shows the image.

Regards,
Robert

**Comment by MikhailTymchukDX** [comment]
Hi @rclancy 
I don't see any attachment in your post.
Would you please add it using the web site interface?

**Comment by rclancy** [comment]
[ToolkitHtmlEditorExtender.zip](https://github.com/DevExpress/AjaxControlToolkit/files/2626602/ToolkitHtmlEditorExtender.zip)
![capture](https://user-images.githubusercontent.com/285101/49182460-72c25e80-f3ae-11e8-9fdf-eaabae8640dc.PNG)
![capture2](https://user-images.githubusercontent.com/285101/49182466-77871280-f3ae-11e8-883f-5fde91c8561f.PNG)

**Comment by MikhailTymchukDX** [comment]
Hi @rclancy 
I have an empty value for the `src` attribute when uploaded an image.
Would you please provide a short video that illustrates the expected behavior?

**Comment by rclancy** [comment]
[bandicam 2018-11-30 09-26-08-679.zip](https://github.com/DevExpress/AjaxControlToolkit/files/2631120/bandicam.2018-11-30.09-26-08-679.zip)

**Comment by rclancy** [comment]
I attached a video that shows exactly what I described previously:
- initial success from your downloaded project (pasting image from Paint selection)
- added a save button, code behind, breakpoint
- pasted another image and can see the base64 in the control html
- clicked Save
- error
- breakpoint shows img was captured
- continued execution but the image is not redrawn even though the base64 is still in the control

You will see in the video that the second time I ran the project, VS hung, but then I re-launched it a 3rd time. This happens often in my environment quite often and is annoying but otherwise causes no problems.

**Comment by MikhailTymchukDX** [comment]
Hi @rclancy 
Thank you for the video, it helped a lot!
I noticed that you used Internet Explorer. In modern browsers (Edge, Chrome etc.) there is a different API for clipboard operations, so image pasting is not working in HtmlEditorExtender.
As an immediate workaround I recommend using Internet Explorer or Mozilla Firefox if possible.

**Comment by rclancy** [comment]
I tried Chrome and it doesn’t even allow pasting the image.

**Comment by AlekseyMartynov** [comment]
Ok, let's summarize.
- Pasting images as `<img src="data:...">` is supported by some browsers (IE, Firefox)
- An old version of the Toolkit (v7.x) successfully transfers HTML with data URLs to the server, but it has some issue causing an `IndexSizeError`.
- The current version of the Toolkit destroys data URLs. I opened a separate ticket to address it: #467

**Comment by rclancy** [comment]
Hi Aleksey,

Sorry, let’s summarise:

  *   I can’t paste images into HtmlTextExtender as was previously supported in very old versions of the Toolkit
  *   I haven’t had any success at reverting my application to an older version of the toolkit to enable pasting of images
  *   The link tool no longer remembers existing URLs and doesn’t offer target options as it did years ago

You’ve closed this case but I don’t have a solution. Are you saying that all I need to do is simply revert to a version of the toolkit about 4 years old and then everything will work fine?

Regards,
Robert

**Comment by AlekseyMartynov** [comment]
@rclancy 

> I can’t paste images into HtmlTextExtender as was previously supported in very old versions of the Toolkit

We understand. As I said in my previous comment, we've reproduced this and opened a separate ticket ['HtmlEditorExtender unconditionally removes tags with data URLs'](https://github.com/DevExpress/AjaxControlToolkit/issues/467). Subscribe to it to be notified when the fix is ready.

> The link tool no longer remembers existing URLs and doesn’t offer target options as it did years ago

The project from https://github.com/DevExpress/AjaxControlToolkit/issues/464#issuecomment-441982966 uses an old version `7.1213`, and the 'Create link' popup is the same as in the current version. Do you have a sample project that you can share with to illustrate the difference?

>  Are you saying that all I need to do is simply revert to a version of the toolkit about 4 years old and then everything will work fine?

No. We didn't say that.

**Comment by rclancy** [comment]
Hi Aleksey,

I have subscribed to the ticket. Thank you. Hopefully there will be a fix soon.
I have no idea what exact old version of the toolkit remembered the link and allowed target selection. I could explore my network backups which would take time, but the issue to me is simple:

  *   Create a link using the link tool
  *   The tool needs to offer target selection (e.g. “_blank”)
  *   Edit the link
  *   The tool needs to remember the link you created previously
Are you saying it does this, or are you saying that it doesn’t and it never did, or do you agree with me that it did before but doesn’t now (3 options)?

Regards,
Robert

**Comment by rclancy** [comment]
I find it hard to understand why the target selection (_blank etc.) for a link in an html editor would not be a fundamental requirement/feature. Why do I need to dig up something years old when the requirement is so basic and so necessary?

**Comment by AlekseyMartynov** [comment]
> I find it hard to understand why the target selection (_blank etc.) for a link in an html editor would not be a fundamental requirement/feature.

I agree that an HTML editor is expected to have a hyperlink customization dialog. However, the specific `HtmlEditorExtender` hasn't had it (at least since version 7.x)

At the current stage, we don't add new features to the Toolkit. We fix reported bugs and ensure compatibility with today's browsers and Visual Studio versions.

If you are starting a new project, I strongly recommend that you choose a more up-to-date editor (Quill, TinyMCE, etc).

If you are upgrading an existing project that uses AJAX Control Toolkit and experience an issue, we are here to help.
