### ISSUE TITLE
upload Tiff/tif files keep resulting OnClientUploadError via AjaxFileUpload drag&drop

### ISSUE THREAD

**Issue by poklin** [DevExpress/AjaxControlToolkit#465]
### The AJAX Control Toolkit \<VERSION\>
- v18.1.1.0
### The installation method
- [x] Installer

### Minimal steps to reproduce the bug
- Drag and drop tif files and click upload buttom

### Actual result
- Keep prompting OnClientUploadError for tif format, other formats are able to uploaded successfully

### Expected result
- Upload successfully for Tiff format

### Browser(s) used
- Google Chrome, Firefox, Edge

### A site deployment method
- [x] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @poklin 
Would you please check your Web.config and make sure that `tiff` and `tif` extensions are presented in the `additionalUploadFileExtensions` setting?
Here is the article that describes the syntax of the setting: 
[AjaxFileUpload setup/Allowed file extensions](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload-setup#allowed-file-extensions)

**Comment by MikhailTymchukDX** [comment]
@poklin Control's setting `AllowedFileTypes` is used to check for allowed extension on a client side, while Web.config setting is used to perform a check on a server side, so you need to add `tiff/tif` extensions in both places.

**Comment by poklin** [comment]
Ahh ic, Thanks for the info! 
Btw where should I insert it to? <ajaxControlToolkit additionalUploadFileExtensions="bmp,wav,tif,tiff" />
Within the <Web.server>"here"</Web.server>  ??? 

Thanks a lot bro!

**Comment by poklin** [comment]
Ok, now I understand. Thanks for the explanation !!!
