### ISSUE TITLE
AsyncFileUpload changes the frame target to "_top"

### ISSUE THREAD

**Issue by Ashvit** [DevExpress/AjaxControlToolkit#466]
### The installation method
 NuGet package

### Minimal steps to reproduce the bug

1. Create 2 WebForms (Main.aspx, Sub.aspx).
2. Add an asyncFileUpload and a button in the sub,aspx.
3. In main.aspx add a frame with src pointing to sub.aspx.
4. Run the code.
5. Select any file using choose file button.
6. Click the other button inside the frame.

### Actual result
The browser loads the sub.aspx page in the window.

### Expected result
the browser should load the main.aspx page in the window.

### Browser(s) used
Chrome, Firefox

**Comment by AlekseyMartynov** [comment]
Reproduced.

Before file select:
![before](https://user-images.githubusercontent.com/4426185/50396183-6052ff00-0779-11e9-8357-959d9716d9b8.png)

After file select:
![after](https://user-images.githubusercontent.com/4426185/50396188-63e68600-0779-11e9-982a-471439928813.png)

Related code:
https://github.com/DevExpress/AjaxControlToolkit/blob/62790ea2799e3c4e086bcefabb93e52b9ddd4cd9/AjaxControlToolkit/Scripts/AsyncFileUpload.js#L376

https://github.com/DevExpress/AjaxControlToolkit/blob/62790ea2799e3c4e086bcefabb93e52b9ddd4cd9/AjaxControlToolkit/Scripts/AsyncFileUpload.js#L503

https://github.com/DevExpress/AjaxControlToolkit/blob/62790ea2799e3c4e086bcefabb93e52b9ddd4cd9/AjaxControlToolkit/Scripts/AsyncFileUpload.js#L503
