### ISSUE TITLE
HTML Editor link option doesnt show buttons 

### ISSUE THREAD

**Issue by tcssistemas** [DevExpress/AjaxControlToolkit#47]
Hello! Im trying to use HTML Editor and adding new Link and the buttons doesnt show.
What can i do?
![htmlbuttons](https://cloud.githubusercontent.com/assets/18148729/14210340/f96a23f4-f7fe-11e5-820c-d33ffe39c0cd.jpg)

**Comment by MikhailTymchukDX** [comment]
@tcssistemas Would you please try using the modern [HtmlEditorExtender](http://ajaxcontroltoolkit.devexpress.com/HtmlEditorExtender/HtmlEditorExtender.aspx) instead of the legacy HtmlEditor?
