### ISSUE TITLE
AjaxFileUploadEventArgs ContextKeys

### ISSUE THREAD

**Issue by NXTwoThou** [DevExpress/AjaxControlToolkit#470]
Could AjaxFileUploadEventArgs have ContextKeys please?

I'm wanting to set a ContextKey in OnClientUploadStart that's actionable in OnUploadComplete

**Comment by AlekseyMartynov** [comment]
You can use a session cookie:

```js
function onClientUploadStart(sender, e) {
    document.cookie = "myValue=" + encodeURIComponent("a b c");
}
```

```c#
protected void AjaxFileUpload1_OnUploadComplete(object sender, AjaxFileUploadEventArgs file) {
    var myValue = HttpUtility.UrlDecode(HttpContext.Current.Request.Cookies["myValue"].Value);
}
```

Will this work in your case?

**Comment by NXTwoThou** [comment]
That works perfectly.  Thank you.  My searches online kept saying to use ContextKey(which of course doesn't work) or super hacky saving to session with ontextchanged/selectedindexchanged stuff.
