### ISSUE TITLE
AJajtoolkit creates a div for the collapsible panel with overflow:hidden

### ISSUE THREAD

**Issue by sharmila2388** [DevExpress/AjaxControlToolkit#475]
### The AJAX Control Toolkit \<VERSION\>
AjaxControlToolkit.18.1.1

ajax toolkit produces a div with overflow: hidden for the collapsible panel.

```xml
<asp:Panel ID="pHeaderBiolist" runat="server" CssClass="accordionHeaderSelected">
</asp:Panel>

<asp:Panel ID="pBodyBiolist" ScrollBars="None" runat="server" CssClass="accordionContent">
    <ej:Grid ID="grid1" runat="server">
        <ClientSideEvents ToolbarClick="toolbarClick"/>
    </ej:Grid>
</asp:Panel>

<ajaxToolkit:CollapsiblePanelExtender ID="collapsepanelbiolist" runat="server"
    TargetControlID="pBodyBiolist" CollapseControlID="pHeaderBiolist"
    ExpandControlID="pHeaderBiolist" CollapsedText="Open" Collapsed="true"
    ExpandedText="Close" CollapsedSize="0" ImageControlID="imgcollapsibleinst"
    CollapsedImage="~/Images/Collapsed.png"
    ExpandedImage="~/Images/Expanded.png"></ajaxToolkit:CollapsiblePanelExtender>
```

I have a grid with a page dropdown list inside the collapsepanelbiolist and the list is hidden when it is opened by the panel. On debugging, I saw that the panel is put inside a div created by the ajax toolkit with style overflow set to hidden.
Kindly let me know how to change it to overflow:visible or any other way to make the dropdown list visible.

**Comment by AlekseyMartynov** [comment]
Hello

Are you sure that `overflow: hidden` is the reason? As I understand it, the inner list has zero dimensions due to `display: none` of the collapsed panel.

Since you are using a 3rd party grid, I suggest that you consider using their collapsible component (accordion) for better interoperability.

**Comment by sharmila2388** [comment]
I have used Ajax collapsible extender panels in all my pages in the
application. In one of those panels, I have this grid with page drop down
list which is hiding since the collapsible extender creates a div wrapper
for that panel with overflow: hidden.

I cannot change all my panels now. That would be a lot of work. Kindly let
me know if a solution.

Please find the below link for further explanation of the issue.

https://mandrillapp.com/track/click/30209653/forums.asp.net?p=eyJzIjoiX09Oei0tZTVHUnN6dC1GcmZ4WG80YmVwM2RZIiwidiI6MSwicCI6IntcInVcIjozMDIwOTY1MyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2ZvcnVtcy5hc3AubmV0XFxcL3Bvc3RcXFwvNjI1NDMzOS5hc3B4XCIsXCJpZFwiOlwiYTQ1M2EwNTVlNGQzNDIzYjk2YjIzMjYzYmI2YTJkYTdcIixcInVybF9pZHNcIjpbXCJjYzZkM2M4ZDFiOGJhODcwMTgxM2EyZTU3NDRhYjhjZWEzODhkOWZhXCJdfSJ9

**Comment by AlekseyMartynov** [comment]
> I cannot change all my panels now. That would be a lot of work.

No need to change all panels. You can only change the panel that causes the issue.

---

Regarding the original question:

> Kindly let me know how to change it to overflow:visible or any other way to make the dropdown list visible.

Handle the extender's [client events](https://github.com/DevExpress/AjaxControlToolkit/wiki/CollapsiblePanelExtender#client-events-1) to manipulate style attributes.
For example:

```html
<ajaxToolkit:CollapsiblePanelExtender
    BehaviorID="Biolist_CollapsibleExtender"
    . . . />

<script>            
    Sys.Application.add_load(function() {
        var extender = $find("Biolist_CollapsibleExtender");
        extender.add_expanded(function(s) {
            s._childDiv.parentNode.style.overflowY = "visible";
        })
        extender.add_collapsing(function(s) {
            s._childDiv.parentNode.style.overflowY = "hidden";
        })
    });
</script>
```
However, without debugging the actual markup, it's not clear whether or not this will fix the dropdown list.

**Comment by sharmila2388** [comment]
I fixed this issue by using the function pageLoad() method and making the parent div of the Ajax panel overflow to visible inside that method. Thanks.
