### ISSUE TITLE
Does the ReorderList support model binding in Web Forms

### ISSUE THREAD

**Issue by SimpleSamples** [DevExpress/AjaxControlToolkit#476]
I am using AJAX Control Toolkit version 18.1. I forget the details of how I installed it except I am nearly certain I installed it from a website. I think I did however submit a comment for Microsoft suggesting they update their page saying how to get started with it and I think they did that surprisingly quickly.

Does the ReorderList support model binding in Web Forms? In particular, I mean the ItemType, SelectMethod and UpdateMethod attributes. Apparently it does, at least somewhat. The SelectMethod does get the data and the bindings work in the ItemTemplate. The problem is that the UpdateMethod is not called. I am able to do the drag and drop during execution but the update does not happen. It is possible that it is my fault but if it is then it would help to at least know that it should work.

I do have a complete sample web app showing the problem but I have difficulty getting Git and GitHub to cooperate. The following is one complete Content portion of an aspx page. As I said, the SelectMethod works but the UpdateMethod is not called.

```xml
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
	<asp:ScriptManager ID="ScriptManager1" runat="server" EnablePartialRendering="true" />
	<asp:UpdatePanel ID="UpdatePanel1" runat="server">
		<ContentTemplate>
			<div class="ReorderShowsDiv">
	<ajaxToolkit:ReorderList ID="ReorderShows" runat="server" PostBackOnReorder="false"
		DragHandleAlignment="Left" ItemInsertLocation="Beginning"
		DataKeyField="Id" CallbackCssStyle="callbackStyle"
		SortOrderField="ListIndex"
		ItemType="Web2017.OnDemandShow"
		SelectMethod="ReorderGetShows"
		UpdateMethod="ReorderUpdateShow">
		<ItemTemplate>
			<div class="itemArea">
				<%# Item.Name %>
			</div>
		</ItemTemplate>
		<ReorderTemplate>
	<asp:Panel ID="PanelReorder" runat="server" CssClass="reorderCue" />
	</ReorderTemplate>
	<draghandletemplate>
		<div class="dragHandle"></div>
	</draghandletemplate>
	</ajaxToolkit:ReorderList>
			</div>
		</ContentTemplate>
	</asp:UpdatePanel>
	<asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
	<asp:Label ID="LabelStatus" runat="server" Text="?" />
</asp:Content>
```

I apologize that the preceding code is not formatted correctly. What can I do to get it formatted?

**Comment by AlekseyMartynov** [comment]
As you correctly noted, only `SelectMethod` works because it's inherited from `DataBoundControl`. `UpdateMethod` requires explicit support, and is available starting with .NET 4.5. AJAX Control Toolkit is built against .NET 4.0.

That is, `ReorderList` cannot be used with WebForms model binding. Use `ObjectDataSource` as demonstrated in the [Sample site](https://github.com/DevExpress/AjaxControlToolkit/blob/18.1.1/AjaxControlToolkit.SampleSite/ReorderList/ReorderList.aspx).

P.S. I fixed the code formatting. Use [GitHub's triple backticks](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code) for code blocks.

**Comment by SimpleSamples** [comment]
Thank you. Using |ObjectDataSource| is an option. I almost have 
something working without drag-and-drop so I will continue with that.

At least now I am familiar with the AJAX Control Toolkit and I will 
learn more about it.
