### ISSUE TITLE
CascadingDropDown extender control continally refreshing in Firefox browser 65.0.1

### ISSUE THREAD

**Issue by RogerMCA** [DevExpress/AjaxControlToolkit#477]
### The installation method
- [ ] Installer

### Browser(s) used
IE, Edge, Chrome, Safari are okay, **Firefox 65.0.1 is not okay**.

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

I have been using the **CascadingDropDown** extender control for several years now in an ASP.NET web site using version 15.1.4

The scenario in which the control is used is like select Make of Car in first dropdown, then select Model in the second.

Just recently a user who prefers Firefox said the dropdown controls continually refresh several times a second as of about 22 Feb 2019 after Firefox updated to V65.0.1
They said it worked fine up until then. In fact he went to another PC with earlier version of Firefox and it worked, updated Firefox and the refreshing started.
I just downloaded the latest version of AjaxControlToolkit (v18.1.1) on my development system and it does the same thing.

I notice that while it is refreshing (several times a second) the IIS Express worker process is busy until the page is closed.

Works fine in other browsers such as IE, Edge, Chrome, Safari.

It would appear the problem is Firefox but I thought the issue should be raised here as well.

**Comment by AlekseyMartynov** [comment]
How to reproduce this?
I'm using Firefox, and the [CascadingDropDown demo](https://ajaxcontroltoolkit.devexpress.com/CascadingDropDown/CascadingDropDown.aspx) doesn't send any excessive requests.

**Comment by RogerMCA** [comment]
I agree the demo doesn’t produce the rapid refreshing and works as intended.

 

My implementation is much more complex than that reading a database and all wrapped up in a user control.

(It has been working for over 5 years – first complaint was when a user upgraded Firefox to 65.0.1)

 

My implementation uses:

<!DOCTYPE html>

In the master page which is the same as the CascadingDropDown demo <https://ajaxcontroltoolkit.devexpress.com/CascadingDropDown/CascadingDropDown.aspx>  uses.

 

When I get time, I shall strip the control down bit by bit until it works in an effort to identify the problem.

 

Kind Regards,

Roger.

**Comment by RogerMCA** [comment]
I did some testing and found it was the AutoPostBack property set to True on the DropDownList control, which I need, so have implemented a workaround for the time being.

Thanks for your response.

 

Kind Regards,

Roger.

 

 

 

I agree the demo doesn’t produce the rapid refreshing and works as intended.

 

My implementation is much more complex than that reading a database and all wrapped up in a user control.

(It has been working for over 5 years – first complaint was when a user upgraded Firefox to 65.0.1)

 

My implementation uses:

<!DOCTYPE html>

In the master page which is the same as the CascadingDropDown demo <https://ajaxcontroltoolkit.devexpress.com/CascadingDropDown/CascadingDropDown.aspx>  uses.

 

When I get time, I shall strip the control down bit by bit until it works in an effort to identify the problem.

 

Kind Regards,

Roger.

**Comment by flo-rider** [comment]
@RogerMCA: I have the EXACT same issue. Could you please post your workaround?

**Comment by manuelra** [comment]
That control has a special check for Opera and Safari which should also apply to Firefox. 
Try the following:


1. Add the AjaxControlToolkit.StaticResources nuget package to your project
2. Modify line of 340 of Scripts\AjaxControlToolkit\Debug\CascadingDropDown.debug.js

from
            `if (list && (Sys.Browser.agent !== Sys.Browser.Safari) && (Sys.Browser.agent !== Sys.Browser.Opera)) {`
to 
            `if (list && (Sys.Browser.agent !== Sys.Browser.Safari) && (Sys.Browser.agent !== Sys.Browser.Opera) **&& (Sys.Browser.agent !== Sys.Browser.Firefox)**) {`

3. Do a similar modification to the Release version of the same file.

**Comment by AlekseyMartynov** [comment]
@manuelra 
Thank you. I'm reopening the ticket.

**Comment by jordi1988** [comment]
As the author said it's because of the "AutoPostBack" property set to true. I replaced it with the following client script called onchange of the dropdown, which will simply do a postback when any value is selected:

`var lastId = null;
function doPostbackForDropDown(control) {
	if (!control) return;

	if (control.value != '' && lastId != control.value) {
		setTimeout('__doPostBack(\'' + control.name + '\',\'\')', 0);
		lastId = control.value;
	}
}`

Version used of ACT: 7.0607

**Comment by AlekseyMartynov** [comment]
To reproduce in the demo, remove `AsyncPostBackTrigger`:

```diff
--- a/AjaxControlToolkit.SampleSite/CascadingDropDown/CascadingDropDown.aspx
+++ b/AjaxControlToolkit.SampleSite/CascadingDropDown/CascadingDropDown.aspx
@@ -42,7 +42,6 @@
             <asp:Label ID="Label1" runat="server" Text="[No response provided yet]" />
         </ContentTemplate>
         <Triggers>
-            <asp:AsyncPostBackTrigger ControlID="DropDownList3" EventName="SelectedIndexChanged" />
         </Triggers>
     </asp:UpdatePanel>
 </asp:Content>
```

Then select a make and a model.

**Comment by AlekseyMartynov** [comment]
We fixed the issue in the `master` branch. Check the ['Updating the Project from CI Builds'](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) guide to learn how to update the project before an official AJAX Control Toolkit release is available.
