### ISSUE TITLE
AutoCompleteExtender not firing text change event in Edge

### ISSUE THREAD

**Issue by Pritish1989** [DevExpress/AjaxControlToolkit#478]
### The installation method
- [ ] NuGet package

### Minimal steps to reproduce the bug
a. Use a Ajax AutoCompleteExtender.
b. Fill the autocomplete textbox using a asmx call.
c. Once the data is selected from the autocomplete textbox the text changed event is not fired. This is only happening for Edge browser. Working correctly in chrome and IE.
### Actual result
Text Changed Event not fired.
### Expected result
Text Changed Event should be fired.
### Browser(s) used
Chrome
IE
Edge
### A site deployment method
- [ ] IIS

**Comment by Pritish1989** [comment]
To Add I see this being fixed as part of the following commit but I still see the issue with the above mentioned DLL version
https://github.com/DevExpress/AjaxControlToolkit/commit/3ce9d94975cd6f5baff57a07f906d93c9c0562f2

**Comment by AlekseyMartynov** [comment]
Please try a recent master build as described in [Updating the Project from CI Builds](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds).

**Comment by Pritish1989** [comment]
@AlekseyMartynov : I tried with a complete new project with no references to Ajax Control Kit what so ever but I am still facing the same issue. I took the DLL fresh from nuget. Please advise.

**Comment by AlekseyMartynov** [comment]
The [Updating the Project from CI Builds](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) article provides the detailed steps.
Have you tried to follow those instructions?

**Comment by Pritish1989** [comment]
@AlekseyMartynov : If I am understanding correctly the above mentioned step comes into handy when the official  version is not rolled out. But the Ajax Control Tool Kit latest version is rolled out and available in Nuget. So installing from Nuget won't suffice? Please advise. 

In mean time let me check the instructions.

**Comment by AlekseyMartynov** [comment]
> But the Ajax Control Tool Kit latest version is rolled out and available in Nuget.

The commit 3ce9d94 hasn't been released yet.

**Comment by Pritish1989** [comment]
@AlekseyMartynov : oh ok.. Thanks for the information.. When can we expect the changes going live?

**Comment by AlekseyMartynov** [comment]
At the moment, we don't have a scheduled date.
