### ISSUE TITLE
Period issue in HTML editor in FIrefox

### ISSUE THREAD

**Issue by EldokIssac** [DevExpress/AjaxControlToolkit#481]
### The installation method

- [x] NuGet package

### Minimal steps to reproduce the bug
Just type some text and at the end try to type some dots in firefox. 
### Actual result
The first period will appear without any issues and the remaining ones will not show up
### Browser(s) used
Firefox
### A site deployment method
- [x] VS development web-server,
- [x] IIS

**Comment by AlekseyMartynov** [comment]
Cannot reproduce in the [online demo](https://ajaxcontroltoolkit.devexpress.com/HtmlEditorExtender/HtmlEditorExtender.aspx) (Firefox 66).
