### ISSUE TITLE
Installer: support VS 2019

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/AjaxControlToolkit#482]
![2019](https://user-images.githubusercontent.com/4426185/57219541-1587a480-7001-11e9-9a75-6b328ffc8b60.png)

---

Workaround:
- [Install from NuGet](https://github.com/DevExpress/AjaxControlToolkit/wiki/Step-by-Step-Installation-Guide#nuget-package)
- [Manually register Toolbox items](https://github.com/DevExpress/AjaxControlToolkit/issues/314#issuecomment-287391322)

**Comment by AlekseyMartynov** [comment]
VSIX updated in https://github.com/DevExpress/AjaxControlToolkit/pull/489.
Now we are working on the Installer.

**Comment by bigbob556677** [comment]
@AlekseyMartynov  Has there been any progress made on this?

**Comment by AlekseyMartynov** [comment]
@bigbob556677 
Yes, we are about to release version 19.1 which will support VS 2019.

**Comment by bbibezic** [comment]
@bigbob556677,
any updates on 19.1 ?

**Comment by AlekseyMartynov** [comment]
[19.1.0 is released!](https://community.devexpress.com/blogs/aspnet/archive/2019/07/01/asp-net-ajax-control-toolkit-v19-1-0-now-available.aspx)
