### ISSUE TITLE
Ignore Whitelist

### ISSUE THREAD

**Issue by jmbroadway** [DevExpress/AjaxControlToolkit#484]
I'd like to ignore the fileupload extension whitelist.  I am aware of possible security implications and have taken appropriate steps.  Is there a way to do this?

**Comment by AlekseyMartynov** [comment]
Currently, there's no option to bypass the whitelist check. Possible solutions::
- Build a custom release from sources with these lines removed: https://github.com/DevExpress/AjaxControlToolkit/blob/18.1.1/AjaxControlToolkit/AjaxFileUpload/AjaxFileUploadHelper.cs#L58-L59
- Suggest end-users to upload ZIP archives (more secure).
