### ISSUE TITLE
Bootstrap and ModalPopupExtender

### ISSUE THREAD

**Issue by vanderrick** [DevExpress/AjaxControlToolkit#49]
When I use 
` PopupDragHandleControlID="P2"`
with
`            <asp:Panel ID="P1" runat="server" CssClass="panel panel-primary" Width="300px">
                <asp:Panel ID="P2" runat="server" class="panel-heading">
                    <h5 class="panel-title">This is a popup</h5>
                </asp:Panel>
                <div class="panel-body">
`
the dragging behaves erratically.  Eventually the panel disappears off the screen.

mostly it works well, so you are to be congratulated.  I appreciate what you've done for the ACT.  Still a good choice for those on a budget.

Van Derrick

**Comment by MikhailTymchukDX** [comment]
@vanderrick Would you please provide a video that shows this behavior?
You can use the [Jing tool](https://www.techsmith.com/jing.html) for this purpose.

**Comment by vanderrick** [comment]
No video.  Below’s the code, however it seems to be working now.  Maybe something got updated….
 
                    <ajaxToolkit:ModalPopupExtender ID="MPE" runat="server"
                        TargetControlID="HF1"
                        PopupControlID="P1"
                        DropShadow="True" CancelControlID="DismissBT" PopupDragHandleControlID="P2">
                    </ajaxToolkit:ModalPopupExtender>
                    <asp:HiddenField ID="HF1" runat="server" />
                    <asp:Panel ID="P1" runat="server" CssClass="panel panel-primary" Width="300px">
                        <asp:Panel ID="P2" runat="server" CssClass="panel-heading">
                            <h5 class="panel-title">This is a popup</h5>
                        </asp:Panel>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="popupNameTB">Name</label>
                                <asp:TextBox ID="popupNameTB" runat="server" CssClass="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="popupPhoneTB">Phone</label>
                                <asp:TextBox ID="popupPhoneTB" runat="server" CssClass="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="popupAddressTB">Address</label>
                                <asp:TextBox ID="popupAddressTB" runat="server" CssClass="form-control"></asp:TextBox>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <asp:Button ID="DismissBT" runat="server" Text="Dismiss" CssClass="btn btn-primary" />
                            <asp:Button ID="SubmitBT" runat="server" Text="Submit" CssClass="btn btn-primary" OnClick="SubmitBT_Click" />
                        </div>
                    </asp:Panel>

**Comment by MikhailTymchukDX** [comment]
Which version of the AJAX Control Toolkit do you use with that markup?

**Comment by vanderrick** [comment]
16.1.0.0.  Well, that’s the version I’m using now.  It’s quite possible the original version was 15.

**Comment by MikhailTymchukDX** [comment]
I cannot reproduce this issue using the markup you provided.
Would you please attach a sample project that illustrates this issue?

**Comment by vanderrick** [comment]
appears to be working now.
