### ISSUE TITLE
Strange Behvaiour With OnItemInserted in ComboBox

### ISSUE THREAD

**Issue by JamesonRGrieve** [DevExpress/AjaxControlToolkit#490]
### The AJAX Control Toolkit 18.1.1

Just a note, this may not be a bug and might just be me making an error that's obvious to anyone else. If that's the case, I apologize, and if you could offer guidance on fixing the error that would be much appreciated.

### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
When modifying the contents of another combobox when inserting into one, it throws a ArgumentOutOfRangeException regarding the selected index not existing.

In the sample solution, insert an item into the manufacturer combobox, I used Chevrolet. 

### Actual result
![Error](https://user-images.githubusercontent.com/37882431/59308071-4e004b00-8c5d-11e9-97f5-b438ab2bef22.PNG)

Upon hitting enter and tab, the page posts back and crashes.

### Expected result
The page should post back with a cleared second dropdown, with the new item which was created in the code selected. As a note, pushing the button displays the desired behaviour, and the only line of code in the OnItemInserted event method is to call the button click method.

### Browser(s) used
Chrome

### A site deployment method
- [x] VS development web-server,
- [ ] IIS

[SampleProject.zip](https://github.com/DevExpress/AjaxControlToolkit/files/3278630/SampleProject.zip)

Thank you for any help you can provide.

**Comment by AlekseyMartynov** [comment]
The `ComboBox_Manufacturer_ItemInserted` handler is raised at the `LoadPostData` stage of the [WebForms page lifecycle](https://www.tutorialspoint.com/asp.net/asp.net_life_cycle.htm). Effectively it means that you clear the `ModelName` items just before the framework applies its current selected index (`Fiesta=1`).

Use a boolean flag and clear the list on `Page_Load` when the page state is fully restored:

```c#
bool manufacturerHasChanged;

protected void Page_Load(object sender, EventArgs e) {
    if(!Page.IsPostBack) {
        ComboBox_Manufacturer.SelectedIndex = 0;
        ComboBox_ModelName.SelectedIndex = 1;
    }

    if(manufacturerHasChanged)
        ResetModelNames();
}

protected void TestButton_Click(object sender, EventArgs e) {
    ResetModelNames();
}

protected void ComboBox_Manufacturer_ItemInserted(object sender, ComboBoxItemInsertEventArgs e) {
    manufacturerHasChanged = true;
}

void ResetModelNames() {
    ComboBox_ModelName.Items.Clear();
    ComboBox_ModelName.Items.Add(new ListItem("Enter a new model...", "seed"));
    ComboBox_ModelName.SelectedIndex = 0;
}
```
