### ISSUE TITLE
Migrating Web Project From VS2010 to VS2015 and updgrading Devexpress version from 10.1 to 18.1.

### ISSUE THREAD

**Issue by SunilSBI** [DevExpress/AjaxControlToolkit#491]
### The AJAX Control Toolkit \<VERSION\>
AjaxControlToolkit.Binary.NET45

### The installation method
- [x] Installer

Hello,

I have an web application which is currently running on VS2010 and having Devexpress version 10.1.Now I am converting VS2010 to VS2015 and updgrading Devexpress version 10.1 to 18.1.

But my conversion process throwing below mentioned error:

a) The name 'ToolkitScriptManager' does not exist in the current context.

Devexpress support team suggested me to try below link:
https://stackoverflow.com/questions/28165184/the-type-or-namespace-name-toolkitscriptmanager-does-not-exist-in-the-namespac

But I think it is not helpful/working.

I tried several things but could not find anything which help me to solve this problem.
Please provide me solution against above mentioned issue. 

Thanks

**Comment by AlekseyMartynov** [comment]
Please follow the [Migration Guide](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below) to upgrade your project.
Section 2 specifically addresses the `ToolkitScriptManager` issue.

**Comment by SunilSBI** [comment]
Hello, 
Thanks for your quick help!

I did the same actions what you suggested, but still I am getting below errors:
a) Error Unknown server tag 'ajax:Pager'.			
b) Error Unknown server tag 'ajax:Grid'.

I have also attached Ajax issues image with my comment.
Please look into it and let me know what changes I need to do now.

Thanks
![AjaxIssues](https://user-images.githubusercontent.com/51921422/59765838-92729300-92bc-11e9-9607-2b3452221cbc.jpg)

**Comment by AlekseyMartynov** [comment]
There are no such components in the Toolkit (`Grid`, `Pager`).

Chances are that your project uses a custom Toolkit build because `10.1` isn't a known version.
Official version history:
- `7.1213.0 `
- `8.0.0 `
- `15.1.2 `
