### ISSUE TITLE
Trying to install AjaxControlToolkit Using an Old VS 2008 with .Net Framework 3.5

### ISSUE THREAD

**Issue by rafaeltangari** [DevExpress/AjaxControlToolkit#492]
Hi, 

I am trying to download AJAXControlToolkit from DevExpress web site. However, I am running Visual Studio 2008 Professional and I cannot upgrade this software. 

When I try to run the setup wizard from DevExpress, tells me that Visual Studio could not be found. How can I install AjaxControlToolkit running my old Visual Studio 2008? 

PS: I am running .NET Framework 3.5, as well. Thanks!

**Comment by AlekseyMartynov** [comment]
Hello

Since version 15.1, AJAX Control Toolkit [minimum requirements are .NET 4.0 and VS 2010](https://github.com/DevExpress/AjaxControlToolkit/wiki#system-requirements). For compatibility with .NET 3.5, use [version 7.x from NuGet](https://www.nuget.org/packages/AjaxControlToolkit/7.1213.0).
