### ISSUE TITLE
MaskedEditExtender with ClearMaskOnLostFocus=False adds extra character at first position

### ISSUE THREAD

**Issue by dannyOS35** [DevExpress/AjaxControlToolkit#493]
### The AJAX Control Toolkit 
Version 18.1.1

### The installation method

NuGet package

### Minimal steps to reproduce the bug
1. On Visual Studio 2013 create a Windows Form App

2. Create a ASP.NET Web Application

3. Add a Textbox

4. Add MaskedEditExtender to that Textbox

5. For that MaskedEditExtender use settings like these:
<ACT:MaskedEditExtender ID="MaskedEditExtender1" runat="server" TargetControlID="TextBoxID" Mask="09-9999-9999"
ClearMaskOnLostFocus="false" AutoComplete="true" InputDirection="LeftToRight"/>

6. Run the application.

7. Click inside and outside the TextBox

8. Perform something that call a PostBack

### Actual result
When one clicks inside and outside the TextBox, the mask adds an extra character. This same behaviour is presented when a PostBack is performed.

### Expected result
No extra character must be added on these situations.

### Browser(s) used
Chrome
Edge
[WebApplication_Mascara.zip](https://github.com/DevExpress/AjaxControlToolkit/files/3335890/WebApplication_Mascara.zip)

**Comment by AlekseyMartynov** [comment]
We fixed the issue in the `master` branch. Check the ['Updating the Project from CI Builds'](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) guide to learn how to update the project before an official AJAX Control Toolkit release is available.

**Comment by dannyOS35** [comment]
Thanks for your attention on this issue. We really appreciate it.
