### ISSUE TITLE
ListSearch Extender FireFox v66+

### ISSUE THREAD

**Issue by TheUlderico** [DevExpress/AjaxControlToolkit#494]
### The AJAX Control Toolkit 17.1.1
(checked the source code for current version and the code is the same)

### The installation method
- [x] A custom build from the source code

### Minimal steps to reproduce the bug
Setup a page List search extender
Open this page in Firefox version 66 or higher
Start typing into the control associated with this list search extender

### Actual result
Nothing is added into the search window and no search is triggered

### Expected result
Typed characters are added to the search window and search is triggered

### Browser(s) used
Firefox - problem since version 66

### A site deployment method
- [x] IIS

We have encountered an issue related to the List search extender, where the search would not work in Firefox. After quick investigation, we have found that the problems starts to occur in versions 66 or higher. 

After checking the source code and small bug-testing, we have found that the issue is located in the file ListSearch.js and more precisely in function called "_isNormalChar". The first if statement in this function is related to the Firefox. If we check the Firefox release notes, we can find that in version 66, there were some changed to the handling of .keyCode and .charCode properties (more on https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66 - Dom events section).

This changed prevents List search extender from working in Firefox v66 or higher.

We are currently working with a workaround with checking the version of Firefox to be lower that 66 in this if statement to support both newer and older versions of this browser.

Thanks for your time.
Ulderico

**Comment by AlekseyMartynov** [comment]
Thanks for reporting.

> We are currently working with a workaround with checking the version of Firefox to be lower that 66

Would you please share this code? We'll include it in the upstream version.

**Comment by TheUlderico** [comment]
We added a check to the version of the browser.
`if (Sys.Browser.agent == Sys.Browser.Firefox && Sys.Browser.version < 66 && e.rawEvent.keyCode)`
The thing is, I'm not 100% sure if adding this does not break this check as a whole in FF. I get what this function tries to achieve, the logic behind it is not 100% clear to me (as I haven't studied it in the detail).

**Comment by AlekseyMartynov** [comment]
We fixed the issue in the `master` branch. Check the ['Updating the Project from CI Builds'](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) guide to learn how to update the project before an official AJAX Control Toolkit release is available.
