### ISSUE TITLE
ValidatorCalloutExtender loses position when validating input box with HtmlEditorExtender

### ISSUE THREAD

**Issue by wilcora** [DevExpress/AjaxControlToolkit#497]
### The installation method
- [ ] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Add update panel.
Add content tag.
add div tags with bootstrap  column/row css tags.
add asp input control
add required field validator
add validator call out extender
add html editor extender

### Actual result
Validator call out pops up in upper left of web page. Its X & Y values are set to a negative value. 
![issue](https://user-images.githubusercontent.com/54113991/63041449-c6150800-be7c-11e9-9f18-6f5964dc371b.jpg)

### Expected result
To pop up next to the editable div tag created by the Html editor extender
### A site deployment method
- [X] VS development web-server,
- [ ] IIS
![issue](https://user-images.githubusercontent.com/54113991/63041547-f8bf0080-be7c-11e9-8910-1b78525f16a3.jpg)

**Comment by AlekseyMartynov** [comment]
Thanks for reporting.
Would you please attach a project that reproduces the issue?
Specifically, I'm interested in the Bootstrap columns/rows configuration.
