### ISSUE TITLE
AnimationExtender causing Build to fail when moving source to another PC

### ISSUE THREAD

**Issue by rezgeek** [DevExpress/AjaxControlToolkit#498]
### The AJAX Control Toolkit \<VERSION\>
19.1
### The installation method
- [X] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug

Create a new VS 2019 project. Add an AnimationExtender for a web form. Build the project. Works fine. Now copy and move the source code to another PC. Try to Build the project. The Build will fail. See error below.

### Actual result

Build failure.

![devex-build-fail](https://user-images.githubusercontent.com/54370816/63452406-d47a9b00-c40b-11e9-9ac5-8847fe50a59e.jpg)

Workaround: The only workaround I have discovered for this issue is to add and remove another AnimationExtender to the project after the source is copied from one PC to another. I have verified both PCs and running the same version of VS 2019 and the same most current version of Ajax Control Toolkit.

### Expected result

Sucessful Build.

### Browser(s) used
Firefox
### A site deployment method
- [ ] VS development web-server,
- [X] IIS

**Comment by rezgeek** [comment]
The issue could apply to the Ajax Control Toolkit as a whole and not be limited to the AnimationExtender.

**Comment by AlekseyMartynov** [comment]
The `AjaxControlToolkit.dll` reference that is automatically added by dragging a control from the Toolbox has a machine-dependent `HintPath`. For example:

```xml
<Reference Include="AjaxControlToolkit, Version=19.1.0.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e, processorArchitecture=MSIL">
  <SpecificVersion>False</SpecificVersion>
  <HintPath>..\..\..\..\Documents\ASP.NET AJAX Control Toolkit\Bin\AjaxControlToolkit.dll</HintPath>
</Reference>
```

For portability, use the [NuGet package](https://github.com/DevExpress/AjaxControlToolkit/wiki/Step-by-Step-Installation-Guide#nuget-package).

NuGet doesn't register Toolbox items, however, you can register them manually as described in https://github.com/DevExpress/AjaxControlToolkit/issues/314#issuecomment-287391322.
