### ISSUE TITLE
AjaxFileUpload - Cannot deserialize. The data does not correspond to valid JSON.

### ISSUE THREAD

**Issue by GohKA** [DevExpress/AjaxControlToolkit#499]
I am using AjaxFileUpload from AjaxControlToolkit V18.1.

I programmatically embed AjaxFileUpload in Panel which is in UpdatePanel which is in Panel that is called up by ModalPopupExtender.
I have a ghost AjaxFileUpload outside the UpdatePanel.

I got this error in the browser console when I try to upload a file.

Error: Sys.ArgumentException: Cannot deserialize. The data does not correspond to valid JSON. Parameter name: data

Please advise what could I miss out.

[Files.zip](https://github.com/DevExpress/AjaxControlToolkit/files/3549786/Files.zip)

**Comment by AlekseyMartynov** [comment]
Hello

It is problematic for me to reproduce the problem because the attached ASPX page depends on external code. I'll be happy to help debug if you attach a project that I can compile and run on my side.

**Comment by GohKA** [comment]
Dear Sir,
Please find the test files and the screenshot error attached.
Thank you.


    On Thursday, 29 August 2019, 6:19:13 pm SGT, AlekseyMartynov <notifications@github.com> wrote:  
 
 
Hello

It is problematic for me to reproduce the problem because the attached ASPX page depends on external code. I'll be happy to help debug if you attach a project that I can compile and run on my side.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using AjaxControlToolkit;

namespace ITE.SIC.AwardNominationSystem.View
{
    public partial class Test : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void CallFileUploadButtonButton_Click(object sender, EventArgs e)
        {
            fileAjaxFileUploadPanel.Controls.Clear();
            AjaxFileUpload fileAjaxFileUpload = new AjaxFileUpload();
            fileAjaxFileUpload.ID = "fileAjaxFileUpload";
            //fileAjaxFileUpload.AllowedFileTypes = "vnd.ms-excel";
            fileAjaxFileUpload.MaximumNumberOfFiles = 1;
            fileAjaxFileUpload.CssClass = "textblacknormal13";
            fileAjaxFileUpload.UploadComplete += new EventHandler<AjaxFileUploadEventArgs>(GhostAjaxFileUpload_UploadComplete);
            fileAjaxFileUpload.OnClientUploadComplete = "uploadFileComplete";
            fileAjaxFileUploadPanel.Controls.Add(fileAjaxFileUpload);

            okButton.Attributes.Add("disabled", "disabled");
            fileAjaxFileUploadUpdatePanel.Update();
            selectFileModalPopupExtender.Show();
        }

        protected void GhostAjaxFileUpload_UploadComplete(Object sender, AjaxFileUploadEventArgs e)
        {
        }

        protected void OkButton_Click(object sender, EventArgs e)
        {
        }
    }
}

**Comment by GohKA** [comment]
Dear Sir,

Attached.

[Test.zip](https://github.com/DevExpress/AjaxControlToolkit/files/3557844/Test.zip)

**Comment by GohKA** [comment]
Dear AlekseyMartynov,

Is there any update on this?

**Comment by AlekseyMartynov** [comment]
I created a project based on the source code from Test.zip.

The error occurs when the AjaxFileUpload script tries to parse the AJAX response:

![](https://user-images.githubusercontent.com/4426185/64120126-127ca500-cda4-11e9-9f4e-eb03bb56cd76.png)

`xhr.responseText` contains full page markup instead of JSON. This happens because the AjaxFileUpload control is not added to the Page hierarchy during the file upload process thus it cannot [intercept requests](https://github.com/DevExpress/AjaxControlToolkit/blob/19.1.0/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs#L252-L266).

If I change the code as follows then the error disappears:

```c#
protected void Page_Load(object sender, EventArgs e)
{
    fileAjaxFileUploadPanel.Controls.Clear();
    AjaxFileUpload fileAjaxFileUpload = new AjaxFileUpload();
    fileAjaxFileUpload.ID = "fileAjaxFileUpload";
    //fileAjaxFileUpload.AllowedFileTypes = "vnd.ms-excel";
    fileAjaxFileUpload.MaximumNumberOfFiles = 1;
    fileAjaxFileUpload.CssClass = "textblacknormal13";
    fileAjaxFileUpload.UploadComplete += new EventHandler<AjaxFileUploadEventArgs>(GhostAjaxFileUpload_UploadComplete);
    fileAjaxFileUpload.OnClientUploadComplete = "uploadFileComplete";
    fileAjaxFileUploadPanel.Controls.Add(fileAjaxFileUpload);
}

protected void CallFileUploadButtonButton_Click(object sender, EventArgs e)
{
    okButton.Attributes.Add("disabled", "disabled");
    fileAjaxFileUploadUpdatePanel.Update();
    selectFileModalPopupExtender.Show();
}
```

**Comment by GohKA** [comment]
Dear AlekseyMartynov,

It is working now after applying your changes.

Thank you so much.
