### ISSUE TITLE
AjaxFileUpload JSON error when used in Gridview - Formview Master - Detail

### ISSUE THREAD

**Issue by DeanMc67** [DevExpress/AjaxControlToolkit#50]
I have a GridView with an SQLdatasource, and a FormView with an SQLdatasource. On selection from the GridView the FormView displays the correct details. - All simple stuff.

If I then put an AjaxFileUpload control in the FormView, I get the following error when I click the upload button:

0x800a139e - JavaScript runtime error: Sys.ArgumentException: Cannot deserialize. The data does not correspond to valid JSON.

Parameter name: data    

How do I use an AjaxFileUpload in a detail Formview?

Here is a simple page to show the issue:

      <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ContactID" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="ContactID" HeaderText="ContactID" InsertVisible="False" ReadOnly="True" SortExpression="ContactID" />
                <asp:BoundField DataField="FullName" HeaderText="FullName" ReadOnly="True" SortExpression="FullName" />
            </Columns>
        </asp:GridView>

        <hr />

        <asp:FormView ID="FormView1" runat="server" DataSourceID="SqlDataSource2" DefaultMode="Edit">
            <EditItemTemplate>
                <ajaxToolkit:AjaxFileUpload ID="AjaxFileUpload1" runat="server" OnUploadComplete="AjaxFileUpload1_UploadComplete" />
                FirstName:
                <asp:TextBox ID="FirstNameTextBox" runat="server" Text='<%# Bind("FirstName") %>' />
                <br />
                LastName:
                <asp:TextBox ID="LastNameTextBox" runat="server" Text='<%# Bind("LastName") %>' />
                 <br />
                <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" />
                &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
            </EditItemTemplate>
         
        </asp:FormView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TheConnectionString %>" SelectCommand="SELECT [ContactID], [FullName] FROM [Contacts]"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:TheConnectionString %>" SelectCommand="SELECT [FirstName], [LastName] FROM [Contacts] WHERE ([ContactID] = @ContactID)">
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="ContactID" PropertyName="SelectedValue" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>

**Comment by MikhailTymchukDX** [comment]
We were unable to reproduce this behavior.
Would you please provide a sample project that illustrates this issue?

**Comment by DeanMc67** [comment]
Hi

I have made a new project, but it works fine.

What should I be looking for in my existing project that may be causing this issue?

I have attached a screen shot of the error.

[cid:image001.png@01D1900E.4446AF40]

**Comment by DeanMc67** [comment]
Hi

Please find attached a sample project showing this issue

Cheers

Dean

**Comment by MikhailTymchukDX** [comment]
A static `AjaxFileUpload._contextKeys` dictionary was added in v15.1.3 ([833fa33c](https://github.com/DevExpress/AjaxControlToolkit/commit/833fa33c)) to track events of several AjaxFileUploads.
This dictionary is filled in the `OnLoad` event handler with the `ClientID` value of a particular `AjaxFileUpload` instance. This means that every `AjaxFileUpload` must be rendered by default to keep this dictionary filled.

However, when you use `FormView`, it is not rendered by default, but is shown conditionally after selecting a record in `GridView`. This means that every POST request performed by client code recreates an `AjaxFileUpload` object along with the dictionary, but it does not contain FormView's ClientID.

There are two workaround options at the moment:
1. Downgrade to v15.1.2 or below.
2. Render `AjaxFileUpload` outside the `FormView`, but hide it with `style="display: none"`. In that case, server code will work correctly.

Please try either of this approaches and let me know your results.

**Comment by DeanMc67** [comment]
Thanks for the update.

I have worked around this by doing the following;


1)    Set a default value (ID=1) to the FormView’s SqlDataSource select parameter

2)    Added a .Hide and .Show CSSclass

3)    Made the FormView’s CSSclass “Hide”

4)    On GridView SelectedIndexChanged (We’ve made a selection) I change the FormView’s CSSclass to “Show”

Is this issue likely to be “fixed”, or is this behaviour now by design?

Cheers

Dean

**Comment by DeanMc67** [comment]
Just to let you know, I downgraded to 15.1.2 and the issue still occurs...

**Comment by MikhailTymchukDX** [comment]
>Just to let you know, I downgraded to 15.1.2 and the issue still occurs...

Right, v15.1.2 code seems to be in intermediate state - client code sends a control's ID to the server, but the server does not process it.
v15.1.1 works with the FormView without errors.

>Is this issue likely to be “fixed”, or is this behaviour now by design?

We will try to make the control's client ID "persistent" to avoid such situations, but we cannot guarantee this approach will work.
