### ISSUE TITLE
AjaxFileUpload fails with <sessionState cookieless="UseUri">

### ISSUE THREAD

**Issue by GEM-134-MiniGun** [DevExpress/AjaxControlToolkit#500]
### The installation method
- [ ] NuGet package

### Minimal steps to reproduce the bug
Dear Support,

I use a too old version of the AjaxControlToolkit (4.5.7.1213), which works with the switch of the sessionState of the cookieless="UseUri". 
I had upgraded to 19.1.0.0 version, but the file upload doesn't work, because control calls this URL: "http://[Server]/AjaxFileUploadHandler.axd?...". The answer for this call is Http 302. 
The next request also calls this URL: "http://[server]/[new session]/AjaxFileUploadHandler.axd?...", but in this case it generate a new session and the header is incorrect, and the response to the requset is http 500.

Part of the web.config file
`<sessionState timeout="60" mode="InProc" cookieless="UseUri" regenerateExpiredSessionId="true" />`

Old version 4.5.7
![kép](https://user-images.githubusercontent.com/55050920/64488773-1731d500-d24c-11e9-9869-675194ff549d.png)

![kép](https://user-images.githubusercontent.com/55050920/64488778-2dd82c00-d24c-11e9-97bf-cb79781324f9.png)

Version 19.1 Call stack
![kép](https://user-images.githubusercontent.com/55050920/64488665-c79ed980-d24a-11e9-9f02-6543b6858f92.png)

![kép](https://user-images.githubusercontent.com/55050920/64488696-fcab2c00-d24a-11e9-873c-7ea3d8e705f8.png)

![kép](https://user-images.githubusercontent.com/55050920/64488703-19dffa80-d24b-11e9-86d7-4155dba411b6.png)

![kép](https://user-images.githubusercontent.com/55050920/64488714-3c721380-d24b-11e9-99f0-2954b40d89a2.png)

Thank you the help.

### Browser(s) used
I tested:
- Firefox 69.0 (64 bit)
- Chrome 76.0.3809.132 (64 bit)
### A site deployment method
- [ ] VS development web-server,

**Comment by AlekseyMartynov** [comment]
We fixed the issue in the `master` branch. Check the ['Updating the Project from CI Builds'](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) guide to learn how to update the project before an official AJAX Control Toolkit release is available.
