### ISSUE TITLE
Could not load control AjaxControlToolkit.TabContainer

### ISSUE THREAD

**Issue by saladi79** [DevExpress/AjaxControlToolkit#501]
We have a website which was using ajaxcontoltoolkit from last 5 years. Not found any issues with toolkit from last 5 years. But getting below exception from last 15 days. Do not know why it is giving errors suddenly. Any help appreciated

Exception information: 
    Exception type: Exception 
    Exception message: Could not load control AjaxControlToolkit.TabContainer. The script reference(s) of this control was not loaded correctly. If AjaxControlToolkit.config is used, probably this control is not registered properly.
   at AjaxControlToolkit.ToolkitScriptManager.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by AlekseyMartynov** [comment]
The presence of `AjaxControlToolkit.ToolkitScriptManager` in the call stack indicates that you are using an old version of the Toolkit. The `ToolkitScriptManager` object has been [removed in v15.1](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below#2---replace-toolkitscriptmanager-with-scriptmanager).

If you are upgrading to a new Toolkit version, check the [Upgrading from v7.x and below](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below) document.
