### ISSUE TITLE
Reorder adds the Opacity property to the LI

### ISSUE THREAD

**Issue by Eric-Burdo** [DevExpress/AjaxControlToolkit#503]
### The installation method
- [ ] Installer
- [ x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Your demo has this issue:   http://www.ajaxtoolkit.net/ReorderList/ReorderList.aspx

1. Look at the run-time styling for the LI elements.
2. Reorder the LI elements.
3. There are now opacity and z-index styling added to the changed LI.

### Actual result
Styling for opacity: 0.999 and z-index: 0 gets added.

### Expected result
There shouldn't be any styling added.

### Browser(s) used
Chrome

### A site deployment method
- [ ] VS development web-server,
- [ x] IIS

**Comment by Eric-Burdo** [comment]
This appears to be on the onDragEnd event on the DropWatcher.js file
- If you set opacity 0.999 then a "floating menu" doesn't appear properly (I didn't attach an example).

**Comment by AlekseyMartynov** [comment]
We fixed the issue in the `master` branch. Check the ['Updating the Project from CI Builds'](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) guide to learn how to update the project before an official AJAX Control Toolkit release is available.
