### ISSUE TITLE
FIPS compliance with AjaxControlToolkit

### ISSUE THREAD

**Issue by swplok** [DevExpress/AjaxControlToolkit#504]
### The AJAX Control Toolkit 4.1.50927

I am looking for any information which could help me understand whether AjaxControlToolkit is FIPS compliant.

**Comment by AlekseyMartynov** [comment]
Relevant StackOverflow thread:
https://stackoverflow.com/a/33356819

**Comment by swplok** [comment]
The article is too general and deals with general functionality in the FIPS environment. My interest is more focused on the AjaxControlToolkit component and its FIPS compliance.
If I use the toolkit in my app in the FIPS environment can I claim my app FIPS compliant?

**Comment by AlekseyMartynov** [comment]
Two AJAX Control Toolkit components use `System.Security.Cryptography`:

- https://github.com/DevExpress/AjaxControlToolkit/blob/02be68ae0dc71eade6d47b846f50a99ace1f7110/AjaxControlToolkit/Gravatar/Gravatar.cs#L130

- https://github.com/DevExpress/AjaxControlToolkit/blob/dd212e9a4121be06fb9c8bb66c7b4a436de13476/AjaxControlToolkit/Twitter/TwitterAPI.cs#L113-L115

`MD5CryptoServiceProvider` is **not** FIPS compliant. The `Gravatar` component will throw in a FIPS-enabled environment. Other Toolkit code doesn't directly use any crypto algorithms.
