### ISSUE TITLE
MaskedEditExtender Delete,  BackSpace not working on Chrome

### ISSUE THREAD

**Issue by wveinti** [DevExpress/AjaxControlToolkit#505]
Hi I'm using the latest version off the AJAX Control Toolkit, added to my project via Nuget. The delete and back button do not work on the textbox on Google Chrome
Please help.. thanks!

### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### A site deployment method
- [ ] VS development web-server,
- [x] IIS

**Comment by AlekseyMartynov** [comment]
Hello
I cannot reproduce the problem in the [online demo](https://ajaxcontroltoolkit.devexpress.com/MaskedEdit/MaskedEdit.aspx) (Chrome 77, Windows).
