### ISSUE TITLE
Sys.WebForms.Res is undefined

### ISSUE THREAD

**Issue by dupuis2387** [DevExpress/AjaxControlToolkit#514]
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Actual result
Sys.WebForms.Res is undefined

### Expected result
Sys.WebForms.Res to be defined and look like 

```
Sys.WebForms.Res = {
                "PRM_MissingPanel": "Could not find UpdatePanel with ID \u0027{0}\u0027. If it is being updated dynamically then it must be inside another UpdatePanel.",
                "PRM_ServerError": "An unknown error occurred while processing the request on the server. The status code returned from the server was: {0}",
                "PRM_ParserError": "The message received from the server could not be parsed.",
                "PRM_TimeoutError": "The server request timed out.",
                "PRM_CannotRegisterTwice": "The PageRequestManager cannot be initialized more than once.",
                "PRM_UnknownToken": "Unknown token: \u0027{0}\u0027.",
                "PRM_MissingPanel": "Could not find UpdatePanel with ID \u0027{0}\u0027. If it is being updated dynamically then it must be inside another UpdatePanel.",
                "PRM_ServerError": "An unknown error occurred while processing the request on the server. The status code returned from the server was: {0}",
                "PRM_ParserError": "The message received from the server could not be parsed. Common causes for this error are when the response is modified by calls to Response.Write(), response filters, HttpModules, or server trace is enabled.\r\nDetails: {0}",
                "PRM_TimeoutError": "The server request timed out.",
                "PRM_ParserErrorDetails": "Error parsing near \u0027{0}\u0027.",
                "PRM_CannotRegisterTwice": "The PageRequestManager cannot be initialized more than once."
            };
```

### Browser(s) used
Google chrome

### A site deployment method
- [X] VS development web-server,
- [ ] IIS

I'm not sure if this falls onto the AjaxControlToolkit project or if this project is separate from MicrosoftAjaxWebForms.js, but looking at earlier versions of the entire webforms ajax "sdk" here https://forums.asp.net/t/1761042.aspx?Sys+WebForms+PageRequestManagerParserErrorException+ it seems that Sys.WebForms.Res used to be defined *somewhere*, but though i have what's in the screenshot
![AjaxScreenshot](https://user-images.githubusercontent.com/5150289/70377270-9af96d00-18e0-11ea-8f21-07ab788d5083.PNG)
Sys.WebForms.Res doesn't seem to be defined anywhere. 

I'm also using Microsoft.ReportingServices.ReportViewerControl.WebForms.150.900.148 if it makes a difference. So, I'm just really confused. 

Do i have a bad AjaxControlToolkit  install? 
A bad Microsoft.AspNet.ScriptManager.MSAjax.5.0.0/Microsoft.ScriptManager.MSAjax.dll install?
A bad Microsoft.AspNet.ScriptManager.WebForms.5.0.0\lib\net45\Microsoft.ScriptManager.WebForms.dll install?
Or a bad .NETFramework\v4.6.1\System.Web.Extensions.dll install?

This is on .Net Framework 4.6.1 and maybe that's my problem? outdated, cross pollinating things exploding?

For what it's worth, i only came across this because my ajax request was taking too long and the framework was spitting a **_createPageRequestManagerTimeoutError** inside **MicrosoftAjaxWebForms.js** and was trying to execute 

_"Sys.WebForms.PageRequestManagerTimeoutException: "+Sys.WebForms.Res.PRM_TimeoutError_ 

but with **Sys.WebForms.Res** being undefined, kaboom.

**Comment by AlekseyMartynov** [comment]
It is a bug in the `Microsoft.ScriptManager.MSAjax` package. The `Sys.WebForms.Res` object is missing from Scripts/WebForms/MSAjax/MicrosoftAjax.js. 

As a workaround, add the following script to the bottom of the page (or a master page):

```html
<script>
    Type.registerNamespace('Sys.WebForms');
    Sys.WebForms.Res={
        "PRM_UnknownToken":"Unknown token: \u0027{0}\u0027.",
        "PRM_MissingPanel":"Could not find UpdatePanel with ID \u0027{0}\u0027. If it is being updated dynamically then it must be inside another UpdatePanel.",
        "PRM_ServerError":"An unknown error occurred while processing the request on the server. The status code returned from the server was: {0}",
        "PRM_ParserError":"The message received from the server could not be parsed.",
        "PRM_TimeoutError":"The server request timed out.",
        "PRM_ParserErrorDetails":"Error parsing near \u0027{0}\u0027.",
        "PRM_CannotRegisterTwice":"The PageRequestManager cannot be initialized more than once."
    };
</script>
```

Alternatively:
- Uninstall the `Microsoft.AspNet.ScriptManager.MSAjax` package
- Delete the `<asp:ScriptReference Name="MsAjaxBundle" />` line from the `ScriptManager` configuration.
