### ISSUE TITLE
CalendarExtender does not apply culture options

### ISSUE THREAD

**Issue by GEM-134-MiniGun** [DevExpress/AjaxControlToolkit#517]
### The installation method
- [x] NuGet package

### Minimal steps to reproduce the bug

1.  Set culture info to "hu-HU"
Thread.CurrentThread.CurrentUICulture = new CultureInfo("hu-HU");
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("hu-HU");

### Actual result
The first day is Sunday as in English calendar.
### Expected result
In default view, the first day is Monday as in Hungarian calendar. Or the first day will be that day, what you have set in CurrentUICulture and CurrentCulture.
### Browser(s) used
Googel Chrome
### A site deployment method
- [x] VS development web-server,
- [x] IIS

**Comment by AlekseyMartynov** [comment]
Make sure to enable [script globalization](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.scriptmanager.enablescriptglobalization):

```xml
<asp:ScriptManager runat="server" EnableScriptGlobalization="true">
```

With this option, provided that you [properly set the current culture](https://support.microsoft.com/en-us/help/306162/), Calendar is properly localized:

![](https://user-images.githubusercontent.com/4426185/71359993-61428a80-259f-11ea-8352-9160e263e804.png)

Also, you will find the client culture script block in the rendered page:

```html
<script type="text/javascript">
//<![CDATA[
var __cultureInfo = {"name":"hu-HU", ...};//]]>
</script>
```

Universal workaround:

```xml
<ajaxToolkit:CalendarExtender FirstDayOfWeek="Monday" />
```
