### ISSUE TITLE
TabContainer doesn't preserve active tab when using LinkButton when validation is present

### ISSUE THREAD

**Issue by Ixpah** [DevExpress/AjaxControlToolkit#518]
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Create a page with a tabcontainer and 2 tabpanels. Place a textbox with a required field validator on the first tab. And a LinkButton on  the 2nd tab. When run click the LinkButton.

### Actual result
The 1st tab will be active.

### Expected result
The 2nd tab with the LinkButton should be active.

### Browser(s) used
Firefox 71.0

### A site deployment method
- [X ] VS development web-server,
- [ ] IIS

[Minimal.zip](https://github.com/DevExpress/AjaxControlToolkit/files/4026146/Minimal.zip)

**Comment by AlekseyMartynov** [comment]
Reproduced.

Without validator:
- LinkButton uses the global `__doPostBack` which is [intercepted](https://github.com/DevExpress/AjaxControlToolkit/blob/0a365c6fcf34c465c5ffb5bf2b1577debc6901ce/AjaxControlToolkit/Scripts/BaseScripts.js#L326-L331) to [update the client state field](https://github.com/DevExpress/AjaxControlToolkit/blob/0a365c6fcf34c465c5ffb5bf2b1577debc6901ce/AjaxControlToolkit/Scripts/BaseScripts.js#L395-L400).

With validator:
- LinkButton uses `WebForm_DoPostBackWithOptions` which lands into the original `__doPostBack` captured early in `Sys.WebForms.PageRequestManager._originalDoPostBack`

**Workaround**:
```xml
<asp:LinkButton ... OnClientClick="$find('TabContainer3')._onsubmit()" />
```
