### ISSUE TITLE
A dropdown ComboBox list is displayed incorrectly inside modalpopup asp.net c# with bootstrap theme

### ISSUE THREAD

**Issue by mukeshkamboj1** [DevExpress/AjaxControlToolkit#519]
### The installation method

- [ ] NuGet package

### Actual result
![combobox](https://user-images.githubusercontent.com/40025869/72130296-1bf3ca80-339f-11ea-9aa2-0d5aa9afe85f.jpg)

### Expected result
![combobox1](https://user-images.githubusercontent.com/40025869/72130309-27df8c80-339f-11ea-9afa-a685ad3d25b9.jpg)

### Browser(s) used
chrome

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS
<div id="myModaltoallinterview" class="modal fade" role="dialog">
    <div class="modal-dialog">
        
        <div class="modal-content"> <div class="modal-body" > <div class="col-md-12" >
            <div class="form-group"><label> Profile </label><br />
                <ajax:ComboBox ID="ddlprofilecategory" ForeColor="Black"   AutoCompleteMode="Append"  runat="server" AppendDataBoundItems="True"></ajax:ComboBox>
            </div>
         </div>
    </div>
</div>

Outside of modalpopup its working correctly, but inside modalpopup , its design not proper.

**Comment by AlekseyMartynov** [comment]
I cannot reproduce the issue.

With the Bootstrap stylesheet included as follows:
```html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
```
a ComboBox inside a ModalPopupExtender is displayed correctly:

![Untitled](https://user-images.githubusercontent.com/4426185/72341371-1b2ea180-36db-11ea-9784-b1ade5345c25.png)
