### ISSUE TITLE
Error in AjaxUpload when using e.GetStreamContents()

### ISSUE THREAD

**Issue by gussj** [DevExpress/AjaxControlToolkit#521]
### The installation method
- [ ] Installer
- [ X ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Using OnUploadComplete="AjaxFileUpload1_UploadComplete1", in AjaxFileUpload1_UploadComplete1 I use the e.GetStreamContents() and It's working (passing the stream to another method) but in the upload control when the upload finish I can see this error:
![image](https://user-images.githubusercontent.com/12020620/73141603-9e99ac80-4064-11ea-9eef-5de2205c1ec8.png)
and the upload can't complete this prevent even the OnClientUploadCompleteAll to being executed.
And it freeze like this:
![image](https://user-images.githubusercontent.com/12020620/73141659-5f1f9000-4065-11ea-9892-0b849099500f.png)
And It's impossible to continue with other files because it get stuck.

### Actual result
Uploads can't complete.

### Expected result
Execute the OnClientUploadCompleteAll and finish all uploads correctly.

### Browser(s) used
Chrome (last version)

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS,
- [ X ] Azure WebApp

**Comment by AlekseyMartynov** [comment]
The following code works correctly in the [Sample web site project](https://github.com/DevExpress/AjaxControlToolkit/tree/master/AjaxControlToolkit.SampleSite/AjaxFileUpload):
```c#
using(var stream = file.GetStreamContents())
using(var reader = new StreamReader(stream)) {
    var content = reader.ReadToEnd();
}
```

Please check similar tickets:
- https://github.com/DevExpress/AjaxControlToolkit/issues/398
- https://github.com/DevExpress/AjaxControlToolkit/issues/396
- https://github.com/DevExpress/AjaxControlToolkit/issues/499
- https://github.com/DevExpress/AjaxControlToolkit/issues/286

or upload a sample project that illustrates the issue.

**Comment by gussj** [comment]
That code works correctly I can actually pass that stream directly to azure storage. Thank you!
