### ISSUE TITLE
AjaxControlToolkit issue in Async WebForms pages

### ISSUE THREAD

**Issue by XomegaNet** [DevExpress/AjaxControlToolkit#523]
### The installation method
- [ ] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
There is an issue with AjaxControlToolkit extenders (or any other extenders) in WebForms pages that run Async tasks.

If your extender is not visible initially, and you run an async task where you make it visible (e.g. if the visibility should be determined based on the data that you read asynchronously), then you will get the following.

### Actual result
System.ArgumentException:
Extender control '[ControlID]' is not a registered extender control. Extender controls must be registered using RegisterExtenderControl() before calling RegisterScriptDescriptors().

### Expected result
No exception is thrown, and the extender control is made visible.

### Browser(s) used
Any.

### A site deployment method
- [x] VS development web-server,
- [x] IIS

### Analysis
After some analysis, here is what causes this.

1. ExtenderControl base class, which all AjaxControlToolkit extenders subclass, calls ScriptManager.RegisterExtenderControl() in its OnPreRender method. Moreover, ScriptManager will throw an exception if RegisterExtenderControl() is called during any stage other than PreRender.
2. For controls that are not visible during the PreRender stage, the OnPreRender method will not be called, and hence the extender control will not be registered.
3. WebForms pages run all async tasks after the PreRender stage, and before the Render stage. So, if you make your extender visible in the async task, then it will not be visible yet in the PreRender stage, and only in the Render stage.
4. Finally, extender controls call ScriptManager.RegisterScriptDescriptors() during the Render stage, which throws the above exception due to the control not having been registered in the PreRender stage. 

Has anyone found a fix or workaround for this?

This seems to be a huge limitation in WebForms, where you cannot effectively use both async tasks and extender controls in the same page.

### Sample page

Below is a sample web page that illustrates this issue.

```aspx
<%@ Page Async="true" MasterPageFile="~/Site.Master" Language="C#" AutoEventWireup="true" Inherits="System.Web.UI.Page" %>
<%@ Import Namespace="System.Threading.Tasks" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="Panel1" runat="server">
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <ajaxToolkit:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="TextBox1" />
    </asp:Panel>
</asp:Content>

<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        Panel1.Visible = false;
        RegisterAsyncTask(new PageAsyncTask(ReadAsync));
    }

    private async Task ReadAsync()
    {
        // Making the panel visible below will result in the following exception:
        // Extender control 'CalendarExtender1' is not a registered extender control.
        // Extender controls must be registered using RegisterExtenderControl() before calling RegisterScriptDescriptors().
        Panel1.Visible = true;
        await Task.CompletedTask;
    }
</script>
```

**Comment by AlekseyMartynov** [comment]
Your analysis looks correct. As it turns out, `ScriptManager` establishes a pretty narrow window between the `PreRender` and `PreRenderComplete` stages to register extender scripts.

If I understand you correctly, you need to hide the panel if the async operation doesn't return any content to render. You can invert the logic then. Set `Panel1.Visible = false` in `ReadAsync`.

**Comment by XomegaNet** [comment]
Thanks @AlekseyMartynov for your suggestion to invert the logic.

The example I posted was pretty simplistic just to illustrate the issue. In the real case though, we have a framework that would make some views visible based on a button click or any other event. It works fine with extenders in the non-async case, since those events all happen before PreRender, and the extender controls would be registered during OnPreRender.

So inverting the logic for async pages in our case seems to be much more complicated, where we'd have to make all controls visible initially, track those that should be invisible, and then make them invisible in the Render stage, unless they have been made visible during the async call.

I was really hoping that there is a better workaround, where we can make the logic work as is, but I guess there is none (thanks, Microsoft).
