### ISSUE TITLE
AjaxUploadControl - Web Server Farm Configuration/Support

### ISSUE THREAD

**Issue by cessna** [DevExpress/AjaxControlToolkit#527]
### The AJAX Control Toolkit 19.1.0
19.1.0
### The installation method
- [ ] Installer
- [X ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Deploy application to a web server farm with 2 content servers.

### Actual result
Failure on client upload start

### Expected result
Completion

### Browser(s) used
Chrome
Firefox

### A site deployment method
- [ ] VS development web-server,
- [X ] IIS

Hi,

Is there a way to set the temporary folder location to like a network location? I've currently set client affinity on the ARR Server to work around this issue. The file is uploaded to the temporary folder location on Content Server 1. Upon, postback the client swaps to Content Server 2 which no longer has the file in the temporary folder location. 

Or is there another way to do this?

**Comment by AlekseyMartynov** [comment]
> Is there a way to set the temporary folder location to like a network location?

You cannot specify a network location directly because the path is mapped via [`Server.MapPath`](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.mappath). However, you can create a symlink within the app root:

```
mklink /D Temp \\host\dir
```
