### ISSUE TITLE
ModalPopupExtender issues with CKEditor and Firefox

### ISSUE THREAD

**Issue by nixxystixx** [DevExpress/AjaxControlToolkit#528]
C#
.Net 4.6.1
CKEditor 4.3
AjaxControlToolKit 19.1.0.0

I have a ajaxToolkit:ModalPopupExtender running on my master page and it opens an email editor which include textboxes for 'to', 'cc' etc
It also has a CKEditor for the body of the email, this works in Chrome and Edge but it causes an error in Firefox.

The console error message states - "TypeError: s is undefined", which links to the ckeditor js file
which in turn errors on " if (!s.checkReadOnly()) {".
Stepping through the file it cannot locate 's'.

The CKEditors work everywhere else on the site and on all browsers.

I've attached a cut down version of the master page.
[DevExpress_MP.txt](https://github.com/DevExpress/AjaxControlToolkit/files/4450835/DevExpress_MP.txt)

Any help would be great.

**Comment by AlekseyMartynov** [comment]
Hello

I checked your code with CKEditor 4.14.0 from https://cdn.ckeditor.com/ in Firefox 75. The popup window opens without any errors.

The only problem I noticed is the absence of `btnCloseEmailPopup`. Because of this, I had to remove the `CancelControlID` property value from the markup.
