### ISSUE TITLE
onchange event on textbox with AutoComplete control triggers twice in Google Chrome

### ISSUE THREAD

**Issue by dahermansson** [DevExpress/AjaxControlToolkit#529]
### The installation method
- [x] NuGet package

### Minimal steps to reproduce the bug

Do something in onchange event on input-field with a AutoComplete control
<input id="myTextBox" onchange="anything()" type="text">

### Actual result
onchange event is triggered twice in Google Chrome but not in Microsoft Edge
### Expected result
onchange event triggered just once. 
### Browser(s) used
Google Chrome Version 80.0
### A site deployment method

Edit [AutoComplete Sample](https://ajaxcontroltoolkit.devexpress.com/AutoComplete/AutoComplete.aspx) to listen to onchange event of the textbox. 

`<input name="ctl00$ctl00$Content$DemoContent$myTextBox" type="text" id="Content_DemoContent_myTextBox" autocomplete="off" style="width:300px;" onchange="alert('')">`

alert will occur twice in Google Chrome

**Comment by AlekseyMartynov** [comment]
Thanks for reporting. Reproduced.

Caused by missing parentheses, `isMsBrowser` is a function:
https://github.com/DevExpress/AjaxControlToolkit/blob/0a365c6fcf34c465c5ffb5bf2b1577debc6901ce/AjaxControlToolkit/Scripts/AutoComplete.js#L728-L729

Regression after #459
