### ISSUE TITLE
Ajax AutoCompleteExtender issue

### ISSUE THREAD

**Issue by m2sestest** [DevExpress/AjaxControlToolkit#539]
AutopCompleteExtender of AjaxControlToolKit v19.1.0 goes into a loop giving the following javascript errors and never reaches the ServiceMethod.

Exception was thrown at line 11, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'O' is undefined
Exception was thrown at line 13, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'C' is undefined
Exception was thrown at line 101, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'U' is undefined
Exception was thrown at line 69, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'S' is undefined
Exception was thrown at line 53, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'v' is undefined
Exception was thrown at line 31, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'a' is undefined
Exception was thrown at line 29, column 3 in eval code 0x800a1391 - JavaScript runtime error: 'l' is undefined
The program '[4112] iexplore.exe' has exited with code -1 (0xffffffff).
The program '[7224] iisexpress.exe' has exited with code -1 (0xffffffff).

### The installation method
- [ ] Installer
- [x ] NuGet package
- [ ] A custom build from the source code

### A site deployment method
- [ ] VS development web-server,
- [x ] IIS

**Comment by AlekseyMartynov** [comment]
Would you please describe how can I reproduce the issue? Either fill in 'Minimal steps to reproduce the bug' or attach a sample project.
