### ISSUE TITLE
Error after updating AjaxControlToolkit from 15.1 to 16.1

### ISSUE THREAD

**Issue by rmarty** [DevExpress/AjaxControlToolkit#54]
Trying to update to the latest and greatest toolkit and after installing the 16.1 package I get the error below when trying to run my project.  Have had no luck identifying the problem.  Rolling back to 15.1 works fine.
The error is:
Extender controls of type 'AjaxControlToolkit.AlwaysVisibleControlExtender' cannot extend controls of type 'System.Web.UI.UpdateProgress'

Is this the real error and I can no longer use the update progress control?
To I have controls being used that keep track of versioning.  I have not been able to find any versions # anywhere in my project that would create that problem

Running ASP 4.6.1 and using master pages with div tags.  I saw a reference that div tags could be a problem but I have had no luck with changing them to panels.  Or at least some of them.

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project that uses AJAX Control Toolkit v15.1 to illustrate usage of AlwaysVisibleControlExtender with UpdateProgress?

**Comment by rmarty** [comment]
I have a very simple project example that would help.  How do I add it as a zip?  Dragging here will not allow a zip file

**Comment by MikhailTymchukDX** [comment]
@rmarty That's strange, because I can upload .zip files. You can try to upload an example to any file hosting site, like Google drive or Dropbox, and provide a link here.

**Comment by rmarty** [comment]
Ok I tried both dragging and using the link in 2 different browsers to drop a zip file here without any luck.  So per suggestions here is a link to a Google Drive folder which contains my sample solution duplicating my issue.  Thanks.

https://drive.google.com/open?id=0B-91rTVYN5KacjJoVWtxcG5vcEE

**Comment by MikhailTymchukDX** [comment]
@rmarty  Your example uses v16.1 instead of v15.1.
I could not make it work by reverting AjaxControlToolkit.dll to v15.1.
Would you please provide a working sample that uses v15.1?

**Comment by rmarty** [comment]
Well lets if you don't mind change course a bit.  This example is a simple example using 16.1 and duplicates the issue.  Wanting to go to ver 16.1 I would like to just use this example and move on.
If these objects are not compatible like the error suggests we just need to know.  If there is a bug then this example will help identify that.  The example of the 15.1 to 16.1 project I cannot provide as there is some propitiatory information in it as well as db access.
So please identify using the exampe of 16.1 only. I believe they will probably be two of the same. Thanks for caring....

**Comment by MikhailTymchukDX** [comment]
Staring with v15.1, the `TargetControlType` attribute value was changed from `System.Web.UI.Control` to `System.Web.UI.WebControl`.

That means that in the version 15.1 product line, as well as in version 16.1, `System.Web.UI.UpdateProgress` is not a part of the inheritance chain and `AlwaysVisibleControlExtender` cannot extend this class.

**Comment by rmarty** [comment]
Thank you for that clarification and your time.
