### ISSUE TITLE
error message 'Severity	Code	Description	Project	File	Line	Suppression State Error		Copying file bin\ar\AjaxControlToolkit.resources.dll to obj\Release\Package\PackageTmp\bin\ar\AjaxControlToolkit.resources.dll failed. Could not find file 'bin\ar\AjaxControlToolkit.resources.dll'.	 When tryinng to publish the project in Asp.Net	'

### ISSUE THREAD

**Issue by hf-lee** [DevExpress/AjaxControlToolkit#540]
### The installation method
- [ ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Actual result
Taking over an Asp.Net web-form project, it use AjaxControlToolkit as part of the rendering. I can update code, compile, build and running in local-machine successfully.  While trying to publish in order move to team-test server, get message 
"Copying file bin\ar\AjaxControlToolkit.resources.dll to obj\Release\Package\PackageTmp\bin\ar\AjaxControlToolkit.resources.dll failed. Could not find file 'bin\ar\AjaxControlToolkit.resources.dll'.	

The 'AjaxControlToolkit' in the reference has following information:
    - Running Version: v2.0.50727
    - Specific Version: false
- Strong Name: true
 - Version: 3.0.30512.20315
	

The project is in .Net framework 3.5 
I tried with 'Exclude debug symbol' in the 'Package/Publish web' under 'project property'

It seems asking for an 'Arabic' language of resource dll, I only need an 'US English' one.

The IDE is VS2017.

### Expected result

Expect the project to be published successfully

### Browser(s) used

N/A - not browser issue

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by AlekseyMartynov** [comment]
Judging by your description, the error is related to the Visual Studio publishing tool, not to the AJAX Control Toolkit itself.

Similar issues are discussed at:
- https://stackoverflow.com/q/47988113
- https://forums.asp.net/t/1971782.aspx
