### ISSUE TITLE
HtmlEditorExtender with EnableSanitization="true" throws error

### ISSUE THREAD

**Issue by RonRas-Dev** [DevExpress/AjaxControlToolkit#541]
### The installation method
- [ ] Installer
- [ 19.1] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
I started a new VB project in Visual Studio. I added the AjaxControlToolkit (19.1) and the AjaxControlToolkit.HtmlEditor.Sanitizer (19.1) using the Nuget Package Manager. I also added the Ajax Control Toolkit to Visual Studio using the installer. 

I created a single aspx page with one text box and the HtmlEditorExtender. If i set the EnableSanitization="false" it works just fine. But when I set the EnableSanitization="true" I get a runtime error:

### Actual result
Value cannot be null.
Parameter name: type
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: type

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

```
[ArgumentNullException: Value cannot be null.
Parameter name: type]
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +12754023
   System.Activator.CreateInstance(Type type) +12
   AjaxControlToolkit.HtmlEditorExtender.CreateSanitizer() +77
   System.Lazy`1.CreateValue() +429
   System.Lazy`1.LazyInitValue() +158
   System.Lazy`1.get_Value() +79
   AjaxControlToolkit.HtmlEditorExtender.get_Sanitizer() +27
   AjaxControlToolkit.HtmlEditorExtender.OnInit(EventArgs e) +47
   System.Web.UI.Control.InitRecursive(Control namingContainer) +390
   System.Web.UI.Control.InitRecursive(Control namingContainer) +183
   System.Web.UI.Control.InitRecursive(Control namingContainer) +183
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1633
```

[z.aspx.designer.zip](https://github.com/DevExpress/AjaxControlToolkit/files/4737285/z.aspx.designer.zip)
[z.aspx.designer.zip](https://github.com/DevExpress/AjaxControlToolkit/files/4737288/z.aspx.designer.zip)

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by AlekseyMartynov** [comment]
Hello

I followed the steps to reproduce and used the attached code snippets. There were no errors on my side.

Please make sure that the project references contain the following item:

![AjaxControlToolkit.HtmlEditor.Sanitizer](https://user-images.githubusercontent.com/4426185/85044120-e34ded80-b195-11ea-8642-8c9293aee109.png)
