### ISSUE TITLE
AjaxFileUpload MaxFileSize Accessibility

### ISSUE THREAD

**Issue by prithee** [DevExpress/AjaxControlToolkit#543]
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### A site deployment method
- [ ] VS development web-server,
- [x] IIS

I do not see any way to access the client property of MaxFileSize of the AjaxFileUpload. 
https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload

As result the file upload can appear to succeed, but not report back a failed upload (due to excessive size) to the user.

**Comment by AlekseyMartynov** [comment]
Hello

Refer to the [`maxFileSize` wiki section](https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload#maxfilesize).

![](https://user-images.githubusercontent.com/4426185/85046875-b1d72100-b199-11ea-9888-3913dcbd6591.png)

An attempt to upload a file of an excessive size should display a message box:

![](https://user-images.githubusercontent.com/4426185/85046994-e5b24680-b199-11ea-8327-c54e3f45b895.png)

See also:
- https://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx
- https://github.com/DevExpress/AjaxControlToolkit/tree/master/AjaxControlToolkit.SampleSite/AjaxFileUpload

**Comment by prithee** [comment]
Thank you very much. What could be a reason for this property not being accessible? From my nuget install I don't see it in visual studio, nor is it accessible in the devtools console, while it clearly is seen in your example.

**Comment by AlekseyMartynov** [comment]
If you can share a sample project that illustrates the lack of this API, I can look into it and hopefully find what's wrong.
