### ISSUE TITLE
Toolkit 18.1.0 and .NET Framework 4.8

### ISSUE THREAD

**Issue by ChrisSfanos** [DevExpress/AjaxControlToolkit#544]
### The AJAX Control Toolkit 18.1.0

Is Toolkit 18.1.0 compatible with .NET Framework 4.8?

**Comment by Mehul** [comment]
Yes, any .NET 4.x framework will work. 

Hey Chris, feel free to direct any queries from other devs here too. :)

Thanks for all your help with the recent release. 👍
