### ISSUE TITLE
ModalPopup extender allows controls to show through after scrolling. Both Chrome and Edge. IE is ok.

### ISSUE THREAD

**Issue by RickBlacker** [DevExpress/AjaxControlToolkit#546]
### The installation method
- [ ] Installer
- [x ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Create a panel that is controlled by the ModalPopupExtender.  IE works fine, Chrome and Edge both have problems.
### Actual result
We have a page that uses the ModalPopupExtender.  When the popup first shows, all controls are hidden behind the popup.   However after scrolling for about 1/4 of a page, buttons under the popup begin to show covering over content in the popup.  Other controls don't do this, only buttons that allow products to be added to a shopping cart. 

### Expected result
Buttons to stay inactive, hidden behind the popup. 
### Browser(s) used
Chrome - Broken
Edge - Broken
IE - Works Ok.
### A site deployment method
- [ ] VS development web-server,
- [ x ] IIS

**Comment by AlekseyMartynov** [comment]
Judging by the description, this may be a CSS `z-index` issue. Could you share a sample project that illustrates this behavior?

**Comment by neillg** [comment]
@RickBlacker I see someone has closed this, but did you ever get to the bottom of the issue?  I am experiencing something very similar in Chromium browsers.  Everything blurs as if the controls are piling up on one another when you scroll through the page.
