### ISSUE TITLE
HTMLEditorExtender ForeColorSelector IE11

### ISSUE THREAD

**Issue by sbboa** [DevExpress/AjaxControlToolkit#547]
### The AJAX Control Toolkit \<VERSION\>
ASP.NET AJAX Control Toolkit v18.1.0 and above

### The installation method
- [DevExpress] Installer 

### Minimal steps to reproduce the bug
Used ForeColorSelector from the HTMLEditorExtender toolbar options

### Actual result
Error @ document.execCommand('stylewithcss', false, true) This command is not supported. 

### Expected result
Font Color should be applied to the text in IE browser

I have tries adding <meta http-equiv="X-UA-Compatible" content="IE=10,chrome=1" /> 
Chrome browser doesn't have any issues.

### Browser(s) used
Internet Explorer 

### A site deployment method
- [ Microsoft Windows Server 2016 Standard ] VS development web-server,
- [Version 10 ] IIS

**Comment by AlekseyMartynov** [comment]
Hello

I just checked the 'Fore Color' button in the [published sample site](https://ajaxcontroltoolkit.devexpress.com/HtmlEditorExtender/HtmlEditorExtender.aspx). Worked well in IE 11. 

![](https://user-images.githubusercontent.com/4426185/86010844-a18a3600-ba24-11ea-9d5f-2db2bf9fff04.png)
