### ISSUE TITLE
Tab container Issue after updating AjaxControlToolkit from 15.1 to 16.1

### ISSUE THREAD

**Issue by cristinadorotan** [DevExpress/AjaxControlToolkit#55]
All tabs remain disabled after selected once. 

ajax__tab_xp .ajax__tab_disabled .ajax__tab_tab

![image](https://cloud.githubusercontent.com/assets/18302632/14309376/be1cb174-fbe4-11e5-9acf-1dabfce6096a.png)

**Comment by MikhailTymchukDX** [comment]
@cristinadorotan 
Would you please provide a sample project that illustrates this issue?

**Comment by cristinadorotan** [comment]
Hy, I have the project but how do I send it to you ? (ASp Web Forms, VB.Net) when I select a TAB, navigate to others, return to the first one selected, the CSSClass for each active and disabled is set on that TAB. This messes up our entire project, because we have specific styles for a disabled tab.

**Comment by MikhailTymchukDX** [comment]
You can attach an archive with the project to your comment.

**Comment by cristinadorotan** [comment]
Essentially my problem is that the ajax__tab_disabled class remains on each tab after I access them.

**Comment by cristinadorotan** [comment]
I cannot upload ZIP files, if you are kind please download from: https://we.tl/HpcOwvo0n9   the project. Thank you!

**Comment by MikhailTymchukDX** [comment]
I downloaded the sample you provided and clicked on tab headers at the About.aspx page, but see no disabled tabs.
Do I need to perform any special action to reproduce this issue?

**Comment by cristinadorotan** [comment]
You need to inspect the tab panel element and see that the disabled CssClass is added on each tab you visited and never removed.

I completed with css to be more, visual, here is the link to the project:

https://we.tl/EeDOKGhazv


Thank you!

**Comment by MikhailTymchukDX** [comment]
@cristinadorotan To work around this issue, you can remove the `ajax__tab_disabled` CSS class in the `OnClientClick` event handler.
As this event occurs before the class is applied, a little timeout is required:
```aspx
<script type="text/javascript">
	function removeDisabledClass() {
		var tabIDs = eval('<%= GetTabIDs()%>');

		setTimeout(function() {
			for(var i = 0; i < tabIDs.length; i++) {
				var header = document.getElementById(tabIDs[i] + "_tab");
				header.classList.remove("ajax__tab_disabled");
			}
		}, 50);
	}
</script>

<ajaxToolkit:TabContainer ID="tab_Container" runat="server">

	<ajaxToolkit:TabPanel ID="tb_A" HeaderText="OPTION_A" runat="server" OnClientClick="removeDisabledClass">
	</ajaxToolkit:TabPanel>

	<ajaxToolkit:TabPanel ID="tb_B" HeaderText="OPTION_B" runat="server" OnClientClick="removeDisabledClass">
	</ajaxToolkit:TabPanel>

	<ajaxToolkit:TabPanel ID="tb_C" HeaderText="OPTION_C" runat="server" OnClientClick="removeDisabledClass">
	</ajaxToolkit:TabPanel>

	<ajaxToolkit:TabPanel ID="tb_D" HeaderText="OPTION_D" runat="server" OnClientClick="removeDisabledClass">
	</ajaxToolkit:TabPanel>

</ajaxToolkit:TabContainer>
```
`GetTabIDs` s a utility method that is used to get an array of header IDs.
I have attached the updated sample project [AjaxControlToolkitTabIssueUpd.zip](https://github.com/DevExpress/AjaxControlToolkit/files/208127/AjaxControlToolkitTabIssueUpd.zip)

**Comment by cristinadorotan** [comment]
Thank you, how does this work when I want to disable a tab on purpose ?

**Comment by MikhailTymchukDX** [comment]
You need to exclude this tab from the class removal loop like this:
```aspx
    <script type="text/javascript">
        var disabledTabIndex = 2; // can be set by external code

        function removeDisabledClass() {
            var tabIDs = eval('<%= GetTabIDs()%>');

            setTimeout(function() {
                for(var i = 0; i < tabIDs.length; i++) {
                    if(i === disabledTabIndex)
                        continue;

                    var header = document.getElementById(tabIDs[i] + "_tab");
                    header.classList.remove("ajax__tab_disabled");
                }
            }, 50);
        }
    </script>

...

<ajaxToolkit:TabPanel
    ID="tb_C"
    HeaderText="OPTION_C"
    runat="server"
    OnClientClick="removeDisabledClass"
    Enabled="false" />
```
