### ISSUE TITLE
Image Preview AsyncFileUpload

### ISSUE THREAD

**Issue by Sarahorg** [DevExpress/AjaxControlToolkit#551]
Hello
I’m a new user to AjaxControlToolkit and I’m using AsyncFileUpload to upload images to the server and it works fine.
The AJAX Control Toolkit ver20.1
recently I’ve been trying to show the preview of the image which is being uploaded to the user but I couldn’t find a proper way to that.
My web application is based on c# and asp.net .
I have googled the thing and I’ve tried some ways but none were useful. I’ll mention some below. The problem is that the image will remain empty or I’ll see a cross on it instead of the uploaded image.

https://stackoverflow.com/questions/21544594/image-preivew-using-ajaxtoolkit-asyncfileupload
https://www.dotnetspider.com/resources/40858-Preview-Image-before-uploading-using.aspx
https://jsbin.com/uboqu3/1/edit?html,js,output
https://stackoverflow.com/questions/18694437/how-to-preview-image-before-uploading-in-jquery/19649483

I would be grateful if you could help me with the issue.
Regards

**Comment by AlekseyMartynov** [comment]
Hello

If you encounter an issue that you believe is caused by an AJAX Control Toolkit component, please submit a sample project and a description, so that we can review it.

**Comment by Sarahorg** [comment]
@AlekseyMartynov 
hi, no its not like that, this is sth i wanted to do but i didnt succeed. 
I just need a sample project/code of previewing the image which is being uploaded using AsyncFileUpload.
and i've mentioned the ways i tried.

**Comment by AlekseyMartynov** [comment]
Could you please share your results and describe what issue you faced?

If your question relates to general web development but not to a particular file upload component, I suggest that you refer to public community resources, such as StackOverflow.

Also, I don't recommend that you use AJAX Control Toolkit in new projects. It is not actively developed anymore, although we maintain it and fix bugs we receive. I would advise you to consider a more up-to-date web component library. Check [DevExpress components](https://www.devexpress.com/Support/Demos/) if you need a rich set of components, good documentation and support.
