### ISSUE TITLE
TabContainer Issue after updating AjaxControlToolkit to 16.1

### ISSUE THREAD

**Issue by biancarus88** [DevExpress/AjaxControlToolkit#56]
Hi Guys!

There seems to be an issue with the fact that the tabContainer_header doesn't support scrollLeft any longer. I have 2 arrows trying to scroll the header (since the tabs do not fit in the page), but the header is completely frozen when i try to apply obj.scrollLeft = obj.scrollLeft + 50; (obj is the tab container header)
The issue is present since upgraded to AjaxControlToolkit 16.1, but it was working fine in 15.1.2 thought.

Thanks

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project with the described markup?

**Comment by biancarus88** [comment]
Hi again!

Trying to put a sample project together, I realized what the bug actually is.
In our project, we have enforced that the tabs, when they do not fit in one line (being too many), to not split on multiple lines, but much rather to show in one line and scroll using 2 arrow buttons on the tab header (using nowrap). This is the issue now, that the nowrap style will not apply anymore to TabContainer header, and i am forced to see all tabs on new lines.
Here you can see a link to the project, as i could not upload it: https://www.wetransfer.com/downloads/007576386370d5549342ee800803487e20160406133239/d36c68a25fd52478047521dfb47f3dc720160406133239/9b9e0b

Thank you!

**Comment by MikhailTymchukDX** [comment]
Does applying this style help you?
```css
.ajax__tab_default .ajax__tab {
    display: unset;
    float: none;
}

.ajax__tab_header {
    overflow-x: scroll;
}
```
