### ISSUE TITLE
ssrs report viewer in asp.net webform

### ISSUE THREAD

**Issue by ddemetrios5** [DevExpress/AjaxControlToolkit#6]
I have upgraded my asp.net webforms project Ajax toolkit from v7 to v16
Everything works ok except for ssrs report viewer

The report parameters load but the report does not render just says loading
When i use the old ajax toolkit it work

**Comment by MikhailTymchukDX** [comment]
@ddemetrios5 Do you mean [this](https://msdn.microsoft.com/en-us/library/dd756405.aspx) control?

**Comment by ddemetrios5** [comment]
Yes it is the ReportViewer control

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project that illustrates this issue?

**Comment by MikhailTymchukDX** [comment]
Closed due to inactivity.
