### ISSUE TITLE
restrict file size before uploading to server

### ISSUE THREAD

**Issue by qunshen** [DevExpress/AjaxControlToolkit#61]
wish to add new feature to AjxFileupload control: restrict file size before uploading to server. File size checking should at client side,not at the server.

**Comment by qunshen** [comment]
Thank you very much!
When  could  I install the new Package? or wating for next release?

**Comment by MikhailTymchukDX** [comment]
We release NuGet packages along with the installer.
The date of the next release is not determined yet.
