### ISSUE TITLE
ExtendedCalender

### ISSUE THREAD

**Issue by m2081859** [DevExpress/AjaxControlToolkit#62]
<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="Orders.aspx.cs" Inherits="Pages_Orders" %> 

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:TabContainer ID="TabContainer1" runat="server" ActiveTabIndex="0" 
        Width="900px" style="width: 900px; visibility: visible;">
        <asp:TabPanel ID="TabPanel1" runat="server" HeaderText="TabPanel1">
            <HeaderTemplate>Open Orders</HeaderTemplate>
            <ContentTemplate>Show orders between : <asp:TextBox ID="txtDateOpen1" 
                    runat="server" AutoPostBack="True" style="font-weight: bold"></asp:TextBox><asp:CalendarExtender 
                    ID="txtDateOpen1_CalendarExtender" runat="server" Enabled="True" 
                    TargetControlID="txtDateOpen1"></asp:CalendarExtender>And: <asp:TextBox 
                    ID="txtDateOpen2" runat="server" AutoPostBack="True" style="font-weight: bold"></asp:TextBox><strong><asp:CalendarExtender 
                    ID="txtDateOpen2_CalendarExtender" runat="server" TargetControlID="txtDateOpen2"
                        Enabled="True"></asp:CalendarExtender><br /></strong><br /><asp:Label ID="lblOpenOrders" runat="server"></asp:Label></ContentTemplate>
        </asp:TabPanel>
        <asp:TabPanel ID="TabPanel2" runat="server" HeaderText="TabPanel2">
            <HeaderTemplate>Completed Orders</HeaderTemplate>
            <ContentTemplate><strong>Show orders between : <asp:TextBox ID="txtDateClosed1" runat="server" AutoPostBack="True"></asp:TextBox><asp:CalendarExtender ID="txtDateClosed1_CalendarExtender" runat="server" 
                    TargetControlID="txtDateClosed1"></asp:CalendarExtender>And: <asp:TextBox ID="txtDateClosed2" runat="server" AutoPostBack="True"></asp:TextBox><asp:CalendarExtender ID="txtDateClosed2_CalendarExtender" runat="server" 
                    TargetControlID="txtDateClosed2"></asp:CalendarExtender><br /></strong><br /><asp:Label ID="lblClosedOrders" runat="server"></asp:Label></ContentTemplate>
        </asp:TabPanel>
        <asp:TabPanel ID="TabPanel4" runat="server" HeaderText="TabPanel4">
            <HeaderTemplate>Charts<br /></HeaderTemplate>
            <ContentTemplate><br /><asp:LineChart ID="LineChart1" runat="server" Height="353px" Theme="" 
                    TooltipBackgroundColor="" TooltipBorderColor="" TooltipFontColor="" 
                    ValueAxisLines="0" Width="16px"></asp:LineChart><br /><asp:LineChart ID="LineChart2" runat="server" Height="353px" Theme="" 
                    TooltipBackgroundColor="" TooltipBorderColor="" TooltipFontColor="" 
                    ValueAxisLines="0" Width="16px"></asp:LineChart></ContentTemplate>
        </asp:TabPanel>
    </asp:TabContainer>
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <br />
</asp:Content>

**Comment by MikhailTymchukDX** [comment]
I am afraid that the issue is unclear to me. Would you please describe it in greater detail?

**Comment by m2081859** [comment]
**READ**
When I open the web browser and click on the text box calendars should drop but instead nothing is happening...its due for my final project today. also when I run the code this box appears 
"Unhandled exception at line 147, column 5 in http://localhost:31434/Orders.aspx

0x800a138f - JavaScript runtime error: Unable to get property 'UI' of undefined or null reference

If there is a handler for this exception, the program may be safely continued."

Followed by this line highlighted
"<script type="text/javascript">
//<![CDATA[
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.CalendarBehavior, {"id":"ContentPlaceHolder1_TabContainer1_TabPanel1_txtDateOpen1_CalendarExtender"}, null, null, $get("ContentPlaceHolder1_TabContainer1_TabPanel1_txtDateOpen1"));
});
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.CalendarBehavior, {"id":"ContentPlaceHolder1_TabContainer1_TabPanel1_txtDateOpen2_CalendarExtender"}, null, null, $get("ContentPlaceHolder1_TabContainer1_TabPanel1_txtDateOpen2"));
});
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.CalendarBehavior, {"id":"ContentPlaceHolder1_TabContainer1_TabPanel2_txtDateClosed1_CalendarExtender"}, null, null, $get("ContentPlaceHolder1_TabContainer1_TabPanel2_txtDateClosed1"));
});
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.CalendarBehavior, {"id":"ContentPlaceHolder1_TabContainer1_TabPanel2_txtDateClosed2_CalendarExtender"}, null, null, $get("ContentPlaceHolder1_TabContainer1_TabPanel2_txtDateClosed2"));
});
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.LineChart, {"ClientSeries":[],"clientStateField":$get("ContentPlaceHolder1_TabContainer1_TabPanel4_LineChart1_ClientState"),"theme":"","tooltipBackgroundColor":"","tooltipBorderColor":"","tooltipFontColor":"","valueAxisLines":0}, null, null, $get("ContentPlaceHolder1_TabContainer1_TabPanel4_LineChart1"));
});
Sys.Application.add_init(function() {
    $create(Sys.Extended.UI.LineChart, {"ClientSeries":[{"Name":"","LineColor":"","Data":[148,62]}],"categoriesAxis":"m2081859,test","chartTitle":"Orders per customer","clientStateField":$get("ContentPlaceHolder1_TabContainer1_TabPanel4_LineChart2_ClientState"),"theme":"","tooltipBackgroundColor":"","tooltipBorderColor":"","tooltipFontColor":"","valueAxisLines":0}, null, null, $get("ContentPlaceHolder1_TabContainer1_TabPanel4_LineChart2"));
});
//]]>
</script>"

**Comment by MikhailTymchukDX** [comment]
I have no issues with this markup (see attached sample project): [CalendarTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/212609/CalendarTest.zip)

Would you please specify the following information? 
1. The AJAX Control Toolkit version you are using.
2. The .NET Framework version of a project.
3. The browser version.
