### ISSUE TITLE
ComboBox is case sensitive in IE even when set to false

### ISSUE THREAD

**Issue by dparks2** [DevExpress/AjaxControlToolkit#8]
AjaxControlToolkit 16.1.0 -- ComboBox is case sensitive in IE 11 even when set to false. Firefox and Chrome work as expected, but IE does not. Also in IE the first letter typed does not always display.
I do not know if this issue is new to 16.1.0

**Comment by MikhailTymchukDX** [comment]
We were unable to reproduce this behavior.
Would you please specify the following?
1. The version of IE 11.
2. Other ComboBox properties, like `DropDownStyle`, `AutoCompleteMode` etc.?

**Comment by dparks2** [comment]
This is as coded from the project:
<ajax:ComboBox ID="cmbVendor" runat="server" DataSourceID="SqlDataSource_Vendors" DataTextField="Vendor" DataValueField="VendorID" AutoPostBack="false" Width="350px" 
										DropDownStyle="DropDownList" AutoCompleteMode="SuggestAppend" CaseSensitive="false" ItemInsertLocation="Append" />

And please see attached screen shot of function in Internet Exporer 11 and the IE 11 version. 

NOTE: the entire list is UPPER case while the user is typing in lower case.

First thing that I would look at is that there is a space in the second character of the first item of the "A" items that may be interfering.
Second thing is that when typing out 3-5 characters the list appears to work, but not every character position.

Again does not appear to be an issue in Firefox or Chrome.

![ajax 16 1 0 combobox issue - ie 11](https://cloud.githubusercontent.com/assets/17791278/13927047/3fa9fa62-ef4c-11e5-8df6-e5a948e2f3cf.jpg)
![ie 11 version](https://cloud.githubusercontent.com/assets/17791278/13927089/72a8d6cc-ef4c-11e5-800e-5542ae443687.JPG)

**Comment by MikhailTymchukDX** [comment]
@dparks2 Every even typed character activates search in the ComboBox while every odd character acts like simple text entered in the textbox.
This behavior is reproduced on the [Sample Site](http://ajaxcontroltoolkit.devexpress.com/ComboBox/ComboBox.aspx).
Is this the same issue you faced?

**Comment by MikhailTymchukDX** [comment]
IE 11 is detected by Microsoft AJAX Framework as the following structure:

```js
Sys.Browser.agent = null;
Sys.Browser.version = 5;
Sys.Browser.name = "Netscape";
```

ComboBox.js file contained the following condition in the `_isNonCharacterKey()` method, which was evaluated as `true`, because the `Sys.Browser.WebKit` property was `undefined` and was not present neither in Microsoft AJAX Framework nor in AJAX Control Toolkit:

```js
else if (Sys.Browser.agent == Sys.Browser.WebKit) {
```

The code inside this code block treated the "v" key as a special key and stopped the search process.
So, this code was removed in PR #38.

**Comment by dparks2** [comment]
@MikhailTymchukDX yes your description of action sounds about right regarding even and odd number character working differently and my own comment above about not every character position appeared to search the list. (you described it better) 

I take it from the new bug label, your last comment and review of PR #38 that this issue may be resolved soon. Thanks.
