### ISSUE TITLE
AjaxFileUpload MIME types

### ISSUE THREAD

**Issue by DeanMc67** [DevExpress/AjaxControlToolkit#80]
Is it possible to get the MIME type that is displayed below the drag and drop area?

I'd like to write these to a database so they can be correctly displayed when requested.

Cheers

Dean

**Comment by MikhailTymchukDX** [comment]
You can use the the `System.Web.MimeMapping.GetMimeMapping()` method to get the file's MIME type based on its extension.
This method can be called in the `AjaxFileUpload.UploadComplete` event hander:

```csharp
protected void AjaxFileUpload1_OnUploadComplete(object sender, AjaxFileUploadEventArgs file) {
    var mimeType = System.Web.MimeMapping.GetMimeMapping(file.FileName);
}
```
Please note that this method is unavailable in versions prior to .NET 4.5.
To use it in .NET 4.0, please apply this workaround: http://stackoverflow.com/a/9145296/644496
