### ISSUE TITLE
Ajax tab Container - Ajax Tab Panel - Tabs Position

### ISSUE THREAD

**Issue by samerselo** [DevExpress/AjaxControlToolkit#81]
I Was Using Version 15.1.4 I've Created a web site the direction of it is right to left and used the folowing styles to set the tabs to the right

.ajax__tab_header {
    direction: rtl;
}
.ajax__tab_xp {
    font-weight: bold !important;
}

but when I've upgraded to version 16.1 the tabs stuck on the left
I've changed the property tabstrip placement to topright 
tried also set the direction of div that contains the control to rtl and textalign also to right

but still stuck to the left refusing going right

**Comment by MikhailTymchukDX** [comment]
I believe you need to apply the `float:right` CSS style:
```css
<style>
    .ajax__tab_default .ajax__tab {
        float: right;
    }
</style>
```
See this issue for more details: https://github.com/DevExpress/AjaxControlToolkit/issues/40#issuecomment-203862229

Please keep us posted of your results.

**Comment by samerselo** [comment]
no that didn't work with latest version but it works fine with 15.1.4
I think I'll revert to the old one

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project that illustrates this issue?

**Comment by samerselo** [comment]
[Test001.zip](https://github.com/DevExpress/AjaxControlToolkit/files/238381/Test001.zip)

**Comment by samerselo** [comment]
this is a quick sample
![111](https://cloud.githubusercontent.com/assets/18696616/14848375/05e93a58-0c76-11e6-99ba-b1742ec92f34.jpg)

**Comment by MikhailTymchukDX** [comment]
Thank you for this sample project.

A custom CSS style defined in the header is overridden with the AJAX Control Toolkit CSS style file, that loads right after it:
![image](https://cloud.githubusercontent.com/assets/17080984/14848882/8f145e5a-0c78-11e6-9d6c-c55bc1afa4a3.png)

To fix it, place a custom CSS style declaration anywhere below the page header.

**Comment by samerselo** [comment]
on this project Ok

but on the real one I Use a General Css in theme for all pages
I'm Using Master page and content pages 
How I can do it in the big project

**Comment by MikhailTymchukDX** [comment]
You need to make your CSS rules more specific to override default CSS rules: http://stackoverflow.com/a/9459093/644496

For example, you can add an empty CSS class to every tab control or place it inside a container with a predefined ID.

Another way is to use the `!important` keyword:
```css
.ajax__tab_default .ajax__tab {
    float: right !important;
}
```

**Comment by samerselo** [comment]
thank you I'll try and Reply

**Comment by samerselo** [comment]
that did it thank you alot
