### ISSUE TITLE
Ajaxfileupload control error raising upload complete event and start new upload

### ISSUE THREAD

**Issue by Narayana187** [DevExpress/AjaxControlToolkit#82]
HI, I'm facing issue with AjaxFileupload control in VS2013 when hosted in IIS(local) server. But it is working fine while I am running with IIS Express. Please help me out.

Screen shot for reference.
![ajax tool kit error](https://cloud.githubusercontent.com/assets/18703281/14857255/1f86d612-0cb9-11e6-962a-98df40eddcbc.PNG)

**Comment by MikhailTymchukDX** [comment]
Do you run the site in Medium trust environment or on a web farm?

**Comment by Narayana187** [comment]
Hi Thanks for your reply. I am running this application in  my local IIS (My system) with the trust level as "Full". still i am not able to use the AjaxFileupload Control. Please Suggest.

**Comment by MikhailTymchukDX** [comment]
What error do you see in a browser's console (F12)?
Are server-side events (`UploadStart`, `UploadComplete` and `UploadCompleteAll`) raised correctly?

**Comment by Narayana187** [comment]
Hi, I have written UploadComplete event in server side.but it is not executing or pointing there to complete the upload process. Seeking your assistance

**Comment by MikhailTymchukDX** [comment]
Would you please comment out this line in the `Layout.master` file
`<asp:ScriptReference Path="~/Scripts/AjaxControlToolkit/Bundle" />`
and upload an error screenshot in the browser's console, like this one?

![image](https://cloud.githubusercontent.com/assets/17080984/14881667/b33d45f6-0d3d-11e6-8ced-f9850180f87a.png)

**Comment by Narayana187** [comment]
I have commented the line in layout.master and tried to upload again., but it is showing same error.In browser console it is showing that."Error raising upload complete event and start new upload".  Please find the screen shots for your reference.
![ajax tool kit error_new screen shot](https://cloud.githubusercontent.com/assets/18703281/14882193/f7db9732-0d54-11e6-8973-b290c4daf749.PNG)

**Comment by Narayana187** [comment]
Yes, I am struck at the same point in the above post. could you please help how to overcome that challenge? Thanks in advance.

**Comment by MikhailTymchukDX** [comment]
Would you please show network data in the browser's developer tools (see the screenshot)? 
![image](https://cloud.githubusercontent.com/assets/17080984/14882623/4e15a60a-0d42-11e6-8f5d-5c0d66c1625f.png)

**Comment by Narayana187** [comment]
Hi Please find the attached..
![ajax tool kit error_new screen shot 1](https://cloud.githubusercontent.com/assets/18703281/14882828/5eac61a0-0d58-11e6-8672-9e6485c6260c.PNG)

**Comment by MikhailTymchukDX** [comment]
The 404 error indicates that client code cannot find the `AjaxFileUploadHandler.axd` upload handler.
It seems that the Sample site is not located in the root of the web site.

You can try to place it in the root of the web site or change the path to `AjaxFileUploadHandler.axd` in Web.config.
Please see this comment for more details: https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203889967

**Comment by Narayana187** [comment]
Hi Thanks for your swift help... Its working fine.
