### ISSUE TITLE
Ajax tab Container - Ajax Tab Panel - Tabs balck horizontal Line

### ISSUE THREAD

**Issue by samerselo** [DevExpress/AjaxControlToolkit#83]
Why a black horizontal line appear in the tab page how I can remove it
see the pic
I've made the page this large bcz one of the tree pages have more controls that the other two

![111](https://cloud.githubusercontent.com/assets/18696616/14880525/e7239498-0d37-11e6-8338-defb9cb7b639.png)

**Comment by samerselo** [comment]
![111](https://cloud.githubusercontent.com/assets/18696616/14880590/5131bc48-0d38-11e6-9dc6-376eb2d1c491.png)

**Comment by MikhailTymchukDX** [comment]
Do you mean this line?
![e7239498-0d37-11e6-8338-defb9cb7b639](https://cloud.githubusercontent.com/assets/17080984/14880774/6ef24706-0d39-11e6-902b-acdb8db3e97c.png)

**Comment by samerselo** [comment]
yes sir

**Comment by samerselo** [comment]
I've Just Solved it
Just modified the line
<cc1:TabPanel runat="server" HeaderText="إضافة طلب إجازة - ساعية" ID="TabPanel1" CssClass="ajax__tab_header">
to be
<cc1:TabPanel runat="server" HeaderText="إضافة طلب إجازة - ساعية" ID="TabPanel1">

and problem Solved

sorry for haste in asking
