### ISSUE TITLE
Unable to override the Upload button click

### ISSUE THREAD

**Issue by Narayana187** [DevExpress/AjaxControlToolkit#85]
Hi, Can you please help me out to override the upload button click event to check the validations as per my requirement. i am unable to override the click event, OnUploadComplete event is triggering once the file is uploaded, but i have to check the file size, file name length etc. before uploading it. could you please help me out.

**Comment by MikhailTymchukDX** [comment]
Unfortunately, there is no option to check these parameters before uploading in v16.1.
We will plan to introduce an enhancement that will allow a user to run a custom validation function before uploading.
