### ISSUE TITLE
Sample Site won't wun

### ISSUE THREAD

**Issue by R-McN** [DevExpress/AjaxControlToolkit#86]
I have recently downloaded and installed the Ajax Control Toolkit v16.1 using the installer exe. When I attempt to run the sample website I get the error below. Any ideas? I am using VS Ultimate 2013 and target framework 4.5.1.

Thank you
Richard

Server Error in '/' Application.
Execution permission cannot be acquired. Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Security.Policy.PolicyException: Execution permission cannot be acquired.

Source Error:

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
Stack Trace:

[PolicyException: Execution permission cannot be acquired.]    System.Security.CodeAccessSecurityEngine.TryResolveGrantSet(Evidence evidence, PermissionSet& grantSet) +10980922    System.Security.CodeAccessSecurityEngine.ResolveGrantSet(Evidence evidence, Int32& specialFlags, Boolean checkExecutionPermission) +44  [FileLoadException: Could not load file or assembly 'App_Code.eijwsdbn, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. PolicyException thrown. (Exception from HRESULT: 0x80131416)]    System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0    System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +34    System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +152    System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity) +34    System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly() +98    System.Web.Compilation.CodeDirectoryCompiler.GetCodeDirectoryAssembly(VirtualPath virtualDir, CodeDirectoryType dirType, String assemblyName, StringSet excludedSubdirectories, Boolean isDirectoryAllowed) +9751035    System.Web.Compilation.BuildManager.CompileCodeDirectory(VirtualPath virtualDir, CodeDirectoryType dirType, String assemblyName, StringSet excludedSubdirectories) +125    System.Web.Compilation.BuildManager.CompileCodeDirectories() +382    System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled() +252  [HttpException (0x80004005): Could not load file or assembly 'App_Code.eijwsdbn, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. PolicyException thrown. (Exception from HRESULT: 0x80131416)]    System.Web.Compilation.BuildManager.ReportTopLevelCompilationException() +62    System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled() +427    System.Web.Compilation.BuildManager.CallAppInitializeMethod() +31    System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +535  [HttpException (0x80004005): Could not load file or assembly 'App_Code.eijwsdbn, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. PolicyException thrown. (Exception from HRESULT: 0x80131416)]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9932052    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

**Comment by MikhailTymchukDX** [comment]
Try to change the trust level to "Full" in Web.config:
```xml
<configuration>
    <system.web>
        <trust level="Full"/>
    </system.web>
</configuration>
```

**Comment by R-McN** [comment]
That's fixed it. Many thanks Mikhail!
