### ISSUE TITLE
Javascript error in AjaxFileUpload.js

### ISSUE THREAD

**Issue by R-McN** [DevExpress/AjaxControlToolkit#88]
Hello,
I'm successfully using the AjaxFileUpload control in VS 2013 but, as I want to check file sizes BEFORE uploading, I'm trying out some javascript code that uses AjaxFileUpload.js. I get the following error every time the page loads. I've seen that MikhailTymchukDX has been making some changes regarding the AjaxFileUpload control [](https://github.com/DevExpress/AjaxControlToolkit/pull/73/files) and I'm wondering if the changes will help with this issue - if so, is there a set of updated files I could download?

Unhandled exception at line 1, column 1 in http://localhost:54093/js/AjaxFileUpload.js

0x800a1391 - JavaScript runtime error: 'Type' is undefined

**Comment by MikhailTymchukDX** [comment]
This feature is implemented in PR #73
You can download the entire repository or the latest version of the [AjaxFileUpload.js](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/AjaxFileUpload.js) file.

As for the error you provided, would you please describe it in more detail:
1. What application do you run?
2. If possible, make a screenshot of the browser console with this error.
I am looking forward to your response.

**Comment by R-McN** [comment]
Hello Mikhail,

Thanks for your support. I’ve recently been employed by a company that has a web application called ‘SafeWells’. It’s a pretty big project, but it is quite old and in need of some modernization – so I’m currently trying to improve its file uploading feature.
The problem happens when I load a page with <script  type="text/javascript"  src="js/AjaxFileUpload.js"></script> which is called by some javascript on the page:
<script type="text/javascript">
    function CloseProperly() {
        window.opener.location = window.opener.location;
        window.close();
    }

    function onClientUploadComplete(sender, e) {
        onImageValidated("TRUE", e);
    }

    function onImageValidated(arg, context) {

        var test = document.getElementById("testuploaded");
        test.style.display = 'block';

        var fileList = document.getElementById("fileList");
        var item = document.createElement('div');
        item.style.padding = '4px';

        if (arg == "TRUE") {
            var url = context.get_postedUrl();
            url = url.replace('&amp;', '&');
            item.appendChild(createThumbnail(context, url));
        } else {
            item.appendChild(createFileInfo(context));
        }

        fileList.appendChild(item);
    }

    function createFileInfo(e) {
        var holder = document.createElement('div');
        holder.appendChild(document.createTextNode(e.get_fileName() + ' with size ' + e.get_fileSize() + ' bytes'));

        return holder;
    }

    function createThumbnail(e, url) {
        var holder = document.createElement('div');
        var img = document.createElement("img");
        img.style.width = '80px';
        img.style.height = '80px';
        img.setAttribute("src", url);

        holder.appendChild(createFileInfo(e));
        holder.appendChild(img);

        return holder;
    }

    function onClientUploadStart(sender, e) {
        document.getElementById('uploadCompleteInfo').innerHTML = 'Please wait while uploading ' + e.get_filesInQueue() + ' files...';
    }

    function onClientUploadError(sender, e) {
        document.getElementById('uploadCompleteInfo').innerHTML = "There was an error while uploading.";
    }

    function onClientUploadCompleteAll(sender, e) {

        var args = JSON.parse(e.get_serverArguments()),
            unit = args.duration > 60 ? 'minutes' : 'seconds',
            duration = (args.duration / (args.duration > 60 ? 60 : 1)).toFixed(2);

        var info = 'At <b>' + args.time + '</b> server time <b>'
            + e.get_filesUploaded() + '</b> of <b>' + e.get_filesInQueue()
            + '</b> files were uploaded with status code <b>"' + e.get_reason()
            + '"</b> in <b>' + duration + ' ' + unit + '</b>';

        document.getElementById('uploadCompleteInfo').innerHTML = info;
    }


    $(".ajax__fileupload_dropzone").bind("drop", function () {
        checkfilesize();
    });
    $(".ajax__fileupload_queueContainer").bind("click", function () {
        checkfilesize();
    });
    $(".ajax__fileupload_uploadbutton").bind("mouseenter", function () {
        checkfilesize();
    });

    function checkfilesize() {
        var maxFlen = document.getElementById('<%=maxFileLength.ClientID %>').value;
        var total_filesize_num = 0;
        var myElements = $(".filesize");
        if (myElements.length == 0) {
            $(".ajax__fileupload_uploadbutton").css("visibility", "hidden");
            return;
        }
        for (var i = 0; i < myElements.length; i++) {
            var filesize = myElements.eq(i).html(); //$(".filesize").html();
            total_filesize_num = total_filesize_num + filesize_tonum(filesize);
        }
        if (total_filesize_num > 5) {
            $(".ajax__fileupload_uploadbutton").css("visibility", "hidden");
            alert('Maximum file size is 5MB only! Please select another one.');
            return;
        } else {
            $(".ajax__fileupload_uploadbutton").css("visibility", "visible");
        }
    }
    function countsumfilesize() {
        var sumfilesize = 0;
        var myElements = $(".filesize");
        for (var i = 0; i < myElements.length; i++) {
            alert(myElements.eq(i).html());
        }
    }
    function filesize_tonum(filesize) {
        var filesize_num = 0;
        if (filesize.indexOf("kb") > 0) {
            var space = filesize.lastIndexOf(" ");
            filesize_num = parseFloat("0." + filesize.substr(0, filesize.length - space + 1));
        }
        else if (filesize.indexOf("MB") > 0) {
            var space = filesize.lastIndexOf(" ");
            filesize_num = parseFloat(filesize.substr(0, filesize.length - space + 1));
        }
        return filesize_num;
    }


</script>

There is a scriptmanager…
<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
And the ajax upload control is:

<ajax:AjaxFileUpload ID="AjaxFileUpload1" runat="server" Padding-Bottom="4"
        Padding-Left="2" Padding-Right="1" Padding-Top="4" ThrobberID="myThrobber" maxFileSize=""
        OnClientUploadComplete="onClientUploadComplete"
        OnUploadComplete="AjaxFileUpload1_OnUploadComplete"
        OnClientUploadCompleteAll="onClientUploadCompleteAll"
        OnUploadCompleteAll="AjaxFileUpload1_UploadCompleteAll"
        OnUploadStart="AjaxFileUpload1_UploadStart"
        OnClientUploadStart="onClientUploadStart"
        OnClientUploadError="onClientUploadError"
        onchange="checkfilesize(); return false;" />

The error occurs during the page load and the VS debugger opens AjaxFileUpload.js, highlights Type.registerNamespace("Sys.Extended.UI.AjaxFileUpload");, and shows:


[cid:image002.png@01D1A625.680F9EF0]

Here is the browser console you referred to…

[cid:image001.png@01D1A622.598FA4E0]

Thanks again for your help.
Regards,
Richard

**Comment by MikhailTymchukDX** [comment]
@R-McN  I cannot see the screenshots you attached.
Would you please re-attach them using the GitHub browser UI?

**Comment by R-McN** [comment]
![rmn1](https://cloud.githubusercontent.com/assets/19165091/15039136/2fff5502-12a2-11e6-919f-51e665aba18c.jpg)
![rmn2](https://cloud.githubusercontent.com/assets/19165091/15039137/30025478-12a2-11e6-88ad-2b83c1806175.jpg)

**Comment by MikhailTymchukDX** [comment]
Is `js/AjaxFileUpload.js` a custom script file or a file from the AJAX Control Toolkit scripts?

**Comment by R-McN** [comment]
It is one of the AjaxControlToolkit files that I got from the sample site (that was installed with the toolkit) and it is in a folder called ‘js’ off the root of my web site.

**Comment by MikhailTymchukDX** [comment]
Why do you place it there?
AjaxFileUpload will work without it by default, but if you need physical files to be downloaded, you have to install the [AjaxControlToolkit.StaticResources](https://www.nuget.org/packages/AjaxControlToolkit.StaticResources/) NuGet package and [disable bundling](https://github.com/DevExpress/AjaxControlToolkit/wiki/How-to-use-bundling-and-CDN#to-disable-bundling).

**Comment by R-McN** [comment]
I added it because I thought that it was required for being able to validate files before they are uploaded to the server and then to remove them from the queue if they are invalid. Am I mistaken?

**Comment by MikhailTymchukDX** [comment]
AjaxFileUpload has no capability to validate files before uploading except for the file extension (as for the v16.1 release).
The code that performs that validation is the code you provided earlier and it has no relevance to the AJAX Control Toolkit code.

`AjaxFileUpload.js` file and all dependencies are loaded automatically in correct order by the toolkit, so you need no extra actions.
Trying to load it explicitly can cause errors, because it uses types defined in files that are not loaded yet.

 You can inspect `Network` tab in a browser's developer tools to get familiar with scripts' load sequence.

**Comment by R-McN** [comment]
OK, I’ll remove the js file. Thanks for your help Mikhail.
Best regards,
Richard
