### ISSUE TITLE
Using the client side methods provided for the AjaxFileUpload control

### ISSUE THREAD

**Issue by R-McN** [DevExpress/AjaxControlToolkit#90]
The documentation at [https://github.com/DevExpress/AjaxControlToolkit/wiki/AjaxFileUpload](url) says that there are a host of client methods available, for example removeFileFromQueueHandler(e). I would like to use this in the client side onClientUploadStart() event to remove invalid files from the upload queue, but there are no examples of how this or any other client side method can be used from an aspx page. 
Has anyone got an example they can share please?
Thank you

**Comment by MikhailTymchukDX** [comment]
Unfortunately, `onClientUploadStart` event occurs right  after the start of uploading, so you can not cancel this process.
However, the newly added `validateFiles()` method allows you to do that.
Please see #87 for code sample.

**Comment by R-McN** [comment]
Thanks for the example Mikhail, but after the handler has been loaded, how and when should the validateFiles() method called? Is there an associated property in the control I should be setting (eg validateFiles=true, or OnClientValidateFile=”validateFiles();”)? I can’t get the validation method to trigger.

**Comment by MikhailTymchukDX** [comment]
This method is called automatically before the start of upload, so there is no need to call it explicitly.
You need the latest code to utilize this method (v16.1 does not contain it).

**Comment by R-McN** [comment]
Aha! Is there a later version of the dll available with this new feature?

**Comment by MikhailTymchukDX** [comment]
No.

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX
I guess it's time to add nightly builds to our AppVeyor artifacts :smile: 

@R-McN
While we don't have nightly builds, feel free to clone the repository or download ZIP from the project home page, and make your custom build!

**Comment by MikhailTymchukDX** [comment]
@R-McN We need to update AppVeyor build settings to introduce nightly builds in a convenient format, so we opened PR #117. You can keep tracking the PR to get required DLLs when it is ready.

**Comment by R-McN** [comment]
Thanks.
