### ISSUE TITLE
Control inside an accordion has an unlogical name (changed from previous versions 4.1)

### ISSUE THREAD

**Issue by blenke** [DevExpress/AjaxControlToolkit#98]
I'm converting an old ajax control toolkit project to version 16.1. I noticed a problem with control names that are placed on accordions. I use the control names as input for a SQL Datasource and would like to keep the name logical.

In version 4.1.60919 a textbox control placed inside the accordion has the following name if I check with F12 in the browser:
`<textarea name="ctl00$MainContent$TabContainer1$TabPanel3$AccordionPane1_content$TextBoxInstCmd32" id="MainContent_TabContainer1_TabPanel3_TextBoxInstCmd32" style="width: 99%; font-family: Verdana;" rows="15" cols="20" wrap="off">Some text</textarea>
`

In version 16.1 the name of the 'AccordionPane1_content' is changed to 'ctl03' like this:
`<textarea name="ctl00$MainContent$TabContainer1$TabPanel3$AccordionPane1_content$TextBoxInstCmd32" id="MainContent_TabContainer1_TabPanel3_TextBoxInstCmd32" style="width: 99%; font-family: Verdana;" rows="15" cols="20" wrap="off">Some text</textarea>
`

In the sql datasource I use this name as input parameter: 
`<asp:controlparameter Name="InstallCmd" Type="String" controlid="TabContainer1$TabPanel3$AccordionPane1_content$TextBoxInstCmd32" propertyname="Text" />`

I can change it to ctl03 to fix the issue but what will happen if I change something in the accordion control, will adding a pane change the name. The name of the control is still AccordionPane1.

**Comment by MikhailTymchukDX** [comment]
What version of ,NET Framework do you use in your project?

**Comment by blenke** [comment]
I’m using version 4.0 but just now tried 4.5.2 and 4.6.1 but the naming does not change. Looks like controls in an accordion do not inherit the name, there are also a few buttons on the page which get the same naming ‘ctl003’.

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX we need to check how the rendering has changed since 4.1. Looks like previously inner controls had explicit IDs, and  now they don't

**Comment by MikhailTymchukDX** [comment]
@blenke This behavior was changed in [v16.1](https://github.com/DevExpress/AjaxControlToolkit/releases/tag/16.1.0) as a result of the [27975](https://ajaxcontroltoolkit.codeplex.com/workitem/27975) workitem fix.

The `AccordionPane` class used to change the ID of its child `AccordionContentPanel` instances. That broke the default ASP.NET naming convention and did not allow operating `UpdatePanel` properly.
So, change IDs in your database to make your project work as it did before.
