### ISSUE TITLE
Bootstrap CSS breaks CalendarExtender formatting

### ISSUE THREAD

**Issue by markhewett** [DevExpress/AjaxControlToolkit#99]
Using the Bootstrap CSS (tested with v3.3.6) breaks the formatting of the CalendarExtender.

This is what it looks like _without_ Bootstrap:

![Without Bootstrap](https://cloud.githubusercontent.com/assets/1621581/15163969/696cb946-16d1-11e6-833c-9ba40093c0b9.PNG)

And this is what it looks like _with_ Bootstrap:

![With Bootstrap](https://cloud.githubusercontent.com/assets/1621581/15164067/f2e4d0c8-16d1-11e6-9a98-a16f1126b267.PNG)

The other views are also impacted:

![Months View](https://cloud.githubusercontent.com/assets/1621581/15164099/271480a0-16d2-11e6-8c03-1ace8024c259.PNG)
![Years View](https://cloud.githubusercontent.com/assets/1621581/15164101/2969d85a-16d2-11e6-816f-f02644358e73.PNG)

Tested by adding a TextBox and CalendarExtender to the default VS2013 web forms project.

    <div class="row">
        <asp:TextBox ID="txtTest" runat="server" />
        <ajaxToolkit:CalendarExtender runat="server" TargetControlID="txtTest" />
    </div>

**Comment by lukasz30096** [comment]
aaa

**Comment by nitinjs** [comment]
I think it is not recommended to use ajaxToolkit with twitter bootstrap
